### ISSUE TITLE
Suspending projects from actions menu should goto confirmation dialog

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1025]
### Current Behavior

When clicking "suspend" in the actions list of the project overview it redirects you to the settings page. On that page the user needs to find the suspend button again, and then gets a pop up to suspend the actual project.

### Expected Behavior

When clicking "suspend" in the actions list of the project overview it shows the confirmation dialog immediatly

### Environment

- FlowForge version: 0.10

**Comment by sammachin** [comment]
Same experience should apply to the delete action in the menu.

**Comment by Steve-Mcl** [comment]
confirmed on staging
