### ISSUE TITLE
Investigate and solve Postgres GH Action Test failures

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1029]
### Description

Raising this so we can schedule some proper time to work this out.

It looks like even though the checkout action reports the right hashes when checking the code out, the test output reflects a much older version.

e.g. https://github.com/flowforge/flowforge/actions/runs/3142469172/jobs/5106097517

Assuming we get some support with our GH Enterprise account, might be worth asking for some help.

**Comment by knolleary** [comment]
I have forked the repo into `knolleary/flowforge` so I can throw lots of debug at it without polluting our local main branch.

Finally got to the bottom of it - PR incoming.

**Comment by hardillb** [comment]
Tests running properly in GH so saying this is Done
