### ISSUE TITLE
AWS ELB - Error: Failed to obtain access token

### ISSUE THREAD

**Issue by GloventDevAdmin** [flowforge/flowforge#1034]
### Current Behavior

Hi Team,

First of all, well done on a very powerful and great platform. Very excited to see what is yet to come.

We have deployed FlowForge on an AWS EC2 instance using the Docker Install (without SSL enabled). The server is behind an AWS ELB (Application Load Balancer) using a AWS ACM wildcard Certificate. The Load Balancer listens on port 443 and forwards this traffic to port 80 of the Target EC2 Forge Server, and the ELB also listens on port 80 which then redirects to HTTPS on the ELB which in turn again forwards to port 80 on the EC2 Forge Server. 

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/18399112/192975741-8cca68a2-d59c-495a-b657-e51217f9a080.png">

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/18399112/192975967-9ab9fb76-ef27-402b-8d8d-181b8313d97d.png">

The Forge Application itself launches without any issues. However, any project that I try and launch from the Forge App gives the following error: "Error: Failed to obtain access token".

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/18399112/192978229-4ade4368-7351-4475-9fdd-3c3b1de9313c.png">

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/18399112/192978286-76b75eb6-238f-47a4-b188-2e0e514f1635.png">

This seems to be because of the HTTP to HTTPS redirects during the /account/authorize, /account/complete/ & /auth/strategy/callback methods. If I forward port 80 traffic on the ELB to the Forge Server instead of redirect to 443, then it works, but the instance is obviously not secure. Do you have any suggestions for me on how to get around this issue? All security groups are set to allow 80 as well as 443 from all sources.

Regards,
Wikus

### Expected Behavior

The expected behaviour is for the ELB to handle all SSL, and for port 80 traffic to be redirected to 443 and for the Node-Red instances/projects to be launched from the Forge Application with single sign-on.

### Environment

- FlowForge version: 0.0.9
- Node.js version: 16.16.0
- npm version:
- Platform/OS: Ubuntu-jammy-22.04-arm64
- Browser: Chrome & Safari

**Comment by hardillb** [comment]
Please provide your `flowforge.yml` file as well so we can see how you have configured things. (You can obfuscate the domain if needed)

**Comment by hardillb** [comment]
Also are you using the docker-compose project, or something you have rolled on your own

**Comment by GloventDevAdmin** [comment]
Herewith docker-compose.yml:

> version: "3.3"
> services:
>   nginx:
>     image: jwilder/nginx-proxy
>     networks:
>       - flowforge 
>     restart: always
>     volumes:
>       - "/var/run/docker.sock:/tmp/docker.sock:ro"
>       - "./certs:/etc/nginx/certs"
>     ports:
>       - "80:80"
>       - "443:443"
>     environment:
>       - "HTTPS_METHOD=redirect"
>   postgres:
>     image: postgres
>     networks: 
>       - flowforge
>     restart: always
>     environment:
>       POSTGRES_PASSWORD: secret
>       POSTGRES_USER: root
>     volumes:
>       - "./db:/var/lib/postgresql/data"
>       - "./setup-db.sh:/docker-entrypoint-initdb.d/setup-db.sh"
>   flowforge-broker:
>     image: "iegomez/mosquitto-go-auth"
>     networks:
>       - flowforge
>     restart: always
>     ulimits:
>       nofile: 2048
>     environment:
>       - "VIRTUAL_HOST=mqtt.glo-x.glocms.net"
>       - "VIRTUAL_PORT=1884"
>     volumes:
>       - "./broker/mosquitto.conf:/etc/mosquitto/mosquitto.conf"
>   forge:
>     build:
>       context: "./flowforge-docker"
>     image: "flowforge/forge-docker"
>     networks: 
>       - flowforge
>     restart: always
>     environment:
>       - "VIRTUAL_HOST=forge.glo-x.glocms.net"
>     volumes:
>       - "/var/run/docker.sock:/tmp/docker.sock"
>       - "./etc/flowforge.yml:/usr/src/forge/etc/flowforge.yml"
>     depends_on:
>       - "postgres"
>       - "nginx"
>       - "flowforge-broker"
> 
> networks:
>   flowforge:

And here flow forge.yml:

> port: 3000
> host: 0.0.0.0
> domain: glo-x.glocms.net
> base_url: http://forge.glo-x.glocms.net
> api_url: http://forge:3000
> 
> #################################################
> # Database Configuration                        #
> #################################################
> 
> db:
>   logging: false
>   ## The database type: sqlite|postgres
>   type: postgres
>   ### SQLite options
> 
>   ## The database filename. Relative to $FLOWFORGE_HOME/var/
>   ## Set to ':memory:' for a database that is wiped on restart
>   # storage: forge.db
> 
>   ### Postgres options
> 
>   host: postgres
>   user: forge
>   password: secret
> 
> #################################################
> # Project Driver Configuration                  #
> #################################################
> 
> driver:
>   ## The type of backend driver to use
>   ##  Can be: localfs/docker/stub/k8s
>   type: docker
> 
>   options:
>     ## Options to be passed to the driver
> 
>     ### LocalFS options
> 
>     ## The first port number to assign to projects
>     # start_port: 7880
> 
>     ## Path to find node executable if not on the default path
>     # node_path: /usr/bin/node
> 
>     ### Docker options
> 
>     ## Docker socket path
>     socket: /tmp/docker.sock
>     # registry: hub.flowforge.com
> 
>     ### K8S options
> 
>     ## Kubectl conf file to contact the cluster
>     # config_file: /opt/share/projects/flowforge/test/config
>     # regsitry: hub.flowforge.com
> 
> #################################################
> # Email Configuration                           #
> #################################################
> 
> email:
>   enabled: false
>   debug: false
>   smtp:
>     host: localhost
>     port: 587
>     secure: false
>     #auth:
>     #    user: username
>     #    pass: password
> 
> broker:
>   url: mqtt://flowforge-broker:1883
>   public_url: wss://mqtt.glo-x.glocms.net
>

**Comment by hardillb** [comment]
Try changing the `base_url` to `base_url: https://forge.glo-x.glocms.net/` (make it explicitly https)

**Comment by GloventDevAdmin** [comment]
> Hi, is there any feedback on my previous suggestion?

Hi Ben,

Apologies for the delayed response, but I have been on paternity leave the last couple of days.

I have tried setting the base_url explicitly to https, but I suspect that the following in the docs prevents that from working:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/18399112/195175175-eb249ced-91f5-4225-a817-3cde5594622f.png">

Taking this into account, I deployed a new instance all together with the https set in base-url, but I still get the same error. Please advise !? 

Regards,
Wikus

**Comment by wikus-glovent** [comment]
Hi Ben,

I had a look in the Logs, herewith the screenshot.:

![image](https://user-images.githubusercontent.com/62133058/195268592-6d3c9f8e-4117-4d08-85ab-d3891d1d17b5.png)

And herewith the activity log for this morning:

![image](https://user-images.githubusercontent.com/62133058/195268762-8f6bfc61-46d6-4359-a879-98537c004aee.png)

But yes, it is definitely the redirect causing some issues. Let me know if you find anything when simulating this with the extra Nginx instance and if there is a secure workaround?

**Comment by wikus-glovent** [comment]
Hi Ben,

Just an update, I don't think the ELB is the issue. Last night I created a new EC2 instance, and pointed my DNS directly to that server. I enabled SSL as per the FlowForge Documentation, and generated a wildcard certificate using Lets Encrypt. So the SSL termination now happens on Nginx, but then the redirects still cause the access token error.

![image](https://user-images.githubusercontent.com/62133058/195518575-8ae66481-e461-4d88-970d-971f73d2f757.png)

Here is the nginx config on compose:

![image](https://user-images.githubusercontent.com/62133058/195518789-af4dcb39-9dcf-453e-a4d8-142a6638e096.png)

**Comment by hardillb** [comment]
I'm still trying to recreate this on my end.

I've tried both with and without a second nginx instance acting as the ELB and it keeps working. I'm digging into the auth plugin code to see if I can inject some extra debug to help now. Will let you know when I have something to test

**Comment by hardillb** [comment]
OK, I have a debug build, it will require you to build a new `flowforge/node-red` container and create a new stack.

1. Please edit the `node-red-container/package.json` as follows
     ```
    {
        "name": "node-red-project",
        "description": "A Node-RED Project",
        "version": "0.10.0",
        "private": true,
        "dependencies": {
            "@flowforge/nr-storage": "^0.10.0",
            "@flowforge/nr-auth": "github:flowforge/flowforge-nr-auth#debug-glo",
            "@flowforge/nr-audit-logger": "^0.10.0",
            "@flowforge/nr-theme": "^0.1.1",
            "@flowforge/nr-project-nodes": "^0.1.0"
        }
    }
     ```
2. Build a new version of the container (from within the node-red-container directory) run:
    ```
    docker build . -t flowforge/node-red:debug
    ```
3. As an admin user in the FlowForge web app create a new Stack, the container name for the stack should be `flowforge/node-red:debug` (https://flowforge.com/docs/install/first-run/#2.-create-a-project-stack)
4. Create a new project using the new stack
5. Once it is started please try and log in
6. Assuming a failure please look in the logs in the FlowForge app for the new project.

**Comment by wikus-glovent** [comment]
Hi Ben,

Okay, so only after your previous reply about adding the nr-auth debug dependency did I stumble across my silly mistake. On my both EC2 instances that I have been testing with, I have habitually created Stacks that use the nodered/node-red:latest containers (which I suppose won't have the nr-auth in) instead of flowforge/node-red:latest container. After creating new Stacks with the correct Container Location, the access token issue has been resolved. 

Apologies for wasting your time. Thanks for your help.

**Comment by hardillb** [comment]
@wikus-glovent Glad you have got to the bottom of this.

If you have time I would love to have a chat with you about what you intend to use FlowForge for. If you want to drop me an email at ben @ flowforge.com we can arrange a time may be next week?
