### ISSUE TITLE
avatar lettering is mis-allinged when only rendering 1 character

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1038]
### Current Behavior

Avatars for users `t4` and `test 6` are not rendered correctly

![image](https://user-images.githubusercontent.com/44235289/193577035-e4535a2c-e847-4f08-8614-303eb963df7d.png)

### Expected Behavior

All allowable alpha numeric characters should rendered OR center the single character

### Steps To Reproduce

create a user named `t4` or `test 6`

### Environment

- FlowForge version: 0.10.0
- Platform/OS: Windows / Linux
- Browser: All

**Comment by knolleary** [comment]
@Steve-Mcl tbh I cannot immediately remember where they came from, would need to dig around.

But this issue doesn't ask for additional characters to be added to the font. It is the issue that a single char doesn't get centrally aligned. That should be a quick fix.

**Comment by Steve-Mcl** [comment]
Verified on staging

![Image](https://user-images.githubusercontent.com/44235289/197735518-02a88ab3-1f27-484f-aca9-2c2be4f61325.png)
