### ISSUE TITLE
Start action is availble on a running project

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#1040]
### Current Behavior

When a project is in its starting or running state the Action button still shows start as an option.

Clicking this puts the project into a starting state within the DB/UI but because the project is already running it doesn't seem to ever update this status.

The only way to get back to a clean state is to suspend the project and then restart it.

![image](https://user-images.githubusercontent.com/187645/194039463-1c65b747-a89c-4693-b0e4-2d3d3eb60d04.png)

### Expected Behavior

The Start action should be disabled when a project is running or starting.

### Steps To Reproduce

open editor, goto a running project, see that the start option is available 

### Environment

- FlowForge version: 0.10.0 (Prod)
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
This issue needs to be merged in conjunction with https://github.com/flowforge/flowforge-nr-launcher/pull/75

**Comment by hardillb** [comment]
Verified on staging
