### ISSUE TITLE
Improve Template creation & Edit Project Settings UX

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1041]
### Persona 1:
**As a:** Platform Admin 

**I want to:** be able to easily setup a template project

**So that:** I can setup projects, without being overwhelmed by options.

### Persona 2:
**As a:** Flowforge User

**I want to:** be able to configure my project and not be overwhelmed by options

**So that:** I can configure my project to my liking, within the constraints of the respective template.

### Conclusion:
Template settings should all be enabled by default (not disabled). Currently, we overwhelm end users with options that they cannot edit (by default) if disabled in a template. 

Whilst the admin can go in and enable them in the underlying template one-by-one, in creating a default behaviour of these settings being editable, we reduce the onboarding friction, and the need for an admin to go through all of the available options (which will only grow) and understand each of them.

Additionally, we should not display locked/disabled settings in the Project > Settings view to a user. There is no value in doing so, and just overwhelms the user with options that they cannot action.

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

- [ ] #1043
- [x] #1042

**Comment by knolleary** [comment]
There are two users to consider here:

 - the admin who is responsible for the platform and for creating the template in the first place
 - the users who create and manage individual projects

> This requires users to understand all of the options available to them in order to enable particular functionality/editing that they may wish to enable.

The counter-argument here is that leaving them editable requires the admin to understand all of the options to ensure they don't accidentally permit something they don't intend.

I suspect the right answer is going to be a mix of option 1 and 2 - some options are locked by default and some aren't, based on our assessment of likely-hood an Admin will want end-users to have access to a particular option.

Essentially - which options make sense to be customisable on a per-project basis (so should be unlocked by default), versus options that are more platform-wide considerations that the Admin is responsible for (so should be set in the template and locked).


There are some options that make much less sense to be customised for individual projects.

Here is the list of all template properties we have in the code. Not all are currently exposed in the Template UX.


  | default value | is editable | Comments
-- | -- | -- | --
disableEditor | FALSE | TRUE |  
disableTours | FALSE | TRUE |  
httpAdminRoot | / | TRUE |  
dashboardUI | /ui | TRUE |  
codeEditor | monaco | TRUE |  
theme | forge-light | TRUE |  
page_title | FlowForge | FALSE | not currently exposed
page_favicon |   | FALSE | not currently exposed
header_title | FlowForge | TRUE | 
header_url |   | FALSE | not currently exposed
timeZone |   | TRUE |  
palette_allowInstall | TRUE | TRUE |  
palette_nodesExcludes |   | FALSE | ^1
palette_denyList |   | FALSE | ^1
modules_allowInstall | TRUE | TRUE |  
modules_denyList |   | FALSE | ^1
httpNodeAuth_user |   | TRUE |  
httpNodeAuth_pass |   | TRUE |  

**^1** these options only make sense if the corresponding `*_allowInstall` is true. But they are properties that would be used to restrict what can be installed. I don't think there's a good reason to let that be customised per-project at all - it is a platform-wide security decision.

**Comment by joepavitt** [comment]
For template creation, we would now have the following styling (includes the correct default values as per Nick's table above):

<img width="1347" alt="Screenshot 2022-10-14 at 16 28 12" src="https://user-images.githubusercontent.com/99246719/195884225-a200ce27-c4ca-4436-937b-b158b918935f.png">

**Comment by joepavitt** [comment]
@knolleary noticed you've included "forge-light" here for theme, but didn't see that in existing table of options. Imagine this would be a dropdown of our available themes, or is it more complex than that?

**Comment by knolleary** [comment]
@joepavitt the work has been done to support multiple themes, but right now we only have the one. So rather than give a choice of exactly one thing, we didn't expose it in the template.

**Comment by joepavitt** [comment]
Will be adding in a CSS-only fix for this issue, but there is a bigger item to update/review the `FormRow` component as this still hasn't been done since our switch to `forge--ui-components`

**Comment by joepavitt** [comment]
Have gone for a middle-ground on layout here, lock positioning as per existing layout, which I'll then move around in hte re-work of FormRow as per above.

<img width="880" alt="Screenshot 2022-10-25 at 11 44 58" src="https://user-images.githubusercontent.com/99246719/197753490-670ad183-6855-4622-9f03-8b3aad307743.png">

**Comment by joepavitt** [comment]
The select styling will also be done as part of the FormRow re-work.
