### ISSUE TITLE
Have a fallback view if all Editor/Palette settings are locked, that explains why no options are available.

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1042]

**Comment by joepavitt** [comment]
<img width="1092" alt="Screenshot 2022-10-06 at 11 41 21" src="https://user-images.githubusercontent.com/99246719/194293116-61e554fb-8f21-4edf-92b7-00e69fba869d.png">

**Comment by hardillb** [comment]
- Editor disabled
 - Editor path
 - UI path
 - Timezone
 - HTTP Username (password is never shown even if you can edit it)
 - Allow user to install new modules in the Function node
 - Allow user to install new nodes

(Which is most of them)

**Comment by joepavitt** [comment]
If we are set on including them at the project level - then as a bare minimum, we need to explain why they are locked:

<img width="2364" alt="Screenshot 2022-10-06 at 13 57 52" src="https://user-images.githubusercontent.com/99246719/194318634-189ddb1e-4740-4530-b5c0-a72782d2d742.png">

**Comment by joepavitt** [comment]
This task is no longer required, as we will show the locked settings as per discussion and design in https://github.com/flowforge/flowforge/issues/1041
