### ISSUE TITLE
Settings should all be  enabled by default when creating a new template

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1043]
When a new template is created (or new options are added to the platform) the default value for Editable are set to Locked, They should default to Editable.

**Comment by joepavitt** [comment]
@knolleary I'm struggling to track down where/how "policy" is set for the default locked value when creating a new template. I've loosely track it down to [this file](https://github.com/flowforge/flowforge/blob/main/frontend/src/pages/admin/Template/index.vue) but struggling to see where the defaults are set?

**Comment by joepavitt** [comment]
Thanks Ben - any major reasons why these are set to `false` by default - or at least any objections to having them true by default?

**Comment by sammachin** [comment]
@joepavitt not sure what this issue is exactly, can it be merged into the conversation on #1041

**Comment by joepavitt** [comment]
This task is a child task of the #1041 story

**Comment by joepavitt** [comment]
Default values listed https://github.com/flowforge/flowforge/issues/1041#issuecomment-1275937891

**Comment by hardillb** [comment]
Verified on Staging

**Comment by ZJvandeWeg** [comment]
@hardillb @joepavitt can we close this issue?
