### ISSUE TITLE
Project "Deployments"

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1046]
### Description

Given the discussion in https://github.com/flowforge/flowforge/issues/787 and the respective designs that followed (see below) we will be updating "Project > Devices" to "Project > Deployments"/

<img width="1614" alt="Screenshot 2022-10-07 at 15 35 51" src="https://user-images.githubusercontent.com/99246719/194579204-6ed96ea1-93ad-40b1-931c-3345ee418f51.png">

To be completed in 2 phases:
1. Updating high level page name to "Deployments" and build "Devices" section of the above design
2. Develop the Cloud/Local part of the design

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

Phase 1:
- [x] Page/Navigation Renaming
- [x] Define "Devices" table and Update table styling & contents

Phase 2:
- [x] Add non-device deployments table, e.g. FF Cloud or Local.

**Comment by joepavitt** [comment]
We'd also see improvement/coherence with the "Snapshot" view with the following change:

<img width="1627" alt="Screenshot 2022-10-07 at 16 19 35" src="https://user-images.githubusercontent.com/99246719/194589693-b9735cea-6812-4a72-8284-b67c0bc8be77.png">

not emphasis here on the "Deployed to Z Devices"

**Comment by joepavitt** [comment]
Deployment UX Prototype (requires Figma login)

https://www.figma.com/proto/rMB2w5ZZUtTC0nxbwLYKJY/FlowForge-Platform?page-id=0%3A1&node-id=493%3A914&viewport=-2491%2C-3339%2C0.49&scaling=min-zoom&starting-point-node-id=493%3A914&show-proto-sidebar=1

**Comment by joepavitt** [comment]
In Snapshot view - need to know where that snapshot was generated from (e.g. device/cloud editor)

**Comment by ZJvandeWeg** [comment]
@Pezmc @joepavitt Has this issue been fully delivered on, or should we move this over, or do we need some follow ups in the backlog?

**Comment by joepavitt** [comment]
Further improvements on the Deployments UX can still be made, but I think @Pezmc did great in getting the main deliverables in, so we can warrant closing this.
