### ISSUE TITLE
Duplicate personal team created each time a user reverifies their email

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1055]
### Current Behavior

When an existing user is prompted to revalidate their email, the flow results in a request to `/account/verify/:token`.

That route was originally added as part of the initial user signup verification - it completes the user account creation by
 - creating a personal team (if that option has been enabled by admin)
 - accepting any pending invites

The problem is we are reusing that route for an existing user to revalidate their email. Which leads to a second personal team being created.

### Expected Behavior

Reverifying an email address should *not* trigger any side-effects for an existing user.

The difficulty here is telling the difference between a validation as part of initial sign-up (which should trigger side-effects), and a revalidation (which shouldn't).

### Steps To Reproduce

 - Enable 'create personal team' option in Admin Settings
 - Invalidate a user's email via admin settings
 - As that user, access the platform - get prompted to revalidate.
 - Click to resend email. (separate bug... invalidating via admin settings doesn't trigger the email to be sent)
 - Follow the link in the email received
 - See a second team has been created.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
> The difficulty here is telling the difference between a validation as part of initial sign-up (which should trigger side-effects), and a revalidation (which shouldn't).

The simple approach would be to add a flag to the JWT we use as verification token to indicate what 'type' of verification this is. However that isn't fool-proof as a user can get to a point where we cannot tell the difference anymore.

For example:

1. User creates account, we send email as part of initial user registration. That can include a flag to say this is initial sign-up.
2. That user ignores the email, reloads FF and logs in. They are presented with a prompt to click the link - and a button to trigger a resend of the email. At this point in time, we've lost the context that they are a new user still working through the initial sign-up - so the resend is the *same* as for an existing user who has to revalidate their email.

The only robust solution would be to add a 'sign-up-complete' flag to the User model - but with a better name. I'm just wary of throwing more single-use flags at the database.

Another option would be, in the spirit of convention/configuration would be to deprecate and remove the 'auto-create team' option all together. We do not enable that option in our FF Managed service - so if we don't deem it to be suitable default behaviour, then do we really need the option. (ofc I can see the benefit of the option otherwise I wouldn't have added it originally... but nor do I want to expand lots of effort working around issues it introduces)

**Comment by hardillb** [comment]
We don't have personal teams enabled on staging so can't verify there. Tested locally and it worked
