### ISSUE TITLE
No verification email sent when admin marks a user email as unverified

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1057]
### Current Behavior

If an admin changes the 'Email Verified' flag for a user, no email is sent to the user to prompt them to reverify.

When that user next comes to the platform they are asked to click the link in the email... an email they haven't been sent. We do provide a button to resend the email, but the current flow will send the user off looking for an email that wasn't sent.

### Expected Behavior

I *think* we should send the email automatically when admin resets the email verified flag.

### Steps To Reproduce

- As admin, edit a user via Admin Settings to set Email Verified to false
- As that user, observe that no email was received

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
@knolleary @hardillb as a non admin on staging, I cannot check this - would one of you be kind enough to verify this pls?

**Comment by hardillb** [comment]
Verified on staging

**Comment by hardillb** [comment]
Email is sent, but seeing an error message when clicking the verify button

**Comment by Steve-Mcl** [comment]
Ben, what is the error?   

I have a suspicion. 

Did you log out before opening the link?

**Comment by hardillb** [comment]
Yes, I was logged out

**Comment by hardillb** [comment]
ERROR: /account/verify/token error - TypeError: Cannot read properties of null (reading 'User')

**Comment by hardillb** [comment]
No error with new build, marking this as done
