### ISSUE TITLE
Automatically create initial default project type/stack/template at install time

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1071]
### Description

To remove some complicated initial setup steps from the first run experience.

Potential approach:

- localfs use the install.sh to install the stack and inject values into the database
- Docker/kube can include in the databse setup script.

**Comment by hardillb** [comment]
scratch that, better option is a db migration script so the tables already exist

**Comment by knolleary** [comment]
@hardillb a migration script would get applied to *all* FF instances when they upgrade - so the migration would have to check for empty tables before creating anything.

Whilst that is doable for project type/template, I think stack is more problematic as it depends on the driver being used as to what properties are required.

**Comment by ZJvandeWeg** [comment]
Moved this item to v1.1. @knolleary can you assign this issue as soon as possible to someone to pick it up?

**Comment by knolleary** [comment]
I had also raised https://github.com/flowforge/flowforge/issues/1194 which is already in-plan for 1.1.
