### ISSUE TITLE
The Node-RED version on the stacks page is old

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#1075]
### Description

It either needs to be updated to be the current version or we need a way for it to make it clear that the user should check for themselves what version they should be using.

https://flowforge.com/docs/install/local/stacks/

**Comment by hardillb** [comment]
Also see https://github.com/flowforge/flowforge/issues/1071

**Comment by hardillb** [comment]
should be closed via the following PRs

https://github.com/flowforge/flowforge/pull/1087
https://github.com/flowforge/flowforge/pull/1086
https://github.com/flowforge/flowforge/pull/1085

**Comment by knolleary** [comment]
All those PRs are now merged. Has this specific issue been resolved?

**Comment by hardillb** [comment]
Yes
