### ISSUE TITLE
Inconsistent errors returned from the API

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1076]
### Description

While working on #929 I noted that there are several different standards that are used for returning errors from the API, including but not limited to:

Code and error as JSON:

```js
reply.code(400).send({ code: 'invalid_source_project', error: 'Source Project Not Found' })
```

Error explicitly as html

```js
reply.code(404).type('text/html').send('Not Found')
```

Error returned as html/json based on request type:

```js
reply.code(404).send('Source Project not found')
```

Error sent as a status and message:

```js
reply.code(400).send({ status: 'error', message: 'Email not enabled - cannot reset password' })
```

Error as error and description:

```js
reply.code(400).send({
    error,
    description
})
```

Error and details:

```js
reply.code(409).send({
    error: 'incorrect-project',
    project: request.device.Project?.id || null,
    snapshot: request.device.targetSnapshot?.hashid || null,
    settings: request.device.settingsHash || null
})
```

### Proposed Solution

Error `code` and `error` seems the most common format in the codebase and is informative for the API consumer.

 - [x] Add this standard to the handbook and ensure we're using it going forward
 - [ ] Update all other responses to match this format - _lower priority_

The consistency will make development against the API easier for the FlowForge team and other consumers.

Given we might have to update the front-end codebase to handle any changes to error codes, updating the existing responses might not be of value, but we should definitely agree on one standard for any newly introduced end points.

**Comment by hardillb** [comment]
I thought @knolleary had been thought and standardised on `reply.code(xxx).send({error: '...', code:'....'}) recently.

It may be that he didn't get them all (or only did a specific subset)

**Comment by knolleary** [comment]
See https://github.com/flowforge/flowforge/pull/1021 standardised this in the vast majority of cases and updated the API docs to outline the approach.

It didn't touch 404s as they are a bit more context specific - but I agree they could be tidied up further. In general, there aren't paths where the frontend will hit a 404 in the API.

The 409 example you've highlighted is a specific case of an API contract between the platform and device agent that cannot be easily changed for compatibility reasons.

**Comment by Pezmc** [comment]
I somehow overlooked this in the docs [docs/contribute/api-design.md](https://github.com/flowforge/flowforge/blob/main/docs/contribute/api-design.md#error-formats) is the relevant link for anyone following along.

I'll do another pass to check if anything was missed but sounds like this is likely already solved.

**Comment by knolleary** [comment]
@Pezmc always good to get a second pair of eyes on things like this. I think you're right that the 404 handling could/should be tidied up and a more consistent code style applied. We can use this issue for that part of it.

**Comment by knolleary** [comment]
For 404s, I think the basic principle should be:

1. If it is a `/api/v1/**` route, then it is something being accessed programmatically. They should have a payload of `{ code: "not_found", error: "Not Found" }` without any further information.
2. Any other route that is human navigable, should return an html 404.
3. There are some routes (eg under `/account/`) that are not part of the platform API, but should be considered programmatic in nature and return the JSON format.
