### ISSUE TITLE
Use of .focus() needs to be revisited due to component library changes

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1081]
Edit: The original issue applied to several pages, see https://github.com/flowforge/flowforge/issues/1081#issuecomment-1279156628 for more details.

---

### Current Behavior

When clicking "Update License" button, console error is displayed

```
Uncaught TypeError: Cannot read properties of null (reading 'focus')
    at eval (License.vue?./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/index.js??ruleSet%5B1%5D.rules%5B10%5D.use%5B0%5D:59:43)
```

This is due to `document.getElementById('license').focus();`  in `License.vue`

### Expected Behavior

* Element to be focused
* No error

### Steps To Reproduce

Open admin settings -> settings -> license -> click "Update License"

### Environment

- FlowForge version: 0.10.0-git
- Platform/OS: Windows
- Browser: chrome

**Comment by knolleary** [comment]
We have had a few places where this pattern has broken. I think some changes to the UI components meant the inputs no longer have the id set.

This has been fixed up in some places (login dialog iirc) but we should do a scour for any other places that need updating.

**Comment by Pezmc** [comment]
It looks like this was caused when FormRow's were swapped to use `ff-text-input`'s. The more generic fix is likely to update FormRows and `ff-text-inputs` to accept an autofocus attribute of some sort (or to set a `ref` used in the parent component to `.focus()`)

**Comment by joepavitt** [comment]
Shouldn't really be using the `document.getElementById` in a Vue world. There is more value in using `ref` as doing so gives you the whole component to play with.

Means we can do something like `this.$refs['text_input'].focus()` subject to implementing the `focus` method on the input component (see https://github.com/flowforge/forge-ui-components/issues/42)

**Comment by Pezmc** [comment]
I found five places where this pattern _was_ used, two of which are fixed, albeit with workarounds, and three which are not-working right now:

### Not working

 - Login Form - `this.$refs['login-username'].$el` is a reference to a div https://github.com/flowforge/flowforge/blob/0dc8b449036ed3310b8d1c3ab9337a057ca174c6/frontend/src/components/auth/Credentials.vue#L60-L65
 
 - Project Settings - `document.getElementById('projectName')` is undefined as form row does not pass the ID to a `ff-text-input`
https://github.com/flowforge/flowforge/blob/0dc8b449036ed3310b8d1c3ab9337a057ca174c6/frontend/src/pages/project/Settings/General.vue#L76-L78

 - Licence (this issue)- `document.getElementById('license')` is undefined as form row does not pass the ID to a `ff-text-input`
https://github.com/flowforge/flowforge/blob/0dc8b449036ed3310b8d1c3ab9337a057ca174c6/frontend/src/pages/admin/Settings/License.vue#L102-L104

### Working but should be Vue-ified

 - Password Update Page - Using order of elements (relatively brittle)
 https://github.com/flowforge/flowforge/blob/0dc8b449036ed3310b8d1c3ab9337a057ca174c6/frontend/src/components/auth/UpdateExpiredPassword.vue#L67-L75
 
  - Team Name - Uses the label to find the closest input element
  
https://github.com/flowforge/flowforge/blob/0dc8b449036ed3310b8d1c3ab9337a057ca174c6/frontend/src/pages/team/Settings/General.vue#L102

(see https://github.com/flowforge/forge-ui-components/issues/42 and https://github.com/flowforge/forge-ui-components/issues/60)

**Comment by Pezmc** [comment]
To address the above properly (and as Joe has already pointed out), this issue is blocked by https://github.com/flowforge/forge-ui-components/issues/42
