### ISSUE TITLE
Instance Logs page doesn't handle errors well

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1083]
### Current Behavior

If the project launcher has crashed, then the polling request to get the latest logs gets an `ECONNREFUSED` error.

If the user is viewing the project logs page, the page is polling the backend for those logs - and the underlying ECONNREFUSED is getting passed back to the user... each time it polls

<img width="831" alt="image" src="https://user-images.githubusercontent.com/51083/195888983-5bdc697c-014a-485a-b14f-e234d4c5b6b9.png">

### Expected Behavior

Better reporting of the error to the user without an explosion of notifications

 - We should spot the ECONNREFUSED error and translate it to something more consumable when returning it to the frontend
 - Pages that poll the API need a better strategy for reporting errors on each poll. Multiple toast notifications aren't pleasant.

### Steps To Reproduce

Manually kill the nr-launcher process for a project whilst viewing its logs page

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Oierotamendi** [comment]
Hello,

I have this problem and I don't know how to solve it. Can you give me more information please?

**Comment by knolleary** [comment]
Hi @Oierotamendi 

this means the underlying Node-RED project has crashed. Normally the platform should automatically restart a project, so this should be temporary.

To help you out here, can you provide more details on how you are running FlowForge (localfs/docker/k8s)?

**Comment by knolleary** [comment]
@Oierotamendi  This issue is specifically about a UI issue around the reporting of the error, rather than anything to do with the underlying reasons that Node-RED isn't running. So to be able to help, we need to understand more about where you have got to.

Can you access the editor for the project? Is it running? Have you restarted anything? Have you managed to run a project at all?

**Comment by Oierotamendi** [comment]
Hello,

I can't access the editor for the project, it says that it is starting all the time but it never starts. I only followed the local installing guide.
![image](https://user-images.githubusercontent.com/56338087/201107975-2d2d9ab6-0b81-4751-9b78-e628861e2f23.png)
![image](https://user-images.githubusercontent.com/56338087/201108154-4a56ff26-1bc5-426d-8147-90e0630bde52.png)

**Comment by hardillb** [comment]
Can you look in the `c:\Users\OOtamendi\MSI_TFG\flowforge\var\projects` directory. In there there should be a directory with the uuid of the project.

There should be a file called `out.log`. Can you post the content of that file please. It should give a hint to why the stack hasn't started.

**Comment by Oierotamendi** [comment]
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found
[
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\nr-launcher\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules\\@flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\app\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\flowforge\\node_modules',
  'C:\\Users\\OOtamendi\\MSI_TFG\\node_modules',
  'C:\\Users\\OOtamendi\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules'
]
executable not found

**Comment by MarianRaphael** [comment]
Also, after creating an instance, when you click directly on the Node-RED logs tab, this happens.


![Image](https://github.com/flowforge/flowforge/assets/73583313/511b72be-99c1-46a0-9fa9-dc143eb314c0)



![Image](https://github.com/flowforge/flowforge/assets/73583313/2b576f2d-a100-477c-972c-5c0c005c5df4)

**Comment by Steve-Mcl** [comment]
This visual issues have been handled in an incoming PR.

Please watch the short video clip below and let me know how this feels.

In particular @joepavitt (re the "offline appearance" of the log panel - it may not be to your liking?) I was attempting to indicate to the user, these logs may be stale.



https://github.com/flowforge/flowforge/assets/44235289/c3f11ac5-dc6a-45dc-ac65-8f7720e91673

**Comment by joepavitt** [comment]
@Steve-Mcl I like the idea, could we go grey (disabled/offline) shading rather than red please? Red indicates "error", and in this case that's not necessarily the case if I understand? Other than that, 👍

**Comment by Steve-Mcl** [comment]
@joepavitt Same for the toast? change from "warning to info"?

**Comment by Steve-Mcl** [comment]
@joepavitt better?

![chrome_vIek5Jc6vj](https://github.com/flowforge/flowforge/assets/44235289/a6241582-e615-4ba9-9ff5-f406b4f4e034)

**Comment by knolleary** [comment]
I would not talk about 'Node-RED Launcher' as that is not a concept we expose anywhere else. I suggest 'Node-RED Instance' is more consistent with what users know.

**Comment by Steve-Mcl** [comment]
Final cut 🤞 

https://github.com/flowforge/flowforge/assets/44235289/92d607e8-6bcc-4b9e-9d37-cc3dc427749a

**Comment by Steve-Mcl** [comment]
Verified fully on local
Not easy to verify on k8s (staging) but it is possible to catch the new banner if you open logs immediately after starting an instance:



![Image](https://github.com/flowforge/flowforge/assets/44235289/c41325e0-a126-42f1-ba29-7f029f2a8cc7)
