### ISSUE TITLE
flowforge-nr-launcher missing try/catch on http request 

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1096]
### Current Behavior

https://github.com/flowforge/docker-compose/issues/45

If `api_url` is wrong (or forge app is down) the the got request to get settings will fail and crash with hard to decipher stacktrace

### Expected Behavior

Catch the error and log suitable message.

Probably exit nr-launcher cleanly (localfs and k8s drivers will automatically try and restart after suitable backoff time, need to check docker)

### Steps To Reproduce

In docker-compose `etc/flowforge.yml` change the `api_url`

### Environment

- FlowForge version: 0.10.0
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: docker
- Browser: na

**Comment by Steve-Mcl** [comment]
verified on local only.
killing forge app does not cause exception in launcher.

**Comment by Steve-Mcl** [comment]
@knolleary @hardillb not sure we can test this on staging?
Should we consider this fairly innocuous PR "done"?

**Comment by knolleary** [comment]
Yes

**Comment by hardillb** [comment]
Ship it, you need to set a bad `api_url` which I can't remember if localfs uses

I will break a docker build when I feel better
