### ISSUE TITLE
FastifyDeprecation: Request#context property access is deprecated. 

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1102]
### Current Behavior

Sometimes seeing this deprecation warning from fastify:

```
(node:29153) [FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.
```

Not tracked it down to a specific route - but recording it here as we need to find and squash it

### Expected Behavior

No deprecated warngins!

### Steps To Reproduce

Not sure at the moment. Cannot trigger it be redoing the things I was up to at the time.

It appeared to happen at the same time as the platform was doing its periodic check of the project states - but just once.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Tracked it down - partly in our code (which will get swept up as part of the searchable apis PR), partly in some fastify plugins we have that are currently downlevel (helmet in particular). Once I get the searchable apis PR in, I'll pr updates to the dependencies and that *should* resolve this issue.

**Comment by knolleary** [comment]
I found I could reliable reproduce running the `users_spec.js` unit test.

I can also confirm the updates in #1111 remove this warning.

**Comment by Steve-Mcl** [comment]
verified on local. 
Is there a way to check on AWS staging?

**Comment by knolleary** [comment]
Verifying on local is good enough for this issue.
