### ISSUE TITLE
Project nodes not working properly

### ISSUE THREAD

**Issue by WilliamBonneterre** [flowforge/flowforge#1118]
### Current Behavior

My project nodes between two projects are not working properly, nor are they working while they Project In and Project Out are linked and inside the same project. (The In sending to the same Out project, in the same flow, linked to an inject node). Despite me having problems with my device linked to said project, I believe the Cloud instance of Node-RED should still be working properly with the debug messages. 

### Expected Behavior

When a Project Out (project #1) node sends a msg to a Project In node (project #2) in different or same projects, the latter should receive the msg sent from the Project Out node, assuming all topics and project links are properly configured.

<img width="960" alt="issue2" src="https://user-images.githubusercontent.com/60229779/197232375-c85e54d5-832b-40d3-a197-090df755ff1e.PNG">
<img width="532" alt="issue2-2" src="https://user-images.githubusercontent.com/60229779/197232387-fa8b4e44-826d-4968-bae3-429500abf741.PNG">

### Steps To Reproduce

1) Create a Project In node and a project Out in the same project or in different projects
2) Link the Project Out to an inject button with a msg.
3) Configure the topic and project links properly
4) Click on the Inject node/Have it configured to send a msg every X seconds
5) Link the Project In node in the other project/same project to a debug node.
6) Notice the lack of response :( 

### Environment

- FlowForge Cloud version

**Comment by joepavitt** [comment]
Worth also noting that William demo'd to me that even within the same project, he could not get the Project nodes to communicate with each other.

The Raspberry Pi on which he had the `flowforge-device-agent` running also reported that the Pi had crashed some time after the snapshot was deployed.

**Comment by knolleary** [comment]
Hi @WilliamBonneterre - can you export these two flows and share them so we can see exactly how they are configured?

**Comment by WilliamBonneterre** [comment]
> Hi @WilliamBonneterre - can you export these two flows and share them so we can see exactly how they are configured?

For sure, here they are : 
`[
    {
        "id": "c46ae2980309832d",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "a5c74c3c1836f1e0",
        "type": "inject",
        "z": "c46ae2980309832d",
        "name": "",
        "props": [],
        "repeat": "5",
        "crontab": "",
        "once": false,
        "onceDelay": "5",
        "topic": "",
        "x": 150,
        "y": 160,
        "wires": [
            [
                "066f7f63f1a49ef4"
            ]
        ]
    },
    {
        "id": "066f7f63f1a49ef4",
        "type": "function",
        "z": "c46ae2980309832d",
        "name": "function 1",
        "func": "let base64value = 0;\nmsg.topic = \"hi\";\nmsg.payload = {\n    \"img_base64\": base64value,\n    \"last_grab\": \"05.10.2022 14:00:00\",\n    \"statusled0\": \"OFFLINE\",\n    \"statusled1\": \"ONLINE\",\n    \"statusled2\": \"ONLINE\",\n    \"statusled3\": \"ONLINE\",\n    \"statusled4\": \"OFFLINE\",\n\n    \"ping0\": \"0.878789s\",\n    \"ping1\": \"0.84689s\",\n    \"ping2\": false,\n    \"ping3\": \"0.55859s\",\n    \"ping4\": \"0.585762s\",\n    \"ping5\": \"0.619098s\",\n    \"ping6\": \"0.94748s\",\n\n    \"mic_presence\": true,\n\n    \"tv_input\": \"HDMI1\",\n\n    \"usb0\": true,\n    \"usb1\": false,\n    \"usb2\": true,\n    \"usb3\": false\n};\nmsg.topic = \"room1\";\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 340,
        "y": 160,
        "wires": [
            [
                "8ee6bec146c02bfa",
                "402720554abfc26e"
            ]
        ]
    },
    {
        "id": "8ee6bec146c02bfa",
        "type": "project link out",
        "z": "c46ae2980309832d",
        "name": "Send Room Info to Mainframe",
        "mode": "link",
        "broadcast": false,
        "project": "3cab3f12-1feb-42ce-a028-326ffbcb5268",
        "topic": "client1",
        "x": 590,
        "y": 160,
        "wires": []
    },
    {
        "id": "3dba62a97c98a091",
        "type": "project link in",
        "z": "c46ae2980309832d",
        "name": "project in 1",
        "project": "all",
        "broadcast": true,
        "topic": "hi",
        "x": 140,
        "y": 320,
        "wires": [
            [
                "ab8320b1b395a403"
            ]
        ]
    },
    {
        "id": "402720554abfc26e",
        "type": "project link out",
        "z": "c46ae2980309832d",
        "name": "project out 1",
        "mode": "link",
        "broadcast": false,
        "project": "2ee4488b-2862-414b-b36e-5270867c623e",
        "topic": "hi",
        "x": 530,
        "y": 220,
        "wires": []
    },
    {
        "id": "ab8320b1b395a403",
        "type": "debug",
        "z": "c46ae2980309832d",
        "name": "debug 1",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 340,
        "y": 320,
        "wires": []
    }
]`

and

`[
    {
        "id": "c46ae2980309832d",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "a5c74c3c1836f1e0",
        "type": "inject",
        "z": "c46ae2980309832d",
        "name": "",
        "props": [],
        "repeat": "5",
        "crontab": "",
        "once": false,
        "onceDelay": "5",
        "topic": "",
        "x": 150,
        "y": 160,
        "wires": [
            [
                "066f7f63f1a49ef4"
            ]
        ]
    },
    {
        "id": "066f7f63f1a49ef4",
        "type": "function",
        "z": "c46ae2980309832d",
        "name": "function 1",
        "func": "let base64value = 0;\nmsg.topic = \"hi\";\nmsg.payload = {\n    \"img_base64\": base64value,\n    \"last_grab\": \"05.10.2022 14:00:00\",\n    \"statusled0\": \"OFFLINE\",\n    \"statusled1\": \"ONLINE\",\n    \"statusled2\": \"ONLINE\",\n    \"statusled3\": \"ONLINE\",\n    \"statusled4\": \"OFFLINE\",\n\n    \"ping0\": \"0.878789s\",\n    \"ping1\": \"0.84689s\",\n    \"ping2\": false,\n    \"ping3\": \"0.55859s\",\n    \"ping4\": \"0.585762s\",\n    \"ping5\": \"0.619098s\",\n    \"ping6\": \"0.94748s\",\n\n    \"mic_presence\": true,\n\n    \"tv_input\": \"HDMI1\",\n\n    \"usb0\": true,\n    \"usb1\": false,\n    \"usb2\": true,\n    \"usb3\": false\n};\nmsg.topic = \"room1\";\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 340,
        "y": 160,
        "wires": [
            [
                "8ee6bec146c02bfa",
                "402720554abfc26e"
            ]
        ]
    },
    {
        "id": "8ee6bec146c02bfa",
        "type": "project link out",
        "z": "c46ae2980309832d",
        "name": "Send Room Info to Mainframe",
        "mode": "link",
        "broadcast": false,
        "project": "3cab3f12-1feb-42ce-a028-326ffbcb5268",
        "topic": "client1",
        "x": 590,
        "y": 160,
        "wires": []
    },
    {
        "id": "3dba62a97c98a091",
        "type": "project link in",
        "z": "c46ae2980309832d",
        "name": "project in 1",
        "project": "all",
        "broadcast": true,
        "topic": "hi",
        "x": 140,
        "y": 320,
        "wires": [
            [
                "ab8320b1b395a403"
            ]
        ]
    },
    {
        "id": "402720554abfc26e",
        "type": "project link out",
        "z": "c46ae2980309832d",
        "name": "project out 1",
        "mode": "link",
        "broadcast": false,
        "project": "2ee4488b-2862-414b-b36e-5270867c623e",
        "topic": "hi",
        "x": 530,
        "y": 220,
        "wires": []
    },
    {
        "id": "ab8320b1b395a403",
        "type": "debug",
        "z": "c46ae2980309832d",
        "name": "debug 1",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 340,
        "y": 320,
        "wires": []
    }
]`

**Comment by WilliamBonneterre** [comment]
Additionally, a new behaviour on my raspberry Pi is that the logs in the terminal are spamming 
`
[warn] Project Link nodes disconnected
[info] Project Link nodes connected

`

Although, as I mentioned, even if my device is not working, the Cloud instance should, correct?

**Comment by joepavitt** [comment]
> Although, as I mentioned, even if my device is not working, the Cloud instance should, correct? 

yep, I'd expect so.

**Comment by WilliamBonneterre** [comment]
Regarding the "Both nodes in the same project/flow not working", a solution I've found is that the Project In node doesn't seem to work when the "Listen for broadcast messages from : " (set to the same project it is within) mode is used, but does work when I use the "Receive messages sent to this project" mode, which I guess is me misunderstanding the "Listen" option. 

This, however, doesn't seem to fix the issue with cross-project messaging.

<img width="955" alt="work1" src="https://user-images.githubusercontent.com/60229779/197238460-eb2d1e97-d95e-4810-88be-a4c7aea686aa.PNG">


<img width="958" alt="work2" src="https://user-images.githubusercontent.com/60229779/197238469-11132603-fcd9-40d2-98ea-be4a1450eac7.PNG">

**Comment by WilliamBonneterre** [comment]
I'm unsure of the steps I took to fix this, but it seems like the cross project communication via the Project In/Out nodes is **now working** after I
1) updated the Project's type (?) on the platform. Seems like it was written that it was last updated a Month ago, and when I clicked on the "Update" button next to the type, it resent me an Invoice, so perhaps there was an issue with my payment making the project non-responsive?
2) After that, I believe the communication was still not working, and after deleting and recreating the Project nodes, it worked.

**Comment by knolleary** [comment]
@WilliamBonneterre I think this is an issue with getting the 'send/broadcast' and 'receive/listen' the right way around on both ends of the link.

If a Project Out node is configured to `Send to configured project`, then the Project In node must be configured to `Receive messages sent to this project`

If a Project Out node is configured to `Broadcast to all`, then the Project In node must be configured to `Listen for broadcast`.

From what I see in the JSON you've shared, the first flow has a Project Out node configured to Send to the other project. But the other project is configured to Listen for broadcasts. So unless I'm misreading it, that mismatch would mean the messages wouldn't get across.

We need to think about how to improve the UX of the nodes to avoid this type of misconfiguration - assuming that is what was the issue here.

**Edit having just seen your most recent comment** - It may be your project was running an older stack and the update got you the latest code... not sure. Glad to hear they are now working for you.

@hardillb I think there's some useful insight to be had here around logging of updates - just not sure what that insight is yet.

**Comment by WilliamBonneterre** [comment]
@knolleary The only thing I'm a bit confused about right now is why updating the stack on my project resent my an invoice despite having paid for the project on the 16th of October. As soon as I updated the stack, it sent me an invoice

**Comment by knolleary** [comment]
@WilliamBonneterre noted. The stack upgrade involves a suspend/resume cycle which would remove the project from billing temporarily. I will talk to the team on how we have the stripe integration setup and what the expected result of that is regarding invoicing.

**Comment by WilliamBonneterre** [comment]
I'm unsure as to what the fix was, but yes, it is now working correctly.
