### ISSUE TITLE
Hide/disable Palette Modules settings if stack is too old

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1127]
### Description

If a project stack is running <1.0 it will not have the necessary code in to support the palette module settings provided by #405

The UI should disable that section with a prompt/link to update the project stack to enable the feature.

**Comment by knolleary** [comment]
A complication here; if the project is suspended, we don't know what version of the launcher it is using so we cannot make any decision on what options to show/warn about.

So this will be an at-best solution that, if the version info is available, will prompt.

**Comment by hardillb** [comment]
Verified on staging with a 2.2.3 (launcher 0.9.0) stack
