### ISSUE TITLE
Admin Stack table doesn't use label

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1137]
### Current Behavior

You can now set human readable (none unique) labels for stacks.

These are not used in the Admin Stack table

### Expected Behavior

Admin Stack table should use Stack Label

### Steps To Reproduce

Add Label to stack

### Environment

- FlowForge version: 1.0
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: K8s/Linux
- Browser: All

**Comment by hardillb** [comment]
Current:

![Image](https://user-images.githubusercontent.com/1800845/198007104-f66186f3-6d59-4a7a-bf43-02921366f433.png)

Proposed:

if no label set

![Image](https://user-images.githubusercontent.com/1800845/198007150-f1a7202e-37ee-4b59-b5b4-62407784b54b.png)


if label set


![Image](https://user-images.githubusercontent.com/1800845/198007350-488099b4-ccdf-4381-ae72-83144190e9ba.png)


@joepavitt Thoughts? The label is what's displayed to the user if present, but we also need to keep track of the unique name as an admin creating new stacks.

**Comment by joepavitt** [comment]
I'm happy

**Comment by hardillb** [comment]
Verified on Staging
