### ISSUE TITLE
Pressing return in search box reloads page

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1143]
### Current Behavior

While filtering a table (e.g. users, devices, teams or projects) if you type in the search box and then press enter it reloads the page (and looses the search term)

### Expected Behavior

Not reload the page

### Steps To Reproduce

Open any page with a table + search option
Start typing in the search box
Press enter

### Environment

- FlowForge version: 1.0.0
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: NA
- Browser: Chrome

**Comment by knolleary** [comment]
This needs fixing on forge-ui-components I think... @joepavitt / @Pezmc can one of you pick this up?

**Comment by joepavitt** [comment]
Not sure it is bound to `forge-ui-components` as it's not happening in https://flowforge.github.io/forge-ui-components/#ff-data-table oddly

**Comment by joepavitt** [comment]
I'll take it and investigate

**Comment by joepavitt** [comment]
Even if that is the case, I feel like adding a `v-on:keydown.enter.prevent=""` on the search bar in the underlying component may also be a clean break, given how we use it, we know we don't need to have any on-enter behaviour, and it's a single line fix for all cases (in theory)

**Comment by knolleary** [comment]
That'll do it.

**Comment by joepavitt** [comment]
Not quite as clean as I'd hoped. @Pezmc put in the great work of introducing the standard `<input/>` events for this release, but the `enter` is done on `keyup`, the `submit` action for a form runs on `keydown`, @Pezmc - do you know of any reasons why I wouldn't be able to just change the `keyup` to `keydown` - feel like we discussed this at some point?

**Comment by Pezmc** [comment]
@joepavitt We explicitly spoke about using `keydown` and how it's preferential for submit events, but I don't recall why we chose to stick with `keyup` at the time. Perhaps to solely to reduce the surface of the changes. Nothing is coming to mind as to why it couldn't be changed.

**Comment by joepavitt** [comment]
Good to know, I've removed the unnecessary `<form>` elements anyway (and there were dozens of them) - so it was a good clean up exercise anyway.
