### ISSUE TITLE
Email features do not pick up if email server is offline when FF launches

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1159]
### Current Behavior

When starting up FF, if the mailbox is offline, but comes online soon/anytime after FF is started, FF mailbox features remain disabled until forge is restarted.

### Expected Behavior

For forge to recover automatically / gracefully

### Steps To Reproduce

* stop SMTP server (or make it appear offline)
* start FF
* start SMTP
* no amount of time or refreshes restore mailbox features in FF

### Environment

- FlowForge version: 1.0
- Node.js version: 16
- Platform/OS: Windows
- Browser: Chrome

**Comment by hardillb** [comment]
On Staging

I can see the new `Connected to AWS SES` log message

And I managed to trigger a "Please verify your email address" email so email is still working.
