### ISSUE TITLE
Text overflows input field

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1161]
### Current Behavior

long version overflows field

![Image](https://user-images.githubusercontent.com/44235289/197550591-6b157dd3-9ea8-4445-b445-aafc01c0cb4b.gif)

See here: https://github.com/flowforge/flowforge/issues/405#issuecomment-1289125480

### Expected Behavior

either scroll text, wrap text or expand field size.

### Steps To Reproduce

enter a long value

### Environment

- FlowForge version: 1.0
- Platform/OS: Windows
- Browser: Chrome

**Comment by Pezmc** [comment]
Seems to be caused by the actual input element being wider than the parent (despite having flex set):

<img width="312" alt="Screenshot 2022-10-28 at 16 26 19" src="https://user-images.githubusercontent.com/507155/198644275-8d54a96b-40ae-4a9c-916e-cccacd31a459.png">

**Comment by Steve-Mcl** [comment]
Verified on staging
