### ISSUE TITLE
Pagination broken on stacks page

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1164]
### Current Behavior

Pagination keeps returning the first page from the API

![2022-10-28 13 39 57](https://user-images.githubusercontent.com/507155/198579059-9269d81d-7113-460b-83d4-5e0205569316.gif)

### Expected Behavior

Should return new results and add them to the bottom of the list

### Steps To Reproduce

Have enough stacks to trigger pagination for stacks, click load more.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by robmarcer** [comment]
I'm assuming this is a bug for the purpose of the release blog. I'll also add the bug tag.
