### ISSUE TITLE
Audit Logging

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1166]
### Description

Improve UX of Audit Logging at the project/team/platform levels

**Stories - Audit Log 1.0:**
- [x] #1183
- [x] #428

**Stories - Audit Log 1.5:**
- [ ] #1448

**Stories - Audit Log 2.0:**
- [ ] #517 - this expected UX requires a singular view of _all_ audit events in a given scope. For example, when viewing the Platform audit log events, I would expect to see everything, including team/project level events. The concept of filtering can be applied at 1.0, but does offer less value.

**Comment by joepavitt** [comment]
Stage 1.0 already in `main` for the 1.2 Release. Stage 1.5 and 2.0 will be pushed back, not worth rushing in

**Comment by knolleary** [comment]
Closing this epic as the core audit logging improvements have been made.

The following pieces (1.5/2.0 as described above) have their own issues for planning/tracking etc.
