### ISSUE TITLE
Unable to delete a suspended project - docker driver

### ISSUE THREAD

**Issue by flecoufle** [flowforge/flowforge#1168]
### Current Behavior

Errors when deleting a suspended project with a docker container driver (workaround restart and then delete it)

![delete project](https://user-images.githubusercontent.com/47251384/198695132-6ef15a2c-9131-41f6-aeb2-508e15c9f011.png)

### Expected Behavior

Delete a suspended project should be OK (otherwise disable the delete) 

### Steps To Reproduce

- create project
- suspend it
- delete it

### Environment

- FlowForge version: 1.0.1
- Node.js version: v16.16.0
- npm version: 8.11.0
- Platform/OS: armv7l/HypriotOS
- Browser: Chrome

- Node-RED Version: 3.0.2
- Launcher Version: 1.0.0

**Comment by hardillb** [comment]
Thanks for raising this, I think I can see where the problem is, will get to it on Monday morning
