### ISSUE TITLE
Friendly stack name not shown in the Change Project Stack option list

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1169]
### Current Behavior

![image](https://user-images.githubusercontent.com/44235289/198990196-97370078-c09e-405e-8a8d-c28bea115d3b.png)

### Expected Behavior

Should show the label as per description
![image](https://user-images.githubusercontent.com/44235289/198990279-4787eae8-61d6-4045-9461-44ef945c2138.png)

### Steps To Reproduce

Operate the "Change Stack" on a project

### Environment

- FlowForge version: 1.0

**Comment by Steve-Mcl** [comment]
Unable to verify on staging due to #1260

**Comment by ZJvandeWeg** [comment]
Verified on staging, while this issue was resolved I uncovered a new one: https://github.com/flowforge/flowforge/issues/1289
