### ISSUE TITLE
Deployments: Add FF Cloud/Local to page

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1176]
### Description

<img width="1353" alt="Screenshot 2022-11-02 at 08 45 18" src="https://user-images.githubusercontent.com/507155/199441753-372782d8-1ea4-4232-835a-c5393012415e.png">

### Epic/Story

#1046

**Comment by knolleary** [comment]
I dare say 'Managed' could be the right label to use for this. Given we don't know where the instance is hosted, picking Cloud/Local could be misleading.

**Comment by Pezmc** [comment]
@hardillb Is the current deployment information (see the first row of the cloud/local table) already available in the API somewhere?

**Comment by hardillb** [comment]
It's `base_url` on the `app.config` object. Not sure if that is made available to the UI off the top of my head
