### ISSUE TITLE
Document Devices Environment variables

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1185]
### Description

Devices executing flows expose environment variables. Which are exposed and what their values are isn't currently documented.

**Comment by robmarcer** [comment]
https://github.com/flowforge/flowforge/blob/Add-details-of-new-env-var-features/docs/user/envvar.md

**Comment by robmarcer** [comment]
https://github.com/flowforge/flowforge/pull/1217
