### ISSUE TITLE
Rollbacks crash Node-RED

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1186]
### Current Behavior

When rolling back to a snapshot, the editor and runtime are stuck in an 'installing' state indefinitely.

### Expected Behavior

The roll back is applied, and Node-RED comes back online

### Environment

- FlowForge version: v1.0
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Verified fixed in staging and 1.0.2 production
