### ISSUE TITLE
Add project type/template/stack stage to Setup process

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1194]
### Description

**As a:** user installing FlowForge for the first time

**I want to:** be helped to create my first Project Type, Template and Stack

**So that:** I have to read less documentation and get a running Node-RED project as quickly as possible.

---

Our current install process requires an Admin to create a Project Type, Template and Stack before any projects can be created. We don't provide much help in doing that and expect a new user to quickly learn what those things are and what needs doing.

The Setup wizard should provide help so much of this can be automated with a minimum of input from the user.

1. Project Type - we can create a default Project Type with a suitable name/description.
2. Template - we can create a default template using all default values
3. Stack - this gets a *little* tricker as it will rely on the user doing *something* to get the stack into place. The wizard should be able to provide accurate instructions for the chosen driver. For localfs, that should be the appropriate set of commands to run (with all the correct paths set) that can be copy/pasted into a terminal. For docker/k8s, something else is needed - tbd.

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

- [ ] Project Type/Stack/Template are setup as part of the first-run setup wizard
- [ ] Install documentation updated to reflect the change
- [ ] First-run doc screenshots updated

**Comment by ZJvandeWeg** [comment]
> I want to: be helped to create my first Project Type, Template and Stack

> The Setup wizard should provide help so much of this can be automated with a minimum of input from the user.

@knolleary Was brainstorming with @joepavitt on this during our 1:1 and we figured: "Why put this in the wizard and not just install a default?" That seems to cut down the scope of this issue, and be more effective for the end user too. What do you think?

**Comment by knolleary** [comment]
For ProjectType/Template, we can. ProjectStack is more complicated, because the user has to do *something* outside of the platform, or provide a piece of information (stack container id, or version number) that we don't know.

But the goal is to minimise the work as much as possible.

**Comment by knolleary** [comment]
Notes from design call between @hardillb and me

 - Localfs
   - [ ] Update `install-stacks` script to be able to install `latest` and have it work out the version number to rename the stack dir properly (avoid conflict if already exists)
   - [ ] Remove question about installing stack from the install script and just do the install

 - [ ] Add `getDefaultStackProperties` api to each container driver (localfs/docker/k8s) that returns the appropriate default values for that driver.
   - [ ] Localfs can scan the stacks directory and pick up the latest stack if finds (should only be one)
   - [ ] docker/k8s - return a hardcoded set of properties using our dockerhub published container name
   - [ ] Default to 256Mb memory, 10% CPU
   -  [ ] If, for any reason, the driver cannot provide defaults (eg localfs cannot find a stack) then it should throw an error.
 - [ ] Setup process can use that api to get the properties needed to create the default stack without having to prompt the user. If there's an error, we can prompt the user appropriately rather than leave them in limbo.

**Comment by hardillb** [comment]
- [ ] Update the container wrapper to add the `getDefaultStackProperties()` function
