### ISSUE TITLE
Ensure FlowForge File nodes do not get pushed to Device with a snapshot

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1202]
### Description

Devices should not use the network file store.

**Comment by Steve-Mcl** [comment]
Just had a thought - I want to get it down as I dont have time to look into this right now and dont want it to be missed...

When we use the new nr-file-nodes in cloud env, are we adding `10-files.js` to the "Palette" -> "Exclude nodes by filename" ? 
If so, does that also exclude them from the device project? (sorry for the noise if that was the intention of this issue Ben)

**Comment by hardillb** [comment]
OK, so how the @flowforge/nr-filenodes are setup they don't load if the config is not present, and we don't setup the config in the device agent.

To answer @Steve-Mcl's question, we also don't pass the module exclude list to the device agent so the default file nodes are available.

I'm going ot say that this is not a problem as things stand.

**Comment by Steve-Mcl** [comment]
Checked and file nodes are not delivered to device
