### ISSUE TITLE
Persistent context storage not avaialble 

### ISSUE THREAD

**Issue by akashtalole** [flowforge/flowforge#1206]
### Current Behavior

User not able to define context storage options e.g. InMemory/ File

### Expected Behavior

FF should provide persistent context storage option.

### Environment

- FlowForge version: v1.0.2
- Node.js version: v16.17.0
- npm version:
- Platform/OS: Windows 11 Docker
- Browser: Chrome

**Comment by knolleary** [comment]
Hi @akashtalole 

We already have this on the backlog with #212 .

**Comment by akashtalole** [comment]
Thanks @knolleary
