### ISSUE TITLE
Blank page when user accepts invitation for joining team

### ISSUE THREAD

**Issue by akashtalole** [flowforge/flowforge#1208]
### Current Behavior

After accpeting invite for joining team, menu and other options not visible. User need to refresh page and then user is able to see side menu and page.

### Expected Behavior

After accepting invite, respective user menu shall be showcase automatically.

### Steps To Reproduce

add new user
add user to team
login with new user
accept invite

### Environment

- FlowForge version:  v1.0.2
- Node.js version: v16.17.0
- npm version:
- Platform/OS: Winndows 11 Docker
- Browser: Chrome

**Comment by joepavitt** [comment]
Thanks for raising @akashtalole - we'll get on fixing this for this coming release.

**Comment by joepavitt** [comment]
Tried to reproduce initially and failed, but then found that the catch is that the new user invited cannot already be a part of any team:

https://user-images.githubusercontent.com/99246719/201308229-3cb99243-23fa-4f4b-99cc-a04c3304d27c.mov

**Comment by akashtalole** [comment]
It happens when user is added first time in any team.

**Comment by akashtalole** [comment]
Thanks
