### ISSUE TITLE
Rollback breaks project if modules are defined in settings

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1213]
### Current Behavior

Rolling back a snapshot causes the palette modules defined in FF to be transformed from an array to a KV object.
Because of this, the project cannot be started (errors with `ERROR: moduleList.forEach is not a function {"reqId":"req-2r","req":{"method":"GET","url":"/api/v1/projects/05fe4b48-480f-4c35-82e6-6a57919e4f4c/settings","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":53238},"res":{"statusCode":500}}` at [`db\controllers\Project.js:76:20`](https://github.com/flowforge/flowforge/blob/main/forge/db/controllers/Project.js#L76)

#### Copied project settings (project starts OK)
```json
{
    "header": {
        "title": "copy-of-proj"
    },
    "palette": {
        "modules": [
            {
                "name": "node-red-contrib-buffer-parser",
                "version": "*",
                "local": true
            },
            {
                "name": "node-red-contrib-cron-plus",
                "version": "*",
                "local": true
            }
        ]
    },
    "disableTours": true,
    "env": [
        {
            "name": "changed-by-me",
            "value": "value is 321"
        }
    ],
    "dashboardUI": "/dash"
}
```

#### Project settings after rollback
```json
{
    "header": {
        "title": "copy-of-proj"
    },
    "palette": {
        "modules": {
            "node-red-contrib-buffer-parser": "*",
            "node-red-contrib-cron-plus": "*"
        },
        "allowInstall": true
    },
    "disableTours": true,
    "env": [
        {
            "name": "changed-by-me",
            "value": "value is 321"
        }
    ],
    "dashboardUI": "/dash",
    "disableEditor": false,
    "httpAdminRoot": "",
    "codeEditor": "monaco",
    "theme": "forge-light",
    "timeZone": "UTC",
    "modules": {
        "allowInstall": true
    },
    "httpNodeAuth": {
        "user": "",
        "pass": ""
    }
}
```

#### NOTE

The format of the modules as stored in the snapshot are KV `object` form.  
I suspect they need to be re-transformed when restored or not transformed in the first place.

e.g...
```json
{
    "settings": {
        /* snip for brevity */
        "timeZone": "UTC",
        "palette": {
            "allowInstall": true,
            "modules": {
                "node-red-contrib-buffer-parser": "*",
                "node-red-contrib-cron-plus": "*"
            }
        },
        "modules": {
            "allowInstall": true,
            "denyList": []
        },
        "dashboardUI": "/dash"
    },
    "env": { /* snip for brevity */ }
    "modules": {
        "node-red": "3.0.2",
        "@flowforge/flowforge-nr-files": "0.0.1",
        "@flowforge/nr-project-nodes": "0.1.1",
        "node-red-contrib-buffer-parser": "3.2.2",
        "node-red-contrib-cron-plus": "1.5.7"
    }
}
```

Also, after rolling back a snapshot with modules, they are no longer read in the editor correctly...
![image](https://user-images.githubusercontent.com/44235289/201489397-ec8fb7dd-eb4b-4edb-8c57-08986da9d419.png)

<br>

### Expected Behavior

rollback to work

### Steps To Reproduce

* create project and add a simple flow
* add modules in FF project/xxx-yyy-zzz/settings/palette
* restart project and ensure working
* create a snapshot (name it V1)
* modify flows and deploy
* create a snapshot (name it V2)
* select snapshot V1 and click "rollback"

<br>

### Environment

- FlowForge version: 1.0.0-git
- Node.js version: 16
- Platform/OS: Win

**Comment by knolleary** [comment]
This was fixed in pr #1192 and released in 1.0.2

Can you check you have the latest code pulled?

**Comment by Steve-Mcl** [comment]
That'll likely be it - I don't think I've pulled since V1 release.
Will check it out and close if fixed.

Ta.

**Comment by Steve-Mcl** [comment]
My apologies, this was due to my code base being out of step with main

All is good :)
