### ISSUE TITLE
Provide API to provision agents at scale

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1218]
### Description

When creating many devices for a team or pre-assigned to a project there's a lot of manual steps to make this work. When a customer is onboarding say over 100 devices; it's a lot of manual work to do so.

It would be great if the agent could start with a flag that allows a cookie cutter approach to provision devices. For example if you can start the agent like `flowforge-device-agent --token="foo" --host="app.flowforge.com"` where `foo` is a secret known to the host; it might check if a `device.yml` is present in the directory. If not, it obtains it from the host.

**Comment by hardillb** [comment]
duplicate of #1212

**Comment by ZJvandeWeg** [comment]
Closing in favour of #1212
