### ISSUE TITLE
Enable tax id collection when creating Stripe Subscription

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1230]
### Description

To ensure proper reporting of tax, we need Stripe to gather VAT numbers where applicable.

This is done by adding:

```
  tax_id_collection: {
    enabled: true,
  }
```

to the options passed to `stripe.checkout.sessions.create({...})` in `forge/ee/lib/nilling/index.js`.
Reference: https://stripe.com/docs/tax/checkout/tax-ids

Once enabled, the user should able to self-identify as a business and provide a VAT number:

<img width="517" alt="Cursor_and_FlowForge_Inc" src="https://user-images.githubusercontent.com/51083/202183248-6966f94f-d533-4c3b-af5e-1cb463324212.png">

**Comment by ZJvandeWeg** [comment]
Verified on staging. There's no documentation updates though @knolleary. What if this field ever changes, how do customers go about updating these fields? Or if the checkbox was missed initially?
