### ISSUE TITLE
Is possible to get a project status stuck in an intermediate state

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1232]
### Current Behavior

Related to "Difficulty editing project settings when project state is intermediate" #1231 where the settings page was effectively unusable due to status refreshing...

It is possible to get a project stuck on an intermediate state e.g. not stopped/not suspended/not started.

##### Other notes...

* For the short time my environment was in this state (approx 10 mins) the `out.log` was littered with around 650 lines containing the following repeated pattern...
```
Loading project settings
Target state is 'running'
Starting Node-RED
/** snipped for brevity **/
Loading project settings
Target state is 'running'
Starting Node-RED
```

### Expected Behavior

Unsure - perhpas there should be a specific state like "Stalled"?

### Steps To Reproduce

1. Stop a project 
2. Edit the project settings and add a non-existing NPM package to the packages table
3. Save settings
4. Start the project 

### Environment

- FlowForge version: 1.0.3-git

**Comment by Steve-Mcl** [comment]
@hardillb 

I would appreciate you testing the PRs for this issue in docker/k8s env if you can? 

#### Steps to test before this PR...
1. Stop a project
2. Edit the project settings and add a non-existing NPM package to the packages table
3. Save settings
4. Start the project
     1. Expect to see state stuck at "installing"


#### Steps to test after PR is applied...
1. Stop a project
2. Edit the project settings and add a non-existing NPM package to the packages table
3. Save settings
4. Start the project
     1. Expect to see state return to `stopped`
     2. Expect to see events updated in the "Recent Activity"
5. In the action menu, try to start/restart
     1. Expect to see state return to `stopped`
     2. Expect to see events updated in the "Recent Activity"

**Comment by hardillb** [comment]
Works on K8s

**Comment by hardillb** [comment]
Works on docker

**Comment by hardillb** [comment]
@Steve-Mcl  Only problem is that the page doesn't stop polling when it enters Stopped state so you can't edit the settings again until you reload the page.

**Comment by Steve-Mcl** [comment]
Tested in both staging an latest git ...

![Image](https://user-images.githubusercontent.com/44235289/213159409-9f0deef5-0ff7-46a7-af4f-8b33678399b1.png)
