### ISSUE TITLE
Add Flow Debugger to default project image

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1233]
### Description

**As a:** flow developer

**I want to:** use the Node-RED Flow Debugger - https://flows.nodered.org/node/node-red-debugger

**So that:** I can add breakpoints and debug my flow

---

The Flow Debugger is a plugin we published last year, but as it's not a default plugin, it doesn't get much coverage.

Being able to add breakpoints to flows, pause them and examine the messages is a capability many other low-code tools don't have.

We should add it as a default installed plugin within FlowForge projects to emphasis the enterprise-/production-ready messaging.

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

- [ ] A newly created project has the Flow Debugger preinstalled

**Comment by MarianRaphael** [comment]
See also https://github.com/flowforge/flowforge/issues/2002 as a possible implementation path.

**Comment by knolleary** [comment]
I believe that once we have #2002 deployed in production, the solution to this will be to update the Template in FF Cloud to include this module. We can verify that approach on Staging now. Note this will should only lead it to be added to newly created instances - existing instances don't re-inherit changes to the template module list.

**Comment by hardillb** [comment]
OK, I'd seen as #2002 as a option, was just about to patch the launcher, will leave it alone until release day.

I'll keep it assigned to me as I can make the change as part of the production deployment.

**Comment by hardillb** [comment]
@Steve-Mcl I made the change, then backed it out, but it still needed the package-lock.json adding so I reused the same branch. The comment in the commit history triggered the closure, but didn't actually make the change, hence I have re-opend the issue.

The code change didn't actually get made.

**Comment by Steve-Mcl** [comment]
ah, my bad.  Thanks for the clarification Ben.

**Comment by MarianRaphael** [comment]
Issue paused, clarification needed.

**Comment by hardillb** [comment]
Tested on staging, happy to apply
