### ISSUE TITLE
Add nrlint to default project image

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1234]
### Description

**As a:** flow developer

**I want to:** ensure my flows follow best practices 

**So that:** I can avoid common mistakes and benefit from the help a linting tool can provide

---

`nrlint` is the Node-RED linting tool we published last year - https://www.npmjs.com/package/nrlint

It is the framework through which we can apply rules to a set of flows and flag up any potential issues.

Having linting by default within FlowForge would be something to highlight in the platform given it isn't a widely known tool in the community.

We should look at how to incorporate into the default project image.

### Which customers would this be availble to

All Users, (CE)

**Comment by MarianRaphael** [comment]
See also https://github.com/flowforge/flowforge/issues/2002 as a possible implementation path.

**Comment by hardillb** [comment]
Grabbing along with #1233 to do as part of the release

**Comment by hardillb** [comment]
Tested with staging, happy to apply.
