### ISSUE TITLE
left over debug console logs?

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1242]
### Current Behavior

Seeing a log of console logs related to oauth...

![image](https://user-images.githubusercontent.com/44235289/202689516-e263624f-8022-48e5-863d-2efe083943ed.png)

https://github.com/flowforge/flowforge/blob/ade243c3734316f34b0c5d56a3ee37e2b344b14e/forge/routes/auth/oauth.js#L172

### Expected Behavior

Not certain we want these?

### Steps To Reproduce

run FF from Git

### Environment

- FlowForge version: 1.0.3-git

**Comment by knolleary** [comment]
Just to remove any doubt - *anything* being console.log'd is a bug that should be removed or modified to a log statement.

This one slipped out with the recent oauth changes - will be tidied up with the Plugin Oauth PR later today

**Comment by Steve-Mcl** [comment]
Fixed in https://github.com/flowforge/flowforge/commit/baacf246b58a3bcbeb11e4601a96d0c748226c5e#diff-6d0da06aa1c965191ab86facf2b73b62631b82fa422e5a034edf64a1ef09124aL172
