### ISSUE TITLE
Update GH Action for installer to not include the version number in filename

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1243]
### Description

This is to ensure we can create a static link to the latest release installer.zip

https://github.com/flowforge/installer/blob/main/.github/workflows/release.yml

**Comment by UlisesGascon** [comment]
Hi @hardillb! I will love to help with this :)

What is the expected output from the GH Action? 

I believe something like the following log message can cover the gap? 🤔

```
🎉 Release ready at https://github.com/flowforge/installer/releases/download/v1.3.0/flowforge-installer.zip
```

**Comment by hardillb** [comment]
@UlisesGascon Thanks for looks at this, it appears we had a duplicate issue on the flowforge/installer project and this has already been completed under https://github.com/flowforge/installer/issues/56

**Comment by UlisesGascon** [comment]
thanks for the update @hardillb!
