### ISSUE TITLE
Label for Checkbox not displayed in-line

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1246]
### Current Behavior

Noticed during Developer Demo

![chrome_9E8svXReyL](https://user-images.githubusercontent.com/44235289/202853897-01a02396-e3d4-409e-b8c7-cd92681f6230.gif)

In startup screen, the checkbox label is being indiscriminately set to `display:block` due to `.ff-layout--box--content label` CSS

### Expected Behavior

Label should be inline with check

### Steps To Reproduce

Start new FF instance & follow installer to Step 3

### Environment

- FlowForge version: 1.0.3

**Comment by joepavitt** [comment]
<img width="722" alt="Screenshot 2022-11-22 at 11 08 10" src="https://user-images.githubusercontent.com/99246719/203299190-7b5dda17-9d6c-4564-a815-025f120a0a21.png">

Just checked the `1133-form-row` branch for https://github.com/flowforge/flowforge/pull/1201 and it's okay there as I suspected it would be, as that re-writes the `checkbox` form row structure. Will wait for that to get merged and verify in `main`, but this issue should get resolved there.

**Comment by joepavitt** [comment]
verified that #1201, now merged in `main` fixes this
