### ISSUE TITLE
Hamburger menu showing scrollbar

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1259]
### Current Behavior

click on the hamburger menu in top right and see a scrollbar

![Screenshot from 2022-11-21 15-06-17](https://user-images.githubusercontent.com/1800845/203089337-44dd5f07-be8a-40e1-a094-8c3bdeae5c8d.png)

### Expected Behavior

No scrollbars

![Screenshot from 2022-11-21 15-13-06](https://user-images.githubusercontent.com/1800845/203090127-37d79ea0-ccc7-432c-b1a3-c04ec339005b.png)

### Steps To Reproduce

Log in to staging as an admin and click the top right hand corner

### Environment

- FlowForge version: v1.0.2-84519e0-20221121.0 (staging build 20221121)
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: k8s/linux
- Browser: chrome

**Comment by Steve-Mcl** [comment]
Ben, I cannot re-create this.

Tried lots of things (zoom in/out, resize, etc)

What browser, version and OS did you see this?

**Comment by hardillb** [comment]
Browser:
Chrome 107.0.5304.110 (Official Build) (64-bit) on Linux

And Firefox

![Screenshot from 2022-11-21 19-35-29](https://user-images.githubusercontent.com/1800845/203143524-1c2fb8b6-3716-47dc-ad5a-bd6c0425a949.png)


@Steve-Mcl Have you pulled the latest forge-ui-componets and rebuilt it?

**Comment by Steve-Mcl** [comment]
Ah - no, I have not - good shout.

**Comment by joepavitt** [comment]
It is something to do with ui-components, but will be resolved in #1201

**Comment by joepavitt** [comment]
verified - now that #1201 is closed & merged, this no longer happens in `main`
