### ISSUE TITLE
Admin Stacks page not rendering

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1260]
### Current Behavior

No stacks showing

![Screenshot from 2022-11-21 15-16-37](https://user-images.githubusercontent.com/1800845/203090875-c04d90e2-1db0-4dbc-9a2c-1a4a75781a63.png)

### Expected Behavior

See all available stacks

e.g.

![Screenshot from 2022-11-21 15-17-20](https://user-images.githubusercontent.com/1800845/203091034-1aa2385d-8b1e-4501-980b-9133be177caa.png)

### Steps To Reproduce

Log in to staging as admin
click top right select admin settings
click on stacks in left hand menu

### Environment

- FlowForge version: v1.0.2-84519e0-20221121.0 (staging build 20221121)
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: k8s/linux
- Browser: Chrome

**Comment by joepavitt** [comment]
Unable to reproduce this currently on local (`main`) - will wait for latest staging build to finish and check there too

**Comment by ZJvandeWeg** [comment]
Verified on staging this is completed
