### ISSUE TITLE
Odd menu behavior when sizing FF webmin

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1269]
### Current Behavior

Hard to explain - see below...

Desktop...
![Code_2ntFliQzvF](https://user-images.githubusercontent.com/44235289/203141836-dd2b4b09-f0ab-4cd9-9fb3-335e4090a3f5.gif)

Mobile...
![chrome_abYbeCkIEt](https://user-images.githubusercontent.com/44235289/203142508-a7a34172-0ec7-4b4a-a714-4479176d34f0.gif)

### Expected Behavior

Menu should disappear when clicking outside its confines

### Steps To Reproduce

1. Size down browser to collapse sidebar (resize-down/rotate-portrait)
2. open the menu
3. note how it cannot be dismissed by clicking outside of the menu (intentional)
4. with the menu open, resize the browser  (resize-up/rotate-landscape)
5. menu cannot be dismissed

### Environment

- FlowForge version: 1.0.x-git
- Platform/OS: Win 11
- Browser: Chrome latest

**Comment by MarianRaphael** [comment]
Should be fixed with https://github.com/flowforge/flowforge/pull/1201
