### ISSUE TITLE
Allow writing of documentation for users and administrators

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#127]
The current documentation is generated through `jsdoc` and oriented at developers. However, as a user or administrator I'd like to be able to read how certain actions should be performed.

Requirements:
- Allow users and developers alike to easily update the documentation
- Have documentation and code in the same repository to update in lock-step

Nice to have:
- Rich formatting options (Markdown?)

**Comment by knolleary** [comment]
The main remaining tasks are more about publishing the docs on the website. I have raised https://github.com/flowforge/website/issues/40 to cover that side of things and I think we can close this off as the original requirement is satisfied.
