### ISSUE TITLE
Multithreading on Node Red

### ISSUE THREAD

**Issue by rajeen2001** [flowforge/flowforge#1287]
### Description

How can it be done to basically allocate and assign CPU allocations to different applications to multithread on Node-Red

**Comment by knolleary** [comment]
Hi @rajeen2001 

For general Node-RED questions, it's best to use the community forum: https://discourse.nodered.org

Node-RED is built on top of node.js which, essentially is a single threaded runtime. It isn't possible to make a single Node-RED instance use multiple CPUs.

If you can share more details on what exactly you're trying to do, we may be able to provide some advice.

**Comment by Steve-Mcl** [comment]
@rajeen2001 are you asking about CPU affinity assignment of Node-RED instances?

Also, please state what install of FF you are using (localfs, docker, k8s)?

**Comment by MarianRaphael** [comment]
It appears that this particular issue should be covered by the epic https://github.com/flowforge/flowforge/issues/1678, which is still in progress. While it may not be directly related to multithreading, it does pertain to the possibilities of scaling Node-RED.

Don't hesitate to follow the progress of the epic and contribute to the discussion if you have any further concerns.
