### ISSUE TITLE
Change stack dropdown doesn't render correctly

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1289]
### Current Behavior

When opening the dialog to change the stack I see only one option:
![Screenshot 2022-11-23 at 09 42 31](https://user-images.githubusercontent.com/2529595/203503548-f076fa47-7687-43a9-9b35-bb1d0f2d5732.png)

It requires scrolling of text pane to show multiple options
![Screenshot 2022-11-23 at 09 42 38](https://user-images.githubusercontent.com/2529595/203503550-1f19c8a2-4258-4a71-85e6-631579f7ad19.png)

### Expected Behavior

The dropdown renders at least the first 2 to 5 options without scrolling. The dropdown pane should be larger

### Environment

- FlowForge version: Staging (release candidate 1 for 1.1?)
- Node.js version:
- npm version:
- Platform/OS:
- Browser: Chrome

**Comment by Pezmc** [comment]
Introduced in https://github.com/flowforge/flowforge/pull/1201

**Comment by Steve-Mcl** [comment]
verified on staging
