### ISSUE TITLE
Document what statistics are shared and how

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#129]
When starting a new FlowForge install, one of the steps is to choose to opt-in to sharing data back to FlowForge Inc. 

For an administrator it's unclear what data is obtained and how/when this is done. Documenting this would aid in transparency to the end-user and help them decide what is shared and why.

**Comment by joepavitt** [comment]
@knolleary just checking that you want that `md` file to be available in the github repo (and linked to from the app), but not as a page in the actual FlowForge app? Or do you want to render the `md` in the app too?

**Comment by knolleary** [comment]
@joepavitt right now we just want the page added to the docs.

There is a separate story around making the docs available in the platform. For now we link to the GH repo.

**Comment by joepavitt** [comment]
will we link to this directly from the notification/message in #291 too?
