### ISSUE TITLE
Deployments UI crashes after deploying a snapshot to devices

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#1302]
### Current Behavior

FlowForge's interface seems to crash once I use the button to deploy a snapshot in the new Deployments section.

https://d.pr/v/bwbuKS

### Expected Behavior

The interface should remain responsive to user interaction and data coming back from the devices.

### Steps To Reproduce

On staging use the Target Snapshot interface to deploy a snapshot to the devices. Once you've done this the UI should stop responding until you manually refresh your browser.

### Environment

- FlowForge version: Staging for 1.1
- Node.js version: Staging for 1.1
- npm version: Staging for 1.1
- Platform/OS: Mac M1 latest
- Browser: Chrome latest

**Comment by Steve-Mcl** [comment]
@robmarcer I suspect this should be added to 1.1 milestone as a bug for visibility (it can always be triaged out if it is a "your side of things" problem :)

**Comment by Pezmc** [comment]
Struggling to re-produce on staging, from the video it looks like JS bug is crashing vue entirely, which is why the UI is unresponsive. @robmarcer can you add more reproduction details and/or share your console log at the time of the error?

**Comment by robmarcer** [comment]
@Pezmc hope this helps - https://d.pr/v/cyKmgs
