### ISSUE TITLE
dropdown only shows one item (have to scroll for others)

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1305]
### Current Behavior

![chrome_av0OQhQ1rd](https://user-images.githubusercontent.com/44235289/203757062-183e21fb-c899-4157-ab9d-672435654e23.gif)

### Expected Behavior

* no scrolling.

### Steps To Reproduce

on team devices, click the kebab menu then "add to project"

### Environment

- FlowForge version: 1.1.0-git

- Platform/OS: Win 11
- Browser: Chrome

**Comment by knolleary** [comment]
Sounds very similar to https://github.com/flowforge/flowforge/issues/1289 which has been fixed and verified.

@Pezmc it looks like the fix for #1289 was only applied to the one dialog. Is the same fix needed here?

**Comment by Steve-Mcl** [comment]
Verified locally.
To test on staging (if we have a respin before release)
