### ISSUE TITLE
Leverage FlowForge credentials instead of http node auth

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1325]
**As a:** user
**I want to:** sign in to HTTP pages with my FlowForge credentials
**So that:** I don't have to share usernames and passwords

---

Node-RED has very basic support for [authentication of pages](https://nodered.org/docs/user-guide/runtime/securing-node-red#http-node-security).

We expose this in the Project Settings within FF.

However this is not always suitable for users:

1. It only supports a single, hardcoded username and password. This is not appropriate for multiple users, having to share passwords. This would fail to meet many organisation's security policies
2. It only supports Basic Auth - again, this would fall foul of some org's acceptable policy

This story will allow a user to select to secure their HTTP Endpoints with their FlowForge login.

When accessing a Node-RED hosted endpoint, if they are not currently logged in, they will be redirected to the FF login page and redirected back once signed in.

**Comment by ZJvandeWeg** [comment]
cc @knolleary for feasibility analysis

**Comment by hardillb** [comment]
Just my 2cents

I have built a solution like this in the past by using the ability to inject a custom middleware block into the `settings.js` file, but I think we have to consider that the http-nodes/dashboard are targeted at different users than access to the FlowForge Platform and access to the Node-RED editor.

A FlowForge user may build a apu/dashboard/web app in Node-RED and then want to grant secured access to a totally different set of users.

I think a better solution (that could also be backed by FlowForge credentials) is allow httpNodeAuth to support an external list of users (so not single user/password)

**Comment by knolleary** [comment]
This item is specifically to provide an option to support securing the HTTP end points via a FF login - and for this to apply across all http nodes/dashboards etc.

The Project Settings currently allow the user to provide Username/Password on the 'Editor' section of settings. That is a slightly odd place for that option to exist .

<img width="529" alt="image" src="https://user-images.githubusercontent.com/51083/207299966-fecaaae9-8807-4308-b949-b290a376052c.png">

1. Add new 'Security' section to Project Settings.
2. Move the 'HTTP Nodes' options to that section.
3. Add radio box options for auth-type
    1. Basic Auth (the existing username/password option)
    2. Add 'Require FlowForge login'

This gives us scope to add other options in the future.

If 'Require FF login' is enabled, then a custom middleware will be added using passport to enable oauth on those routes. We *should* be able to reuse a lot of the work in the existing ff auth plugin here. The key will be getting the passport bits right, including a new cookie-based session token (as the Node-RED editor does it's own thing for session tokens that cannot be reused).

**Comment by knolleary** [comment]
Here is what the new Security section of Project Settings will look like:

![Image](https://user-images.githubusercontent.com/51083/211337154-238cc7cb-db46-427c-a023-fd29033ca7a1.png)

**Comment by hardillb** [comment]
This has been verified on Staging
