### ISSUE TITLE
Update Audit Log to render new data format

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1340]
### Description

With the work conducted in https://github.com/flowforge/flowforge/issues/1183 we now need to update the Audit Log UI to display the new design's icon and verbose messaging for each audit log. 

This task will encompass the format changing of each row of the audit log, and updates to the Audit Log component to render the new icons & verbose language for each audit entry type.

### Epic/Story

#428

**Comment by joepavitt** [comment]
<img width="1363" alt="Screenshot 2022-12-01 at 09 20 48" src="https://user-images.githubusercontent.com/99246719/205014680-a9a305c7-c5af-4b95-9406-34c1bf018236.png">

**Comment by joepavitt** [comment]
Have decided to render the raw `body` in the case of an error, these will be too diverse for us to produce natural language outputs for now - if customers call for it in the future, we can format them.

<img width="1339" alt="Screenshot 2022-12-01 at 09 21 09" src="https://user-images.githubusercontent.com/99246719/205014759-ab45a927-7b04-42cf-8371-d664b9775942.png">

**Comment by Steve-Mcl** [comment]
> Have decided to render the raw `body` in the case of an error, these will be too diverse for us to produce natural language outputs for now - if customers call for it in the future, we can format them.
> 
> <img alt="Screenshot 2022-12-01 at 09 21 09" width="1339" src="https://user-images.githubusercontent.com/99246719/205014759-ab45a927-7b04-42cf-8371-d664b9775942.png">

Joe, would a `<details>` (details disclosure element) not be a good fit for errors?

**Comment by joepavitt** [comment]
Sensible - happy with it as it for now though in the interest of holding up this PR, and can add it as a smaller task alongside the accordion date cleaning.
