### ISSUE TITLE
Node Red - Unable to find nodes in Manage Pallet > Install Nodes

### ISSUE THREAD

**Issue by blueoceans2002** [flowforge/flowforge#1367]
### Current Behavior

Hi,
I am completely new to node red.
In a regular node red, I am able to install the nodes from manage palette. Interestingly in Project based node red I am unable find and install the nodes. I have this feature enabled in project setting. Any help will be highly appreciated. Big thanks

![image](https://user-images.githubusercontent.com/119927769/205864006-53d74c4f-e0d2-47c8-9385-2913f92bca31.png)

### Expected Behavior

In a regular node red, I am able to install the nodes from manage palette.

### Steps To Reproduce

1.Click on Projects and select any one project
2.Open Editor
3. In Node red click on Hamburger menu and then click on Manage Pallet to open "User setting" model
4. Go to Palette, click on install tab
5. In the search type "UI" or "dashboard" to find a list of nodes
6. The search should result in list of nodes but in my case no nodes are being rendered. 

### Environment

- FlowForge version: v1.1.0
- Node.js version: v17.9.1
- npm version: 8.11.0
- Platform/OS: Mac Monterey
- Browser: Chrome

**Comment by knolleary** [comment]
Hi @blueoceans2002 

The catalog is downloaded by the browser from the Node-RED community - FlowForge doesn't get involved at all.

Can you open the JavaScript Developer Console in your browser and check for any error messages?

Can you check you can access the [catalogue](https://catalogue.nodered.org/catalogue.json) directly?

**Comment by hardillb** [comment]
You can open the developer tools with Option + ⌘ + J

Also with those open if you click the little 2 arrow circle button at the top right of the under the red close button, this should trigger a reload of the catalogue. Please let us know if there are errors in the console section of the developer tools but also under the network tab.

**Comment by blueoceans2002** [comment]
Hi @knolleary 
As you mentioned there is a error message, please see below image. Also where can I access the catalogue directly, browser inspect page source files?
![image](https://user-images.githubusercontent.com/119927769/205901620-3de0c70c-f9bb-4f51-a296-73bcf148b96d.png)

@hardillb I did click on the refresh button, it did not trigger the catalogue.

Thanks

**Comment by knolleary** [comment]
hi @blueoceans2002 - I provided the link inline in my comment, but that may not have been too clear. The full url is https://catalogue.nodered.org/catalogue.json

Can you also check the 'Network' tab in the dev tools - reload the page with it open, then filter the view for 'catalog' to see if is even trying to make the request.

**Comment by blueoceans2002** [comment]
Hi @knolleary I think it is making the request, please find attached screenshot
![image](https://user-images.githubusercontent.com/119927769/206061755-79eaaa90-4528-4576-80b0-5270084d96a5.png)
Thanks

**Comment by knolleary** [comment]
That is strange. It appears like the catalog has loaded successfully - with data (we can just see the content-length value looks about right at the bottom of your screenshot). Can you check the 'Response' tab of the request - it should look like a big mess of JSON.

Yet the Palette Manager reports 0 nodes found (note the `0/0` to the right of the search bar - the second `0` is how many nodes have been provided by the catalog).

I'm a bit at a loss to explain this combination of clues and we haven't had any reports on Node-RED of this type of thing before.

**Comment by ChrisDeRose** [comment]
Hi,
I'm also facing this issue and I've followed the steps above and the screenshot below shows a part of the 'Response' tab 
 
![Response Tab](https://user-images.githubusercontent.com/109937846/206206626-48a4023f-5372-4c16-84c6-acca2047ea19.png)

Thanks

**Comment by hardillb** [comment]
Hi @ChrisDeRose can you close the "What's New" tab in the bottom of the devloper tools so the Console tab is showing and hit the refresh button please. Just want to double check there are no errors showing.

I'm trying to work out how to add some more debug easily. I have an idea I just need to test it

**Comment by ChrisDeRose** [comment]
This is what I get
![Console](https://user-images.githubusercontent.com/109937846/206218656-19829e37-c0e7-487e-b7ba-69d363d27d37.png)

**Comment by knolleary** [comment]
@ChrisDeRose @blueoceans2002 Thank you for reporting this issue. As @hardillb mentioned, we managed to recreate locally and have identified the fix. This issue has been closed automatically when we merged the fix. There a couple other bits we need to get in place, then we'll do a maintenance release tomorrow (2022-12-08).

I'll update this issue when the release is available for you.

**Comment by blueoceans2002** [comment]
@knolleary @ChrisDeRose Thank you so much for the fix! 
Has this been released to Docker Version aswell? 
thanks
Regards
Satish

**Comment by knolleary** [comment]
@blueoceans2002 @ChrisDeRose we will have an update for you later today. The release was delayed yesterday - we will be getting it done this morning.

**Comment by hardillb** [comment]
OK, version 1.1.2 of FlowForge has been published. Upgrade instructions

**Localfs**

Instructions are here https://flowforge.com/docs/install/local/#upgrade

Where the `x.y.z` in the instructions should be replaced by `1.1.2`

Make sure you stop FlowForge first and once you restart make sure to "suspend" and restart any projects to make sure they pick up the latest version of the launcher.

**Docker Compose**

- run `docker-compose -p flowforge down`
- run `docker pull flowforge/node-red`
- run `docker pull flowforge/forge-docker`
- run `docker-compose -p flowforge up`

Again once back up and running "suspend" and then restart any projects you have to ensure they are on the new container version.

**Comment by blueoceans2002** [comment]
@hardillb Big thanks
