### ISSUE TITLE
Team "Library" UI View

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1368]
### Epic

#237

### Description

**As a:** Team Member/Owner

**I want to:** see all of the saved flows, subflows and custom function nodes

**So that:** I can manage common flows, subflows and nodes across my team & improve the time-to-value in building new node flows.

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

**MVP:**:
- [ ] Can click "Library" in the side navigation menu of a Team view
- [ ] "Library" view lists all saved flows/subflows/nodes for a given team.

**Stretch:**
- [ ] Can delete/manage/re-organise flows/subflows/nodes in the Library

**Comment by joepavitt** [comment]
@knolleary would this be an admin-only view, or open to all team members? I'm imagining that view mode would be all, but deletion, etc. may end up being admin-only?

**Comment by joepavitt** [comment]
Current import/export functionality for nodes & flows in Node-RED:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/99246719/206514936-08186216-4d05-4dfd-9d41-40c7dcc93693.png">

<img width="730" alt="image (1)" src="https://user-images.githubusercontent.com/99246719/206514942-5cac61d9-aa1f-446f-9837-28798e9dbcbd.png">

**Comment by joepavitt** [comment]
First Draft Design:

<img width="1718" alt="Screenshot 2022-12-09 at 11 27 02" src="https://user-images.githubusercontent.com/99246719/206692509-475830f9-caba-435f-a576-a735b79f8b71.png">

**Comment by joepavitt** [comment]
@knolleary just wanted to double check - when exporting, do we have knowledge on whether it's a "flow"/"function node", or do we just see `json`?

**Comment by joepavitt** [comment]
Will also want to add a "preview" window of some kind, for the `js` (function) files, this is easy, for the `flow.json` samples - more complex, and opens the need for a NR Node Preview Widget

**Comment by ZJvandeWeg** [comment]
#237 is going to be shipped without this issue attached as just delivering the API's makes it available for users

**Comment by joepavitt** [comment]
For what it's worth - this is maybe a day or two's work of UI dev to add the UI

**Comment by joepavitt** [comment]
With #237 ready, and other items on my todo list awaiting progress out of my control, I'm going to start working on this, in the hope we can ship for 1.3

**Comment by joepavitt** [comment]
Closed by #1576
