### ISSUE TITLE
Unable to edit 'Prevent Install of External nodes' template option

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1376]
### Current Behavior

The 'Prevent Install of External nodes' option in a template cannot be edited - it appears to be permanently disabled.

This is true for both the Admin editing the template **and** the Project Settings view if the admin has set it to be Editable:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/51083/206243280-a0556e58-da15-4140-8045-ee1201a1c9ea.png">

### Expected Behavior

Admin should be able to edit the value.

Users should be able to edit the value if marked Editable by an admin.

### Steps To Reproduce

1. Edit the template as an admin
2. go to Palette section
3. see you aren't able to edit the value

### Environment

- FlowForge version: 1.1

**Comment by hardillb** [comment]
Verified on staging
