### ISSUE TITLE
Apply a quota to the amount of persistent context storage available

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1385]
### Epic

#212

### Description

**As a:** FlowForge admin

**I want to:** limit the amount of context storage available to each project

**So that:** I don't end up with runaway storage costs

### Which customers would this be availble to

Specific Team Tiers (EE)

### Acceptance Criteria

- [x] Hard codeed Context Quota enabled

**Comment by Steve-Mcl** [comment]
@hardillb Can I mark this as complete? (I believe we have the acceptance covered)

**Comment by hardillb** [comment]
Yes, done
