### ISSUE TITLE
Check usage of Axios

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1390]
### Description

Review https://github.com/flowforge/flowforge/pull/1328

in light of

https://github.com/axios/axios/issues/5357

**Comment by hardillb** [comment]
Possible work around is to ensue that `br` is not in the Accepted-Encoding header

**Comment by Pezmc** [comment]
Given it's a Axios issue, rather than a Brotli issue, I'd propose we downgrade to 1.1.3 which does not have this issue until there's a stable release ready, rather than disabling brotli encoding.

**Comment by knolleary** [comment]
Given we have already downgraded to 1.1.3, there's nothing more to do here.
