### ISSUE TITLE
Wildcard TLS Updates

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1398]
### Description

- “Docker-compose-1.x.0” - inconsistent placeholder numbering
- Should be a child section of HTTP(s)
- Needs more text about this requiring a dedicated domain and certs
- Shuffle around letsencrypt
- Make clearer this isn’t needed for local setup

**Comment by hardillb** [comment]
I think the updates on the other issues have covered most of this.

Only the last point might need some more work.

We can review after Demo on Friday

**Comment by hardillb** [comment]
Closed by #1438
