### ISSUE TITLE
Docker Docs: Improve "Running FlowForge"

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1399]
### Description

- Make clearer where (directory) to run the commands in the install/docker documentation
- docker compose vs docker-compose
    - Joe would have just picked the first one, if that didn't work, then try the second one. Can we help guide the user?

**Comment by joepavitt** [comment]
@hardillb I feel like these were both accomplished?

**Comment by hardillb** [comment]
I think so
