### ISSUE TITLE
Identify how to handle upgrading Node-RED

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#140]
We need to identify how to upgrade Node-RED in a running system.

There are a few different aspects to take into account:

 - An administrator may want to limit what versions are available to platform users
 - A user will want to choose for themselves when to upgrade (as it requires downtime of their running application)
 - Each backend driver will have its own way of upgrading - but that should be transparent to end users

**Comment by knolleary** [comment]
Pushing to 0.2

**Comment by sammachin** [comment]
This will be achieved through project stacks and allowing the owner to change the stack to one that contains a newer version of node-red #288

**Comment by knolleary** [comment]
Given we have identified how upgrades should work (via #288) this task is complete.
