### ISSUE TITLE
Billing Page when Subscription is Cancelled

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1421]
### Description

Right now, the billing page still looks like a team has an active subscription, even when it's cancelled.

<img width="1367" alt="Screenshot 2022-12-13 at 17 11 24" src="https://user-images.githubusercontent.com/507155/207371671-54ef9882-314c-4128-a562-1c01c2427c3a.png">

<img width="1046" alt="Screenshot 2022-12-13 at 17 16 34" src="https://user-images.githubusercontent.com/507155/207371899-c07a638b-84e4-4d02-9423-31ca230fcee0.png">

### Epic/Story

#1162

**Comment by joepavitt** [comment]
Updated Billing page with cancellation detail included:

<img width="1179" alt="Screenshot 2022-12-16 at 10 29 33" src="https://user-images.githubusercontent.com/99246719/208078810-c1465bc3-6f21-425d-8f5e-3f9e4f32aa70.png">

**Comment by joepavitt** [comment]
In the situation where the entire subscription is entirely canceled/expired:

<img width="1599" alt="Screenshot 2022-12-16 at 10 46 28" src="https://user-images.githubusercontent.com/99246719/208081829-e7dfec95-398e-4c9c-8e59-952644cea1ed.png">

**Comment by Pezmc** [comment]
I'm moving the leftover design changes into a separate issue, since they're not directly coupled to the subscription cancellation work in #1162.
