### ISSUE TITLE
Platform needs to keep track of state of Projects

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#145]
We need a way to detect crashed projects, log the fact and try and restart.

At the moment the only time the health of the wrapper launcher is checked is when the `details` api endpoint is checked and even this prints the error and returns.

Current thinking is to run a check on a setInterval timer that periodically gets all the projects in the database and their desired state and checks each one. This is similar to the start up check, so could reuse the same code.

**Comment by knolleary** [comment]
With #16 merged can this be closed?

**Comment by hardillb** [comment]
Yes
