### ISSUE TITLE
Rethink the "Project" termonology

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1450]
### Description

When talking to customers the concept of a project always needs explaining, but it's distracting from what the subject of the conversation is. Each time this topic comes up it shows the UX around projects doesn't click instantly.

One more then one occasion a customer continued the conversation talking about "Instance" or "Device" where the FlowForge term would be "Project". As such we should pick our battles, and not educate our audience on terminology, but move towards our customer and rename Project.

**Comment by knolleary** [comment]
We have looked at this a number of times and never identified a better alternative.

A Project is a Node-RED application. It runs in the FlowForge environment. The project's flows can be pushed out to also run on devices. That is our operational model, whatever labels you put on the different bits.

If a user wants a different model, where they want to run Node-RED on multiple devices and manage each device individually, I can see how they may not appreciate the Project/Device relationship as they aren't interested in the instance running in the FF env. If *that* is the feedback you're getting, it would be good to get the details on that.

The work that was started around Deployments was a step to help clarify/reinforce the relationship between a Project and where it runs.

I'm wary of just saying we need a new label on things, where better clarity could be found in how we present and communicate what we already have.

**Comment by joepavitt** [comment]
Had a good conversation with @MarianRaphael about this yesterday, and given the feedback that ZJ has seen in conversations with customers, and the recent HubSpot contact form, where they also referred to "instances", I'm going to explore in Figma today what a change of terminology would look like.

Fairly sure our "pricing" page too would improve in clarity as "$15/instance" is clearer than "$15/project".

**Comment by joepavitt** [comment]
Okay, so a summary of my thinking, with some visuals to support points where appropriate. This comment is likely to evolve over the next 24 hours as I add and re-think certain spaces, but will follow a very similar format to the write-up I've done in #1492 

## Current Model
<img width="1219" alt="Screenshot 2023-01-05 at 14 12 08" src="https://user-images.githubusercontent.com/99246719/210799928-fae81aa8-7aab-4be0-8590-240009d43a1b.png">

### Concepts:
- **Team**: Organisational concept, allows multiple users to be centrally managed
- **Project**: Technical concept, we currently map a project to a single instance of Node-RED, and we charge by Project.
- **Deployment**: When creating a Project, with that you get a single deployment, which is your Node-RED instance/editor running wherever FlowForge runs.
    - **Cloud Deployments:** In our "Deployments" screen, we show that there is a single "Cloud" deployment of your Project, which in essence is the single instance of Node-RED that you're paying for.
    - **Device Deployments:** It is in then possible to remotely deploy Snapshots of a Project out to devices via the FlowForge Device Agent. We currently do not charge for this.
- **Snapshot:**: It is possible to take moment-in-time Snapshots of a Project, these can then be deployed out to device agents.

### Problems with Current Model

- Confusion with Node-RED nomenclature. Across several interactions with prospective customers and users, we regularly hear the term "instance", and users expect to pay "per instance" - and get confused when we're using the term "Project"

... more to come...

**Comment by joepavitt** [comment]
@knolleary @ZJvandeWeg My option 2 I think is actually in a state where I'd be happy to welcome contributions/thoughts. Having written out (1) I don't think that makes sense as an option.

**Comment by MarianRaphael** [comment]
Thanks for the work and the visualization @joepavitt this makes things clear! I like option 2. About individual terms (in the visualization) can certainly be discussed. From my perspective, it is important to divide the topics into small packages and not to deal with everything at ones. 

> In this iteration, Projects would be able to have n instances of Node-RED running.

This already contains enough complexity. It is then the basis for the [staging](https://github.com/flowforge/flowforge/issues/1492) topic. Devices I would consider separately (and keep it as it is for now). I like your visualization from here as a first step:
![](https://user-images.githubusercontent.com/99246719/210342501-c21cf56c-6237-4ec5-9920-8a0bfa16f1e6.png)

### Implications (My thoughts and input)

> huge technical overheads for us, as we'd need to have "logs", "settings", etc. per deployment.

Again, I would keep it as simple as possible in the first step until we get feedback and move on. 

### About logs
I would suggest expanding the logs of the Node-RED instances in a simple list per project, then they don't have to move at all. Per project will certainly be only 1-3 instances, at the beginning. 

### About settings
The big step and the goal would be to split Project settings and Instance settings. If this is too much effort for one iteration, from my perspective, it would also be ok to allow only one setting configuration per project for all instances, as a first step.  

### Billing
I would not touch the billing concept, based on the original motivation of this topic.
> We charge "per Instance".

Wording change from project to instance

**Comment by MarianRaphael** [comment]
> one setting configuration per project for all instances
Maybe tricky with environment variables. I am unsure whether it is not better to separate it directly and clearly.

**Comment by joepavitt** [comment]
Agree with pretty much everything you've said @MarianRaphael. If we proceed with (2), I see the following implementation path:

### Phase 1: Terminology Only

#### Changes:
- Change "Deployments" wording to "Instances" in FlowForge
- Change "Cloud" to "Local Instances" & change "Devices" to "Remote Instances"
    - Could arguably be skipped over, but feel it's cleaner to the user what this separation is if we use consistent "___ Instances", rather than "Cloud" and "Devices", with the latter (without knowledge of what they are) seemingly out of place.
- Change Website to say we charge "per instance".

#### Comments:
- Still constrained here to having one "local" instance per project.

### Phase 2: Multiple Instances per Project

#### Changes:
- Bare minimum requirement here is that each instance would need to have its own Settings page, as per our current "Device" page, for the reason you've raised (env vars)
- Audit Logging needs consideration here for each instance - quick fix would be to just log `project..` events where we now have Instances, and with the recent introductions of the new Audit Log formatting, it makes it easy to distinguish between the source of the logs (i.e. which instance they belong to)
- I imagine @knolleary will be able to flag a lot of complexities on introducing multiple instances per project that I haven't considered

#### Comments:
- Still constrained here to having one "local" instance per project.
- Under the covers here, we could just transfer everything we have for a "Project", and convert that to the functionality of an Instance, then on the front-end, we package those and arrange them into the new "Projects" concept, which actually keeps the Projects UX as things stand.
- Audit Log filtering becomes more valuable here, and relevant at the "Project" level, as we could filter by "Instance".
    - Although this does break our audit logging concepts a bit, as we use `project.` there.

### Phase 3: Staged Deployments

#### Changes:
- Focus UX functionality on whichever direction we decide is appropriate from https://github.com/flowforge/flowforge/issues/1492

### Flexible Changes

Components that could slot wherever feels appropriate:

- Introduce Billing per Device, then our "$X/instance" becomes universally applicable.

**Comment by joepavitt** [comment]
Hadn't considered consequence of this - renaming of "Project Link" nodes would be required?

**Comment by joepavitt** [comment]
Removing myself as assignee as I have now delivered my designs & thoughts on the matter

**Comment by knolleary** [comment]
I will put this on my slate for 1.4 in as much as thinking through the internal architectural approaches that could be used to support the type of change described above.

**Comment by joepavitt** [comment]
Nick and I working through options on terminology:

### Option 1:

<img width="1949" alt="Screenshot 2023-02-09 at 12 02 18" src="https://user-images.githubusercontent.com/99246719/217807440-37aa84cc-bdb0-46d6-a2d3-4ff683ee9a80.png">

**Pros**:
- Cleaner pricing given that user just pays "Per Instance" 

**Cons**:
- If we remove the term "Devices" here, what intuitive link does the user have to "Devices" as a page at the top-level? It feels disconnected
    - Do we need to rebrand "Devices" as a consequence of this? To what?

### Option 2:

<img width="1924" alt="Screenshot 2023-02-09 at 11 53 23" src="https://user-images.githubusercontent.com/99246719/217805753-2a560c9f-6392-4b71-9762-33b7f2806fbd.png">

**Pros**:
- Closer tie to "Devices" as a concept being outside of the FlowForge platform

**Cons**:
- Does this complicate pricing model? We want to advertise as a "$ per Instance"
    - Potentially not confusing, because some instances run in FlowForge, some run on Devices 
    - Instance terminology in the page name and labelled text
- Confusion on the "Add" actions? 
    - One for "Add Instance" and one for "Add Device"

**Comment by joepavitt** [comment]
I believe the Option 1 "Instances" screen feels cleaner - _*however*_ I am not sure I can think f a cleaner term to replace "Devices" with at the top level that enables us to make this change on this screen.

**Comment by ZJvandeWeg** [comment]
Having spoken internally and externally, I've removed 'Project' from my vocabulary in favour of 'Application'. That does help with defining what it does, and how it's used.

**Comment by joepavitt** [comment]
Okay, so each Application ,could still have multiple Instances (FF-Hosted & Remotely?)

**Comment by joepavitt** [comment]
Okay, so each Application ,could still have multiple Instances (FF-Hosted & Remotely?)

<img width="1159" alt="Screenshot 2023-02-13 at 20 00 52" src="https://user-images.githubusercontent.com/99246719/218562383-b720012e-e146-4e01-8bb1-db5b4940fc0c.png">

**Comment by ZJvandeWeg** [comment]
@joepavitt I'm suggesting that image indeed.

**Comment by knolleary** [comment]
Work to track and implement via #1689
