### ISSUE TITLE
SSO with Plus Addresses

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1460]
### Current Behavior

Create a brand new account using a plus addressed email (e.g. example+20221212@flowforge.com).

Assuming you're logged into the google account example@flowforge.com, you end up logged in as the `example@flowforge.com` account, not newly created example+20221212@flowforge.com account. 
This leaves you effectively locked out of the newly created account.

This isn't necessarily a true bug since as far as I'm aware google auth doesn't support plus addresses, but FF should prevent the user from ending up in this circumstance.

### Expected Behavior

Signed into the correct account
Or blocked at signup if SSO is enabled on a domain and trying to use a plus address

### Steps To Reproduce

Have SSO enabled for google workspace at a domain e.g. @flowforge.com
Create a brand new account using a plus addressed email (e.g. example+20221212@flowforge.com).
Verify the email address.
Try to log in with example+20221212@flowforge.com
Land in example@flowforge.com instead.

### Environment

- FlowForge version: v1.1.1
- Node.js version: v16.19.0
- npm version: n/a
- Platform/OS: Cloud
- Browser: chrome

**Comment by hardillb** [comment]
Tested on Staging
tried to sign up as `ben+sso@flowforge.com` and got bounced with the correct error message
