### ISSUE TITLE
Duplicate Activity Log for Project whose state is in flight

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1461]
### Current Behavior

When a projects status is transitioning the activity log shows duplicate entries after the first polled refresh. 

![2022-12-17 11 11 26](https://user-images.githubusercontent.com/507155/208234820-fd66aa97-9d3d-4847-b704-a93a02093d0e.gif)

### Expected Behavior

Show the entries only once

### Steps To Reproduce

Start a new project that takes at least 2 seconds to boot e.g. when creating a new project

### Environment

FF Cloud

**Comment by Steve-Mcl** [comment]
verified in local and staging
