### ISSUE TITLE
SSO: user not redirected to editor when signing in

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1481]
### Current Behavior

Without SSO, if a logged-out user attempts to access a project editor directly they are prompted to log in and then redirected back to the project editor they were trying to access.

If SSO is enabled, this doesn't happen - they are left on the FF dashboard once login completes.

Whilst this is not the desired behaviour, the mitigation is that the user can reload the editor url once they are logged in and access it without problem.

### Expected Behavior

If I access the editor url directly, I expect to be taken back there after logging in via SSO.

### Steps To Reproduce

1. Make sure you're logged out (with SSO enabled)
2. Access a project url directly - go through the login process with SSO

### Environment

- FlowForge version: 1.2

**Comment by hardillb** [comment]
Verified on Staging
