### ISSUE TITLE
Staged Deployments

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1492]
### Description

**As a:** FlowForge Team Owner

**I want to:** to manage multiple staged deployments of my Node-RED flows & instances

**So that:** I can feel reassured that any new updates running in Production is stable.

There is also likely a lot of crossover with the work/discussion going on in https://github.com/flowforge/flowforge/issues/1450 which is looking at defining the concept of a FlowForge "Project".

### Which customers would this be available to

All Users, (CE)

### Acceptance Criteria

- [ ] Agree on Concept hierarchy & High-Level UX (e.g. General Single Project & Multiple Deployments, Multiple projects with  exporting, staged deployment specific UX)
- [ ] Size server-side/FE workload in order to implement output from above

### Stories:
- https://github.com/flowforge/flowforge/issues/1580

**Comment by joepavitt** [comment]
We have seen from multiple customers now, the request/desire to use FlowForge to run staged deployments of their flows, e.g. `test`, `development`, `staging` and `production`. 

## Current Model
- Customers can spin up multiple Projects, each project representing a different stage of their deployment.
- In order to update the next stage of their pipeline, they would be able to make use of our "Export to Project" functionality, which would transfer over the flows, settings, etc.

## Problems with Current Model
- "Projects" becomes synonymous with a Node-RED Instance, which may lead to UX confusion.
- If I have multiple different, unrelated Node-RED flows, then having to have multiple FlowForge "Projects" per set of Node-RED flows becomes an organisational mess as my single "Projects" view in fact shows a merger of multiple different use cases/flows.
- It is not intuitive to a user that the Export to Project approach would enable Staging, and it's not easy to track progress through a stage deployment.

## Some Options
Given the above, I list here a few proposed alternative options for the design of the staged concepts/system:

### 1) Deployments can have defined "Stages"
Listed in our "Deployments" tab, we would still only have a single "Deployment", but that deployment can be staged (we'd bill for additional stages) - progress is easily tracked, and the flows pushed through these stages are clearly moved from one-stage to the next.
- **Pros:**
     - Very clear progress tracking of staged deployment
     - Could be single click approval to move to next "stage"
     - Similar UX/Pattern to what most DevOps platforms offer
- **Cons:**
     - Constrained just to "Staging" use case
     - Billing complexities int hat we also charge for "Stages"
     - Introduces _another_ concept ("Stages") in an already over-crowded FlowForge nomenclature

### 2) Multiple "Cloud" Deployments
A more general option for a project is multiple-deployments running in the cloud. A single project could have _n_ number of instances running in the cloud, with identical flows and project settings. Users would be required to configure this option themselves as a staging environment, but would be able to have a "Test" deployment, "Staging" deployment, etc. We would need to add easy functionality on transferring/progressing between two deployments - linked to Snapshots?
- **Pros:**
    - Flexibility - can be used for more use cases than just a staged deployment
    - Fewer conceptual changes from our current model
- **Cons:**
    - Requires manual setup by every user
    - May not be intuitive that this is a way of doing staged deployments

## Other areas for consideration
- Do deployments/stages each get their own env vars, etc. - it's very likely this would be required, so opens a big can of worms.

**Comment by joepavitt** [comment]
As part of 1.3 iteration, I'll put some quick Figmas together on how the (1) and (2) proposed could look to ensure they're communicated effectively.

**Comment by joepavitt** [comment]
First draft Figmas added for (1) and (2) in the comment above. Also added (3), with explanations of cons expanded on (1) and (2) which may justify need for (3)

**Comment by joepavitt** [comment]
Draft UX added for (3), have also dropped in some thinking on this approach, which originally I was against as I wrote it out, but now I've designed it, I think I prefer the UX.

**Comment by joepavitt** [comment]
Removing myself as assignee, as I have presented options & respective designs for each approach.

**Comment by joepavitt** [comment]
As explained in https://github.com/flowforge/flowforge/issues/1450#issuecomment-1386713544 we are proceeding in 1.4 with a shorter term solution for "Staged Deployments" with https://github.com/flowforge/flowforge/issues/1580

In order for this issue here to be accomplished, we need to enable multiple Cloud instances per Project, which is a significant overhaul of our existing architecture.

**Comment by knolleary** [comment]
I think we can put this onto the backlog now. I'll do some technical design work around #1450 in 1.4, but keeping this in mind as well.

**Comment by joepavitt** [comment]
Yep, that's fine, going ahead with #1580  for 1.4 though, right?

**Comment by MarianRaphael** [comment]
See also https://github.com/flowforge/flowforge/issues/2022

**Comment by joepavitt** [comment]
Moving to 1.8

**Comment by joepavitt** [comment]
@MarianRaphael what do we want to do with this epic? Keep it open for management/grouping sake, but remove from iteration/milestone?

**Comment by MarianRaphael** [comment]
@joepavitt I would close it with the current implementation of the DevOps Pipeline. The original idea of this epic is, in my opinion, fulfilled. There will be follow-up tasks centred around "Staged Deployments," but these should be new epics and stories.
