### ISSUE TITLE
Unable to sign up for FF Cloud account using a plus address

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1514]
### Current Behavior

<img width="448" alt="Screenshot 2023-01-09 at 12 09 46" src="https://user-images.githubusercontent.com/507155/211295043-4f666ca6-9853-4637-a84b-e581b7533cac.png">
<img width="470" alt="Screenshot 2023-01-09 at 12 10 09" src="https://user-images.githubusercontent.com/507155/211295097-a0f31aa9-8985-472a-83c9-0ce76379c92e.png">

> SSO IS ENABLED FOR THIS EMAIL DOMAIN. YOU MUST REGISTER USING THE EMAIL THAT MATCHES EXACTLY WHAT YOUR SSO PROVIDER IDENTIFIES YOU AS.

### Expected Behavior

Should be able to create a FlowForge Account without error using a plus address.

### Steps To Reproduce

Head to FF Cloud, https://app.flowforge.com and try to sign up for a new account using a plus address on any domain.

### Environment

- FlowForge version: FF Cloud
- Browser: Safari/Chome/Firefox

**Comment by hardillb** [comment]
Missing `await` here https://github.com/flowforge/flowforge/blob/5a33d959182a47ac9022d1aa04ffa43825b03bbf/forge/routes/auth/index.js#L313
