### ISSUE TITLE
Allow Private Certificate Authorities

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1525]
### Description

**As a:** FlowForge Admin

**I want to:** secure my install with TLS certificates issued by an internal CA

**So that:** I comply with local security policy for internally hosted services

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

- [ ] Able to provide a CA cert
- [ ] Have Project Container load CA Cert
- [ ] Node-RED complete oAuth handshake against FlowForge app with private Certificate

**Comment by hardillb** [comment]
https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs

One possible option is to use a custom stack image that includes the CA certs in the system cert store and the `NODE_OPTIONS=--use-openssl-ca` or `node --use-openssl-ca` option to have it pick them up instead of the ones baked in the nodejs binary.

**Comment by corentin-pasquier** [comment]
According to NodeJS documentation, there is an environment variable for this kind of need :
[https://nodejs.org/api/cli.html#node_extra_ca_certsfile](https://m365.eu.vadesecure.com/safeproxy/v4?f=_LVfWcbohPSvUkvsbmUoBzYKIJVv7A9kv29wlxer4JGbSUv6unFSuP4bn4IVY32X&i=Cy2kJaFq62JF7NUL6x_A-YhrvKyA2X-Z2lf4a8QmU6sPUasgF10lvvCqm-GyfA2GJaUHJRG5vpznMLLF699YVQ&k=edUB&r=5hz29CcoBr_axlFHEokQLxlh81eBsA6bm1v_3ws7HcvSQpHrb0Jp0HnRh7tMOmvi&s=3680d68c95fb7f0109920aa1f85856c8f5e2db5fd238329f03550a361111eed7&u=https%3A%2F%2Fnodejs.org%2Fapi%2Fcli.html%23node_extra_ca_certsfile)
 

I have an smtp under an internal PKI certificate. The smtp configuration is not working without setting the `tls.rejectUnauthorized` configuration to false in the flowforge-config file.


I tried this :
•	Sharing my host certificate in the container
![image](https://user-images.githubusercontent.com/18682315/221191410-8e2cf54f-ee0f-4792-8791-8bbc80221773.png)
![image](https://user-images.githubusercontent.com/18682315/221191430-b6faab93-485e-4f22-8533-51932621b648.png)

•	Creating a flowforge-environment config-map
![image](https://user-images.githubusercontent.com/18682315/221191454-8008c9cc-d3c4-4011-93ea-991e56c2be7e.png)

•	Sharing this config map in the container
 ![image](https://user-images.githubusercontent.com/18682315/221191473-dba81901-aba5-4a6a-893a-4611ce2b16de.png)

 
This seems to be well configured in the container :
 ![image](https://user-images.githubusercontent.com/18682315/221191499-88c26c0e-5239-407b-a851-efe10248bce3.png)

 
However, It’s not working when I go to the flowforge settings :
 ![image](https://user-images.githubusercontent.com/18682315/221191564-207a8f64-1a90-45e0-84cc-719e1a55a450.png)

 I guess my environment variable is ignored as mentioned in the link above :
“This environment variable is ignored when node runs as setuid root or has Linux file capabilities set.”

**Comment by hardillb** [comment]
Tentative solution in place for kubernetes, will look at adding Docker/localfs support later.

Will try and target 1.5 for release
