### ISSUE TITLE
Optionally set snapshot as target at creation

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1527]
### Description

Today, setting a new target snapshot is a two step process:

### Creating the snapshot

<img width="300" alt="Screenshot 2023-01-10 at 13 51 34" src="https://user-images.githubusercontent.com/507155/211556444-ee2ea9e1-4032-42aa-9f9a-22ec6c512f4e.png">

### Set it as the device target

<img width="300" alt="Screenshot 2023-01-10 at 13 48 30" src="https://user-images.githubusercontent.com/507155/211555949-f9aa99b8-7165-4be4-b27e-764ed66c1243.png">

-------

Adding a checkbox to automatically set the new snapshot as a device target, will simplify this process into a single step:

##### Mockup

<img width="658" alt="Screenshot 2023-01-10 at 13 50 34" src="https://user-images.githubusercontent.com/507155/211556683-2794de1d-83f3-4553-832d-61798b3180e9.png">

**Comment by joepavitt** [comment]
@Pezmc is this in progress and can we expect it in 1.4?

**Comment by Pezmc** [comment]
It is not in progress yet. I can't say if it'll be ready for 1.4.

**Comment by Steve-Mcl** [comment]
@Pezmc I think might be a quick win - I can pick it up if you wish?

**Comment by joepavitt** [comment]
@Steve-Mcl if you have the bandwidth today/tomorrow morning, that'd be great.

**Comment by Steve-Mcl** [comment]
Tested on staging - we have lift off :)
