### ISSUE TITLE
Deployment Categories - Terminology Change

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1530]
### Description

As part of the ["Rethink Projects"](https://github.com/flowforge/flowforge/issues/1450) epic, it was [proposed](https://github.com/flowforge/flowforge/issues/1450#issuecomment-1372564433) to change some of the terms used on our existing "Deployments" page.

Currently we categorise our deployments into two groups:

- **Cloud** - contains the single instance of Node-RED deployed with, and managed by, FlowForge
- **Devices** - lists any devices bound to the project, and the respective snapshot deployed to them.

We've heard feedback on multiple occasions that it is not clear what the "Devices" section offers, and so, we are going to change the wording (as agreed in the [Product Sync on Jan 10th](https://github.com/flowforge/flowforge/issues/1450#issuecomment-1372564433) to:

- **FlowForge Hosted** - The single instance of Node-RED currently included with FlowForge.
- **Remote** - lists all instances of Node-RED, bound to this project, but not hosted at the same domain as FlowForge.

### Epic/Story

#1450

**Comment by joepavitt** [comment]
Closed by #1531

**Comment by Steve-Mcl** [comment]
Verified on staging
