### ISSUE TITLE
No email is sent on user sign-up

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1537]
### Current Behavior

When a new user signs up, we are not sending them the expected verification email.

The user is able to log in where they are asked to click the link in the (unsent) email, or click a button to resend (which does work).

### Expected Behavior

Email sent to user when they sign-up

### Steps To Reproduce

1. Run with user sign-up enabled and email configured
2. Sign-up a new user
3. Observe no email is sent

### Environment

- FlowForge version: 1.2
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
This was another side-effect of #1514 and was fixed by #1515

**Comment by Steve-Mcl** [comment]
Verified a + email sends email on sign up on local.
