### ISSUE TITLE
SSO User unable to edit settings

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1542]
### Current Behavior

If a user is signed in via SSO, we prevent them from editing their email address.

However it looks like we are now also preventing them from editing any other user setting - such as 'default team'.

Whilst their can click edit on the User Settings page, the 'save' button never becomes enabled.

### Expected Behavior

An SSO user is able to set their default team.

### Steps To Reproduce

 - Sign-in with SSO
 - Go to user settings, click edit
 - Note the 'save' button never becomes active

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
Verified on staging
