### ISSUE TITLE
Stripe Checkout Team Product Description

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1549]
Needs technical investigation to see if feasible - use two different team products in Stripe?

> As this is your first FlowForge team, we’re giving you free credit equivalent to a Small Project for one month’. This will be applied to your next Stripe invoice.

**Comment by Pezmc** [comment]
> wouldn't that mean users would have to switch products after their 

(from https://github.com/flowforge/flowforge/issues/1521#issuecomment-1381011101)

@joepavitt  No it would not, they'd sit on the same team plan forever. It would just change at subscription creation time.

**Comment by knolleary** [comment]
I don't think this is the way to go. We have a solution for now. We know there are wider changes we want to make around billing - having separate team products will complicate things that we want to make simpler.
