### ISSUE TITLE
Charges Section on Create Project Page

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1550]
![image](https://user-images.githubusercontent.com/507155/212283235-5b4156c7-f339-41ad-a0fe-e3b77f143f40.png)

**Comment by Steve-Mcl** [comment]
Verified Charges Section on staging
Verified Credit Balance info local only

**Comment by Steve-Mcl** [comment]
@knolleary is there a way for credit to be applied to staging so we can verify this feature works on cloud?

**Comment by Steve-Mcl** [comment]
verified on staging
