### ISSUE TITLE
More subtle credit balance banner on Create Project Page and Billing Page

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1551]
Possible design: 
![image](https://user-images.githubusercontent.com/507155/212283338-0372d447-63b8-4a9a-9ec0-9d8beeb086f9.png)

**Comment by Pezmc** [comment]
@joepavitt Currently the banner looks like this, any suggestions on what to change? 
![image](https://user-images.githubusercontent.com/507155/212283437-96d55604-8a8b-4f76-a17f-dfcf629eb123.png)
<img width="1181" alt="Screenshot 2023-01-13 at 10 18 22" src="https://user-images.githubusercontent.com/507155/212283561-8f95960d-d8c9-495d-b7bf-f9d27b7bc5ac.png">

**Comment by joepavitt** [comment]
Having the underline/border-bottom make it feel like an input box, remove border all together please. The contrast in background color should do the job in separating the content

**Comment by Steve-Mcl** [comment]
Same question as #1550: is there a way for credit to be applied to staging so we can verify this feature works on cloud so we can verify this?

**Comment by Steve-Mcl** [comment]
Verified on staging


![Image](https://user-images.githubusercontent.com/44235289/213212728-a6eb3aa7-9617-413a-aa65-fafdb658c29b.png)
