### ISSUE TITLE
I use the default flowforge code, and I want to use a custom node in the built-in nodered, what should I do

### ISSUE THREAD

**Issue by songenen** [flowforge/flowforge#1562]
### Current Behavior

I run `npm i flowforge-nr-file-nodes` in flowforge , install my custom nodes
<img width="217" alt="image" src="https://user-images.githubusercontent.com/59854272/212531986-a65091c3-a68b-41fe-a4eb-20d608b50908.png">

### Expected Behavior

<img width="208" alt="image" src="https://user-images.githubusercontent.com/59854272/212532023-f8bf92fc-ca81-43aa-9975-5013f1afd61c.png">
it can be displayed here

### Environment

- FlowForge version:1.1.0
- Node.js version:18
- npm version:8.19
- Platform/OS:arch latest
- Browser:chrome latest

**Comment by hardillb** [comment]
The simplest option is to:

- Use the `npm pack` https://docs.npmjs.com/cli/v8/commands/npm-pack to create a tgz file for your project
- You can then upload this file to the Node-RED Project under the `Manage Palette` optionhttps://docs.npmjs.com/cli/v8/commands/npm-pack
![Screenshot from 2023-01-15 09-23-29](https://user-images.githubusercontent.com/1800845/212533085-753e8441-9707-4b6f-a1c0-f877164e4542.png)

If you are using the Docker or Kubernetes version of FlowForge, you can also build your own stack container.

**Comment by songenen** [comment]
i don't have this button

**Comment by songenen** [comment]
Can I run `npm install ~/repos/nodered/nodes/create-chart` in the ~/.nodered directory to achieve the same effect

**Comment by hardillb** [comment]
No, the FlowForge projects do not use the default Node-RED UserDir.

- What version of Node-RED do you have configured for your Stacks?
- And what options do you have selected under the `palette` option in the Template you are using?

**Comment by songenen** [comment]
I'm using 2.2.2, run `npm run install-stack --vers=2.2.2 `, I can also upgrade it to above 3.0

<img width="873" alt="image" src="https://user-images.githubusercontent.com/59854272/212533866-68d9fd78-b057-4872-8452-6f4f91e38de5.png">

pallet I only added exclude 10-file.js

**Comment by hardillb** [comment]
You will need a Node-RED 3.0.x for the tgz upload button.

You will need to create a new stack (use `bin/ff-install-stack.sh 3.0.2` in the FlowForge install directory), then create the stack under the Admin Settings.

**Comment by songenen** [comment]
After I changed to 3.0.0, nodered: port 12080 has been loading and there is no response.
I want to modify the source code of nodered after git clone, so how to modify the started nodered after the operation is my modification, not the nodered under /var/stacks
<img width="586" alt="image" src="https://user-images.githubusercontent.com/59854272/212535432-88a8e95a-28ad-47c5-8ca0-039a919ebb8e.png">

<img width="531" alt="image" src="https://user-images.githubusercontent.com/59854272/212535236-d142762d-842f-4090-8893-7c4ce23467ac.png">

**Comment by songenen** [comment]
Now it loads, but still no button

<img width="837" alt="image" src="https://user-images.githubusercontent.com/59854272/212535789-e1248659-edbb-46f0-bddc-41ce41278f7d.png">

<img width="751" alt="image" src="https://user-images.githubusercontent.com/59854272/212535838-251499f1-8d32-4123-a86c-98e229afb703.png">

**Comment by songenen** [comment]
Now I run `npm run install-stack --vers=3.0.2`, but still no button
<img width="833" alt="image" src="https://user-images.githubusercontent.com/59854272/212536659-af53a636-ca19-487a-9e30-b9091e6c0bf1.png">
<img width="404" alt="image" src="https://user-images.githubusercontent.com/59854272/212536701-782b7a5c-5510-42cb-9135-27b660cfe3df.png">

**Comment by hardillb** [comment]
Sorry, I screwed up, it was early this morning and I wasn't thinking. The tgz upload feature is explicitly disabled in FlowForge.

Let's start again. What problem are you actually trying to solve here:

1. To install a custom node into a single project?
2. To install a custom node so it is available to all projects?

For option 2 you can run the following command in the FlowForge directory.

    npm install --prefix var/stacks/3.0.2 ~/repos/nodered/nodes/create-chart

This will install your node along side the Node-RED 3.0.2 that is used for the 3.0.2 stack.

**Comment by songenen** [comment]
it ran successfully，Thank you very much
