### ISSUE TITLE
Social media graphic for new free trial

### ISSUE THREAD

**Issue by iskerrett** [flowforge/flowforge#1571]
### Description

Can we create a social media graphic for twitter and LinkedIn to announce the new 30-day free trial.  Ideally it is a graphic with the FlowForge logo plus a 'Free Trial' wording.

**Comment by knolleary** [comment]
Delivered for 1.3

**Comment by joepavitt** [comment]
![Twitter Post Image - Free Trial](https://user-images.githubusercontent.com/99246719/213571324-280d613a-280d-46aa-a83d-37603a297fee.png)
