### ISSUE TITLE
Pseudo-Staged Deployments

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1580]
### Description

**As an:** owner of a project

**I want to:** be able to push my updates and settings from a Project to another project

**So that:** that I can update production instances when, and only when, I am comfortable to do so.

We currently offer the "Copy to Project" functionality, which does enable this workflow, but in an attempt at making this more explicitly a use case for Staged Deployments, and one that doesn't require the overhaul of DB and server-side changes that are proposed in <>, this is an alternative that should take far less time to achieve, whilst offering a slightly improved UX from where we are today.

**_Not sure if this is a Premium Feature?_**

### Which customers would this be available to

None

### Acceptance Criteria

- [ ] "Deploy to" or "Push to Stage" option made available for a project
- [ ] User can select a single project from their team that becomes the next "stage" in the pipeline.
- [ ] User has the option to click a button 9with confirmation) that will then transfer the relevant contents of this project to the target project.

TBC:
- What are the "relevant contents", especially in comparison to wha we offer currently from the "Copy to Project" functionality

**Comment by joepavitt** [comment]
In our existing "Export" functionality, we use:

<img width="642" alt="Screenshot 2023-02-01 at 13 52 34" src="https://user-images.githubusercontent.com/99246719/216061795-d75bd865-bc91-4ea8-9849-cf87e4f2bc70.png">

Of these options, when pushing a project to the "next" stage, 

- Flows - Include
- Credentials - Exclude
- Template - Exclude
- Project Settings (include nodes, configs) - Grey Area
- Env Vars - Keys Only - ensure any newly created env vars are replicated in next "stage", without copying values

**Comment by knolleary** [comment]
@joepavitt correction - `credentials` should be include.

**Comment by joepavitt** [comment]
broken in Staging when clicking "View Target Project" 



![Image](https://user-images.githubusercontent.com/99246719/218861263-6aefe73e-a731-40cc-a6fa-7101da92282d.png)

**Comment by joepavitt** [comment]
PR opened with fix: https://github.com/flowforge/flowforge/pull/1706

**Comment by Steve-Mcl** [comment]
All good from my testing @joepavitt 
Move to Done? or is there anything outstanding?

**Comment by joepavitt** [comment]
> Move to Done? or is there anything outstanding? 
All good, thanks Steve
