### ISSUE TITLE
"Create Account" text updates

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1581]
### Description

It has been requested that we provide updates to the Create account page: https://github.com/flowforge/website/issues/333#issue-1535111693 that details the availability of a Free Trial.

Complexity here is that we only want this message showing on FF Cloud, and not on local install of FlowForge.

**Comment by knolleary** [comment]
Proposal: Add `billing.createAccountBanner` to `flowforge.yml` that, if set, is displayed as a banner on the create account page.

We can then set that to whatever we want it to say. Could be plain text, or HTML if we want richer customisation.

Longer term, it might make sense to move out of `billing` and have a separate file of UI customisations that can be applied to individual instances... but this would be a quick first pass.

**Comment by hardillb** [comment]
Wouldn't it be hung off the `/api/v1/settings` endpoint? from `forge/routes/api/settings.js`?

**Comment by joepavitt** [comment]
<img width="811" alt="Screenshot 2023-01-18 at 17 13 27" src="https://user-images.githubusercontent.com/99246719/213249123-be11e6ad-06df-4f6e-a216-cf1cdbf8acf2.png">

**Comment by joepavitt** [comment]
Agreed - can you create an issue for that on this repo please?
