### ISSUE TITLE
Team Library 2.0

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1597]
### Description

**As a:** FlowForge Team Member

**I want to:** be able to share and manage common flows & functions that my team use

**So that:** we can easily spin up new instances of Node-RED, prevent duplicate effort in recreating commonly used nodes & patterns

https://github.com/flowforge/flowforge/pull/1576 saw the addition of a very basic Team Library interface. This story tracks the additional features that we didn't quite get into 1.3 Release, that we would like to see in the interface.

### Which customers would this be availble to

None

### Acceptance Criteria

- [x] #1657
- [x] We have no way to show a rendered view of the flow, but providing access to the JSON would also be valuable to allow a user to copy an entry without having to open up a NR editor.
    - Included in #1657 too
- [x] #1690
   - [x] https://github.com/flowforge/flowforge/pull/1704
- [x] #1691
   - [x] https://github.com/flowforge/flowforge/pull/1704
- [x] https://github.com/flowforge/flowforge/pull/1713

**Comment by joepavitt** [comment]
> Add 'delete' option (will require backend api as well)

@knolleary still okay to add a Delete endpoint to the Storage API? If it's fairly straight forward, I don't mind attempting it.

**Comment by joepavitt** [comment]
Pez taking over the last 2 bits

**Comment by joepavitt** [comment]
@Pezmc is this done? what's the status?

**Comment by Pezmc** [comment]
@joepavitt https://github.com/flowforge/flowforge/pull/1704 is open but has some UX bugs that I'm working on
