### ISSUE TITLE
Improve communication of Device Last Seen and Status

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1599]
Reference: https://github.com/flowforge/flowforge/issues/1116#issuecomment-1385580139 

Highlight the last-seen value of a device based on time since we last saw it.

- The eye is drawn to the "Running" pill, not the "Last Connected"
- We could move the connection into a pill too, red/yellow/green status depending on last connected status, which flags to the user.
- It's perfectly valid that the flows could be running, even though we haven't connected in a month, so it's difficult to flag otherwise.

For now we can use a fix set of time bands (TBD) for the colour of status.

**Comment by knolleary** [comment]
Another option to consider is to relabel 'Status' to 'Last Known Status' to emphasis it may be out of date information? Not sure, but may be worth seeing how it looks.

**Comment by Steve-Mcl** [comment]
Checked locally and on staging



![Image](https://user-images.githubusercontent.com/44235289/218722133-1df274f3-cb36-490e-b835-248562dab215.png)
