### ISSUE TITLE
Add license identifier in telemetry packet

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1607]
### Description

Our existing telemetry packet does not include any information about the license being used - we should update it to include something.

This would enable us to easily identify telemetry for a paying customer. It would also help monitor for reuse/misuse of a license - as each license should only be associated with one `instanceId`.

We don't want to include the whole license in the packet, so we should either use an easily computed short hash of the license, or start including an identifier in the license payload we can use to directly correlate with.

### Epic/Story

https://github.com/flowforge/flowforge/issues/1638

**Comment by Steve-Mcl** [comment]
As discussed with Steve / Nick

### Proposal
1. Include a UID to identify the licence
2. No need for encoding / encryption of the proposed UIR within the JWT
3. ~~FF would need to associate licenses issues (i.e. no customer number)~~

### Associated changes to support this...
* License Generator
* Telemetry "gathering"
* Telemetry ping collector should receive this. (DB migration of telemetry DB)
* Associated docs

**Comment by Steve-Mcl** [comment]
@knolleary @ZJvandeWeg 

After working through this and determining might would be useful to us, I see the possibility of 3 elements:

```
        'platform.license.id': app.license.get('id') || '',
        'platform.license.type': app.license.active() ? 'EE' : 'CE', // future proof
        'platform.license.dev': !!app.license.get('dev') // is developer licences?
```

My thoughts are as follows...
1. Existing licences will not have an ID & would therefore be reported as `''`
2. Have just a blank `id` is rather implicit in indicating whether a license is OLD or CE
3. A future development license may also have an `id` and this field helps us understand which is which at a glance

Of course, some of this can be gleaned by matching the `id` with a (future) database of licences but in the case of "now" and manually generated dev licences i think this may be of some use.  And lastly, having `type` permits future licensing values (e.g. `UE` or `TRIAL`? 

Happy to go either way but would like some feedback before progressing please.  Ta.

**Comment by ZJvandeWeg** [comment]
I'd squeeze a dev license into the type, but otherwise this direction would work for me.

**Comment by Steve-Mcl** [comment]
> I'd squeeze a dev license into the type, but otherwise this direction would work for me.

Hmmm, not a bad idea. 

Lets see what Nick says.

**Comment by knolleary** [comment]
Agreed - just `id` and `type` and have the development license report as `DEV`.
