### ISSUE TITLE
Make credit clearer prior to Project type selection

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1612]
### Description

Users are turning way from creating free projects because we only make the credit visible once a Project Type has been selected, e.g.:

<img width="1012" alt="Screenshot 2023-01-25 at 15 49 22" src="https://user-images.githubusercontent.com/99246719/214621519-f8e385a4-2565-4b96-bf79-f06d9e5db66d.png">

It would be good to show a note that a user has X Credit available on the screen, which is then reinforced once the Project Type is selected.

**Comment by joepavitt** [comment]
We could introduce a banner across the top as per https://github.com/flowforge/flowforge/issues/1578#issuecomment-1403444861

or as per the original design: https://github.com/flowforge/flowforge/issues/1521#issuecomment-1379195095

**Comment by joepavitt** [comment]
This could also be a candidate for a backport (thoughts @knolleary?) or at least part of the early release with the other billing changes going in

**Comment by knolleary** [comment]
The other billing changes (#1578) will remove the need for the account credit work.

We should backport the fix for this and do a maintenance release to get it live sooner rather than later.

**Comment by Pezmc** [comment]
There's one big caveat with this due to the changes in https://github.com/flowforge/flowforge/pull/1610; but I can copy the changes across.

**Comment by joepavitt** [comment]
> There's one big caveat with this due to the changes in https://github.com/flowforge/flowforge/pull/1610; but I can copy the changes across. 

not a concern if this is just a backport fix until the #1578 goes in?

**Comment by knolleary** [comment]
/me takes a look at the changes in #1610 and doesn't look forward to the merge conflicts the changes to `createProject` will bring when #1578 is ready....

**Comment by joepavitt** [comment]
fyi @knolleary https://github.com/flowforge/flowforge/pull/1613 is merged with `backport` label

**Comment by Pezmc** [comment]
Backport PR is here: https://github.com/flowforge/flowforge/pull/1614
