### ISSUE TITLE
Require a marketing landing page to promote FF Cloud sign-ups

### ISSUE THREAD

**Issue by iskerrett** [flowforge/flowforge#1621]
### Description

We need create a landing page that will summarize the benefits of using FF Cloud, promote a free trial, and allow to sign-up for a FF Cloud account. Similar to:
https://www.confluent.io/get-started/
https://app.posthog.com/signup

L

**Comment by iskerrett** [comment]
I think the Confluent and Posthog pages are good examples that we should emulate. 

https://www.confluent.io/get-started/?product=cloud
https://app.posthog.com/signup


Some comments:
- I like how on the  click the logos to get back to the home page.
- I would be nice to add the sign up with Google or GitHub to the page.

Text for form:
- I find the text pretty small on the existing form. 
- I don't think we need Sign Up at the top of this form.
- We should be asking for company name, maybe make it optional.
- Text at top of the form: The first 30 days are free to try FlowForge Cloud. No credit card is required.

Text on the side:
Title: Get Started with FlowForge, for free.
Bullet 1: 
Title: Quick to Start.
Text: Quickest way to get started with Node-RED. No installation required!

Bullet 2: 
Title: Collaborate
Text: Share Node-RED instances with team members.

Bullet 2: 
Title: Manage 
Text: Manage remote deployment of Node-RED instances to hundreds of remote targets.

**Comment by joepavitt** [comment]
Taking influence from Confluence as pe the above, first pass at design:

<img width="1537" alt="Screenshot 2023-02-07 at 17 09 02" src="https://user-images.githubusercontent.com/99246719/217314702-c4091df9-fae9-463f-8813-c656b17911b4.png">

**Comment by joepavitt** [comment]
Cleaner font sizing & a "Already have an account?" being added to the right-side.

<img width="1684" alt="Screenshot 2023-02-08 at 09 08 59" src="https://user-images.githubusercontent.com/99246719/217486277-106c8d19-78df-4dfb-b5d9-357ab05df4f0.png">

**Comment by joepavitt** [comment]
Implementing options are:

**Option 1:**
- Content is driven by `flowforge.yml`
    - Quicker, but also pain to update as would require restart of prod/staging each time

**Option 2:**
- We add a section into the admin settings with the option to inject html content onto the page, if sign up is enabled.
    - Slightly longer to implement, but far easier to iterate on with the content.

@knolleary and I vote Option 2. Nick is building it asap.

**Comment by knolleary** [comment]
Nick has built it asap - https://github.com/flowforge/flowforge/pull/1692

**Comment by joepavitt** [comment]
could I get my user upgraded to admin on staging please @hardillb so that I can verify this works as expected?

**Comment by joepavitt** [comment]
our markup for landing page will be:

```
<h1 class="mb-6 text-4xl">
    Get started with <span class="text-teal-400">FlowForge</span>, for free
</h1>
<p class="mb-12">
    Lorem ipsum dolor sit amet consectetur. Netus ac in viverra ornare enim
    lobortis dignissim amet. Eget faucibus quam tortor amet.
</p>
<div class="mb-12 flex">
    <div style="flex-shrink: 0">
        <img class="w-24" src="https://flowforge.com/images/pictograms/time.png">
    </div>
    <div class="ml-4">
        <h3>Lorem ipsum dolor consectetur.</h3>
        <p>
            Lorem ipsum dolor sit amet consectetur.
            Netus ac in viverra ornare enim lobortis dignissim amet. Eget faucibus quam tortor amet.
        </p>
    </div>
</div>
<div class="mb-12 flex">
    <div style="flex-shrink: 0">
        <img class="w-24" src="https://flowforge.com/images/pictograms/security.png">
    </div>
    <div class="ml-4">
        <h3>Lorem ipsum dolor consectetur.</h3>
        <p>
            Lorem ipsum dolor sit amet consectetur.
            Netus ac in viverra ornare enim lobortis dignissim amet. Eget faucibus quam tortor amet.
        </p>
    </div>
</div>
<div class="mb-12 flex">
    <div style="flex-shrink: 0">
        <img class="w-24" src="https://flowforge.com/images/pictograms/bias_for_action.png">
    </div>
    <div class="ml-4">
        <h3>Lorem ipsum dolor consectetur.</h3>
        <p>
            Lorem ipsum dolor sit amet consectetur.
            Netus ac in viverra ornare enim lobortis dignissim amet. Eget faucibus quam tortor amet.
        </p>
    </div>
</div>
```

subject to finalisation/agreement on text once it's rendered and available to view

**Comment by hardillb** [comment]
@joepavitt there are admin user creds in 1password

**Comment by joepavitt** [comment]
Thanks Ben, verified working in Staging, although some Tailwind CSS classes don't get rendered properly, as the injected HTML wouldn't naturally be included in the tailwind build process, so classes that aren't used anywhere else in FF are not actioned.

<img width="1727" alt="Screenshot 2023-02-14 at 20 43 23" src="https://user-images.githubusercontent.com/99246719/218858940-41a81fb3-0e94-4689-93d9-62e5fcf74868.png">

**Comment by joepavitt** [comment]
@iskerrett this is now with the text you've provided, scope to include replace the Lorum Ipsum paragraph if anything relevant for that space you can think of.

<img width="1158" alt="Screenshot 2023-02-14 at 20 46 51" src="https://user-images.githubusercontent.com/99246719/218859788-5d67c3e6-6c64-4bb4-afbf-1639c478c5c0.png">

I think the three detail statements feel a little mis-matched and underwhelming, particularly the headlines for 2 and 3, and the description for 2. Any scope for being more descriptive/sales-y?

I need to update the icons too, but can do that tomorrow.

**Comment by iskerrett** [comment]
Some suggested changes:
- For the text under the FlowForge logo on the right-hand side,  I would suggest the following: "Experience FlowForge with one project free for 30 days. Sign-up now with no credit card required."
- For the left-hand side text
- Change the headline to 'Get Started Faster with Node-RED and FlowForge'
- Add sub-headline: '30-day free trial with no credit card required
--  Change text under Quick to start to be: The quickest way to get started with Node-RED. No downloads and installation are required. Just sign-up and start building with Node-RED.
-- Change text under Collaborate to be: "Seamlessly collaborate with team members. WIth FlowForge, automatically share Node-RED instances with team members. No more manual export / import required.'
-- Change Manage to Managed Deployments. Change the text to "Rolling out Node-RED to multiple devices or servers? FlowForge automates this process to ensure reliable and repeatable deployments.'

**Comment by joepavitt** [comment]
I did change "Deployment" to "Instance", only because we've made that terminology change in-product this release, so don't want to confuse it.

I have hesitations on our leading line being about speed to Node-RED, suits the people that want to try Node-RED out, and works great for the trial period, but are they the same people that we would expect to lead to meaningful ARR?

**Comment by joepavitt** [comment]
(I will also update the images before going into production)

**Comment by joepavitt** [comment]
<img width="1728" alt="Screenshot 2023-02-16 at 12 18 20" src="https://user-images.githubusercontent.com/99246719/219362808-d542edd4-21f5-41d9-820f-b67737379f59.png">

```
<h1 class="text-4xl">
    Get Started Faster with Node-RED and FlowForge
</h1>
<p class="mb-6">
    30-day free trial with no credit card required
</p>
<div class="mb-6 flex">
    <div style="flex-shrink: 0">
        <img class="w-24" src="https://flowforge.com/images/pictograms/time.png">
    </div>
    <div class="ml-4">
        <h3>Quick to start.</h3>
        <p>
            The quickest way to get started with Node-RED. No downloads and installation are required. Just sign-up and start building with Node-RED.
        </p>
    </div>
</div>
<div class="mb-6 flex">
    <div style="flex-shrink: 0">
        <img class="w-24" src="https://flowforge.com/images/pictograms/community.png">
    </div>
    <div class="ml-4">
        <h3> Collaborate</h3>
        <p>
            Seamlessly collaborate with team members. With FlowForge, share Node-RED instances with team members, with easy-to-manage access control. No more manual exporting / importing required.
        </p>
    </div>
</div>
<div class="mb-6 flex">
    <div style="flex-shrink: 0">
        <img class="w-24" src="https://flowforge.com/images/pictograms/edge.png">
    </div>
    <div class="ml-4">
        <h3>Managed Instances</h3>
        <p>
             Rolling out Node-RED to multiple devices or servers? FlowForge removes friction from this process to ensure reliable and repeatable deployments, remotely and to the Cloud.
        </p>
    </div>
</div>
```

**Comment by joepavitt** [comment]
this is now live: https://app.flowforge.com/account/create
