### ISSUE TITLE
Improve Empty State across Platform

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1633]
### Description

**As a:** new FlowForge user

**I want to:** get clear information on what functionality is available on each screen/page of FlowForge

**So that:** that I can get an understanding of what features I may or may not want to use.

Existing Screen for "Register Device":

<img width="1727" alt="Screenshot 2023-02-01 at 09 38 28" src="https://user-images.githubusercontent.com/99246719/216006380-e0d25a28-db55-42d3-986b-e579a9e13dab.png">

Information is hidden away in the "i" button next to the page header, but users don't seem to be interacting with this. We should utilise the placeholder space to inform the user what functionality the page offers. 

We should also utilise this space to make more engaging graphics that draw the attention of user's eyes and add more personality to the platform.

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

**Design**:
- [x] Design lo-fi template placeholder screen that can be subbed with relevant graphics & instructional content 
- [ ] Design each placeholder graphic:
    - [x] #2065
    - [x] #2066
    - [x] #2067
    - [x] #2068
    - [x] #2069
    - [x] #2070
    - [x] #2071
    - [x] #2097
    - [ ] Empty Audit Log - less of a priority

**Development**:
- [ ] Add new designs into the application

**Comment by joepavitt** [comment]
Inspiration: 
- https://saasinterface.com/pages/empty-state/
- https://emptystat.es/
- https://dribbble.com/tags/empty-states

Worth putting a moodboard together in Figma

**Comment by joepavitt** [comment]
Great article re: Empty State posted by @ZJvandeWeg: https://www.toptal.com/designers/ux/empty-state-ux-design

**Comment by joepavitt** [comment]
Areas we need to have empty state designs for:

- No Applications (`/team/<team-name>/applications`)
- No Instances (`/team/<team-name>/instances`)
- No Instances within an Application  (`/application/<app-id>/instances`)
- No Devices (`/team/<team-name>/devices`)
- No Devices within an Instance (`/instance/<instance-id>/devices`)
- Empty Team Library (`/team/<team-name>/library`)

Possibly:
- Empty Audit Log - less of a priority

**Comment by joepavitt** [comment]
Should be prioritising 
- Warm fuzzy feeling (graphic)
- Instruction/information about the functionality that the user can achieve with the given screen
- A single, clear CTA (e.g. "Create Application", "Add Device")

**Comment by joepavitt** [comment]
@Yndira-FlowForge fyi - have created a bunch of template pages for you to design on in Figma: https://www.figma.com/file/rMB2w5ZZUtTC0nxbwLYKJY/FlowForge-Platform?node-id=2069-12404

I'll work with you on terminology/instructions to include, and then would be great to iterate and moodboard some different styles for graphics

**Comment by joepavitt** [comment]
Key Messages to communicate:

- Applications; Groups of instances (shared settings, staged deployments, high availability)
- Instance: One Node-RED w/settings, audit log, etc. etc.
- Snapshot: Rollback/history/commits
- Devices: Central Hub (FlowForge) enables comms/updates/interaction with remote things (Devices)
- Team Library: Shared store of _stuff_ - where _stuff_ are flows or JavaScript functions

**Comment by ZJvandeWeg** [comment]
@joepavitt @Yndira-FlowForge Consider splitting this issue to make it easier to iterate. Let's start with just an empty state for say Applications and afterwards do others.

**Comment by Yndira-FlowForge** [comment]
Like this?
<img width="2468" alt="6-Dark grey" src="https://user-images.githubusercontent.com/129537638/236266200-c929594e-b1c3-4fca-be1b-e85c38a01e8b.png">

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt 
I exported the png's of the [latest version](https://github.com/flowforge/flowforge/issues/1633#issuecomment-1535044616) to 🎨 Design/Media/Empty States/PNGs

**Comment by joepavitt** [comment]
Tahnks @Yndira-FlowForge I'll take over from here to add into the Platform

**Comment by joepavitt** [comment]
verified on staging
