### ISSUE TITLE
Improve licensing for large customers

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1638]
### Description

**As a:** administrator

**I want to:** have enterprise friendly licensing

**So that:** I worry less about FlowForge operations if we're adopting really well

### Which customers would this be available to

Specific Project Types (EE)

### Acceptance Criteria

```[tasklist]
### Tasks
- [ ] #1639 
- [ ] #1640
- [ ] #1607
- [ ] #1739
- [ ] https://github.com/flowforge/flowforge/issues/1745
```

**Comment by joepavitt** [comment]
Nick and I talking - proposing this for 1.5

**Comment by knolleary** [comment]
We've completed the technical work on this for now.

The docs do not have any content regarding licensing, so adding docs on this requires a whole new section. This is tracked in #1745 - and will be delivered post 1.5 and backported (as it is docs-only).
