### ISSUE TITLE
Allow License overages

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1639]
### Description

For an administrator it's a worry extra to understand how many more Node-RED instances they can roll out through FlowForge. And there might be times where a new one is needed _now_ but the license might not allow it. Going through procurement, legal, etc to increased the licensed number of instances is too cumbersome.

FlowForge should allow to go over the licensed number of items.

### Epic/Story

#1638

**Comment by Steve-Mcl** [comment]
### proposal
* For a licenced platform, disable guards to permit additional "things"
   * Do we want no limit or a percentage overage in first iteration? (ZJ)
* Unlicenced platform will continue to have limits imposed

### DEV NOTE
See DB pre-create hooks for all models limited by licensing.

**Comment by ZJvandeWeg** [comment]
> Do we want "no limit" or a "percentage overage" in first iteration?

No limit. A second iteration might include us recording a high water mark in terms of Node-RED projects and devices

> Unlicenced platform will continue to have limits imposed

Correct

**Comment by ZJvandeWeg** [comment]
@Steve-Mcl if it's very little effort to log this for the admin, that's a good suggestion

**Comment by knolleary** [comment]
I remember seeing GitLab had quite a good system for recording and tracking overages when I was originally investigating approaches for licensing. Whilst definitely not a 1st iteration thing, I think we can learn some useful things from their approach at the point in time we want to start doing that.

**Comment by Steve-Mcl** [comment]
re-opening as #1744 not yet merged
