### ISSUE TITLE
Send telemetry for all licensed FF instances

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1640]
### Description

To allow overages: https://github.com/flowforge/flowforge/issues/1639 FlowForge Inc should be able to understand if the number of licensed units is going over, and by how much.

As such the licensed editions should always have telemetry enabled.

### Epic/Story

#1638

**Comment by Steve-Mcl** [comment]
### Proposal
* When a license is applied, telemetry will be enabled
* Admin settings option should be either hidden or [x] checked & disabled with accompanying text.

**Comment by ZJvandeWeg** [comment]
> As discussed with Steve & Nick 2023/02/21
> 
> 
> 
> ### Proposal
> 
> * When a license is applied, telemetry **will** be enabled
> 
> * Admin settings option should be either hidden or [x] checked & disabled with accompanying text. 
> 
> 

Yes. Agreed. Think hidden is best, not to hide, but remove annoyance that the option is in lockable

**Comment by Steve-Mcl** [comment]
> Yes. Agreed. Think hidden is best

NP: will update PR to NOT show the option when licensed
