### ISSUE TITLE
Autosaving Env Vars

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1646]
### Current Behavior

Not _technically_ a bug, but an annoying feature nonetheless. When defining Environment Variables on a project, you have to hit both the "+" _and_ the "Save Settings".

I'm assuming this is linked to the fact we could delete an env var by mistake, and ensuring the "Save Settings" is clicked backs this up, but it can be unintuitive when adding environment variables.

### Expected Behavior

I propose one of two alternatives:

1. (preferred) Auto save/update when a key is added or deleted to that table, with confirmation alerts. Where deleting should probably provide an "Are you sure?" dialog warning.
2. Disable the "Save Settings" button until changes have been made, to make it clearer to the user that the button must be clicked

### Steps To Reproduce

https://user-images.githubusercontent.com/99246719/216337871-faebb214-0ca3-4ee7-a80d-7e42cb86a9e5.mov

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by joepavitt** [comment]
It's a fairly quick win, so I could squeeze this into 1.4 as part of the work I'm doing with pseudo-deployments, but want to check for any gotchas I may have not considered?

**Comment by MarianRaphael** [comment]
Idea: Popup/Hint asking do you want to restart

**Comment by MarianRaphael** [comment]
Verified on staging
