### ISSUE TITLE
Data viz with Node-RED

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1647]
### Description

Node-RED Dashboard is often a reason people cite why Node-RED is successful. The dashboard is highly flexible, and used to chart data, but also interactive. It's used host buttons to trigger flows, forms, and this level of interaction is what sets it apart from say Grafana.

This epic sets out to understand the challenges with Node-RED dashboard currently, what the next steps are to improve on that state, and what the business case is for FlowForge to invest in it. FlowForge should only offer paid features if that aligns with using many of these dashboards, there's no intent to start a Node-RED Dashboard 2 that's unavailable to the community.

Further, issues with Node-RED Dashboard should be investigated with the Node-RED community.

**Comment by MarianRaphael** [comment]
See https://github.com/flowforge/flowforge-nr-dashboard
