### ISSUE TITLE
Show a preview of Team Library entries on click

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1657]
Currently, it is not possible to click on any of the `.json` or `.js` files in a Team's library. This task will enable that, and then show a preview of it's content in the team Library UI.

**Comment by joepavitt** [comment]
Not sure which way to go in terms of layout/interaction:

<img width="1955" alt="Screenshot 2023-02-03 at 16 33 34" src="https://user-images.githubusercontent.com/99246719/216656707-27f0e418-2eb3-4b71-81f3-3a3bea00a064.png">

**Option 1 - New Page**
- Gives clean separation, easier to build, and navigate to straight from URL.
- Scales the best to mobile too

**Option 2 - Dialog**
- More "preview"-y than Option 1,
- Doesn't scale well

**Option 3 - Bottom**
- More "preview"-y than Option 1
- Easy to switch to another file in a single click, rather than having to go "back"
- Doesn't scale great when we have lots of content in a single folder

**Option 4 - Side**
- More "preview"-y than Option 1
- Easy to switch to another file in a single click, rather than having to go "back"
- May have to switch to Option 3 on smaller screens

**Comment by joepavitt** [comment]
option 1 implemented for starters:

https://user-images.githubusercontent.com/99246719/216664841-79a7d99c-1235-411c-a1cd-b251b9922d0e.mov

**Comment by ZJvandeWeg** [comment]
If the flow isn't rendered, why would we pursue this?

**Comment by joepavitt** [comment]
Because its not just flow.json files they can save.

Also possible to save function.js files, which are useful to inspect. Having flows here also makes them easier to export outside of flowforge, as no need to open Node-RED to get them.

Very easy win here, was only 1 hr of work, just need to add some styling/syntax highlighting to it.

Iteration towards then showing the flow eventually, but that's a big piece of work.
