### ISSUE TITLE
Remove HubSpot form capture

### ISSUE THREAD

**Issue by iskerrett** [flowforge/flowforge#1660]
### Description

We seem to be capturing people who reset their FF Cloud password in HubSpot. We don't need to be doing this. I believe this is because we have some HubSpot javascript on our site that automatically captures any form completion. We have converted all the relevanant forms to HubSpot forms so this javascript is no longer needed.

**Comment by hardillb** [comment]
Moved to flowforge/flowforge

**Comment by hardillb** [comment]
Is this just the password reset page? I assume to make things work we still need to capture the signup page. @iskerrett can you check that we are not grabbing password on the new user signup page

**Comment by joepavitt** [comment]
Just spoke with Ben on this, have explored in HubSpot a bit further, the form being captured is the "Forgot Password" form, not the "Reset Password" form as feared:

<img width="1157" alt="Screenshot 2023-02-07 at 10 19 15" src="https://user-images.githubusercontent.com/99246719/217217701-e5655e89-f210-4997-b6e3-847daa3b34b5.png">

Whilst not ideal, it's certainly not as much of a concern as previously though, and in actual fact may be of use to use to prevent forced hack attempts into accounts if this is flagged here.
