### ISSUE TITLE
UX improvements for team library

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1707]
### Description

Right now any navigation is not stored, so a user cannot navigate "back" to a previous page

### Epic/Story

#1597

**Comment by MarianRaphael** [comment]
@Pezmc is this issue solved?

![Image](https://user-images.githubusercontent.com/73583313/230089292-3b5c3c1f-985f-483f-ae7b-126d984f7ce0.png)

**Comment by Pezmc** [comment]
Looks like it!
