### ISSUE TITLE
New Device Status missing 

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1709]
### Current Behavior

Missing status pill:

<img width="1728" alt="Screenshot 2023-02-15 at 14 24 08" src="https://user-images.githubusercontent.com/99246719/219054279-c2eac2f9-9efe-43d5-8e48-66aca5c91dd7.png">

Should have been added in https://github.com/flowforge/flowforge/pull/1679

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
Verified in local


![Image](https://user-images.githubusercontent.com/44235289/219100333-d74bb8c1-7701-4203-b39f-8ffd6d341fcf.png)

And on staging



![Image](https://user-images.githubusercontent.com/44235289/219100492-77de07ca-6630-4a33-bd28-fbf3bf548c4d.png)

**Comment by joepavitt** [comment]
Thanks Steve
