### ISSUE TITLE
Add new "Instance" abstraction layer in UI

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1718]
**Epic:** https://github.com/flowforge/flowforge/issues/1689

This story will track progress on adding a new abstraction layer into the UI for our new "Instance" concept. We already have the standalone screens for devices (i.e. Remote Instances), this will entail adding an equivalent for FlowForge Managed Instances.

From a routing perspective, most of what we currently view at the `/project/<project-id>/...` level will move into a new `/instance/<instance-id>/...` routing. Details broken into relevant tasks:

- [x] Overview `/instance/overview`
    - Identical (for now) to the existing Project overview.
- [x] Snapshots `/instance/snapshots`
    - Identical (for now) to the existing Project Snapshots screen 
- [x] Remote Instances `/instance/remote-instances` - https://github.com/flowforge/flowforge/pull/1795
- [x] Audit Log `/instance/audit-log`
    - Identical (for now) to the existing Project Activity screen
- [x] Node-RED Logs `/instance/logs`
    - Identical (for now) to the existing Project Logs screen as this is restrained just to the single Cloud/Local instance of Node-RED
- [x] Settings `/instance/settings` - https://github.com/flowforge/flowforge/issues/1734
    - Work to be done, alongside #1719 to define which settings are moved, and which are kept at an instance-by-instance level.

Given the scope of the new "Instance", we can also re-introduce the top level banner with name, status and actions across all relevant screens in the scope of this Instance.

Open discussion also around the new organisation concept above Instance being renamed to "Application" here: https://github.com/flowforge/flowforge/issues/1735

**Comment by joepavitt** [comment]
Proposed first steps
- new `instances.js` in `/api`
    - re-map all the existing Project API, but gives us scope to update (just API changes) in the future
    - use this new service in the new `/instance/<instance-id>/...` screens

**Comment by Pezmc** [comment]
Partially completed in #1792, adding a devices page is still in progress.

**Comment by Pezmc** [comment]
The devices page under instances doesn't have a design in Figma yet, so I am:

 - Using the application design with all create/register/snapshot features at the instance level
 - Using the application design, with only a list of devices at the application level

**Comment by Pezmc** [comment]
The main tabs are completed, the follow up task of re-working Application/Instance level settings is being tracked in https://github.com/flowforge/flowforge/issues/1734 and #1719
