### ISSUE TITLE
Remap Project-Level navigation.

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1719]
Epic: https://github.com/flowforge/flowforge/issues/1689

Where https://github.com/flowforge/flowforge/issues/1718 handles the moving of existing `/project` pages into the new `/instances` mapping, this Story handles the content of what will replace those pages at the `/project` level.

Whilst we are still using the same name "Project", the functionality of a Project is changing, as we are enabling multiple "Instances" per Project with #1689. This means that a Project will now purely be an organisational/folder-type concept, and not explicitly have any functionality directly bound to it with respect to Node-RED.

Top-level routes we are expecting to have on a project-by-project basis:

- [x] ~Overview~
    - ~We will still need a high-level insight into the instances, status, etc. within a given project. This would also act as the landing page for any given navigation to a project, for example from the higher-level "team"~
- [x] Instances - New landing page
    - An almost exact mirror of how we present this screen today. Unlikely to require much change, we want to view all instances mapped to a given project.
- [x] Audit Logs
    -  Needs a dropdown to select instance. Otherwise the same as today. We want to view all instances mapped to a given project.
- [x] Node Log
    -  Needs a dropdown to select instance. Otherwise the same as today. We want to view all instances mapped to a given project.
- [ ] #1734
    - Some discussion required here as to which settings remain at the new "Project" level, and which are moved down into Instance

**Comment by Pezmc** [comment]
Overview, instances, audit log, node logs completed in #1792, re-working the settings tab will the tracked in #1734, so considering this done.

**Comment by joepavitt** [comment]
verified in staging
