### ISSUE TITLE
Require some visual feedback when creating a project

### ISSUE THREAD

**Issue by iskerrett** [flowforge/flowforge#1721]
### Description

I sign-up for FF Cloud.  The first thing I see is create project page  I select create project and then nothing happened. 

I realize it takes time to spin up the instance but I had to wait for over 30 seconds, not really sure what was supposed to happen while I waited. I think we should have some type of information message stating 'project creation typically takes 30-xx seconds, please be patient'

**Comment by Steve-Mcl** [comment]
Ian, upon creation (and subsequent restarts) you are shown the project instance and if you look at the status badge/pill it will say "starting" or "installing" then eventually switch to "started".

I dont propose we switch to a full blown spinner but perhaps an animated activity icon near the status pill when not equal to a resting state (e.g. when stopped or started, the spinner is stopped/hidden) would make this a little more obvious?

The reason for this opinion is that I suspect more familiar users will not sit watching this page - they will create the next project or watch the Node-RED log - or do other things on the platform while it spins up.

**Comment by iskerrett** [comment]
I agree we shouldn't do a spinner but as a newbie the 'starting' or 'installing' status is awfully small in a large UI.

**Comment by MarianRaphael** [comment]
Follow-up work will be captured here: https://github.com/flowforge/flowforge/issues/2487
