### ISSUE TITLE
Device "Last Seen" status shows "never" even though it has previously been seen

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#1723]
### Current Behavior

Demonstration:

https://user-images.githubusercontent.com/44235289/219595859-7db5b5b5-8845-4527-9e39-83f78269320e.mp4

### Expected Behavior

Should say "Just now" or "Moments Ago"

### Steps To Reproduce

watch / refresh the devices page

### Environment

- FlowForge version: 1.4 (staging)

**Comment by joepavitt** [comment]
That's a funky one - I'll bring that into 1.5 given the feature was just added.

**Comment by Steve-Mcl** [comment]
@joe I'll pick this up - I know what is wrong.

Because the device "lastSeenAt" is recorded by at the server (uses servers timestamp), you cannot then use the client browsers time to compute a "last seen difference" because the clients browser timestamp can easily be different to the server - thus calculating a minus value in the diff (minus value is used in vue as meaning "never").

We either need to pass the server time with the "lastSeenAt" OR compute the "last seen difference" friendly text on the server where the original "lastSeenAt" timestamp is generated and recorded (AKA single source of truth)

Hope that rambling make even a little bit sense ;)

**Comment by joepavitt** [comment]
verified in staging
