### ISSUE TITLE
Figma Prototyping for Instances UX

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1732]
Given the shift from Project > Node-RED Instance being a 1:1 Mapping, there are some significant changes likely to be required into the FlowForge UX, mostly due to the introduction of a 3rd level of navigation depth, e.g. Team ? Project > Instance.

Until now, we've only ever had two-levels, which has meant our nested side navigation was suitable, need to re-consider the UX for the 3-levels being introduced.

We need Figma prototype/layouts for the Instance-level navigation as a priority in #1718, then to be scaled to full UX navigation for #1719

**Comment by joepavitt** [comment]
Stage 1 - #1718 (@Pezmc fyi)

Navigable Instance UX Prototype:

https://www.figma.com/proto/rMB2w5ZZUtTC0nxbwLYKJY/FlowForge-Platform?page-id=0%3A1&node-id=1816%3A8374&viewport=-1024%2C-9402%2C0.73&scaling=min-zoom&starting-point-node-id=1816%3A8374&show-proto-sidebar=1

Just gives the top-level options and basic screen layout for Instances. At this stage, we do not need "Create Instance" workflow, as still have the underlying 1:1 mapping with Project <> Instance.

**Comment by joepavitt** [comment]
Mention from Nick re: devices. Remote Instances are managed at the Application level - but actually, have 1:1 mapping with an Instance.

**Comment by joepavitt** [comment]
Prototype gap: can't currently click instance rows at Application level

**Comment by knolleary** [comment]
Given the high-level design has been done and delivered, do we want to close this item in favour of more the more targeted issues we have planned?

**Comment by joepavitt** [comment]
> Given the high-level design has been done and delivered, do we want to close this item in favour of more the more targeted issues we have planned?

Sensible
