### ISSUE TITLE
Allow users to delete accounts

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1767]
### Description

**As a:** FlowForge User

**I want to:** be able to delete my account

**So that:** I can stop using the platform.

This should handle leaving teams (and nominating replacement admin if needed) with multiple members, deleting teams that they are the sole member of (and deleting any projects held within).

Also needs to be aware that once account deleted no way for the user to access the stripe page to change any billing details for EE users.

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3
- ...

**Comment by knolleary** [comment]
For a first iteration, it is sufficient to allow a user to delete their account if they are not the sole owner of any team.

We already provide the tools for a user to transfer team ownership, or delete projects and teams to get to that state.
