### ISSUE TITLE
Inconsistent Add/Register Device buttons and dialogs

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1801]
Note this is based on the code in #1795 which moves a few things around, but doesn't modify these specific elements. Any fix should target its branch (or on main if that PR has been merged by the time this issue is addressed) to easily avoid any merge-conflict heartache.

There are three places a user can click a button to add a device to their team and/or application. The button text and dialog appearance is inconsistent.

Page | Button Label | Dialog
---|---|---
**Team Device** | `+ Register Device` | Dialog has a long piece of text explaining what it does plus the two inputs for data entry
**Application(Project) Overview** | `Add Device +` | Dialog has no text, just the two inputs.
**Instance/Remove Instances** | `Add Device +` | Dialog has no text, just the two inputs.

I presume the latter two are a reused view - which is good. The former needs bringing into line.

Whilst looking at the **Team Device** page, I noticed the Register Device button appears on the left, whereas all our other equivalent buttons appear on the right.

**Edit**: I realise that is due to screen-width and the long help text being shown causes the line to wrap much sooner than other views. And I can confirm that all the other equivalent header buttons wrap like that... Would be good if the button stayed where it was expected to be and have the text wrap inline.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/51083/224372323-3030a3db-1326-4d7c-a9b6-9a8e4860fa46.png">

**Comment by Steve-Mcl** [comment]
Related? https://github.com/flowforge/flowforge/issues/1724

**Comment by Pezmc** [comment]
@Steve-Mcl I don't think that's related in this case, but as of #1809 the Team > Devices page uses the same component as all the other devices _lists_, so it'll only need to be fixed in one place (Device > Settings).

Ideally, there should be a DeviceForm component, that's shared between the modal the settings page.
