### ISSUE TITLE
Application UX issues

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1802]
We have merged the bulk of the initial Application/Instances UX rework into `main` and that is now on `staging`.

There is one more inflight PR (#1795) that isn't merged yet due to failing tests.

This issue highlights some UX issues I've spotted whilst using the new UX in the branch associated with #1795 - although much of this stuff in `main`. These are nit-picky details that hopefully we can knock off quickly before 1.5 ships.

### Application Overview:  Rename 'Overview' tab in Application view to 'Instances'

I'm still getting lost when navigating around applications and instances. I think labelling the top tab in the Application view as 'Instances' (because its the view that lists all the application instances) would make sense at this time. Doesn't need to change the url.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/51083/224371196-1f8123d0-6571-44b9-91e3-e2790def4a7e.png">

### Create Instance page

This should be 'Create Application' page that *also* creates their first instance.

### Application Overview: remove 'Create Instance' button

This will get re-added in 1.6 once we have full support for multiple instances in the runtime.

### Application Overview: inconsistent buttons

Size, font weight, icon position is inconsistent between these two buttons. I appreciate this isn't specific to Applications, but would be great if there was a quick tweak to bring these into line.

<img width="184" alt="image" src="https://user-images.githubusercontent.com/51083/224372849-ad857f05-96d3-4fe4-96bb-a6aa144c72ba.png">

### Instance Remote Instances: naming

I appreciate it was the whole purpose of #1795 to introduce a tab to the Instance view to list the devices, and that it should be labelled Remote Instances.

Having used it, it just doesn't feel right to me. It's a list of the Devices assigned to the Instance. I may be getting fatigue for the term 'instance', but given we call them Devices at the team level, it does kinda feel like we should label them Devices in this view (especially as it reuses the icon).

<img width="190" alt="image" src="https://user-images.githubusercontent.com/51083/224380110-8eae9f93-309f-4cff-bb5c-c5f37ac14bc1.png">

### Any Instance view

The `Actions` dropdown button has different styling to all other buttons. When they are sat so close it becomes distractingly obvious.

<img width="154" alt="image" src="https://user-images.githubusercontent.com/51083/224379705-ca58c0e9-8c9d-4bba-b095-bcb757152d9a.png">

```[tasklist]
- [x] Application Overview:  Rename 'Overview' tab in Application view to 'Instances'
- [x] Create Instance page
- [x] Application Overview: remove 'Create Instance' button
- [x] Application Overview: inconsistent buttons
- [ ] Instance Remote Instances: naming
- [x] Any Instance view
```

**Comment by joepavitt** [comment]
Having played more with this in Figma, I am too not liking the Hierarchy of:

- Application
    - FlowForge Managed Instances
    - Remote Instances/Devices
    
Given that devices are bound to a "FlowForge Managed Instance", I'm working in Figma at the moment, but I _think_ the direction I'm heading is that the option will be "Devices" at the Instance-level view.

**Comment by knolleary** [comment]
The last task has been split out to https://github.com/flowforge/flowforge/pull/1827

All of the other items have been addressed, so happy to close this off.
