### ISSUE TITLE
Git versioning

### ISSUE THREAD

**Issue by lgtome** [flowforge/flowforge#1804]
## Description

In the node-red we have option inner settings.js like this:
```js
editorTheme: {
  projects: {
     enabled: true <--- this option
  ...
  }
...
}
```
this option enable project features like git versioning. If I provide this option inner flowforge - it does not work.

- FlowForge version: 1.3.2
- Node.js version: 16.13.2 or 14.17.5 or 12.22.12

**Comment by hardillb** [comment]
Git Projects only works with the Node-RED FileSystem Storage Plugin.

FlowForge does not use this storage pluigin, it uses a custom one that stores flows in a backend database.

You can use the snapshot feature to take tagged named copies of your project's flows, and we continue to iterate on version control solutions in FlowForge.

**Comment by lgtome** [comment]
> Git Projects only works with the Node-RED FileSystem Storage Plugin.
> 
> FlowForge does not use this storage pluigin, it uses a custom one that stores flows in a backend database.
> 
> You can use the snapshot feature to take tagged named copies of your project's flows, and we continue to iterate on version control solutions in FlowForge.

Thank you 🙏
