### ISSUE TITLE
Reminder email about trial doesn't include a link to FF Cloud

### ISSUE THREAD

**Issue by iskerrett** [flowforge/flowforge#1815]
### Current Behavior

Current email you receive from FF Cloud.

Hello Ian Skerrett,

Just to let you know, your free trial on team 'Team Ian Skerrett' ends in 5 days.

As you have not yet setup billing on the team, when the trial ends, we will suspend any trial projects you have created.

If you want them to keep running, please setup billing before the trial ends. You will only get charged once the trial ends.

Cheers!

Your friendly FlowForge Team

### Expected Behavior

It would be nice to have a link to make it easier for the person to go back to FF Cloud.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by robmarcer** [comment]
@iskerrett, I suggest we move this over to the new Hubspot integration, what do you think?
