### ISSUE TITLE
Allow changing the NR theme to a dark theme

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1816]
### Description

FlowForge doesn't currently allow users to set the dark theme for Node-RED. The code appears in the templates already it seems

**Comment by Steve-Mcl** [comment]
Related #214

**Comment by Steve-Mcl** [comment]
Static entries for Forge Light and Forge Dark added

![Image](https://user-images.githubusercontent.com/44235289/226362577-c60b7c73-f155-4100-b9f2-8c23f164540a.png)


![Image](https://user-images.githubusercontent.com/44235289/226362800-70738024-9fab-47dd-87c9-77f903bba226.png)

**Comment by Steve-Mcl** [comment]
Proposed acceptance criteria

- [ ] Can be locked
- [ ] Can be changed & remains set after restart/refresh
- [ ] Actually sets the theme of Node-RED (instance will require restart after changing this setting)

**Comment by Steve-Mcl** [comment]
Re-opening until 2nd PR (#1857) is reviewed & merged
