### ISSUE TITLE
Access Node-RED log output from device agent

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1820]
We already have a means and method of displaying log output from a node-red instance running inside the platform. We should be able to achieve the same for devices - providing a 'logs' view on the device page. However, we cannot make http requests to gather the logs - instead we need a mechanism to stream the logs over MQTT from the device, and proxy it via a websocket connection to the frontend.

This will only be available for devices connecting to the platform via MQTT. That should be true of all FF Cloud devices as we have the broker properly configured. For self-hosted, the broker remains an optional component, but it does limit the features available if you don't set it up.

1. Device Agent buffers N lines of combined stdout/err history from the Node-RED process.
    - this should include any logging from the device agent as well, in the same way the nr-launcher component does it.
2. The platform can send a command via MQTT to the device to turn on or off log streaming.
    - the device will send its history of messages before starting to send messages live.
3. Due to the overhead involved, we won't automatically stream device logs to the frontend. The device logs page should have a button to start/stop streaming logs. On starting:
   1. opens a websocket connection to the platform to a device logs endpoint
   2. runtime accepts the connection, checks to see if the device is already streaming, if so, sends over its own locally buffered log contents and continues to send log events as they arrive 'live'.
   3. if the device is not currently streaming, the platform sends a command to the device to start streaming - and then forwards anything received over the websocket
   4. When all websockets are closed for a given device, after a short grace period, a command is sent to the device to turn off device streaming.

There's a lot more hidden detail to figure out - topic name spaces, command formats, websocket security, but that is the general shape of how we can expose device logs in the frontend.

_Originally posted by @knolleary in https://github.com/flowforge/flowforge/issues/1703#issuecomment-1440686757_

**Comment by hardillb** [comment]
The above design assumes that MQTT messaging is available, the device agent will run with just HTTP polling.

I am going to start on the assumption that this feature requires MQTT.

**Comment by knolleary** [comment]
@hardillb can we get the PR's that delivered this feature linked in?

**Comment by hardillb** [comment]
@knolleary 

- https://github.com/flowforge/flowforge/pull/1900
- https://github.com/flowforge/flowforge-device-agent/pull/66

**Comment by MarianRaphael** [comment]
Released with 1.6
