### ISSUE TITLE
Replace submodules with subtrees

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#183]
To include another Git repository into this repository we're currently using submodules. The developer experience with submodules is lacking, to say the least.

Much better, from a Git perspective and a developer experience perspective, is using sub-trees. Submodules put a commit in the `git-tree` object, where usually its' just `blob`s and `tree`s. Subtree's don't, they actually create a tree, which is expected. `git log` now too 'just works' on these directories. 

Further, it simplifies the setup and maintainance for developers as `git pull` does everything you'd want it to do.

**Comment by hardillb** [comment]
Closing this as https://github.com/flowforge/flowforge/pull/186 removed all the submodules
