### ISSUE TITLE
Removing old projects with missing subcriptions fails

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1837]
### Current Behavior

Trying to remove an old project that doesn't have a subscription
```
{"log":"[2023-03-15T10:16:30.192Z] INFO: request completed {\"reqId\":\"req-c6w3\",\"res\":{\"statusCode\":500},\"responseTime\":448.01773262023926}\n","stream":"stdout","time":"2023-03-15T10:16:30.274528936Z"}
{"log":"[2023-03-15T10:16:30.192Z] ERROR: Problem removing project from subscription: Error: Customer cus_M3Aypx6T6nn19k does not have a subscription with ID sub_1LL4c9J6VWAujNoL1CbsXuzb\n","stream":"stdout","time":"2023-03-15T10:16:30.274520217Z"}
{"log":"Customer cus_M3Aypx6T6nn19k does not have a subscription with ID sub_1LL4c9J6VWAujNoL1CbsXuzb\n","stream":"stdout","time":"2023-03-15T10:16:30.274331285Z"}
{"log":"[2023-03-15T10:16:30.192Z] WARN: failed removing project from subscription\n","stream":"stdout","time":"2023-03-15T10:16:30.274305386Z"}
{"log":"[2023-03-15T10:16:29.983Z] INFO: Removing Project 748ea4fd-a066-4a3d-ac51-2b356239c6db to Subscription for team zRkvganGby\n","stream":"stdout","time":"2023-03-15T10:16:30.018689666Z"}
{"log":"[2023-03-15T10:16:29.744Z] INFO: incoming request {\"reqId\":\"req-c6w3\",\"req\":{\"method\":\"DELETE\",\"url\":\"/api/v1/projects/748ea4fd-a066-4a3d-ac51-2b356239c6db\",\"hostname\":\"app.flowforge.com\",\"remoteAddress\":\"192.168.88.80\",\"remotePort\":58142}}\n","stream":"stdout","time":"2023-03-15T10:16:30.018684544Z"}
```

### Expected Behavior

If team has no subscription then the project should still be deleted

### Steps To Reproduce

Try to delete project "careful-water-pipit-5027"  (Ben is a team admin)

### Environment

- FlowForge version: 1.4.1
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: K8s/Linux
- Browser: NA

**Comment by hardillb** [comment]
This is interpreting a value returned from Stripe, if Stripe ends up saying things don't exist that really do, we have much bigger problems.

In this specific case I believe Sam deleted the subscription in Stripe to test (this really should have been done in Staging, but that ship has sailed), but without writing code to walk the full subscription table and checking against stripe, I'm 99% sure it's a one off.

But if a customer gets billed for a project they have already deleted, hopefully they will notice and we can match it up and remove it in stripe.

I vote for the second option.

**Comment by Steve-Mcl** [comment]
tested locally. not practical to test on staging.
