### ISSUE TITLE
Team Devices table doesn't update properly when adding/removing devices from instance

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1838]
### Current Behavior

Two bugs found on the Team Devices table on staging.

Start with Team Devices table with a single unassigned device

1. Assign to an instance via the dropdown menu
2. **bug 1**: the table doesn't refresh to show it is assigned
3. Refresh the page to see the correct information
4. Remove the device from the instance via the dropdown menu
5. **bug 2**: the table empties and says you don't have any devices in the team - which is wrong, I just unassigned from the instance, not removed it from the team.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Pezmc** [comment]
I've not been able to reproduce 1 on staging or locally: 
https://user-images.githubusercontent.com/507155/225296187-07410230-a1ac-4a5c-a829-0dbac71cc879.mov

I have been able to reproduce 2, fix incoming
