### ISSUE TITLE
Deprecate `FF_PROJECT_*` envvars and add `FF_INSTANCE_*` equivalents

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1844]
### Description

Part of #1689 

With the move from Project terminology to Instance, these env vars need to be updated.

The task is to add directly equivalent `FF_INSTANCE_*` env vars.

We cannot remove `FF_PROJECT_*` as flows will depend on them. We will mark them as deprecated. The only reason we haven't marked them as deprecated in 1.5 already is we don't have the `FF_INSTANCE_*` alternatives in place - no good deprecating something without its replace available.

A bit of thought is needed in whether we completely hide `FF_PROJECT_*` env vars in the UI, or keep them in the list with a footnote to say they are deprecated.

**Comment by Steve-Mcl** [comment]
A quick win would be to colorise the old entries and change the icon on the right to something that indicates _depreciation_

**Comment by Steve-Mcl** [comment]
For example: 
![image](https://user-images.githubusercontent.com/44235289/226680219-5ffd885a-b31a-4b96-9927-a94dd61cfc91.png)

**Comment by knolleary** [comment]
Adding the headline label to make sure this gets highlighted in the release material.
