### ISSUE TITLE
Changing to a team as a member shows unauthorized error

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1845]
### Current Behavior

Switch to a team that the user is a member (not owner) with billing enabled shows a popup toast with "Request failed: Unauthorized"

Looking at the browser logs this appears to come from the call to get the billing details (to show the menu on the left).

![test](https://user-images.githubusercontent.com/1800845/225379511-dbaba086-b96d-49f3-9d6e-fb0290bc927b.gif)

### Expected Behavior

Not show the error and silently not show the billing menu item

### Steps To Reproduce

Log into flowforge with a user that is in multiple teams and is only "member" level in a given team.
Switch to that team from the drop down in the top right of the screen.

### Environment

- FlowForge version: 1.4.1
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Kube/Linux
- Browser: Chrome

**Comment by Pezmc** [comment]
So the root cause here is being on the billing page _before_ navigating to the other team (as seen in the gif above). 

That makes the surface area significantly smaller than we might have thought.
