### ISSUE TITLE
Delelting instances from the instance list fails

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1859]
### Current Behavior

If you try and delete an instance from the instance list (not the instance overview) using the entry in the kebab menu it fails and hangs at the spinner screen.

If you pick delete from the "Actions" drop down button on the overview page it works.

### Expected Behavior

Delete should work eveyrwhere

### Steps To Reproduce

- Create instance
- navigate to the instance list for a team
- select delete from kebab menu at end of row

### Environment

- FlowForge version: 1.5
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: K8s/Linux
- Browser: Chrome

**Comment by knolleary** [comment]
Confirmed; doesn't look like any request is being made to the API when this option is selected.

**Comment by Steve-Mcl** [comment]
confirmed on staging
