### ISSUE TITLE
Restarting Node-Red Insance triggers crash

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1860]
### Current Behavior

Triggering Node-RED Restart (from the action button) managed to start 2 NR instances in the container. Such that the logged version was crashing because port 1880 was already in use.

### Expected Behavior

There should only ever be 1 instance of NR running and the Launcher should not try and restart until it is sure the previous one is exited.

Also if the restart action if fired twice it should ignore the second occurrence 

### Environment

- FlowForge version: 1.5
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: k8s/Linux
- Browser: NA

**Comment by knolleary** [comment]
I believe the work done in https://github.com/flowforge/flowforge-nr-launcher/pull/111 will address this issue
