### ISSUE TITLE
Remove use of webpack alias

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1908]
### Description

Using webpacks non ES standard aliases looks _slightly_ nicer but breaks one of the key advantages of ES modules, static analysis.

Our aliases e.g. `@`:

 - Lock us to webpack making it harder to swap to another tool
 - Prevent lots of tooling from working correctly, including VSCodes "open file" shortcuts.
 - Prevent static analysis, e.g. eslint checking all files exist
 - Doesn't autocomplete
 - Make it harder to differentiate the scope of the component
 - Encourage shared components not being placed in a shared components folder

Example: https://github.com/elastic/kibana/issues/6430

**Comment by Steve-Mcl** [comment]
> Can I handle that as a follow up?

Sure thing.

**Comment by Pezmc** [comment]
Done in https://github.com/flowforge/flowforge/pull/1910 @Steve-Mcl
