### ISSUE TITLE
FlowForge RBAC for Dashboard viewers only

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#1924]
### Description

As a FlowForge team owner,

I want to assign users a view-only dashboard access role,

So that customers can securely view dashboards without accessing the NR editor or requiring separate credentials.

### Which customers would this be availble to

ee

### Customer requests

* https://app-eu1.hubspot.com/contacts/26586079/company/6583736804
* https://app-eu1.hubspot.com/contacts/26586079/company/7289320689

### Acceptance Criteria

- [ ] Given the existing Role-Based Access Control (RBAC) system,
When a new role (e.g., "dashboard-only viewer") is created,
Then the users assigned to this role should only have access to the dashboard endpoints of the Node-RED instance, without any access to the NR editor.

## Notes
- The solution approach involves extending the existing RBAC system to create a new role below the "viewer" role that only has access to the dashboard endpoints of the Node-RED instance.
- The new role should leverage the existing FlowForge authentication system, allowing users to sign in without the need for separate credentials.

**Comment by MarianRaphael** [comment]
Requested by customer

**Comment by dlolsen5** [comment]
I too would welcome this feature. Our company considers the dashboard logic as IP and don't want viewers to have access to it. Until this is implemented I don't think I will be able to use FF as a dashboard delivery platform.

**Comment by ZJvandeWeg** [comment]
Requested by prospective customer: https://app-eu1.hubspot.com/contacts/26586079/company/7289320689

**Comment by ZJvandeWeg** [comment]
Another customer requested this a while ago, before we linked issues this way: https://app-eu1.hubspot.com/contacts/26586079/company/6583736804

**Comment by knolleary** [comment]
Some notes from starting to look at this:

When accessing the editor, we set the `autoLogin` flag in the Node-RED `adminAuth` configuration which means it doesn't prompt the user to click to login, but bounces them straight to FF to login (if needed).

When we add this new level of user, they will be able to access the `httpNode` routes, but not the admin routes. If they try to access the editor, the `autoLogin` will bounce them to FF, find they are logged in, then bounce them back.... but if they don't have the right permissions they are considered logged out and the `autoLogin` kicks in again and they are bounced to FF again... and end up in an endless redirect loop.

Need to find a way to break out of that loop. For the best UX, it may require an upstream change in Node-RED to not attempt an autoLogin if a login has just failed. However, identifying we're in that scenario is not so simple thanks to the way Passport works.

**Comment by knolleary** [comment]
I have the basic role working in terms of allowing access to just the HTTP routes, but there is more work to do around what the user is allowed to access in FlowForge itself.

Currently, the frontend includes a bunch of assumptions about the minimum set of things a team member is able to access regardless of their role.

This includes:
 - Snapshots
 - Devices
 - AuditLogs
 - Node-RED logs

There is code that calls apis across all of those things without any permission checks; it is assumed they can access those things.

We need to define what the UX should be for a dashboard-only user. It feels like they should have *very* limited access to anything 'behind the scenes' of the instance/application/team - they are intended to be consumers of the flows, not developers working on the flows. As such, we'll need to add a bunch of permission checks through-out the UI to ensure we don't try access things the dashboard-only user is not able to see.

If the user cannot do anything, is there value in letting them see lists of applications/instances etc? They cannot access the editor, and we don't know what paths on the instance have been created for them to access.

We currently allow Viewer level users to see the team members page, but they cannot remove themselves from the team - that feels like an oversight. A user should always be able to remove themselves. If we think that is the case, then the Dashboard user should have the same ability.

**Comment by joepavitt** [comment]
I would be showing a placeholder page (with a more appropriate graphic than this) but something along these lines:

<img width="1448" alt="Screenshot 2023-06-15 at 10 06 26" src="https://github.com/flowforge/flowforge/assets/99246719/a6df6d9d-c325-42fd-830a-8c759e2b8cc3">

**Comment by knolleary** [comment]
@joepavitt yeah, that works. Will work towards that.

**Comment by MarianRaphael** [comment]
Verified on staging
