### ISSUE TITLE
Iterate on verification email screen

### ISSUE THREAD

**Issue by Yndira-FlowForge** [flowforge/flowforge#1925]
- The FlowForge text could be the same font as the logo
- It needs an icon or animation, seems empty

![Image](https://user-images.githubusercontent.com/129537638/230348692-f8f8490a-729a-4cf8-9480-f1c96bc70637.png)

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt [check this out](https://www.figma.com/file/rMB2w5ZZUtTC0nxbwLYKJY?node-id=0:1#456979367) please, let me know what you think

**Comment by Yndira-FlowForge** [comment]
[Figma final version](https://www.figma.com/file/rMB2w5ZZUtTC0nxbwLYKJY?node-id=0:1#456979367) to implement

![Image](https://github.com/flowforge/flowforge/assets/129537638/fd8d42bd-7b14-44c2-88e0-8426bc53b325)

**Comment by joepavitt** [comment]
@MarianRaphael could get this into 1.9 fairly easily? Maybe a little late now for tomorrow.

**Comment by Steve-Mcl** [comment]
@Yndira-FlowForge @joepavitt 

Happy to pick this up however, I dont think the wording is relevant for all cases.

For example, on a CE edition or where there is no trial setup, this would wronlgy inform the user that `"Once verified, you’ll be able to access and start your free trial."` 



<br>

_Perhaps this would be better as a more generic phrase - e.g._:


<br>

### *flowforge*
 \[ email icon \]
**Please verify your Email**
Once verified, you can access the platform
<kbd>Verify My Email</kbd>


<br>

<br>

PS: I would have updated figma and provided a screenshot but I get an error about multiple fonts missing & updating them/replacing them with alternatives - being unfamiliar with figma, I was not keen to break it!

**Comment by Yndira-FlowForge** [comment]
Hi @Steve-Mcl thanks for your input, I see your point.

How about "Once verified, you will be able to access the platform"?

I just updated the Figma, it's strange that it's showing you those alerts...

![Verify email V2](https://github.com/flowforge/flowforge/assets/129537638/313e2397-e106-43e6-8631-65d9295d734d)

**Comment by Steve-Mcl** [comment]
Yes, better imo Yndira thanks 

Though, tbh, I don't think the comma after **Please** is necessary?

**Comment by Yndira-FlowForge** [comment]
I trust you 100% on that one @Steve-Mcl, without the comma works too ;)

**Comment by Steve-Mcl** [comment]
@Yndira-FlowForge 

I cannot find that particular icon.

I did find `envelope_open.png`



![Image](https://github.com/flowforge/flowforge/assets/44235289/3cd7829d-e205-4ec9-bb90-3c6cbe9f0a7f)

But it is not the same.

**Comment by Yndira-FlowForge** [comment]
@Steve-Mcl It's in the [exports folder](https://drive.google.com/drive/folders/12CVebPePLnM-HGmbj2az89-EcylDAD1x?usp=sharing), is [this one](https://drive.google.com/file/d/1RsNw0q465YKtWmmgBksaYrYXK0i8XlVy/view?usp=sharing).

**Comment by Steve-Mcl** [comment]
Verified on staging (using temporary account as documented in handbook)



![Image](https://github.com/flowforge/flowforge/assets/44235289/ae38a0c3-89f4-4060-9507-36063f573e63)
