### ISSUE TITLE
Application overview: Suspended instances show as starting

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1932]
Slight up date to this is that we know see `unknown` instead of `starting`. The API response also returns `unknown` when getting `/status` at the Application level.

When you view the Instance overview page, it works fine.

![Image](https://user-images.githubusercontent.com/99246719/230583884-5261afec-4f0b-428c-960f-9c37a977e08b.png)
![Image](https://user-images.githubusercontent.com/99246719/230583886-950e695b-17a3-4eac-bb30-5c78383d305a.png)
![Image](https://user-images.githubusercontent.com/99246719/230583885-c9bcf71c-a005-45b7-8a6e-6fb9026e5cfd.png)

**Comment by Pezmc** [comment]
Potentially fixed in https://github.com/flowforge/flowforge/pull/1926

**Comment by joepavitt** [comment]
Not an issue on staging - reducing priority - appears to only occur locally.

**Comment by Pezmc** [comment]
The `unknown` comes from the container wrapper, issue is likely linked to https://github.com/flowforge/flowforge/issues/1949 and/or issues in Joe's local development environment, unable to reliably reproduce locally.
