### ISSUE TITLE
Application Level Audit Log Entries

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1978]
### Description

https://github.com/flowforge/flowforge/issues/1935 introduced Team level Audit Log entries for applications (i.e. Team.application.created/updated/deleted).

However, there is not a concept of an event belonging to an application yet. Audit Log events are currently only stored the platform, user, instance or team level.

Ideally, there should also be audit log entries at the application level introduced too, i.e. `application.instance.created` and `application.instance.updated`.

With the current implementation, this will mean that instance created event, for example, has an instance level, application level, and team level audit log entry.

Longer term, there has been recent suggestions on re-working this database structure so that a single event can belong to multiple entities i.e. /cc: @joepavitt @Steve-Mcl 
 - Get all events that occurred within this team
 - Get all events that occurred within this application
 - Get all events that occurred within this instance

**Comment by Steve-Mcl** [comment]
Additional info: It seems we currently ship FF with access to Audit Logs at application level but they are broken - have been for around 6 month.

https://github.com/flowforge/flowforge/assets/44235289/e98f1368-c6c8-4abf-8e0b-80fc993f695d

**Comment by joepavitt** [comment]
They're not broken, they were never implemented. There would have been a very short period of time where Application === Instance, and they would have rendered. Once Applications were truly Applications, that tab should have been (but wasn't) removed

**Comment by Steve-Mcl** [comment]
Joe, I realise that **application audit logs** were never implemented, the code behind this page is _by its design_  written to show the owned projects' **Project Audit Logs**. That is not working.

**Comment by Steve-Mcl** [comment]
Progress parked in branch 1978-application-audit-log


### Progress:
* fixed displaying project logs as mentioned in previous comment
* modified filter to show "Event Scope" (as discussed) - included first entry of  "This Application" followed by the instances
  * not ideal but a start - ideally, our `ff-dropdown-option` could include an icon then we can clearly differentiate application from instance
* APIs in place for accessing application audit logs


### TODO:
* add framework for making application level log entries
  * _a list would be helpful_

![chrome_V1m2VzZfqK](https://github.com/flowforge/flowforge/assets/44235289/99eca49a-918d-4bad-ae67-92c47b3ab79d)

**Comment by Steve-Mcl** [comment]
Verified on staging


### Application level logs (new feature)
![image](https://github.com/flowforge/flowforge/assets/44235289/caffd563-1f4f-443d-84a2-9db6f3a7bf0a)


### Instance level logs viewed from inside application (previously not working)
![image](https://github.com/flowforge/flowforge/assets/44235289/536002e0-262d-41fa-bb68-62a086ea8005)
