### ISSUE TITLE
Application/Instances views missing info popup dialog and header description

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#1995]
### Current Behavior

Devices view has the ℹ️ icon and description of the view:

<img width="415" alt="image" src="https://user-images.githubusercontent.com/51083/231713705-57a6f236-b8f7-49ac-b625-c5417f743de4.png">

Applications and Instances view do not:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/51083/231713938-b3b250bf-db97-48c5-b7ca-81dcd9e6c41a.png">

<img width="338" alt="image" src="https://user-images.githubusercontent.com/51083/231713984-384b762a-8795-4dde-b0fc-3c6e9dd0749a.png">

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
We may want to consider moving the grey subtitle into the popover as this will help improve small device layout issues. See #1971
