### ISSUE TITLE
Timed Snapshot Deployments for Devices

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2008]
### Epic

https://github.com/flowforge/flowforge/issues/1509
https://github.com/flowforge/flowforge/issues/1492

### Description

As a FlowForge User, 
I want to set a timer when my snapshot should be deployed,
in order to run deployments during specific time windows, such as at night or during a shift change.

### Which customers would this be availble to

All Users, (CE)

**Comment by knolleary** [comment]
Duplicate of #1953 - will let you pick which we keep
