### ISSUE TITLE
Local installation instructions minor issues - Raspberry

### ISSUE THREAD

**Issue by jdotbdot** [flowforge/flowforge#202]
### Current Behavior

The installation instructions say 
 **cp -R flowforge-installer-x.y.z/* /opt/flowforge**
But the unzipped directory is flowforge-install-0.1.0 not flowforge-installer-0.1.0  (no "er")

And 
**sh ./install.sh**
On a Raspberry at least, sh is /bin/dash which can't understand **if [[ "$MYOS" == "debian" ]]** syntax.
Since the unzipped install script is executable, this could be avoided by just running
**./install.sh**

Installation seems to be hung at  http fetch GET 200 https://registry.npmjs.org/@node-red/editor-client/-/editor-client-2.1.6.tgz 118490ms (cache miss) too.

### Expected Behavior

A smooth installation without error messages

### Environment

- FlowForge version: 0.1.0
- Node.js version: 16.13.2
- npm version: 8.1.2
- Platform/OS: Raspberry Pi Zero 2 / Raspbian GNU/Linux 11 (bullseye) 5.10.63-v7+
- Browser: n/a

**Comment by hardillb** [comment]
Fixed in the flowforge/installer and PR queued up for main project https://github.com/flowforge/flowforge/pull/201

**Comment by hardillb** [comment]
Thanks for raising this, the docs have been updated to match in both places.

As for hanging up on installing the the `@node-red/editor-client`, this is either a network glitch or a problem at the npmjs.org end of things that we can't easily fix.

I do know the install script needs a little bit more error handling and will be adding it before the next release.
