### ISSUE TITLE
Add support for sending email via HubSpot

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#2021]
### Description

We integrate with HubSpot to track interactions with customers of FlowForge Cloud. That includes any emails sent to the customer.

This is separate from the emails the FF platform sends itself; such as the initial welcome email.

We would like to enable the ability to send all customer emails via hubspot (if so configured) so we can track the interactions and assess the effectiveness of the emails.

**Update 7/7/23**: read this comment for the current plan of action: https://github.com/flowforge/flowforge/issues/2021#issuecomment-1624451446

---
**Original description**

This would be an optional configuration via `flowforge.yml`.

Open questions
 - Does this apply to all emails? If the goal is consistency in appearance, then it should - unless we also do #1967 to let us apply more custom templates for our platform-sent emails to achieve consistency between the two.
 - Presumably Hubspot requires the contact to exist already. That implies we need to generate the hubspot contact as part of the sign-up process as well....
 - What does this mean for the 'email change' email we just added - that gets sent to their new address to verify its real? Hubspot won't know about that new address...
 - What configuration is needed for the platform to know how to send a particular email template to a particular user?
 - There are 'transactional' emails around email verification/forgot password etc that need custom content such as link urls - is that possible to achieve via hubspot api?

**Comment by robmarcer** [comment]
@knolleary This feels like it's very close to conversations I've heard over the past few weeks with @iskerrett. I wonder if the goals are not what was intended, or maybe it's just unrelated but sounds similar?

My take is as follows.

Our goal is to move all emails which are not integral to using FF over to Hubspot. By integral, I mean emails such as email verify, password reset, invite a team member. It could be just those three but we'd need to audit all the emails to work out what we feel is 'integral'. 

Everything else would go via Hubspot and we can use our existing integration with Hubspot to trigger those emails. This allows us to iterate on the content, timing and targeting of those emails rapidly as part of trying to do better 'customer success'. 

This would also draw a good line between what FlowForge self hosting users will need to for the platform to function and what we want to be able to send to make FlowForge Cloud successful.

If I'm on the right tack I think the steps would be:

1. Identify all emails being send via FF Cloud.
2. Decide which are 'integral' to all FF installs and which are customer success driven.
3. Set up all the existing non-integral emails to be sent via our existing Hubspot integration.
4. Remove the triggering of those emails via FF's configured SMTP connection.

I would deal with step 3.

I suppose we could also move the 'integral' emails over as well, I just think that will require more development to get up and running and all the steps above will still probably need to be done.

Hope I'm not misunderstanding the motivation behind this issue, sorry if that's the case.

**Comment by knolleary** [comment]
@robmarcer this issue was raised in direct response to the request from @iskerrett for us to look at this.

There are a number of open technical questions on how we do this that I outline in the description - largely around how the integration with hubspot works. As this item is still unplanned on the backlog I haven't spent any time on the hubspot api to understand how it works to see what is feasible.

**Comment by robmarcer** [comment]
@knolleary thanks for the context, I'm even more confident now that what @iskerrett wants is what I've set out. The request came from a discussion I had with him which he said he would raise with you. I think it's just got a little lost in translation.

I don't think you need to look into how we will integrate with Hubspot as we already have a way to write users to Hubspot as needed and trigger emails.

So I'm now very sure the steps are:

1. Identify all emails being send via FF Cloud (I might be able to deal with this, if someone points me in the direction of the code that deals with it).
2. Decide which are 'integral' to all FF installs and which are customer success driven (I can make a proposal for review).
3. Set up all the existing non-integral emails to be sent via our existing Hubspot integration (I can do this).
4. Remove the triggering of those emails via FF's configured SMTP connection (possibly not something I can help with).

**Comment by knolleary** [comment]
The list of emails are:

 - https://github.com/flowforge/flowforge/tree/main/forge/postoffice/templates
 - https://github.com/flowforge/flowforge/tree/main/forge/ee/emailTemplates

> Set up all the existing non-integral emails to be sent via our existing Hubspot integration (I can do this).

I was working on the assumption that the platform would still 'trigger' these emails, but done via a hubspot api call rather than SMTP. But this sounds like you are saying the integration will just somehow know what to send and when with no prompting from the platform. That means building a lot of application state logic into the integration - duplicating what we already have in the platform.

Lets schedule some time to talk through this as I don't think we're on the same page in terms of implementation details.

**Comment by robmarcer** [comment]
That sounds great @knolleary, please drop something in my calendar when you have time. Thanks for your help.

**Comment by knolleary** [comment]
Following subsequent discussion on this feature, we've reached the understanding that the requirement is simply for the platform to be configured to not send certain emails. The assumption is an external business process will be created that takes full responsibility for deciding when certain emails need to be sent and ensuring they are sent.

That simplifies the task and I have reduced the sizing accordingly.

Some types of emails will have to continue being sent by the platform - email validate, password resets etc.

I propose adding an option to Admin Settings (UI, not flowforge.yml) that allows the admin to turn off sending of the non-transactional emails (welcome aboard, trial due to expire, etc). Will need to consider if it's a single checkbox, or a list of email-types that the admin gets to pick individually.

**Comment by iskerrett** [comment]
When we announce the starter tier in 1.11, the introductory email will need to change? I could not find a version of this email at the links specific in [comment ](https://github.com/flowforge/flowforge/issues/2021#issuecomment-1532735018). Where can I find this email?

**Comment by MarianRaphael** [comment]
See also: https://github.com/flowforge/CloudProject/issues/175

**Comment by knolleary** [comment]
This is a list of all emails the platform current sends. To move this forward, I need a clear confirmation which ones will be dealt with by Hubspot without the platform doing anything.

Email | Description
----|----
`EmailChanged` | Sent to confirm a user's email has been changed on the platform
`PasswordChanges` | Sent to confirm a user's password has been changed on the platform
`PasswordReset` | Sent when a user requests a password reset - includes the link to click to action the request
`PendingEmailChange` | Sent when a user requests to change their email - includes the link to confirm the request
`TeamInvitation` | Sent when an existing user is invited to join a team
`UnknownUserInvitiation` | Sent when an unknown user is invited to join a team
`UsernameChanged` | Sent to confirm a username has been changed on the platform
`UserSuspended` | Sent when a user is suspended on the platform
`VerifyEmail` | Sent when a user signs up and has to verify their email for the first time - includes the link to confirm
`LicenseExpired` | Sent when the platform license has expired
`LicenseReminder` | Sent when the platform license will expire soon
`TrialTeamCreated` | Sent when a user signs up and starts a trial
`TrialTeamEnded` | Sent when a trial ends - but they have configured billing
`TrialTeamReminder` |Sent when there are 7 days/2days remaining of the trial
`TrialTeamSuspended` | Sent when the trial ends and they have not configured billing


I think it is primarily the `TrialTeam*` ones - the others are more transactional emails.

I will work on that basis, but please flag up if any others should be covered by this.
