### ISSUE TITLE
DevOps Pipeline still mentions Projects

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#2022]
### Current Behavior

Here, you can configure the next stage in your DevOps Pipeline. You can deploy changes made to this project, directly onto the next stage in your DevOps Pipeline.

This feature is often used to create a Dev > Staging > Production pipeline, where each stage of your pipeline is a standalone FlowForge Instance.

Changes are only pushed to the next stage upon manual actioning of the "Push" button below.

### Expected Behavior

Here, you can configure the next stage in your DevOps Pipeline. You can deploy changes made to this Application, directly onto the next stage in your DevOps Pipeline.

This feature is often used to create a Dev > Staging > Production pipeline, where each stage of your pipeline is a standalone FlowForge Instance.

Changes are only pushed to the next stage upon manual actioning of the "Push" button below.

### Steps To Reproduce

Visit the settings page for an instance then select DevOps

### Environment

- FlowForge version: 1.6.0
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by joepavitt** [comment]
verified on staging
