### ISSUE TITLE
Installed locally, problem with Editor button.

### ISSUE THREAD

**Issue by jdotbdot** [flowforge/flowforge#204]
### Current Behavior

I did a "local" install of Flowforge on a headless Raspberry Pi via ssh. The Pi is at IP 192.168.1.102

I access Node-red from a PC, a different IP on the same network :192.168.1.102:1880
Flowforge is available at 192.168.1.102:3000 but the Editor button tries to open localhost:7880 and of course it is unable to connect (192.168.1.102:7880 gives the same error)

I can't see a simple fix in flowforge.yml. "base URL" doesn't seem to make a difference.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
Changing the `base_url` will only apply to projects created after the change.

**Comment by hardillb** [comment]
Can we close this now?

**Comment by jdotbdot** [comment]
Sorry, I'll check your response now...

**Comment by jdotbdot** [comment]
OK I have reinstalled RPiOS Lite (Bullseye), updated it and flowforge, changed the base URL in flowforge.yaml to http://192.168.1.25:3000, started the service and created a project.

The editor button now tries to open 192.168.1.25:7880 but I still get the same error:
Firefox can’t establish a connection to the server at 192.168.1.25:7880.

**Comment by hardillb** [comment]
Please look in the `var/projects` directory, there should be a uuid (the project id) named directory, In there will be a file called `out.log` Attach that file to this issue and also if there is anything shown in the `logs` tab that will be useful as well

Also please fill in the important details at the end of the template (all the version information)

**Comment by jdotbdot** [comment]
out.log contains this
`Launcher Started
Loading project settings
Target state is 'running'
Starting Node-RED
`
"logs" in browser has this
`27/01/2022 20:47:41
[system]
Launcher Started
27/01/2022 20:47:41
[system]
Loading project settings
27/01/2022 20:47:41
[system]
Target state is 'running'
27/01/2022 20:47:41
[system]
Starting Node-RED
27/01/2022 20:47:45
[info]
Welcome to Node-RED
===================
27/01/2022 20:47:45
[info]
Node-RED version: v2.2.0
27/01/2022 20:47:45
[info]
Node.js  version: v16.13.2
27/01/2022 20:47:45
[info]
Linux 5.10.63-v7+ arm LE
27/01/2022 20:47:48
[info]
Loading palette nodes
27/01/2022 20:47:52
[info]
Settings file  : /opt/flowforge/var/projects/78934ec8-54b0-470c-8af7-682b97d0eda3/settings.js
27/01/2022 20:47:52
[info]
Context store  : 'default' [module=memory]
27/01/2022 20:47:52
[info]
Server now running at http://127.0.0.1:7880/
27/01/2022 20:47:52
[warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
27/01/2022 20:47:52
[info]
Starting flows
27/01/2022 20:47:52
[info]
Started flows`

Environment
    FlowForge version: 0.1.0 (presumably)
    Node.js version: 16.13.2 (installed by flowforge installer)
    npm version: 8.1.2
    Platform/OS: Raspberry Pi Zero 2 / RPiOS Lite Bullseye
    Browser: Firefox 96.0.1 (Windows 10)

**Comment by hardillb** [comment]
OK, the logs imply everything is running properly.

Can you try running `sudo iptables -L` to see if there is any default firewall rules blocking things

Also just checking, how are you accessing the pi zero to start FlowForge? Are you using ssh from the Windows machines?

**Comment by jdotbdot** [comment]
iptables command not found.
This is on another Pi on the same network
`pi@GlassPi:~ $ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
`

Yes, ssh over wifi from WIndows.

I don't know if this is relevant but if I install Node-red I can always access it at IPAddress:1880 
Can't do that on this Flowforge installation, I guess you wouldn't expect to?

**Comment by hardillb** [comment]
Output from a different pi isn't really useful, but if `iptables` is not installed then it's unlikely that there are any rules enabled (and base Raspberry Pi OS lite doesn't have any ruels by default).

Given the logs say things are running, we can double check with `ps -efc | grep flowforge` and `ps -efc | grep node-red` but I expect the processes to all still be running.

Also have you tried to access the editor link again since starting the project? I just want to make sure it wasn't just the Pi Zero being slow to start a project.

P.S. multi line code blocks need to start with 3 \`  backticks on a line before and after the code. Single ticks don't work. I've edited the last 2 comments to help make them readable.

**Comment by jdotbdot** [comment]
Good thought. Yes, Node-red editor loads now. So I guess Flowforge or NR was doing something in the background. The Pi Zero2 is only a tiny computer!

So yes, close this. Maybe make a note in the installation instructions.

3 backticks: I hit the Insert code button and pasted where the cursor is. It works in Node-red forum :-)
