### ISSUE TITLE
Add api token scoped to just admin/stats end-point for system monitoring

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#2043]
### Description

**As an**: Admin user
**I want to**: enable scripted access to the stats admin endpoint, without providing full admin access to the platform
**So that**: I can securely monitor the system.

---

Our current ways to monitor the platform involve scanning logs, relying on stripe callbacks and other tricks that have to be setup manually.

The issue with the stripe callback notifications is that it only applies once billing is setup in a team - which is no longer something every user has to do when signing up to FF Cloud.

But more generally, it should be easier to monitor the current state of the platform.

We already have in place with the `/api/v1/admin/stats` end-point that can be used to monitor basic stats of the platform. However this endpoint is protected by admin level access.

**An Admin user should be able to create a long-lived access token that provides read-only access to the stats end-point and nothing else.**

We have an item in the backlog to support users creating API tokens - #14. That is a far more general solution (which we will need eventually), but this issue is a quick iteration to enable much better monitoring integration.

**Comment by Steve-Mcl** [comment]
Nick tested locally.
