### ISSUE TITLE
FlowForge should show device agent version in the dashboard

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#2047]
### Description

It can be time consuming to ensure I am running the up to date version of the device agent on my devices.

I can login to each and run ```flowforge-device-agent --version``` but with multiple devices that becomes a very slow and manual process.

A user should be able to view what version of the device agent is running on each of their devices when viewing devices in the FlowForge dashboard.

This could also be a step towards a UI which allows a user to update to the latests device agent without logging into each device.

**Comment by hardillb** [comment]
The device-agent version is now part of the check in details and stored in the database as part of the device-agent log streaming, so the data should now be available (for newer versions of the device-agent/flowforge). So any UI should handle the version not being present for old versions of the agent.

**Comment by knolleary** [comment]
Done via #2042 as the agent version is important info to know when trying to access the editor.

<img width="973" alt="image" src="https://github.com/flowforge/flowforge/assets/51083/ed3e4d4b-2e64-4d68-8ef7-8514bc2b0a18">
