### ISSUE TITLE
Stuck Loading graphic when deleting an Instance

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2060]
### Current Behavior

https://eu.posthog.com/recordings/187c021551318d7-0cafc371dac9b7-26031b51-100200-187c021551443ea?t=1353

### Expected Behavior

- Loading graphic should stop showing once the instance has been deleted.

### Steps To Reproduce

- Create an Application & Instance
- Delete the Instance from the "Instance > Overview" page.

### Environment

- FlowForge version: 1.6.0
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Pezmc** [comment]
@joepavitt I wasn't able to reproduce this locally or on staging, are you still seeing this issue?

**Comment by joepavitt** [comment]
I hadn't tried to reproduce myself to be fair, was just reference the session recording from PostHog. It may be linked with the fact the instance got caught in an odd state as we ran out of resources that night. So the Instance may not have actually been created?

Was thinking, if you follow that session recording, should at least be able to track down where we have a missing `this.loading = false` in order to reset state?

**Comment by Pezmc** [comment]
Deleting instance is wrapped in a finally() so as far as I can see on first read through, should always be deleted: https://github.com/flowforge/flowforge/blob/01706a5418291b9b26923c4083937b7167e4a75e/frontend/src/pages/instance/index.vue#L254-L256

**Comment by Pezmc** [comment]
Unable to reproduce
