### ISSUE TITLE
Empty State: No Application (/team//applications)

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2065]
Key Messages to communicate:

Applications; Groups of instances (shared settings, staged deployments, high availability)

**Comment by Yndira-FlowForge** [comment]
Based on the results of the workshop and after our discussion, here's a proposal for this empty state.

- Dashed line means what has not been created yet.
- Plus symbol implies you can add it.
- We're keeping the squares on the outlines of each shape; this connects with the pictograms and adds some originality as well.
- The gear icon inside the square gives a hint of shared settings by everything inside of it.
- The NR icons reinforce what the text says about an app containing groups of NR instances.

![Image](https://user-images.githubusercontent.com/129537638/235643862-95e8995d-d2de-4167-af5c-d1eaa3188396.png)

**Comment by joepavitt** [comment]
This is great Yndira - would only make a _minor_ change, of removing a dash below the "node" in the top-right, so it looks like it's flowing/moving more. With the solid line, the gap is sufficient, with dash, it needs to be larger.
