### ISSUE TITLE
Empty State: No Snapshots within an Instance (/instance//snapshots)

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2068]

**Comment by Yndira-FlowForge** [comment]
And, the last one!! @joepavitt 

![Image](https://user-images.githubusercontent.com/129537638/236157942-6d077b0e-9520-4d9a-a98c-4540742619fd.png)

Please, check out these too #2071 #2069 and #2070

**Comment by joepavitt** [comment]
Excellent
