### ISSUE TITLE
engine not specified in package.json

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#207]
### Current Behavior

Installed on windows under nodejs 14. Several issues were encountered running FF - possibly related to nodejs 14 (will try again after updating nodejs)

### Expected Behavior

an entry in package.json `engines` entry would nip this in the bud

Additionally, should node version be mentioned in readme?

### Steps To Reproduce

install on computer with node js < 16

### Environment

- FlowForge version: 0.1.1
- Node.js version: v14.16.1
- npm version: 6.14.12
- Platform/OS: Win 11
- Browser: NA

**Comment by hardillb** [comment]
The first test in the install script should have failed with NodeJS 14 and exited before actually running the npm install.

If you haven't upgraded to NodeJS 16 yet we can run some trials on Monday to work out why the tests in the batch file failed.

But adding a `engines` section will help (but it's not clear in the npm [docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines) if it's just a warning by default and only a hard failure if the user has the right flag in their settings or if this only applies to the `npm` entry not the `node` entry)

Also I think Nick mentioned the NodeJS 16 requirement is in the installer [README.md](https://github.com/flowforge/installer#nodejs) but should be added to the central install docs.

**Comment by Steve-Mcl** [comment]
@hardillb apologies, I should have been more explicit - this was not an installer install but an install following the instructions in this repo (i.e. git clone, npm install / build) so the engine check was not performed. 

Also, I've since updated to node 16 on my personal computer. Once I get a works computer, I could of course use 14 or setup a windows VM with v14
