### ISSUE TITLE
Empty State: Team Library (/team//library)

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2071]
Team Library: Shared store of stuff - where stuff are flows or JavaScript functions

**Comment by Yndira-FlowForge** [comment]
For this one, I changed the shape to be a circle (representing the library), with a couple of flows in it and a team icon with syncing arrows around it, meaning everyone sees the same "stuff," and all the additions made by everyone are available within the team library.


![Image](https://user-images.githubusercontent.com/129537638/235714078-7afc7603-794c-434a-aeca-ee4c377f5da6.png)

**Comment by joepavitt** [comment]
> Would it make sense to include a link to the instances as the starting point to add something to the library?

Definitely, we won't have a single Instance though, so would need to _either_ go to /applications or /instances. I'm thinking the latter.
