### ISSUE TITLE
Enable configuration of "pipelines" at the API and DB level

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2076]
### Story

https://github.com/flowforge/flowforge/issues/2075

### Description

We need to add a new "Pipeline" model to the DB. This should enable definition of multiple stages within a single pipeline. Discussion should be undertaken to define what features need to be stored at the "stage" level too.

#### 1. Pipelines

We have a single "Pipeline" object which stores everything in a single object

#### 2. Pipelines & Stages

We have a "child" model called a "Stage" which maps the relevant data on a stage-by-stage basis. Then, the 'Pipeline" object is simply a mapping of multiple "Stages"

**Comment by joepavitt** [comment]
Currently, we simply require a definition of the Instance at the "Stage" level, at which point all of the relevant data is transferred.

<img width="551" alt="Screenshot 2023-05-03 at 12 03 54" src="https://user-images.githubusercontent.com/99246719/235898858-edb56441-9461-4617-b8cf-7001c987c202.png">

We have however had discussions with customers about having much more customisable staging, e.g. multiple development instances merging into a single production instance (which then has multiple flow tabs inside). How do we build something that scales here? I'm thinking Option 2 serves us better long term.

**Comment by joepavitt** [comment]
Having the stage-by-stage model also permits us to store "Last Run" data for that stage, and where that run was triggered from (i.e. did the user just manually run this stage (like a workflow trigger on GH Actions) or was it triggered as part of an automated step in a pipeline?

**Comment by Pezmc** [comment]
Based on the design in https://github.com/flowforge/flowforge/issues/2082, I'd lean strongly towards option 2. An application (or pipeline) should have multiple stages that reference each other (and the underlying instance).

Can an application have multiple pipelines? (and is that in scope for 1.7)

i.e. is the structure:

```mermaid
graph TD;
    Application--has many-->Pipeline;
    Pipeline--has many-->Stage;
    Stage--has one-->Stage;
    Stage--has one-->Instance;
    Instance--belongs to-->Application
```

Or this, where several stages are implicitly a pipeline:

```mermaid
graph TD;
    Application--has many-->Stage
    Stage--has one-->Stage;
    Stage--has one-->Instance;
    Instance--belongs to-->Application
```

**Comment by joepavitt** [comment]
No reason why an Application couldn't have multiple pipelines at the moment. The one definiton that we know for sure _now_, but is likely to change is a single Stage of the Pipeline tying to just one instance, for example, we've had one customer ask if they could have 100+ instances of Node-RED that then combine into a single "Production" instance.

So in that case, Stage 1 maps to 100+ instances, Stage 2 is just one. So I'd say:


```mermaid
graph TD;
    Application--has many-->Pipeline;
    Pipeline--has many-->Stage;
    Stage--has many-->Instance;
    Instance--belongs to-->Application
```

**Comment by Pezmc** [comment]
Thank you for the extra context, in the interests of keeping it simple I'd propose:

- Introduce pipeline model which has:
   - Pipeline info, name, settings, etc...
   - Application ID
   - Starting Stage ID
- Introduce stages model which contains:
   - Stage specific info, name, settings, last run, etc.. as well as:
   - Next stage ID
   - An pipeline ID (only one pipeline per application for now)
- Add stage_id to instance model

```mermaid
graph TD;
    Application--has one-->Pipeline;
    Pipeline--has many-->Stage;
    Stage--has one-->Stage;
    Instance--belongs to-->Application
    Instance--belongs to-->Stage
```

I think that gives flexibility to add complexity down line, while keeping it simple now.

**Comment by Pezmc** [comment]
It could also sit at the pipeline level, but then the relationship, uniqueness, etc, can't be enforced by the database. It would also mean a pipeline has a list of stages, and it's not possible to look up which pipeline a stage is from, except by having the relationship stores twice (from pipeline->stages and from each stage->pipeline).

With this set-up, I'm picturing the query is more like: `Application.getPipeline()`, `Pipeline.getStages()` which can then be a `SELECT * FROM stages WHERE pipeline_id=5`.
