### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'port') (WINDOWS)

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#208]
### Current Behavior

Following installer instructions in the [installer repo](https://github.com/flowforge/installer) I downloaded and installed on Windows 11.

Upon launching flowforge, the following error occurs...

![image](https://user-images.githubusercontent.com/44235289/150640459-36252063-6c42-448d-afd8-69cb7791ac61.png)

```bash
[2022-01-22T13:15:03.972Z] INFO: FlowForge Data Directory: C:\Users\Stephen\Downloads\flowforge-installer-0.1.0\flowforge-install-0.1.0\bin
[2022-01-22T13:15:03.974Z] INFO: Config File: C:\Users\Stephen\Downloads\flowforge-installer-0.1.0\flowforge-install-0.1.0\bin\etc\flowforge.yml
[2022-01-22T13:15:03.975Z] ERROR: Failed to read config file C:\Users\Stephen\Downloads\flowforge-installer-0.1.0\flowforge-install-0.1.0\bin\etc\flowforge.yml: Error: ENOENT: no such file or directory, open 'C:\Users\Stephen\Downloads\flowforge-installer-0.1.0\flowforge-install-0.1.0\bin\etc\flowforge.yml'
C:\Users\Stephen\Downloads\flowforge-installer-0.1.0\flowforge-install-0.1.0\app\node_modules\@flowforge\flowforge\forge\app.js:51
    process.env.PORT = process.env.PORT || server.config.port || 3000;
                                                         ^

TypeError: Cannot read properties of undefined (reading 'port')
    at C:\Users\Stephen\Downloads\flowforge-installer-0.1.0\flowforge-install-0.1.0\app\node_modules\@flowforge\flowforge\forge\app.js:51:58
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[process exited with code 1 (0x00000001)]
```

### Expected Behavior

To run without any prior configuration 
* or documentation to be explicit if configuration is required before launch?
* and/or for installer to ensure defaults are set / config is written?
* and/or launcher to gracefully handle missing config?

Additionally - should the installer batch pause at the end of its operation for users to check installation status?

Lastly, as node-js is a pre-requisite, would a platform common installer running in node js (similar to the `node-red admin init` setup) be a possible means of improving installation?

### Preamble
As there were no explicit instructions for where to unzip to or where to install for windows I proceeded as a non-tech user might do.  As the zip downloaded to `C:\Users\Stephen\Downloads\` I simply opened the zip (double click in explorer) and unzipped using the built in `Extract All` button which then unzipped to `C:\Users\Stephen\Downloads\flowforge-installer-0.1.0\`

### Installing
Following installer instructions for windows in [installer repo](https://github.com/flowforge/installer) ...
* download [flowforge-installer-0.1.0.zip](https://github.com/flowforge/installer/releases/download/v0.1.0/flowforge-installer-0.1.0.zip)
* double click (to open in explorer) the downloaded zip
* unzip (using explorer "extract all" button) to default location
  * As there were no recommendations for windows, I accepted the default location `C:\Users\Stephen\Downloads\flowforge-installer-0.1.0`
  * This unzipped as follows...
![image](https://user-images.githubusercontent.com/44235289/150640628-8b3dfeb7-3fc4-433b-892c-63ecebbedccb.png)

* Double click into `C:\Users\Stephen\Downloads\flowforge-installer-0.1.0\flowforge-install-0.1.0\` 
* Double click `install.bat`

Installation proceeded and exited (did not pause to show results - I am assuming success - Any logs on windows?)

### Startup ...
* Browsed into `bin\` and double clicked `flowforge.bat` 
  * A terminal opened and present the error described above

### Additional info
the bin folder `C:\Users\Stephen\Downloads\flowforge-installer-0.1.0\flowforge-install-0.1.0\bin` does not contain the directory `etc` and (obviously) neither does the file `\bin\etc\flowforge.yml` exist

### Environment

- FlowForge version: 0.1.1 (installer 0.1.0)
- Node.js version: v16.13.2
- npm version: 8.1.2
- Platform/OS: Windows 11
- Browser: NA

**Comment by hardillb** [comment]
@Steve-Mcl I think this has been all fixed now. Can you give it a test please so we can close this before Thursday.

**Comment by Steve-Mcl** [comment]
@hardillb 

### Following the instructions to the letter...
install part went well (the package-lock not found entry in the install log *might* throw some folk)
```bash
**************************************************************
* FlowForge Installer                                        *
*                                                            *
**************************************************************
NodeJS Found
**************************************************************
* NodeJS Version 16 or newer found                           *
**************************************************************
**************************************************************
* npm found                                                  *
**************************************************************
8.1.2
The system cannot find the file specified.
Could Not Find C:\flowforge\app\package-lock.json
**************************************************************
* Installing FlowForge                                       *
**************************************************************
        1 file(s) copied.
**************************************************************
* Installed FlowForge                                        *
* Start with bin\flowforge.bat
**************************************************************
```

### Muddling my way through it like I did in the OP...
* download zip (this went to c:\user\stephen\downloads)
* opened and extracted using exploreres built in **extract** button
* Entered the extracted folder via explorer and double clicked `instal.bat` which resulted in the windows protection dialog 
![image](https://user-images.githubusercontent.com/44235289/154233226-634dc5f0-d70f-417d-808d-065d6bad50f3.png)
* After clicking "more info" then "run anyway" this is the result...
```sh
**************************************************************
* FlowForge Installer                                        *
*                                                            *
**************************************************************
NodeJS Found
**************************************************************
* NodeJS Version 16 or newer found                           *
**************************************************************
**************************************************************
* npm found                                                  *
**************************************************************
8.1.2
The system cannot find the file specified.
Could Not Find C:\Users\Stephen\Downloads\flowforge-installer-0.1.1\flowforge-installer-0.1.1\app\package-lock.json
**************************************************************
* Installing FlowForge                                       *
**************************************************************
        1 file(s) copied.
**************************************************************
* Installed FlowForge                                        *
* Start with bin\flowforge.bat
**************************************************************
Press any key to continue . . .
```

Next: opening `bin` folder then double clicking `flowforge.bat` results in the same "Windows Protected your PC" message.  Bypassing that (clicking "more info" -> "run anyway") fired up a terminal with the following...

```sh
[2022-02-16T09:33:48.273Z] INFO: FlowForge Data Directory: C:\Users\Stephen\Downloads\flowforge-installer-0.1.1\flowforge-installer-0.1.1
[2022-02-16T09:33:48.275Z] INFO: Config File: C:\Users\Stephen\Downloads\flowforge-installer-0.1.1\flowforge-installer-0.1.1\etc\flowforge.yml
[2022-02-16T09:33:48.292Z] INFO: Database driver: sqlite
[2022-02-16T09:33:48.292Z] INFO: Database file: C:\Users\Stephen\Downloads\flowforge-installer-0.1.1\flowforge-installer-0.1.1\var\forge.db
[2022-02-16T09:33:48.684Z] INFO: No license applied
[2022-02-16T09:33:48.817Z] INFO: Email not configured
[2022-02-16T09:33:48.928Z] INFO: Server listening at http://0.0.0.0:3000
```

Accessing `http://localhost` I can see FlowForge is working & i can complete setup. 


### NOTES: (some of this you might want in separate issues on other repos - but I will list here for now)
1. should the last INFO line be changed to `Server listening at http://localhost:3000` or `Server bound to 0.0.0.0 on port 3000`?
2. On windows, a CMD terminal is fired up when a project is created/started.  If I close that terminal...
    1.  FlowForge fires it back up after a short time but it does this...
    ```
        Launcher Started
        Loading project settings
        Target state is 'running'
        Starting Node-RED
        Node-RED exited rc=1 signal=null
        Starting Node-RED
        Node-RED exited rc=1 signal=null
        Starting Node-RED
        Node-RED exited rc=1 signal=null
        Starting Node-RED
        Node-RED exited rc=1 signal=null
        Starting Node-RED
        Node-RED exited rc=1 signal=null
        Node-RED restart loop detected. Stopping
    ``` 
    and all the while, flowforge shows: ![image](https://user-images.githubusercontent.com/44235289/154239152-b1bfa21c-1d18-49c6-8f1b-8ac793451faf.png)

**Comment by hardillb** [comment]
You just can't close those windows.
Closing it kills the launcher (but not the underlying node-red) so the driver starts a new launcher, which can't start a new Node-RED because it's already running).

There is some work to do with getting windows not to start command windows, but it's investment in Windows I'm loathed to make at the moment...

**Comment by Steve-Mcl** [comment]
I understand Ben, but as a user (not as me) testing it I simply did the unexpected (simulated a terminal crash). 

As for the original issue, it is resolved.

**Comment by hardillb** [comment]
OK, closing this issue, but opening a new [issue](https://github.com/flowforge/flowforge/issues/305) one to look at the command windows in the 0.3.0 time frame.
