### ISSUE TITLE
New /application/pipelines view

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2082]
### Story

https://github.com/flowforge/flowforge/issues/2075

### Description

<img width="1379" alt="Screenshot 2023-05-03 at 14 12 40" src="https://user-images.githubusercontent.com/99246719/235926093-48047a00-154c-43a7-84f9-cd43f27f1863.png">

#### Acceptance Criteria
- [x] User can create a new pipeline
- [x] User can add stages to the pipeline
- [x] User can manually kick off a given stage of the pipeline
- [ ] User can remove a stage from a pipeline

**Comment by Pezmc** [comment]
Verified on staging, but given I did most of the wrapping up here, would appreciate a second set of eyes!

**Comment by Steve-Mcl** [comment]
Operationally, the acceptance criteria passes.

Visually, there are some glitches on smaller devices (URLs escape bounding box, horizontal layout not optimal for small screens) and as a wish list item, it would be good to know that the stages "match".  e.g. when pushing a stage, the toast says **"... has started"** but it is impossible to says when it is done (other than implicitly there is no error). This is especially visible when the 2nd stage is suspended:  Also, when simply navigating to the page it is impossible to tell if the stages are actually sync'd.  



https://github.com/flowforge/flowforge/assets/44235289/0babb959-b22f-4779-8f15-ce6e05f524a5

**Comment by joepavitt** [comment]
@Steve-Mcl can you open an issue to capture your feedback here please. All good stuff, just want to make sure it doesn't get lost.
