### ISSUE TITLE
Edit common Node-RED settings

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#209]
### Description

A user familiar with Node-RED will be used to modifying their settings file to customise it in someway, or to enable/disable certain features.

We need to provide a way for users to modify their settings. There will be some settings the user cannot change as they are part of the NR<->FF integration.

From the default settings file, the following settings should be configurable by the Admin in a template #141 and also where permitted by the template policy (#TBC) an owner should be able to modify on a per project basis

 - apiMaxLength - or should this just be hardcoded by us?
 - [x] #210 
 - httpNodeRoot - to be discussed - (depends on #210)
 - [ ] #211
 - [ ] #212 (epic)
 - [ ] #216
 - [x] #213
 - [ ] #214
 - [x] #215

**Comment by sammachin** [comment]
Moved to a story as this is a component of the tempates epic, however it encompasses individual stories for each setting

**Comment by sammachin** [comment]
Closing this and will track individual settings on a per story basis
