### ISSUE TITLE
Action buttons are visible to regular members / non owners (though they all fail to operate)

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#2093]
### Current Behavior

Action buttons are visible to regular members / non owners (though they all fail to operate)

![image](https://user-images.githubusercontent.com/44235289/236275066-7faceae6-9b09-45b5-be57-dbcf96a28bf5.png)

### Expected Behavior

Unsure. The buttons used to be on the settings tab but were moved as they felt like they didnt belong.

I seem to remember a conversation where a new "Actions" tab should be added to contain them?

### Steps To Reproduce

visit the general tab of any instance as a member user

### Environment

- FlowForge version: 1.6.0-git
- Platform/OS: all
- Browser: all

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
Assigned to @joepavitt as requested

**Comment by joepavitt** [comment]
Doesn't appear to be working on Staging
