### ISSUE TITLE
Empty State: DevOps Pipelines

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2097]
For the work being merged in FlowForge 1.7 here: https://github.com/flowforge/flowforge/pull/2094/

Demo for the upcoming feature can be found in the #feature-demos channel on Slack.

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt 
Keeping the dashed lines as what is going to be created, I thought of this.
The square would be the pipeline with existing instances inside, and the flows would be replicas of the first instance in the pipeline...
And the text, just stole a couple of phrases from your video to give it a bit of context. I'm sure you'll have a better idea.

<img width="1515" alt="Screenshot 2023-05-08 at 12 47 27" src="https://user-images.githubusercontent.com/129537638/236805918-dffa86ad-514d-4e93-b0ec-447e23cc377e.png">

**Comment by Yndira-FlowForge** [comment]
don't mind at all!! just retouched it a bit to match the grid I've been using ;)
