### ISSUE TITLE
Allow httpAdminRoot to be changed

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#210]
### Epic

#209

### Description

**As a:** User

**I want to:** Change the path the editor is served from

**So that:** I can use the `/` path to serve application content rather than the editor

**Alternative:** Should we unilaterally move the editor to a fixed path (`/editor`, `/red`, `/admin` ... something else) and *not* allow the user to change it.

**Comment by hardillb** [comment]
Vote for unilateral move, personally I think `/red` is least likely to clash with anything that comes immediately to mind.

**Comment by knolleary** [comment]
`httpAdminRoot` is part of the #141 implementation.

A Template can set a value for `httpAdminRoot` and then optionally allow it to be overridden by individual projects.
