### ISSUE TITLE
Empty State bug: post setup of billing

### ISSUE THREAD

**Issue by Yndira-FlowForge** [flowforge/flowforge#2133]
### Description

**Considerations:**
![image](https://github.com/flowforge/flowforge/assets/129537638/6520bf59-c1ec-4a30-b3a6-2c5a4adf6f20)

**Inspirations:**
[Previous empty states designed](https://github.com/orgs/flowforge/projects/10/views/1?filterQuery=#:~:text=Improve%20Empty%20State%20across%20Platform)

**Comment by ZJvandeWeg** [comment]
@Yndira-FlowForge This is not an art request, there's a bug in the logic that after setting up team billing it doesn't show this:

<img width="1046" alt="Screenshot 2023-05-22 at 08 55 02" src="https://github.com/flowforge/flowforge/assets/2529595/1f412c27-c67d-4e4f-bca1-c24537b6ce8c">

**Comment by joepavitt** [comment]
We still want some confirmation that they've successfully signed up, so have changed behaviour such that a message/alert is shown to confirm, then the Empty State defaults to that requested above.

<img width="1728" alt="Screenshot 2023-07-04 at 12 04 56" src="https://github.com/flowforge/flowforge/assets/99246719/80eae819-54ea-41be-8fd3-24fe303b17ef">

**Comment by Pezmc** [comment]
Verified on staging
