### ISSUE TITLE
Allow user to customise the editor theme

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#214]
### Epic

#209

### Description

**As a:** User

**I want to:** change the theme of my editor

**So that:** I can pick between light/dark modes

---

We should provide a list of predefined themes for them to choose from. An Admin may want a say in what themes are available.

**Comment by sammachin** [comment]
Thanks Nick I'll move this one back into the backlog then

**Comment by Steve-Mcl** [comment]
Following discussion with Sam 2022/08/08...

* interim solution to consider:
  * Provide hard coded drop down selection of `Forge Light`, `Forge Dark`, `Classic`
* long term:
  * A means of enumerating installed theme plugins that populate the theme selection
  * This would permit corporate/reseller to add own theme in stack

**Comment by Steve-Mcl** [comment]
Any thoughts on this for V1 release? or is this still longer term? 

_Shouting up at this point in time only because I spotted this outstanding feature/issue while cleaning up related issues & thought it prudent to ask._

**Comment by sammachin** [comment]
Its still in the Long term backlog, we've had no indication from users that they want to change the theme so until we see some signal its likely to remain low priority

**Comment by ZJvandeWeg** [comment]
Closed by: https://github.com/flowforge/flowforge-nr-launcher/pull/108

**Comment by Steve-Mcl** [comment]
@ZJvandeWeg I would propose we leave this open.

#1816 only permits the choice of our own themes (i.e. it will not be possible at this time to enumerate other installed (contrib) themes) as discussed for longer term capabilities in [this comment](https://github.com/flowforge/flowforge/issues/214#issuecomment-1208237983).

**Comment by knolleary** [comment]
As per above comment - the intent of this story was to support user-installed themes as well. Right now, via #1816 we provide the choice of our own themes. Reopening - and can stay on the long-term backlog.
