### ISSUE TITLE
Allow admin to limit what modules users can install into their projects

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#216]
### Epic

#209

### Description

**As an:** admin

**I want to:** limit what users can install into their projects

**So that:** I can lock down the environment

---

This relates to both the palette and function node external modules - all held under the `externalModules` setting.

That allows the admin to provide allow/deny lists of modules.

**Comment by ZJvandeWeg** [comment]
@knolleary Should and/or can this be tied to the stack? Instead of on the admin level?

**Comment by hardillb** [comment]
@ZJvandeWeg This is a template thing not a stack thing as it's controlled by the Node-RED Settings which are built from the template.

The person creating the stack has full control over what nodes are pre-installed into the stack, but control over what the user can install once the project is started is controlled by `externalModules` block in the settings object.

**Comment by hardillb** [comment]
Are we applying this to both `palette` and `modules`?

**Comment by knolleary** [comment]
With 0.5, the launcher has been updated to set both palette and modules settings based on what the platform provides.

But the UI only exposes palette.allowList. That's okay for a first iteration, but to consider this complete we need to have `modules.allowList`, and both `{palette,modules}.denyList`

**Comment by hardillb** [comment]
We only expose `palette.denyList` not allow at the moment. But adding the rest should be easy
