### ISSUE TITLE
Pipelines: Add message to users explaining delete/re-assign doesn't auto-redeploy

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#2164]
@joepavitt @Yndira-FlowForge This is likely something you'll have good suggestions on how to improve.

Right now, deleting pipelines and pipeline stages is totally naive.

That is to say:
 - When you delete a stage, it vanishes from the pipeline, and pipeline stage before it is mapped to any pipeline stage after it. 
 - When you change the instance assigned to a stage, the assigned instance is swapped

Neither option triggers a redeploy.

We need to communicate this limitation to users clearly.

For reference, this is how the delete and update pages currently look:

<img width="1065" alt="Screenshot 2023-05-22 at 12 59 12" src="https://github.com/flowforge/flowforge/assets/507155/dfdfc57f-07e0-4f58-b56f-84f1e1dd82b2">
<img width="1099" alt="Screenshot 2023-05-22 at 12 58 51" src="https://github.com/flowforge/flowforge/assets/507155/dd80431e-bf2c-4d0d-9f1f-d19b619993bd">

**Comment by joepavitt** [comment]
Having seen Steve run through this yesterday, and having to gone to make these text changes just now - not sure they're needed. The pipeline is always triggered by the "play" icon, so at that point, it would be explicit that it's going from Stage 1 to Stage 3 (now 2) if the old Stage 2 is deleted.

**Comment by Pezmc** [comment]
More than happy to defer to you and @Yndira-FlowForge, please feel free to close out as a #wontfix
