### ISSUE TITLE
Add "Copy" button to Device Config dialog

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#2199]
Task

Add a "Copy" button to copy Device YAML text to clipboard
Same for the provisioning token

Part of flowforge/flowforge-device-agent#76

**Comment by Pezmc** [comment]
@Steve-Mcl Is this something I can help with? Or are you already on it?

**Comment by Steve-Mcl** [comment]
@Pezmc this is still up for grabs. Feel free to jump on it.

**Comment by Steve-Mcl** [comment]
tested on staging for both normal and provisioning dialogs.
