### ISSUE TITLE
Stuck on the form Create a new Application & Instance after using an already known instance name

### ISSUE THREAD

**Issue by flecoufle** [flowforge/flowforge#2221]
### Current Behavior

![image](https://github.com/flowforge/flowforge/assets/47251384/cd3940f1-0af0-4a1c-9a54-0e7b3aafd4ed)

with an already known instance name we can't continue because application name is reset and locked (and is of course mandatory)

### Expected Behavior

If checks failed keep app name entry and leave it unlocked

### Steps To Reproduce

Clic "Create Application" action in "/team/x/applications/create"
Input an App name, instance type and stack
Input by "mistake" an already used instance name
Clic button "Create Application"

### Environment

- FlowForge version: 1.7.2
- Node.js version: (helm chart 1.7.2)
- npm version: (helm chart 1.7.2)
- Platform/OS: x86_64 linux
- Browser: Chrome 114.0.5735.90 (64 bits)

### Have you provided an initial effort estimate for this issue?

I am not a FlowForge team member

**Comment by Steve-Mcl** [comment]
Confirmed in local environment.

Thanks for reporting the issue.

**Comment by Pezmc** [comment]
@Steve-Mcl I'd lean towards #2 but that is going to involve significant refactoring and if I recall correctly there were already plans to change this sign up form to be in two separate stages, so the work would be redundant.

I'd propose a middle ground between 1 and 2 that provides good UX without too much heavy lift:

- Update the form to check if the name is already in use on keyup, making it much less likely to be submitted with a name that's already in use (perhaps disable submit until it completes)
- If the user still ends up with an application and no instance yet, use your 1. suggestion and drop them on the new application with an error toast explaining to try again (or just redirect to the "add instance" to application page).

**Comment by Pezmc** [comment]
I had a feeling that this form used to work just fine if creating an instance failed, after some spelunking I've confirmed there was indeed logic to support that and we've had a regression, proposed fix in https://github.com/flowforge/flowforge/pull/2227
