### ISSUE TITLE
Team Invites for external users

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#2232]
### Current Behavior

If a user invites an external user (someone without an existing FF account) to their team with an sso-enable email domain, when that user registers and logs in, they are not added to the team they were invited to and must be re-invited.

### Expected Behavior

Invitations should be auto-accepted when the new user logs in the first time.

### Steps To Reproduce

1. invite a someone with an sso-enabled email to a team
2. follow link in invite email - create account, login via SSO
3. Observe you haven't been added to the team and are asked to create a team instead

### Environment

- FlowForge version: 1.7

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Pezmc** [comment]
Verified on staging
