### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#224]
### Description

Identify the events needed to trigger billing and the additional data that may need to be stored to integrate with a billing platform such as stripe

**Comment by sammachin** [comment]
https://docs.google.com/document/d/1dmBrv8mrSwbNbveTNNwRZHXrLLsc3NMDovkjb5XpA-Y/edit?usp=sharing

**Comment by knolleary** [comment]
The core functionality and concept has been delivered. No need to keep this epic open.
