### ISSUE TITLE
Request: Migration of Domain

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2240]
### Epic

https://github.com/flowforge/flowforge/issues/324

### Description

As a: FlowForge Customer,

I want to: migrate my FlowForge instance from an old domain to a new domain,

So that: new NR instances will be created with the new domain, while all existing NR instances remain untouched.

### Which customers would this be availble to

Licensed Edition (EE)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
Should this be:

1. a one off "all instances get moved" at start up following the change
2. should existing instances continue to run on the old domain for ever
3. should existing instances be allowed to migrate to the new domain at their choice
4. should existing instances run on both domains

**Comment by MarianRaphael** [comment]
In my opinion:

1. no
2. yes (as an option)
3. yes (as an option)
4. no (not necessary)

**Comment by hardillb** [comment]
OK, so what we currently have means that the following will happen (on docker and k8s)

- The domain is stored in the `etc/flowforge.yml` file
- The instances URL is built at creation time and stored in the project.url field in the database
- on k8s this is used to create the Ingress object which lasts for the life of the instance (even if the instance is suspended)
- on Docker this is generated from the name and the current configured domain and as an env var on the instance container and is recreated every time the instance started.

This means that on docker changing the domain will currently change the configured proxied hostname but not change the URL in the project object (which will cause a problem) on next restart.

Plan for first past:

- Make the driver extract the current domain from the URL (if it exists)
- Reuse that extracted domain over the configured one if present

**Comment by MarianRaphael** [comment]
About Point 6: Would it be possible to use the “Duplicate Instance” functionality to migrate to the new domain? In other words, is our “Duplicate Instance” functionality equivalent to creating a new instance in this scenario? 

My guess would be, yes. This would allow for a very straightforward migration path.

**Comment by hardillb** [comment]
Process to migrate forge app and hosting domain:

1. register new domain
2. set up DNS entries for
    1. forge app
    2. wildcard domain
3. Leave the existing entries for the old domain in place
4. Stop the forge app
5. edit the flowforge.yml to set the `base_url` and `domain` entries

Existing instances will continue to run on the old domain and make use of API on the hold forge app hostname.
New instances will use the new domain and access forge API on the new hostname.

The old domain/forge app hostname must remain available until all old instances are running.

**Comment by MarianRaphael** [comment]
I would suggest documenting this approach in our docs.

**Comment by hardillb** [comment]
Docs done
