### ISSUE TITLE
Project Environment Variables

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#225]
### Description

**As a:** User

**I want to:** set environment variables for a project

**So that:** I can deploy a common set of flows to different projects, but use env vars to customise each instance

---

Need to consider how env vars are stored - particularly ones that could hold credentials.

**Comment by sammachin** [comment]
Environment variables should be part of the template, and then editable on a per project level

**Comment by knolleary** [comment]
## UI Appearance

This is the rough UI I put together a few months ago when I was experimenting with various things.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/51083/159508653-fc0f245b-932d-4c11-a365-e835e432167d.png">


The table is a list of env var name/value pairs. The user can edit any of the names/values of normal env vars. If the user ticks 'encrypt' then the value is encrypted and not visible to the UI anymore - nor can the name be changed. In this instance, the user can only delete the entry and re-add it.

There will be a 'Save settings' button at the bottom to apply the changes - consistent with the other settings tabs.

## Storing env var values

The current Template/Project Settings model works like this:
 - A `ProjectTemplate` stores the template values in a text field called `settings` as a JSON blob
 - A Project has a `ProjectSettings` object with a key name of `settings` and a text value that is a JSON blob
 
The true value of a particular project setting is taken from the `ProjectSettings` object, falling back to the `ProjectTemplate` if the project hasn't overridden the value.

The simple approach here will be to add `env` to the JSON blob in both places - as we would any other project setting that can be provided by a template.

<details><summary>Side note on thread safety of this blob approach - expand me for details</summary>possibly not an immediate concern, but having just thought of it, I want to write it down. Having a single field in the database as a JSON blob may be fine when a requests to update it happen one at a time. But there will be a race condition if two users edit the project settings at the same time - even if they are editing *different* values in settings. If they save their changes at the same time, there is a real risk of one user's changes overwriting the other user's.</details>

### Encryption of secrets

Given env vars will often be used to provide credentials, it is important we have a sensible strategy for storing their values.

They key requirement is that once a credential type env var has been set, the only thing that should be able to read its true value is the `nr-launcher`. The question is how to best to achieve that.

One approach would be to delegate storage of credentials to the container driver layer. K8S could plug that into K8S Secrets (and rely on whatever administrative level encryption has been setup). The downside is we would still have to implement something sensible for localfs and docker (unless there's a standard dockerised Secrets manager we could plug in).

The alternative is we encrypt ourselves. The question is what to use as the key - as the launcher would need to be given the key to decrypt things... and if we have the key lying around to give to the launcher when it is started, then we have the decryption keys sat next to the encrypted data. We have the added complication that if a Template provides an encrypted env-var, it has to be decrypted using a *different* key to any project-defined env-var. That would suggest the launcher has to have the decryption keys for both things - unless the runtime re-encrypts the template secrets using the project key before delivering them to the launcher.

We could follow the approach taken by K8S Secrets - not encrypt by default and rely on admin provided keys to enable encryption. That also has to support key rotation.

Conclusion: **I propose this is deferred to a later iteration.** As long as we tighten the security around the `<project>/settings` endpoint to ensure only projects are able to access it - and not user-based sessions.

**Comment by knolleary** [comment]
## Apply template policy to env vars

The current strategy for Templates is that a Project can override any of the settings - and that the template can set a policy against each setting as to whether the Project can override or not.

We need to decide what level of granularity is needed with env vars.

The most coarse grained is:
> A Template can set a policy that prevents a project from setting or modifying any env vars.

I'm not sure what problem this would solve - I cannot think of a reasonable use case for not allowing a project to even set its own env vars. **I do not believe we should implement a policy at this level**. We can introduce one in the future if there is a requirement for it.

I think it is a far more reasonable approach to say:

> A Template can predefine env vars and set a policy for each individual env var to say if it can be modified/removed by a Project.

That allows a template to provide a set of 'required' env vars that a Project shouldn't be allowed to mess with.

## Merging Template/Project level settings

Currently we can use a hardcoded list of valid settings to pull project settings to override template settings.
In the case of env vars, we need to *merge* the env vars provided by the template and those provided by the project.

**Comment by sammachin** [comment]
Leaving this in Review as it needs adding to docs, I can do that early next week based on the text above
