### ISSUE TITLE
The link to 'High Availability preview feature' doesn't link anywhere

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#2258]
### Current Behavior

Click the link in the text on the HA setting page doesn't do anything.

### Expected Behavior

It should take me to the docs.

### Steps To Reproduce

Go to the settings page of an instance, select High Availability, click 'High Availability preview feature'.

Video https://d.pr/i/q3tKC3

### Environment

- FlowForge version: 1.8 staging
- Node.js version: staging
- npm version: staging
- Platform/OS: Mac current
- Browser: Chrome current

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
This is because the page will be published as part of the release.
