### ISSUE TITLE
Support Single Sign On

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#226]
### Description

We need to support external authentication systems for the core platform.

This will allow easier integration with existing systems, rather than having to create users manually.

Node-RED supports arbitrary SSO options via the use of pluggable PassportJS. We need to consider if that is the right approach, or do we want to be a bit more curated in what we support.

We have already had a query about Active Directory support.

SSO solves authentication, but we also need to consider how this relates to authorisation. For example, should Team membership be controllable via an external source of truth (LDAP etc).

---

#### Platform Configuration

 - An Administrator will be able to associate a particular email domain with an SSO SAML configuration
    - Need to scope whether this is done via Admin Settings in UI, or via yml config files.
       - For self-hosted, there is likely to only be a single SSO config that doesn't change - so can be done via yml
       - For FF Cloud, if done via yml, will require restart of the platform to pickup any changes... not ideal
 - **Future** 
    - An Administrator can disable user/password login entirely - requiring all users to login via SAML. Although need to consider the potential impact of locking Admins out if the SSO service is unavailable.

#### User login

 - Any user trying to login with a registered email domain will be redirected via SSO - even if they had a previously created an account with password
    - Should we allow Admins to still login via password as a safety net? If the SSO service goes down, we don't want them unable to login to fix things. Alternative here is a warning to ensure Admins use a different email domain that isn't covered by SSO... but that may not satisfy security requirements.
 - A SSO User will *not* be able to change their email address - as that is their primary identity

#### Adding Users

 - For self-hosted instances, an Admin will be able to manually add users to the platform, rather than auto-creating accounts when a user tries to login the first time.
 - For FF Cloud, given customers will need to contact us (as the admins) to setup the SSO configuration for them, we could also take on the task to create users from a list they provide. It's manual work, but keeps the scope of 1.2 manageable. This will be something to keep under review through 1.2 to see if we can do something better.

 - **Future**
    - If enabled for the SSO configuration, auto-create a user when they login for the first time via SSO.

----

### UX

Two options for how to expose SSO in the log-in dialog:

- **Option 1** - Add prompt to log-in dialog to use SSO instead (this is what Figma does)
  - Pro: for a mixed platform, doesn't add friction for non-sso users
  - Pro: its the pattern Figma uses, so not completely unreasonable
  - Con: Does a user know if they need to use SSO?

![Image](https://user-images.githubusercontent.com/51083/204833056-60e52990-e58e-409f-b846-9ac59c2049c5.png)

- **Option 2** - Initial login is just Username/Email. If it is SSO enabled, redirect, otherwise prompt for password
 - Pro: removes choice from the user - they are hand-held more through the process
 - Con: adds friction (more clicks) for the non-SSO user

![Image](https://user-images.githubusercontent.com/51083/204832959-010ef683-0665-40a9-b061-27c159bac799.png)

---

- [ ] https://github.com/flowforge/flowforge/pull/1349

**Comment by sammachin** [comment]
Some initial thoughts https://www.figma.com/file/PE8MshC8ZRy1aqxDCbKW7A/SSO

**Comment by joepavitt** [comment]
Design/Dev work to begin in Iteration 1.1. Milestone to be set once scope is better understood.

**Comment by knolleary** [comment]
I've updated the description to describe the scope for work for 1.2. This includes a couple options around the login UX for feedback /cc @joepavitt

**Comment by joepavitt** [comment]
If, for non-SSO users in option 2, we can have it autofill the username/email with what they've already typed and auto-focus the password field, then in theory, this isn't any more/less clicks than the existing workflow?

**Comment by hardillb** [comment]
We don't need to show the username again for the second step, we could just prompt for the password (This is what e.g. Docker Hub does)

**Comment by knolleary** [comment]
The core support for SSO has been delivered in 1.2. We will have follow up work to enable it for specific Identity Providers that require more options to be set than we currently expose.

 - #1447 

There will also be stories to be defined around User Provisioning - as currently a user must exist on the FF platform before they can sign-in.
