### ISSUE TITLE
HA: Support querying individual replica logs in logging API

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#2260]
The initial implementation of HA with #2156 treats the replicas as a single blob. We return aggregated logs across all replicas. This will make it harder to examine issues in individual replicas.

Users need a way to view the logs of individual replicas.

**Comment by hardillb** [comment]
First pass idea is to see if we can tag each log entry with details of which instance it came from.

**Comment by hardillb** [comment]
delivered by https://github.com/flowforge/flowforge/pull/2367 and https://github.com/flowforge/flowforge-nr-launcher/pull/133

**Comment by hardillb** [comment]
Verified on staging
