### ISSUE TITLE
Instance names in delete popup not easily selectable

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#2267]
### Current Behavior

double clicking on the instance name used to select just the name, this made copy/paste to the Name box a lot quicker/easier when deleting instances.

I'm sure this component is probably reused for deleting other things that require confirmation.

![Screenshot from 2023-06-09 14-55-02](https://github.com/flowforge/flowforge/assets/1800845/8e3522da-777c-4002-9ed0-5ece9faa120a)

Looks like the `<code>` tag used to have the `class='block'`

### Expected Behavior

Double click on the name selects just the name, not the whole line.

### Steps To Reproduce

Try to delete and instance
double click on the instance name &lt;code&gt; section

### Environment

- FlowForge version: 1.8.0
- Node.js version:  16.x
- npm version: 8.x
- Platform/OS: NA
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sumitshinde-84** [comment]
I would like to work on this issue @hardillb , can you please assign it to me ?

**Comment by sumitshinde-84** [comment]
Hello @hardillb,

I hope you're doing well. I wanted to seek your assistance regarding an issue I'm facing while setting up Flowforge in my development environment using flowforge-dev-env.

I encountered the following error message during the Flowforge setup process:

```"ERROR: Failed to create default ProjectStack: SequelizeUniqueConstraintError: Validation error."```

I would greatly appreciate it if you could guide me through the steps to complete the Flowforge setup successfully.

Thank you in advance for your help!
![flowforge](https://github.com/flowforge/flowforge/assets/110285294/6395ee79-2b5e-49ac-9938-be14112fac83)

**Comment by hardillb** [comment]
Most likely cause is that you have not installed a stack.

- What do you have in `flowforge-dev-env/packages/flowforge/var/stacks`?
- What was in the FlowForge logs?

Did you follow the instructions here: https://flowforge.com/docs/contribute/#development-setup

I suggest you stop the flowforge, delete `var/forge.db`, from inside the `packages/flowforge` directory run:

```
npm run install-stack --vers=3.0.2
```

Then restart flowforge with `npm run serve` and start the setup wizard again.

**Comment by sumitshinde-84** [comment]
Thank you, @hardillb, for your invaluable guidance. I truly appreciate it

**Comment by sumitshinde-84** [comment]
hii @hardillb , I made some changes to the code, but I noticed that the changes are not appearing on the local server. Could you please assist me in identifying the problem?

**Comment by sumitshinde-84** [comment]
yes  i am using  ```npm run serve``` but still my changes appearing on the local server.

**Comment by hardillb** [comment]
Then without details of which file you are changing I can't say.

Check the build output for errors

**Comment by sumitshinde-84** [comment]
i am trying to make changes in this file  ```frontend/src/pages/application/Settings/dialogs/ConfirmApplicationDeleteDialog.vue``` , and there is no error in build log .

**Comment by sumitshinde-84** [comment]
hey @hardillb ,  i have resolved issue but now i wanted push changes how i can do that because i have  used ```flowforge-dev-env``` to setup local enviroment
