### ISSUE TITLE
Allow Device Agents to Inherit Environment Variables from Instance

### ISSUE THREAD

**Issue by sharpernb** [flowforge/flowforge#2269]
### Description

Would define Parent/Master > Child/Replica relationships at the Child Level.
In addition, the inheritance would allow for manually configured Environment variables to propagate in the event of NR flow dependencies.

### Have you provided an initial effort estimate for this issue?

I am not a FlowForge team member

**Comment by knolleary** [comment]
Hi @sharpernb 

When you create a snapshot of an instance it does already include all of the environment variables set on that instance. So when that snapshot is deployed to a device, the device will have those env vars available to it.

Does that satisfy your request or have I misunderstood some aspect of it?

**Comment by sharpernb** [comment]
Yessir, It should do the trick! Thank you!
