### ISSUE TITLE
User directed to /settings/billing after creating first Application

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2285]
### Current Behavior

When new users sign up to FlowForge Cloud, they are guided to create their first Application & Instance. After this, they are directed to the billing page, which detracts from their onboarding experience.

### Expected Behavior

Users should be directed to their newly created Instance, not the Billing page.

### Steps To Reproduce

- Sign up to FlowForge trial
- Create first Application & Instance
- Note you're re-directed to /billing page

### Environment

- FlowForge version: 1.8.0

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sumitshinde-84** [comment]
@joepavitt I would like to work on this issue , please assign it to me .

**Comment by joepavitt** [comment]
You're welcome to dig into it @sumitshinde-84 - it's likely to be more complex in terms of initial setup of FlowForge for the first time, etc. but please keep us updated on any progress you make with it.

**Comment by sumitshinde-84** [comment]
@joepavitt I am delighted to inform you that I have successfully familiarized myself with the setup process for FlowForge. Having previously worked on other issues within FlowForge, I have gained valuable experience and knowledge that greatly assisted me in understanding the setup procedure. If I encounter any issues during the setup process, I will reach out to you for assistance.

**Comment by sumitshinde-84** [comment]
@joepavitt how i can enable free trial on local enviroment instead of membership, because i think in developement process  we have enabled membership.

**Comment by joepavitt** [comment]
We have instructions [here](https://flowforge.com/docs/contribute/#configuring-billing) on setting that up, although our Stripe API keys are all secrets stored in 1Password. Not sure how best to go about that, @knolleary any thoughts? Is it easy enough to setup their own keys? Guessing it's more complicated as also need to match Stripe `product` keys, etc?

@sumitshinde-84 you'll see the setting in there `billing.stripe.new_customer_free_credit` which you can just set to match the cost of a `project_price`

**Comment by sumitshinde-84** [comment]
i think expected solution will be this by changing ```this.team.projectCount >0 ``` to 1
 ``` 
 if (this.team.billing?.active ?? true) {
            return
        }

        // Redirect to billing if:
        //   - team has cancelled their subscription
        //   - team is not a trial team, or:
        //   - team is a trial team and:
        //     - has expired, or:
        //     - already has a instance created
        if (this.team.billing?.canceled ||
            !this.team.billing?.trial ||
            (this.team.billing?.trialEnded || this.team.projectCount > 1)  <------------------- changing 0 to 1 
        ) {
            this.$router.push({
                path: `/team/${this.team.slug}/billing`
            })
        }
    }
```  

what do you think @joepavitt @hardillb

**Comment by joepavitt** [comment]
At that point in the sign up workflow, I would expect `projectCount` to be 1 - for context `project` is the old name for what we now call an `instance`, just hadn't got round to updating a lot of server-side code to reflect that change.

I think that statement is a catch all to make sure, whilst on trial, a user hasn't somehow setup 2 x Instances (which is forbidden on trial, without billing details).

So either, `projectCount` is more than 1 (incorrectly), or there is logic elsewhere triggering the redirect

**Comment by sumitshinde-84** [comment]
hiii @joepavitt  i have connected through stripe cli and i have also changed     ```biiling.stripe.new_customer_free_credit: 0.50```
and added product in stripe with same price but free trial not enabled .

**Comment by joepavitt** [comment]
@Pezmc what have I missed here?

**Comment by knolleary** [comment]
@sumitshinde-84 have you enabled trial mode via admin settings:

<img width="521" alt="image" src="https://github.com/flowforge/flowforge/assets/51083/377959cb-e991-406c-95a1-6167185138fb">

**Comment by joepavitt** [comment]
Just added https://github.com/flowforge/flowforge/issues/2304 as that's a missing instruction from our docs currently

**Comment by sumitshinde-84** [comment]
No I haven't enabled trial mode via admin , thanks you so much @knolleary for your Precius guidance.

**Comment by sumitshinde-84** [comment]
hii @knolleary  @joepavitt , i am trying to configure email but getting this error ```[2023-06-16T13:21:12.634Z] INFO: Email not configured
[2023-06-16T13:21:12.635Z] WARN: [comms] Broker not configured - comms unavailable```  
can you please tell me what mistake i have did 

``` email:
  enabled: true
  debug: true
  smtp:
    host: localhost
    port: 465
    secure: true
    auth:
        user: project.1
        pass: secret.1
```
![WhatsApp Image 2023-06-16 at 6 58 25 PM](https://github.com/flowforge/flowforge/assets/110285294/dd694428-7953-482b-9c6f-ea498957a895)

**Comment by hardillb** [comment]
@sumitshinde-84 you do not need broker comms enabling for this issue. Ignore that warning (also this is to do with using a MQTT broker, not email)

**Comment by joepavitt** [comment]
So this occurs because the `beforeMount` in `InstanceForm.vue` is triggered on submission of the `createApplication` form. 

The `InstanceForm` has a sanity check for users on trial, that they're not trying to create an instance if they're already got on (trial users only allowed one instance). The problem is, because this `beforeMount` is (for some yet undetermined reason) running on submission, just after the new instance has been created, this logic thinks they're trying to add a second Instance, when in fact they just created one.

**Comment by joepavitt** [comment]
The state to render `InstanceForm` in `createApplication` is defined by `loading`. `loading` is set as `true` when submitting the form. So there is a very very minor time period, where loading is set back to `false`, but the view hasn't quite yet directed to the newly create Application, within which the `beforeMount` runs.

The solution, I _think_, is to move the `beforeMount` into a `beforeRouteEnter` - going to try now

**Comment by joepavitt** [comment]
> move the beforeMount into a beforeRouteEnter

Doesn't work because the component isn't at the route level, more exploration required

**Comment by Pezmc** [comment]
@joepavitt I'm available this morning to duck if you want to walk through this together
