### ISSUE TITLE
New 'empty state' image for when a dashboard-only user attempts to access the team

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#2293]
### Related Issue

#1924

### Description

**Considerations:**

https://github.com/flowforge/flowforge/pull/2292 adds a new role to the platform where a user can access HTTP endpoints created by Node-RED, but cannot access the team info in the platform.

When they try to access the team, as per the #2292 they are presented with an empty state layout telling them they don't have access. In that PR, I've reused the empty library image - but it could/should have its own image:

<img width="1183" alt="image" src="https://github.com/flowforge/flowforge/assets/51083/78160a9b-5a0f-4adb-8734-a742dfec2338">

**Comment by Yndira-FlowForge** [comment]
Hi @knolleary 
I think this could work
<img width="1515" alt="Screenshot 2023-06-19 at 11 52 03" src="https://github.com/flowforge/flowforge/assets/129537638/4d88f3c7-fb00-466e-86cc-1cbf1c01ea8b">

The png is in our [drive folder](https://drive.google.com/open?id=1Gyp8CZciFwYwUUqtHGwBUF4TN1zhDYkF&usp=drive_fs)
