### ISSUE TITLE
Pipelines: The Instance URL is too large

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2297]
### Current Behavior

<img width="1119" alt="Screenshot 2023-06-16 at 11 03 49" src="https://github.com/flowforge/flowforge/assets/73583313/1f571dba-1a40-43b2-a191-4d69e91c5c35">

### Expected Behavior

The URL should fit into the visualization.

### Steps To Reproduce

Create a Pipeline with a long URL

### Environment

- FlowForge version: 1.8
- Platform/OS: FF Cloud
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
I believe there is already an issue around this Marian.

👀 

Ah, here:  https://github.com/flowforge/flowforge/issues/2247

**Comment by MarianRaphael** [comment]
Thanks for the hint! I'll close this issue
