### ISSUE TITLE
UI: Disable delete button if it won't work

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#2300]
### Description

When deleting an application the delete button is red while it won't work if there's instances in the application:

![Screenshot 2023-06-16 at 11 38 16](https://github.com/flowforge/flowforge/assets/2529595/fbb1feeb-a954-4a24-9aff-ece9bb863792)

Fix: Disable the button if it won't work. Or alternatively; just remove all resources

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sumitshinde-84** [comment]
@ZJvandeWeg  when we try to delete Application when application contain instances we will get notified ```Application failed to delete: Please delete the instances within the application first``` , so according to me its not bug .

**Comment by sumitshinde-84** [comment]
@ZJvandeWeg If you have already discussed the matter and ultimately decided to remove it, I would be interested in taking up the task and working on it.

**Comment by joepavitt** [comment]
> so according to me its not bug .

Agree that technically it's not a bug, although it is a UX frustration we could address and saves the user a click to understand a block in their flow. Having the button disabled, with a note in italics and red underneath to say _why_ it is disabled would be appropriate here.
