### ISSUE TITLE
Application audit log not created for new instances

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#2301]
### Description

When someone creates a new instance, it should generate an entry in the audit log

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sumitshinde-84** [comment]
@ZJvandeWeg  I think this issue is already resolved , right ?

**Comment by MarianRaphael** [comment]
![Screenshot 2023-07-07 at 11 54 24](https://github.com/flowforge/flowforge/assets/73583313/b63059a6-a737-40d2-b735-82ea71f18cc5)
