### ISSUE TITLE
Allow a user to put their project into Safe Mode

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#232]
### Description

**As a:** user

**I want to:** restart my project in safe mode

**So that:** I can edit the flows without them running.

---

**Prereq task:** #392 

'Safe Mode' allows Node-RED to run without running the current flow configuration. The user can access the editor, make changes and then deploy them to exit safe mode.

This is used when the flows are broken in someway that kills the runtime - the user can restart in safe model to fix things. We already have logic in the launch that puts NR into safe mode if it restarts 5 times in quick succession - but allowing the user to do it manually is a useful feature.

It will also drive requirements/discussion in the core of NR around extending safe-model to longer-held state of the runtime (that isn't reset when deploying a change).

**Comment by Steve-Mcl** [comment]
@knolleary 

With the PR for persistent stop mode (allow node-red to be stopped/started) do you think this feature satisfies this requirement?

**Comment by knolleary** [comment]
Being able to stop the flows in NR but still edit them is the prerequisite capability we need before we can expose this feature in FF.

This feature will *only* be available if the stack is running Node-RED 3.0.

We still need to understand how this ability is exposed in the FF API and UI. We already have 'start' and 'stop' actions (which start/stop Node-RED currently). We need to rationalise these actions. Please can you work up a proposal? Until we have that we don't know what changes are needed in the api and UI.

**Comment by sammachin** [comment]
Moving this back to Design,

**Comment by sammachin** [comment]
@knolleary is there still value in this now that we have start/stop flows?

The current way we use safe mode in terms of automatically putting a project into it on multiple crashes has value but I think adding a user option to control it as well as stopping flows would be confusing.

propose to close this issue and focus on the start/stop experience

**Comment by knolleary** [comment]
I agree. Much less value in putting into manual safe mode with the ability to stop/start the flows.
