### ISSUE TITLE
Cross-Instance Snapshot Management

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2335]
### Description

Introduce a mechanism to manage and control snapshots at an application level. This feature not only allows the visibility of each snapshot across all application instances, but also permits the assignment of each snapshot to any instance or device within an application.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
> permits the assignment of each snapshot to any instance or device

Can I just sanity check what you're meaning here. To move a snapshot from one Instance to another, we'd be using Pipelines. We'd discussed the point that Pipelines should auto-capture a snapshot when a promotion of a stage occurs (to backup existing target stage work before the push, and to capture a snapshot of the flows pushed). Not sure a single "Snapshots" view at the Application level helps here though. Feels like it it could get quite messy?

**Comment by MarianRaphael** [comment]
Indeed, I see where you're coming from. Let me clarify what I had in mind. My initial thought was based on the fact that presently, the only mechanism for updating Devices is through the use of snapshots. In this context, when Devices are managed separately from an Instance at an Application level, snapshots must be accessible from that level.

However, we're now moving toward a model where Devices can be assigned to Pipelines, and Pipelines will essentially serve as the medium for updates. As a result, the "Cross-Instance Snapshot Management" becomes optional.

**Comment by joepavitt** [comment]
yep - I think the point that needs to be captured (if not already) is that we can have multiple entities (most likely devices) bound to a single stage of a pipeline - then that would in theory, mimic the Snapshot workflow.

**Comment by knolleary** [comment]
Another point to clarify, the 'Device in pipeline' work about to be completed makes use of the devices being assigned to an instance. The new work allows you to set the target snapshot on the instance when it is deployed to. This will in turn update the assigned devices.

We have not enabled devices to be a direct target in the pipeline stage.
