### ISSUE TITLE
Device Groups

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2340]
### Epic

https://github.com/flowforge/flowforge/issues/1509

### Description

As a FlowForge user, who manages a large number of devices, I want to have the ability to create "Device Groups" and assign "Target Snapshots" to these groups so that I can manage my devices more efficiently.

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

- [ ] option to create a new "Device Group"
- [ ] see the list of devices assigned to the group and have the ability to add or remove devices
- [ ] Possibility to assign target snapshots to the group
- [ ] can be assigned to an application

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Do we expect that a Device can belong to multiple groups?

**Comment by MarianRaphael** [comment]
No

**Comment by MarianRaphael** [comment]
Precision about: Possibility to assign target snapshots to the group

Device Groups have a list of snapshots, (same concept as for instances), which come from Snapshots created from devices within the group. Devices cannot be part of multiple Device Groups and can only be part of either an Instance or a Group.

**Comment by knolleary** [comment]
> Device Groups have a list of snapshots, (same concept as for instances), which come from Snapshots created from devices within the group. Devices cannot be part of multiple Device Groups and can only be part of either an Instance or a Group.

This is not what the original epic describes. Based on reading the description of the Epic and this Issue, I believed this was about better organising devices within an Instance - so you can selectively roll-out a snapshot to some of your devices in a more managed way.

If this is actually about having a way for a device to not be assigned to an instance, but still manage snapshots etc, then that is a very different piece of work and it would help if the descriptions were updated to make it clear.

We need a more complete UX design for this to understand what is required - the screenshot above doesn't give us much to go on. Where do Device Groups sit in the navigation? Are they owned by an Application? Are they owned at the Team level? What are the relationships between Applications, Instances, Devices and Groups?

I have a very long list of questions to understand the requirements of this - but I think it would be easier for us to get together and discuss the high-level concept/design to make sure we are aligned.

**Comment by knolleary** [comment]
I have increased the sizing to XXL - this is going to require quite a lot of work to fit into our model, including the updates needed in the Device Agent itself to support not being assigned to an Instance but still having a snapshot to run.

**Comment by Steve-Mcl** [comment]
> > We may wish to consider TAGGING
> 
> Wouldn't multiple devices with the same tag be a group?

Yes, but with more flexibility.  I see limited (or difficulty) scalability in the concept of a group table whereas tags (with appropriate properties) could be used for more than just "a collection of devices".  I see tags as a way of future implementing new related features with little to zero DB changes if engineered correctly (as opposed to constantly adding and updating tables and columns to fit the current iterations` needs.)

Lets discuss tomorrow :)

**Comment by joepavitt** [comment]
> If this is actually about having a way for a device to not be assigned to an instance, but still manage snapshots etc, then that is a very different piece of work and it would help if the descriptions were updated to make it clear.

I think what is happening here is that this issue has been scoped in the assumption that https://github.com/flowforge/flowforge/issues/2334 will be done alongside it, but they are in fact two separate pieces of work, that _could_ be done apart from each other

**Comment by MarianRaphael** [comment]
See also https://github.com/flowforge/flowforge/issues/2655

**Comment by MarianRaphael** [comment]
Replaced by https://github.com/flowforge/flowforge/issues/2655
