### ISSUE TITLE
Add Create Account to the sign in page.

### ISSUE THREAD

**Issue by iskerrett** [flowforge/flowforge#2350]
### Description

The Sign In button is the #1 click item on our home page.  Therefore, it would be nice to have a 'Create Account' url for those that visit the sign up page but don't have an account.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
@iskerrett `https://app.flowforge.com/account/create` is the url of the sign-up page.

**Comment by sumitshinde-84** [comment]
@knolleary  I think we should add register or sign-up link at login form same as we have added at sign-up form .

**Comment by sumitshinde-84** [comment]
@knolleary i would like to work on this issue , can I ?

**Comment by knolleary** [comment]
There is nothing to be done in the platform. The create account page is already available on a well define URL.

The only task will be to update the website to add a create account link in the desired places. That's for @iskerrett to define where and how it should appear.

I don't think there are any further actions for us to take in this repo.

**Comment by MarianRaphael** [comment]
I would close this issue here, nothing to add, see comment from @knolleary
