### ISSUE TITLE
Migration of Teams to Starter or Premium Tier Based on Current Consumption

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2360]
### Description

Due to transitioning from a purely instance-based payment model to an optional pre-paid package model (starter package). We are introducing two tiers, Starter and Premium. Teams will need to be migrated to these new tiers based on their current consumption.

See therefore also [google sheet](https://docs.google.com/spreadsheets/d/1X-S5QkoCT8nxYicLVIgg6okRB5ERjfUUPjplzoW4GkU/edit?usp=sharing)

### Epic/Story

https://github.com/flowforge/flowforge/issues/2328

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Following on from https://github.com/flowforge/flowforge/issues/2328#issuecomment-1624430958, we need to work out how this migration actually happens at a technical level. It will be hard to get very specific until we have a firmer implementation of the TeamTiers I describe in the linked comment.

But the key point is, the migration isn't something we can hard code into the FF platform - it has to be an administrative task done after the FF Cloud-specific TeamTiers have been created as the business logic is specific to FF Cloud.

1. We upgrade FF Cloud to 1.10 and now have the admin tools to create the new TeamTiers
2. Admin creates the two new Tiers and marks the existing Tier as 'inactive' so it can't be 'upgraded' to
3. We then have over a *lot* of teams to migrate - all that have existing Stripe subscriptions (or not if they didn't activate post-trial). It doesn't feel practical to do this manually.

We need to consider a number of scenarios:

1. A user who never setup stripe billing and the trial has expired (or they joined before trials existed). They are inactive - we can update to the new Starter, but without billing setup.
2. A user who has setup billing, but is currently inactive. They pay $0/month. If we upgrade them to the new Starter, they will get an unexpected $15/month charge. We cannot do that without a notice period warning them of the change in the charges and a way for them to cancel.

In fact, *any* changes to our pricing really needs to be clearly communicated with our customers - emails etc - with plenty of notice before changes are applied. Trying to coordinate that in parallel to the work to implement all of the TeamTiers is going to be difficult.

I propose we focus on implementing the new TeamTier structure, introduce it for new customers, but keep existing customers on the existing tier/pricing. They will get the option in the app to 'upgrade' to one of the new plans - no reason to prevent them opting-in. We can then do a more managed (and well communicated) migration of users off the existing tier when we have something more concrete to communicate with them.
