### ISSUE TITLE
"What brings you to FlowForge?" question at sign-up

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2362]
### Description

**As a:** FlowForge Admin

**I want to:** better understand why a user has joined FlowForge

**So that:** we can better segment users and enhance our understanding of what features are being used, better understanding of churn and most importantly understanding what the user expectations would likely be.

### Which customers would this be availble to

None

### Acceptance Criteria

- [ ] On sign-up to FlowForge Cloud users will be asked "What brings you to FlowForge"
    - Learning Node-RED
    - Personal Use
    - Business Operations? (need a better term here?) for work? 
- [ ] Is this data stored in the `User` table or elsewhere? Posthog maybe?
    - Either way, we should definitely include it in _at least_ Posthog, as analytics are useful there.
- [ ] How is this configurable for OS versions

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sumitshinde-84** [comment]
I am  interested to work on this issue,  can you please assign it to me.

**Comment by joepavitt** [comment]
Thanks for your interest @sumitshinde-84 think I'm going to be taking this one myself as a few design challenges (architecturally and UX) to tackle with it.
