### ISSUE TITLE
I can't promote a NR instance through the DevOps Pipeline

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#2363]
### Current Behavior

When I try to promote the content of an instance to the next stage of the DevOps pipeline I get an error 'Request Failed: Not Found'.

I wondered if the issue was that the stack I was promoting to was older than the source but I am still getting the same error after getting them both on the same stack.

### Expected Behavior

I should be able to promote the instance onto the next stage.

### Steps To Reproduce

I took a pre-existing instance, added it to the first stage of a DevOps pipeline.

Created a new instance, added it to the second stage of the pipeline.

Tried to promote from one to the next.

This video shows the exact steps. https://d.pr/v/iz8WrQ

### Environment

- FlowForge version: 1.8
- Node.js version: 16.20.0
- npm version: Current
- Platform/OS: Mac current
- Browser: Chrome current

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by robmarcer** [comment]
This bug was also reported by a FF user on 1st July via the FF live chat tool.

**Comment by robmarcer** [comment]
@knolleary in the 'FlowForge Team' on FF Cloud, application 'Customer Success', DevOps pipeline 'CS'.

I am trying to move production (main) to dev (dev) first so I can then reverse the pipeline and work on dev going forward. Each time I try to promote I get the error.

Source instance - https://d.pr/i/rcy2wo
Target instance - https://d.pr/i/h5Gi6c

Let me know if you need any more details.

**Comment by robmarcer** [comment]
This is becoming a blocker for me, I can't get it to work at all (I've tried on three different teams). If anyone has any work-arounds that would be really appreciated as I can't demo the pipeline to customers / sales. @MarianRaphael @knolleary

**Comment by knolleary** [comment]
Clicking the promote button on the stage generates this error on the browser console:
```
GET https://app.flowforge.com/api/v1/pipelines/rLV3DM0Jm4/stages/undefined 404
```

That `undefined` looks very wrong...

**Comment by MarianRaphael** [comment]
I am having the same problems with these two instances. It's also weird that they switch positions in the pipeline.
https://github.com/flowforge/flowforge/assets/73583313/0b539cf3-c8c2-4e5d-86a9-71c2adf9c9dd

**Comment by knolleary** [comment]
The issue is related to the fact the pipeline UI is presenting the stages in the wrong order. The second stage is being displayed as the first stage in the pipeline. So when you click the 'promote' button, it is trying to promote the second stage to its target - but it doesn't have one.

What I do not currently know is *why* it is presenting them the wrong way around. My local environment, running the 1.8 code, does not do this (and clearly, wouldn't have passed any of the testing we did if this was systemic).

**Comment by knolleary** [comment]
I can see the UI is presenting the stages in the order they are provided by the API response. For some reason, they are out of order for this particular application. But not for others.

The UI ought to be able to validate the order, as each stage should have a 'NextStageId' property (except for the final stage in the pipeline). Equally, the API ought to be providing them in the right order.

**Comment by knolleary** [comment]
Issue closed as the fix has been merged to `main`. We will get this rolled out to production today - I will confirm back here when that is done.

**Comment by knolleary** [comment]
@robmarcer the fix is now in production. I have had a quick look and I can see your pipeline has its stages in the right order now. I have not clicked the 'promote' button in your instance, but please do so and confirm its working for you.

**Comment by robmarcer** [comment]
Thanks @knolleary @Pezmc @MarianRaphael, it's working correct for me now. I'll let the customer know.
