### ISSUE TITLE
Allow anonymous access to project

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#238]
### Description

**As a:** Team Owner

**I want to:** make a project publicly accessible to anonymous users

**So that:** non-platform users can view my flows when I share them

---

This will need to be an administratively enabled feature - and disabled by default.

**Comment by knolleary** [comment]
To distinguish this from #657 - this story would allow a user to share the Node-RED editor url with anyone. They can access the editor, in read-only mode. They cannot access the FlowForge UI for the project.

**Comment by sammachin** [comment]
duplicated in #857
