### ISSUE TITLE
Project flips from IP address to localhost and breaks

### ISSUE THREAD

**Issue by vtgav** [flowforge/flowforge#240]
### Current Behavior

I installed flowforge successfully on a raspi, and accessed it from my laptop. The URL was the raspi IP address and the assigned port (7880). The screen initially showed the node-red login screen. When I click login the page changes to localhost:3000 and puts up an error page because its gone to my laptop rather than raspi IP + port 3000.
![2022-01-27 09_03_21-FlowForge _ 192 168 0 50](https://user-images.githubusercontent.com/647054/151326767-865f360e-7a2e-4845-9c99-3e413a774e1f.png)
![2022-01-27 09_03_37-localhost](https://user-images.githubusercontent.com/647054/151326770-e1e76b7a-4dc5-4f49-bc10-95ac8f505c77.png)

### Expected Behavior

The URL would remain at raspi IP + port 7880 and I'd be able to login

### Steps To Reproduce

This was once only on first creation of the project.
All other ways into the new project I can find now show its URL as localhost:7880
![2022-01-27 09_08_58-FlowForge](https://user-images.githubusercontent.com/647054/151327664-423536b3-41e5-48c9-8607-32a8169ca0db.png)

### Environment

- FlowForge version: I think its 0.1.1 ( downloaded 26-jan-22 ) but how can I tell ?
- Node.js version: v14.18.3
- npm version: 6.14.15
- Platform/OS: Pi OS 32 bit ( bullseye - Debian 11 )
- Browser: chrome

**Comment by hardillb** [comment]
There are seveal issues here:

1. You need to set the `base_url` in the `etc/flowforge.yml`. It defaults to `http://localhost:3000` for testing on the local machine. If you are going to access it from a different machine, it needs to be set to `http://[ip address]:3000` where the IP address is the external IP of the Pi. You will need to delete the project and re-create it as access URLs are assigned at creating time.
2. FlowForge requires NodeJS v16

**Comment by hardillb** [comment]
The notes about configuring `base_url` are [here](https://github.com/flowforge/flowforge/blob/main/docs/install/configuration.md) and are linked to from the installer README.md

**Comment by hardillb** [comment]
Issues raised to log version #242 and to check NodeJS version on startup #24

**Comment by vtgav** [comment]
@hardillb thanks for you instant response on this - and my apologies for not checking the documents in detail and spotting this !!

**Comment by vtgav** [comment]
updated node.js to 16.13.2 and changed config to identify IP address - all working fine now, thanks

**Comment by hardillb** [comment]
Closing this now, will track the PR for the version logging and checking in their respective task issues.
