### ISSUE TITLE
Mismatched credit text / values when money is owed

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#2416]
When a users credit value is positive (i.e. owes) the UI does not handle this correctly in all places.

![image](https://user-images.githubusercontent.com/44235289/251124691-894043be-bb52-4ba6-9ffc-40c146e3b837.png)

Issue was discovered while developing #2404 and is not something that needs fixing today since we currently do not support moneys owed.

_Originally posted by @Steve-Mcl in https://github.com/flowforge/flowforge/issues/2404#issuecomment-1621475907_

**Comment by joepavitt** [comment]
For record, Stripe responds with:

```json
"customer": {
    "name": "Mr J Pavitt", 
    "balance": 1500
}
```

if a user owes us money, in this case $15.00

**Comment by joepavitt** [comment]
When in credit:

<img width="647" alt="Screenshot 2023-07-27 at 13 55 34" src="https://github.com/flowforge/flowforge/assets/99246719/ba809940-4144-4a78-814b-d79873b66c76">

When in debit:

<img width="692" alt="Screenshot 2023-07-27 at 13 55 02" src="https://github.com/flowforge/flowforge/assets/99246719/c6dcd879-8c8e-4edd-9aed-8b62d0a9fd9c">

**Comment by joepavitt** [comment]
Not sure how we verify this on staging, any ideas @hardillb?

**Comment by hardillb** [comment]
Possibly by adding credit to the user on Stripe
