### ISSUE TITLE
Accept T&C checkbox on signup page broken

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#2419]
### Current Behavior

The checkbox doesn't render properly when trying to setup a new account.

Will add image later

### Expected Behavior

Checkbox to render

### Steps To Reproduce

Try and sign up as a new user

### Environment

- FlowForge version: 1.9.0
- Node.js version: 16.x
- npm version: 8x
- Platform/OS: Kubernetes/Linux
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
[Screencast from 2023-07-06 09-48-54.webm](https://github.com/flowforge/flowforge/assets/1800845/fccfb0ea-4e8e-4f82-8257-465b0c33c21e)

**Comment by knolleary** [comment]
To clarify as the video is a bit unclear on what state it's in... this is the unchecked box:

<img width="411" alt="image" src="https://github.com/flowforge/flowforge/assets/51083/ee4b38da-93d6-446a-9aef-fb562499e702">


This is the checked box

<img width="420" alt="image" src="https://github.com/flowforge/flowforge/assets/51083/3338720e-6b56-4163-a702-1faabae44a99">

Thankfully, the internal state is correct -  the sign up button is active when checked.

Assigning to 1.10, but labelled backport as we should ship the fix in a maintenance release.

**Comment by joepavitt** [comment]
on it

**Comment by joepavitt** [comment]
Verified on staging
