### ISSUE TITLE
Add clarity on what to do with the `device.yml` in modal

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2430]
![image](https://github.com/flowforge/flowforge/assets/99246719/3b0c4f15-d51b-4908-ac63-159fdab3e0db)

Add more description, or link to documentation of Devices here. It's possible the user got this far without any information on Device Agents, etc.

**Comment by Steve-Mcl** [comment]
Joe, also, perhaps describe it more like "settings" or "configuration" than  "credentials" since other stuff it is now possible  to add other settings too (e.g. Https settings)

**Comment by joepavitt** [comment]
Great point Steve. I shall make it so

**Comment by joepavitt** [comment]
Closed by #2535
