### ISSUE TITLE
Copy to Clipboard visible when no library entry is selected

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#2449]
### Current Behavior

Copy to Clipboard visible when no library entry is being viewed

https://github.com/flowforge/flowforge/assets/44235289/7fc0ffa2-3896-4494-9a99-847ff2558c7a

### Expected Behavior

copy to clipboard should be hidden or disabled when not viewing an entry

### Steps To Reproduce

1. visit team library 
2. select an entry
3. click the breadcrumb to go back up the tree

### Environment

- FlowForge version: 1.9
- Node.js version:
- npm version:
- Platform/OS:
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Don't think that's the screenshot you intended to share for this issue. But no matter, the description is clear.

**Comment by Steve-Mcl** [comment]
> Don't think that's the screenshot you intended to share for this issue. But no matter, the description is clear.

Nope. Updated :)
