### ISSUE TITLE
Syntax error in install.sh

### ISSUE THREAD

**Issue by jdotbdot** [flowforge/flowforge#245]
### Current Behavior

Install.sh gives an error message:
**************************************************************
**************************************************************
 No NodeJS found
 Do you want to install NodeJS 16?
**************************************************************
y/N: y
./install.sh: line 71: [: missing `]'

Not sure if this modifies the subsequent behaviour, potentially it might miss out a part of the installation.

Line 71 is   if [ -x "${yn}"]; then
It should be   if [ -x "${yn}" ]; then
(Requires a space before the closing ] )

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS: Linux
- Browser:

**Comment by hardillb** [comment]
Thanks, will be fixed when 0.1.1 is tagged
