### ISSUE TITLE
Snapshots: unlock portability and re-distributivity. Add an internal API to export snapshot - for automation

### ISSUE THREAD

**Issue by elenaviter** [flowforge/flowforge#2460]
### Description

This issue is a more fine-grained follow-up for [Controllable automation for migration of the projects between FlowForge instances](https://github.com/flowforge/flowforge/issues/2321), thus about specific request for **API** that **extracts a project snapshot, full version** of it, e.g. **with flows**.

### Short description:
- add an API to extract the snapshot(s) as is, w/o filtering out the “sensitive” parts (flows, settings) as of now
- define the service which is responsible for it
- define the needed level of authentication to access this API (e.g. user's cookie, or project-token, or anything else)

> Having such an API on user-cookie-auth routes probably breaks the idea of “only project-identity-owning representatives can access the **flows and settings inside the project**”. 

> In that case, the API could be allowed for “project”-token (consider it can be invoked ‘by project’) which won’t break the idea on project exclusive access to its intellectual property. E.g. the service responsible for API could be `/storage/:projectId/snapshots/:snapshotId`. 

As stated before, this API plays a crucial role in automation of content migration between FlowForge instances, while maintaining the **version control** with the manner of snapshots (they are great for this).

### Have you provided an initial effort estimate for this issue?

I am not a FlowForge team member

**Comment by knolleary** [comment]
Thanks for raising this issue.

I don't think the `/storage/*` api is the right place to add public apis. The `/storage` apis are exclusively for use between the Node-RED instances and the platform via the instances `project` scoped token. Those tokens are not meant to be used by other actors in the system - and definitely not for APIs intended to remove information from the system.

From the description in your original issue, it sounds like you want an API to export a snapshot out of the FlowForge platform. That needs to be part of the public API - `/api/v1/*` - and should probably require Team Owner level permissions for the access token.

We already have APIs for snapshots (https://app.flowforge.com/api/static/index.html#/Snapshots), including one for getting the snapshot metadata.

 - `GET /api/v1/projects/{instanceId}/snapshots/{snapshotid}` [🔗](https://app.flowforge.com/api/static/index.html#/Snapshots/get_api_v1_projects__instanceId__snapshots__snapshotId_)

One complication with getting the full snapshot is that the credentials are encrypted with the instances key. That key is not exposed in anyway, so the snapshot would not be importable anywhere else. That means the endpoint needs to allow the caller to provide a new credential key to be used to re-encrypt the credentials.

 - `POST /api/v1/projects/{instanceId}/snapshots/{snapshotid}/export` - return the full snapshot, including settings, envars, flows and credentials.
     - that expects a body payload of `{ "credentialSecret": "my-secret-key" }`

We already have an [end point](https://app.flowforge.com/api/static/index.html#/Snapshots/post_api_v1_projects__instanceId__snapshots_) that can import a snapshot to match.


I see you've already raised a PR that implements this all in a different way. However as this is part of the public API we need to agree the design before implementing.

**Comment by elenaviter** [comment]
Thank you, Nick, for your clarifications, I greatly appreciate them! 
This issue aims to demonstrate the critical need for 'snapshot' exporting capabilities, which I'll explain further.

### Project delivery: version control, contents, recommendations, documentation
Let's also consider another aspect of the "snapshot" - that of **version control for projects** and the **transfer of data between different FlowForge instances**. 

From this viewpoint, the 'snapshot export'-ed entity could be purely project-semantic-oriented, focused on the **description** (metadata and documentation) and **content** (flows, env, deps). 

For instance, it might not contain any credentials or specific project-related environment variables, except for the `project ID` - `project ID` will help automation processes gathering the full project descriptor to associate the snapshot with information about the Project's stack requirements (cpu/memory/and optionally, image) for a 'recommended resources quota' and other info not yet included in the project's "documentary metadata" (I'll illustrate this with an example in the second section of this comment)*.

#### Export time
In essence, 
it's about the "pure descriptor of the project" – its "business: logic and configuration", i.e., npm dependencies, environment, and flows. 
> It also might include additional information not currently part of the project config as stated in second section of this comment, such as documentation and 'hidden dependencies' (business services used by flows that are not in the form of libraries and therefore don't appear in the dependencies). 

It excludes specific project instance details (identified by ID), so that what remains is only the essence of the project:

- The public part (flows, non-secret environment variables as part of settings, documentation, and recommendations) can be stored externally in a customer-selected store for version control and redistribution.
- The secure part (secret environment variables) can be stored as secrets in a customer-selected secret store. 

By that, the exported snapshot-delivery might closely resemble the original but without credentials and any part of the environment that links the snapshot to a specific project in a specific FlowForge instance which makes it agnostic about the instance.

#### Load time
With this approach, the goal of 'exporting a snapshot' is not to import it as a snapshot, but to load it as a project ('create or update project A from external delivery descriptor with validation'). 
If it needs to be loaded as a snapshot, this descriptor should be enriched with a secret credentials, as you mentioned, by automation or from FlowForge UX, by TeamAdmin ('import as a snapshot for Project A').

When it comes to "loading" this project delivery descriptor into a project (of any FlowForge instance), consider an API "create/overwrite the project from delivery descriptor (our exported unlinked snapshot)". This will accept the project descriptor definition similarly to what 
`POST:/api/v1/projects` and `PUT:/api/v1/projects/:id` do when `sourceProject` is in the body. Thus, the project can be created (or updated) based on this descriptor on a FlowForge instance other than the descriptor's origin (although it could still be the same FlowForge instance with this approach). Reminds the "import flows to project in Node-RED" but is a way wider scope (a Project with all definitions).

### *Place for project documentation, author recommendations, customer-specific integrations
This one on another aspect: project documentation that I wanted to open as a separate issue to discuss but want to give an agenda. 
> Still, this part can be added onto delivery descriptor externally but if we do not store it side-by-side with the Project (and it's snapshots) we don't let it in in the target FlowForge thus leave the deliveries undocumented and decentralized.
As project authors, we want to document the project in-place to provide the details necessary for automation integration of this project within the customer's ecosystem and let them be visible and editable in FlowForge interface.

By 'documentation', I mean the project author's guidelines, which are crucial to understand the project's requirements for device provisioning, proper servicing configuration, and ensuring a closed "integrations cycle". This means that all required integrations by the project are deployed as the project dictates. Below is an example of "project documentation":

- **Scale**: minimum/maximum replicas
- **Public endpoints exposure claim**: yes/no, and if yes - for example, what's the recommended subdomain name, if any
- **Customer ecosystem integration information**: custom description of "hidden integrations" (custom-formatted definition of any customer-specific services required by the project when these services are not Node-RED projects and cannot be referenced as such). This allows the project to declare its internal integrations in a customer-specific format and for automation to see the real demands of the project during delivery.

FlowForge does not intend to use this information, as it does not manage provisioning and validation for any of these integrations or devices. However, it's valuable to develop a project within FlowForge side-by-side with its documentation and to store this documentation alongside the project, within FlowForge (and also within the Snapshot).

Nick, I apologize for the length of the text. I'll appreciate any feedback from you.

**Comment by elenaviter** [comment]
Hey Nick, based on your feedback, I've updated the implementation of this feature. Please take a look at the new commit when you have a chance. Thank you for your guidance!

**Comment by knolleary** [comment]
@elenaviter thanks for the update on the PR - its review is on my task list.

In terms of your previous comment, there are some areas I'm not entirely clear on.

> With this approach, the goal of 'exporting a snapshot' is not to import it as a snapshot, but to load it as a project ('create or update project A from external delivery descriptor with validation').

I am cautious of us adding lots of different ways of doing the same ultimate task unless there is a clear purpose in doing so.

In my mind the appropriate way to 'apply' a snapshot to a Node-RED instance is:

1. [Import that snapshot](https://app.flowforge.com/api/static/index.html#/Snapshots/post_api_v1_projects__instanceId__snapshots_)
2. [Trigger a rollback to apply that snapshot](https://app.flowforge.com/api/static/index.html#/Instance%20Actions/post_api_v1_projects__instanceId__actions_rollback).

The existing "Import snapshot API" serves two purposes; creating a snapshot from the current state of an instance (used in the FF UI when you create a snapshot), *or*, creating a snapshot using just the info passed into it (used by the Node-RED FF Tools Plugin to import a snapshot). It is this latter use that I think allows you to import a complete snapshot taken from any other instance. That would need verifying as it isn't quite the Tools Plugin use case so may not have been fully tested around taking a complete snapshot object.


Our API does also have this [Import](https://app.flowforge.com/api/static/index.html#/Instances/post_api_v1_projects__instanceId__import) API that can be used to upload *only* the flows/credentials. This is used in the FF UI to allow a user to upload an existing flow file/credentials file they may have from a local Node-RED instance - a way to help them import existing flows into the platform. That API doesn't support the other properties included in a snapshot.


Personally, I'm in favour of keeping this focussed on the Snapshot as the object that gets imported and then applied - and we could consider add a flag to the Import Snapshot api to automatically rollback to it as well.

> This one on another aspect: project documentation that I wanted to open as a separate issue to discuss but want to give an agenda.

Agreed this should be a separate item to discuss. You describe a number of very custom things you want some structured format for in the Instance model. One approach would be for the Instance to support having a very generic 'metadata' property that is treated as YML (as its far more text-box friendly to edit). The FF platform wouldn't have any knowledge or interest in the contents of that property, but would be a space where additional custom structured info could be stored. If that property was then also included in the snapshot object, you'd have a place to store your information. Please do raise a separate issue on this topic.

**Comment by ggworld** [comment]
@knolleary - Any news on this PR - after you handling ENV issue this what held us back from using Licensed version

**Comment by knolleary** [comment]
@ggworld Hi - the changes had already been approved, but there were some test failures that needed resolving so it just missed the 1.11 release.

I can see the updates from @elenaviter - will get it reviewed and merged this week.

**Comment by ggworld** [comment]
@knolleary - pls. let's have this in 1.12  (with [#145](https://github.com/flowforge/flowforge-nr-launcher/pull/145) and [#146](https://github.com/flowforge/flowforge-device-agent/pull/146)).
Let's see how can we have an early drop (before the release so we can verify all is working as planned).
