### ISSUE TITLE
Improve error feedback when trying to access expired Device editor tunnel

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#2473]
### Description

ref https://github.com/flowforge/flowforge/issues/2439

If the device agent tunnel times out and closes, the editor will not be able to deploy any changes. A user may then go back to the FF dashboard, re-enable the editor and then try to continue working in the existing editor tab. That cannot work because there is a new editor tunnel under the covers that the existing editor tab doesn't know about or have access to.

After re-enabling the editor, they need to click the 'Open Editor' button to get a new tab with the new session url.

Some exploration is needed to refine exactly what improvements can be made to the UX here.

1. A better error (ie something that helps the user move forward) if the user reloads the editor tab for the 'old' session.
2. Better reporting in the editor if the tunnel has expired; I'm not sure what is feasible here as its 'normal' Node-RED error handling that cannot be customised currently.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
#2488 has addressed the main points in this item

**Comment by Steve-Mcl** [comment]
Previously verified on staging and released into the wild.

Re-verified and with latest updates to device agent.
