### ISSUE TITLE
Improve reliability of Device Editor tunnel

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#2483]
### Description

If the tunnel between the platform and device fails for any reason, the user has to currently re-enable the editor in the flowforge platform to get the tunnel re-established.

This can be disruptive to the editor experience. Particularly if it drops whilst editing flows; the user cannot deploy those changes and the editor must be reloaded (losing those changes) once the tunnel is re-enabled. This is because the tunnels are currently treated as single-use sessions.

We need to consider users who enable the editor and want it to remain enabled forever (or at least, more than just a single period of editing flows).

We need to modify the tunnel handling so that a device is able to reconnect to its previous tunnel session.

This should also consider the case where the Forge app is restarted; so session info should not be ephemeral - a device should be able to reconnect its tunnel after the forge app is restarted.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
Previously verified on staging and released into the wild.

Re-verified and with latest updates to device agent.
