### ISSUE TITLE
Redirect to Instance Overview in onboarding UX

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2495]
### Description

Task taken from https://github.com/flowforge/flowforge/issues/2487.

We want to streamline UX for onboarding, currently losing users attention when on the Application Overview page, want to send them to the Instance overview, after creating first application, instead where they'll have more insight into what is going on whilst in "Starting" state.

### Epic/Story

#2487

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by MarianRaphael** [comment]
See also: https://github.com/flowforge/flowforge/issues/2475

**Comment by MarianRaphael** [comment]
Yes, verified on staging. 
When I create an application, I am forwarded to the Instance Overview:
<img width="1414" alt="Screenshot 2023-08-02 at 10 23 07" src="https://github.com/flowforge/flowforge/assets/73583313/bfedf58c-f777-4b26-afcc-e3e1c877b4e1">
