### ISSUE TITLE
Failed to start project with error: ERR_INVALID_URL if template have custom Editor URL Path

### ISSUE THREAD

**Issue by vnStrawHat** [flowforge/flowforge#2571]
### Current Behavior

if templates have custom value of Editor URL Path, new instance will cannot be start because error: ERR_INVALID_URL 

### Expected Behavior

new instance able to start as normal

### Steps To Reproduce

1. Create new template
2. in Editor URL Path. set to /editor
![image](https://github.com/flowforge/flowforge/assets/4435695/20a0b2c0-8c97-4369-bc68-dc708d2c74ad)
3. Save
4. go to Application
5. Create new Instance
6. select template created in step 1
7. Recent Activity will show error and can not start
![image](https://github.com/flowforge/flowforge/assets/4435695/f1d5fff4-c565-4e19-b042-e147f2aa39da)

### Environment

- FlowForge version: v1.10.0
- Node.js version: v16.20.1
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I am not a FlowForge team member

**Comment by hardillb** [comment]
Hello, thanks for raising this.

I'll have a look, but could you please confirm which version you are using (localfs/docker/kubernates)

Thanks

**Comment by hardillb** [comment]
I can't immediately reproduce this with the localfs build

**Comment by vnStrawHat** [comment]
I am using docker-compose with images in [docker hub](https://hub.docker.com/u/flowforge)

**Comment by hardillb** [comment]
OK, I can reproduce this with the docker driver. Will keep digging

**Comment by hardillb** [comment]
OK, I know what the problem is, just got to work out how to fix it...

**Comment by hardillb** [comment]
@vnStrawHat version 1.10.1 should have just been published and there should be new docker containers on docker hub. 
You can upgrade by
```
# docker compose -p flowforge down
# docker pull flowforge/forge-docker
# docker compose -p flowforge up -d
```
