### ISSUE TITLE
Frontend rendering issues in mobile

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#264]
### Current Behavior

As pictured below from OnePlus 7t pro (Android 11, screen resolution 1440 x 3120)...

![Screenshot_20220203-184256](https://user-images.githubusercontent.com/44235289/152703520-25ba0796-cd00-407d-b8ed-029a74925069.jpg)

### Steps To Reproduce

Log in to FlowForge via mobile.

### Environment

- FlowForge version: 0.1.1
- Node.js version: 16
- npm version: 8
- Platform/OS: Android
- Browser: chrome

**Comment by sammachin** [comment]
This will hopefully be resolved with the app rebrand in 0.5

**Comment by joepavitt** [comment]
Just an update to this post-rebrand merge: 

<img width="414" alt="Screenshot 2022-05-03 at 08 58 22" src="https://user-images.githubusercontent.com/99246719/166420888-05a464a6-1cc4-4b11-ab2a-122aa57ce40e.png">

**Comment by knolleary** [comment]
Are we happy to mark this as done? Otherwise its a bit of an open-ended task.

**Comment by joepavitt** [comment]
Yep - agreed
