### ISSUE TITLE
Navigation from a Node-RED instance back to FlowForge

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#269]
### Description

When working on a project, I'd like to navigate back to the project page on FlowForge when needed. 

It's unclear how to achieve that in the current version of the product. (V0.1)

**Comment by knolleary** [comment]
Node-RED provides some limited options for adding custom UI elements. This is an opportunity to identify what we really want the view to look like and work back from there in terms of and requirements to the `editorTheme` setting of Node-RED itself.

**Comment by sammachin** [comment]
@Steve-Mcl is this implmented in 0.7

**Comment by sammachin** [comment]
How does Node-RED get the project name?

**Comment by sammachin** [comment]
Equally I like showing the project name on the top of the editor, makes it easy to see which project you're in

**Comment by Steve-Mcl** [comment]
> How does Node-RED get the project name? 

It is currently aligned to the new `title` property in settings
![image](https://user-images.githubusercontent.com/44235289/177528901-a96d1475-d33f-4a25-9dde-8444ebd1098a.png)
I left this 1 piece of UI in FF as it can be re-mapped to project-name when project-name editing is supported.

> I do wonder if this would be more useful in the node-red menu, thats where i would think to look for it rather than clicking the project name

Just followed the figma - I am open to any and all suggestions Sam/guys.

**Comment by sammachin** [comment]
> > Equally I like showing the project name on the top of the editor, makes it easy to see which project you're in
> 
> Do you mean as the browser tab title? or the header (as it is now)?

The header as it is now, I very rarely read the tab title as I have too many tabs open to be useful when its down to 2-3 chars

**Comment by sammachin** [comment]
@Steve-Mcl how does Node-RED know the project ID and URL to get back to the right page in the forge application?

**Comment by Steve-Mcl** [comment]
Quick version...
It is implanted into settings.js by the launcher into the theme header URL setting. 

Do you need more detail @sammachin ?

**Comment by sammachin** [comment]
Link in hamburger menu not working due to bug at https://github.com/flowforge/flowforge-nr-theme/blob/af2524d44c5d6b7f4c049fc960fa294db04a6047/common/forge-common.js#L41
Steve will fix and this can then be closed as implemented,

There are 3 ways to navigate back to the Forge Application from a Node-RED Instance:
Clicking the FF Icon/Project Title in the top right, 
Using the logout link in the User Icon
From a link in the hamburger menu.

**Comment by sammachin** [comment]
Fixed in https://github.com/flowforge/flowforge-nr-theme/pull/15
