### ISSUE TITLE
Select Project Components to Export

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#270]
### Epic

#268

### Description

**As a:**  Owner

**I want to:** Select which components of a project will be exported
Components are:
- Policy 
- Flows
- Credentials
- Node-RED settings
- Env Vars
- Installed Nodes

**So that:** I can move a project from dev to prod without copying over certain values

**Comment by knolleary** [comment]
This story cannot be delivered by itself. It is a requirement that cuts across a number of the export stories that define where a project is exported to.

The primary 'export' stories this it is part of are:
 - #271 
 - #272 
 - #273
 - #279 

Whilst the precise UX for _initiating_ those different types of export will be different, there should be a consistent user experience around selecting the components that need exporting - which is the remit of this story.

This means we need:

 - [ ] A Vue component that can be reused across those other stories that provides the list of components of the project a user can chose to include, or exclude, in the export.
 - [ ] A standard JSON representation of that selection that is used across the whatever runtime apis the other stories lead to

I think we can refine the list of components that can be selected from the original description - or at least simplify it for the initial implementation.

But there are going to be some slight different requirements between the related stories.

For example - when copying a project to a new project (#271) or an existing one (#272), then we would include the info on which Template the new project should use. I don't think that is optional. But when exporting a project *out* of the system (#273) then we need the combined Template/Project settings as a single view - the template doesn't play a role outside of the system boundary.

The default would be to export everything - a full copy of the project.

We then need to consider the use-cases for why a user may deselect any of these components.

 - Flows (including credentials)
     - A user has configured a project just how they want, with preinstalled nodes etc. They want to create a copy for a new app they want to develop - so leave the flows behind.
 - Flow credentials
     - A user wants to create a copy of a project, without copying the flow credentials. For example, to share the project with someone else - but leave it to them to add their own credentials
 - Env Vars
    - Similar to credentials - being able to 'not' copy over the _values_ is important.
 - Project Settings
     - I'm struggling to define the use case for this part. If copying to another FF Project (ie not exporting beyond the system boundary), then the new project will have to use the same Template as the original - that is non-negotiable. To not copy over any project-overridden values feels odd.
      - It depends on how granular this option needs to be. Does it go to the level of individual settings (that feels unnecessarily burdensome to the user).. or are there some more logical groupings?
 - Installed Nodes
    - If the nodes are required to run the flows, then choosing not export that information feels pointless.
    - If you aren't exporting the flows, then you could leave out the installed nodes... but at that point, what are you left with that warrants exporting at all?

To manage the scope of this, I would propose the most useful selections to provide are just:

 - Flows
 - Flow Credentials (if the user deselects Flows, then Flow Creds should be deselected - it is not technically feasible to export only the creds and not the flows themselves)
 - Env Vars - options: export all, export keys only, export none

All other parts get exported.

I think this will address the most useful usages of the export feature - and doesn't prevent a future iteration that adds the other options as we identify the use case they satisfy.

**Comment by knolleary** [comment]
RE flowforge/flowforge-nr-launcher#16 - if the user selects to export credentials, the UI component should prompt for a `credentialSecret` token to use to re-encrypt the credentials with. This is not required in all uses of this common component - so should be a configurable option of the component.

**Comment by sammachin** [comment]
Agreed on Settings, if a user wants to take a copy of a project and then edit those settings in their version they can, the only limitation will be any settings that were locked in the policy but then they would have the same issue editing a new project.

Agreed on installed nodes, the only use case I can think of is it you had a load of unused nodes in your project but then you should go into the editor and remove them before export, rather than us having to create a UI to select/deselect individual nodes from FF.

**Comment by knolleary** [comment]
Good stuff.

Please have a read through of https://github.com/flowforge/flowforge/issues/270#issuecomment-1090771228 - particularly the last part. I propose we don't need to include all of these things in the list.

**Comment by knolleary** [comment]
Component delivered in 0.5
