### ISSUE TITLE
Duplicate Project

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#271]
### Epic

#268

### Description

**As a:** Owner

**I want to:** Export an existing project to create a new one

**So that:** I can deploy from Dev to Prod the first time.

All values that are in the export should be set and anything not included should use the platform/policy defaults

**Comment by knolleary** [comment]
The 'export' terminology works when you want to leave the system boundary, but when operating inside the system we can be more direct in the terminology and call this 'Copy project' or 'Duplicate project'


### UX

 - The 'Danger' settings tab is where we put administrative actions on a project - this will add a 'Duplicate Project' option on that tab.
     - Aside: the name 'Danger' made sense when it contained the destructive delete action. It now has the 'Change Stack' option, which is something done with caution, so the name still works. 'Duplicate Project' doesn't quite fit the pattern. We should consider renaming that tab to something more appropriate, with a 'Danger' section.
 - Clicking the button will open a dialog to walk through the process.
    - The dialog should look like the 'create project' view where they set the name etc.
        - the Template/Stack should be pre-filled with the right values. I do not think the Template field should be changeable - see #270 for my thoughts on that (we can iterate on that if needed)
     - The dialog also has the options for which project components to copy over - see #270 for details
  - Confirming the dialog kicks off the create and redirects the user to the new project's page - same behaviour as the existing create project flow.

### Runtime API

As this is about creating a new project - with some pre-existing content - the existing `POST /api/v1/project` end point should be extended to support this functionality.

I propose the payload gains an option additional property:

```
...
sourceProject: {
   id: <source project id>
   options: <copy options>
}
...
```

The `<copy options>` object provides the additional information the user provided as to what gets copied over (#270)

**Comment by sammachin** [comment]
Just to confirm, the stack will be changeable when duplicating a project though? but the default would be the same stack as the source project?
Given that it will (soon) be possible to change the stack on a project anyway I can't see why we would want to force a duplicate to be the same stack? That would just require the user to duplicate and then switch the stack.

**Comment by knolleary** [comment]
> Just to confirm, the stack will be changeable when duplicating a project though? but the default would be the same stack as the source project?

Yes - I called out that Template wouldn't be, but didn't say explicitly that stack should be changeable. Have edited above to be explicit.

**Comment by knolleary** [comment]
Delivered in 0.5
