### ISSUE TITLE
Failed node installation on Node-RED makes an entry in instance settings>palette>modules leading to instance start-up failure

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#2710]
### Current Behavior

If a node package install fails in a Node-RED instance, the name+version are still added to the "Installed Modules" list e.g

#### FF Settings
![image](https://github.com/flowforge/flowforge/assets/44235289/4af1cbfe-6383-48e0-91e8-360cad3c7222)

#### Associated package.json (thanks @ppawlowski)
```
➜  ~ (arn:xxx:xxx:eu-xxx-x:xxxxxxxxxx:cluster/flowforge-test/flowforge) kubectl exec -it big-flow-3mb-xxxxxxxxxx-xxxx-- bash -c 'cat /data/package.json'                                                                            
{
  "name": "node-red-project",
  "description": "A Node-RED Project",
  "version": "1.11.0",
  "private": true,
  "dependencies": {
    "node-red-debugger": "*",
    "nrlint": "*"
  }
}%
``` 

This means at a future point in time, a restart of the container will attempt to install the failing node & cause a start-up failure.

### Expected Behavior

If module fails to install from the instance palette manager, I do not expect the instance>settings>palette>modules to retain this failing entry.

### Steps To Reproduce

On staging: 
1. attempt to install flowforge dashboard
   1. It will (currently fail due to no-token access)
1. check the instance>settings>palette>modules list

restart the instance - the instance will fail to start due to the inaccessible module in the list.

### Environment

- FlowForge version: 1.11
- Node.js version:
- npm version:
- Platform/OS: Cloud & Local Dev (windows)
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
The FF platform listens to the instance audit events to know when a node has been installed. In particular the `nodes.install` event.

The same event identifier is used if a node fails to install - but with an added `error` property. We need to check for that property to prevent us adding things to the package list that failed to install.

```
11 Sep 11:15:50 - [audit] {"event":"nodes.install","module":"@flowforge/doesnotexist","version":"0.4.0","error":"not_found","level":98,"path":"/nodes","ip":"::1","timestamp":1694427350178}
```
