### ISSUE TITLE
Export to Existing Project

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#272]
### Epic

#268

### Description

**As a:** Owner

**I want to:** Export a project to update an existing project
Any components in the export should replace the current ones in the project, anything not in the export should not be modified

**So that:** I can deploy my changes from Dev to Production

**Comment by knolleary** [comment]
Much of #271 applies here too - the goal is for a consistent UX between the two stories. 

1. Under Danger section of project settings, add a 'Copy to existing project' option.
2. Opens a dialog - user is shown a list of projects in the current team
    (as with #271, I propose restricting this to 'within the same team' for MVP - otherwise we also have to think through the security/policy questions that come up with copying outside of the team boundary)
3. User selects team, then show the list of options to copy over - #270

### Runtime API

The `PUT /api/v1/project/:id` endpoint is the existing 'update a project' endpoint. This feature should add a mode to that triggers this behaviour.

The payload should include an object consistent with that proposed in #271 
```
{
 sourceProject: {
    id: <source project id>
    options: <copy options>
 }
}
```
Note this property *cannot* be mixed with the other options.

As per comment on limiting to the same team (for now), the api should ensure the target project is in the same team as source project.

**Comment by sammachin** [comment]
Yes all within the same team for now.

Where a component is selected to be copied over it will overwrite any existing data for example if Source project has Env vars A B & C and target project has Env D, E then this action will end up with the target project only having A, B, C.

**Comment by knolleary** [comment]
> Where a component is selected to be copied over it will overwrite any existing data for example if Source project has Env vars A B & C and target project has Env D, E then this action will end up with the target project only having A, B, C.

Correct - the assumed behaviour would be to overwriting rather than merging.

If it becomes evident there is a use case for merging some particular settings, we can address as a future story.

**Comment by hardillb** [comment]
Should credentials be copied even if the flow isn't in this situation?

Duplicating and exporting both currently only copy creds if the flow is also copied, but I can see a case for just copying over the creds in this usecase.

**Comment by hardillb** [comment]
@knolleary & @sammachin Should the export also change the template and stack of the target project?

**Comment by sammachin** [comment]
Stack should stay as it is on the target project, for example you might have a "dev" project thats on a lighter stack than your production.

Template should replace the target I think? In most use cases I would expect both projects to be using the same template anyway

**Comment by knolleary** [comment]
Stack - stays the same
Template - gets updated

**Comment by knolleary** [comment]
Delivered in 0.5
