### ISSUE TITLE
Add option for monthly invoices rather than triggering invoices on every billing change

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#2746]
### Description

We currently ask stripe to generate new invoices with every billing interaction. That can lead to many emails and receipts - which is inconvenient to users.

There is a requirement to move to monthly invoicing. This issue is to track the work needed to achieve that.

First task is to investigate the Stripe api to understand how the existing invoicing behaviour is being triggered - and to identify how to modify that behaviour.

Need to clarify if this should be a whole-sale change to how our billing operates, or only for certain TeamTypes. If the latter, will need a flag adding on the TeamType to indicate the desired billing mechanism.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Having investigated the details, this behaviour will require a a code change to achieve - it isn't something we can configure on the stripe side.

In summary, wherever we modify a subscription, we are currently including `proration_behavior: 'always_invoice'` to trigger an immediate invoice. This was a deliberate choice when billing was first introduced.

To keep to the monthly invoicing, this flag needs removing for all of the relevant calls to the stripe api. It will then revert to the default behaviour of adding a prorated item to the next invoice.

So, the question is: should we just modify this behaviour globally, or do we want this to be only applied for certain TeamTypes.


REF: https://stripe.com/docs/api/subscriptions/update#update_subscription-proration_behavior

**Comment by ZJvandeWeg** [comment]
> So, the question is: should we just modify this behaviour globally, or do we want this to be only applied for certain TeamTypes.

Whatever is quickest, I do think that the starter package should be prepaid in principle. As it will leave an abuse window for 2 months otherwise.

**Comment by knolleary** [comment]
We will have the ability to enable Prorated items on the Team TeamType in tomorrow's maintenance release via https://github.com/flowforge/flowforge/pull/2758
