### ISSUE TITLE
If new user automatically creates a personal team they are not automatically added to the inviting team

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#275]
### Current Behavior

If the "Create a personal team for users when they register" is checked but "Allow new users to register on the login screen" is not then when a user is invited to join a team they are added to their personal team, but not the original inviting team.

The invite for the original team is still available under the users settings, but they have to look for it.

### Expected Behavior

User to be added to the inviting team as well as their new personal team

### Steps To Reproduce

Invite a new user to a team via email having set the options mentioned earlier

### Environment

- FlowForge version: 0.1.1
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Alpine/Docker
- Browser: Chrome

**Comment by hardillb** [comment]
The in UI action is to invite them to a specific team, so I think unless we add a way to invite to the platform then it should follow through on that action.

The Create a Personal team is a second optional action that was enabled in the settings, if that is not enabled somebody invited to the platform but not a member of any team can do nothing.

**Comment by sammachin** [comment]
Ok that makes sense, but we should modify the text of the email so that it tells you which team you have been invited to as well then, at the moment it just says "You have been invited to collaborate on the flowforge platform"

**Comment by knolleary** [comment]
> The Create a Personal team is a second optional action that was enabled in the settings, if that is not enabled somebody invited to the platform but not a member of any team can do nothing.

But they will have a team invitation waiting for them that is show prominently on the welcome screen - so they aren't left stranded.

The question is whether, when inviting an external user, them registering on the platform should automatically accept any invites that are waiting for them. I made the choice not to do that - for them to have to accept the invites once they have signed in.

When a new user registers, we don't currently have a way to correlate that signup with which invite link they clicked on to get there. That means if an external user is invited to multiple teams (so they get multiple emails) - we won't know which one they accepted. I'm not sure auto-accepting any pending invites when they register is quite right.

**Comment by hardillb** [comment]
OK, Sam implied he didn't see the invite for the original team until he went looking for it, but as admin it's not a path I've followed yet.

**Comment by sammachin** [comment]
Yes it seems like if the "Create Personal Team" is set then you don't see the welcome screen with the other invitation

**Comment by knolleary** [comment]
Ah yes - the 'welcome screen' only shows if you have no teams. Otherwise you get dropped into your default team.

The whole experience of that first sign-in needs looking at in detail as it has to do lots of things to welcome the user and help them know what to do next.

We also need a better indication of pending invitations (#277 )

**Comment by ZJvandeWeg** [comment]
@hardillb @knolleary can we fix this issue somehow now, and later schedule #277 and auxiliary issues? Now this issue is unassigned and there's no progress it seems.

**Comment by knolleary** [comment]
This issue is in the 0.2 Milestone - it will get resolved for the release this week.

**Comment by knolleary** [comment]
Looking at this again, I can see it is working as intended. As I mention in a previous comment, a specific design point is that a user cannot be added to a team without their permission - they have to accept the invitation.

The question is whether signing up to the platform should be taken as implicit acceptance of any pending invites.

To be pragmatic, for 0.2, we can change it so invites are automatically accepted in this one scenario - and review that once we have #277

**Comment by sammachin** [comment]
We should also edit the text of the invite email thats sent to include the team name you have been invited to.

**Comment by ZJvandeWeg** [comment]
> To be pragmatic, for 0.2, we can change it so invites are automatically accepted in this one scenario

Thanks! 👍 

> We should also edit the text of the invite email thats sent to include the team name you have been invited to.

@sammachin Can we open a new issue for this? That limits the scope of this one, and keeps it focussed.

**Comment by hardillb** [comment]
Invites to teams for existing users (https://github.com/flowforge/flowforge/blob/main/forge/postoffice/templates/TeamInvitation.js) does include the team name, it's only invites to new users (https://github.com/flowforge/flowforge/blob/main/forge/postoffice/templates/UnknownUserInvitation.js) that don't mention the team name (at the moment).

I can see why it's not included for new users as the concept of teams may not yet be known to them.
