### ISSUE TITLE
Project Stacks

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#285]
### Description

A Project Stack is a description of the underlying software/hardware configuration that a project runs on.

It covers:

 - Node.js version
 - Node-RED version
 - Driver-defined properties:
   - Memory
   - CPU

Administrators can define stacks via the admin settings section of the UI. They must define a default stack as part of the initial setup of the platform.

When a User creates a project, they pick from the list of available stacks.

Users can change the stack used by a project - this will require downtime of the project as it has to be stopped and re-provisioned. *This is how we can support upgrading the version of Node-RED*

Admins can mark a stack as inactive. This hides it from being selected when creating new projects - but doesn't affect existing projects that use that stack.

Admins can see information on what projects are using what stacks. If a stack is created to upgrade node.js/node-red due to a security issue, they will have tools available to them to manage upgrading existing projects to the new stack.

 - [x] #326

**Comment by sammachin** [comment]
Is npm version also part of the stack?

**Comment by hardillb** [comment]
I don't think it needs to be, it shouldn't have an impact on the running of a project.

At worst it may have an impact on installing modules

**Comment by knolleary** [comment]
The core functionality and concept has been delivered. No need to keep this epic open.
