### ISSUE TITLE
Update Telemetry wording in UI to say we now collect data

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#291]
### Description

The current wording for the Telemetry option (in both Setup screens and Admin Settings) says:

> This release does not collect any information
> A future release will collect anonymous statistics about how FlowForge is used. This allows us to improve how it works and make a better platform.
> We will clearly communicate when this feature is implemented and exactly what information is being gathered.

That needs to be updated now that we are able to collect data.

### Epic/Story

#142

**Comment by joepavitt** [comment]
@knolleary any strict language that we do need to use in place of this? Or something generally informative acceptable enough?

**Comment by knolleary** [comment]
I think it's mostly a case of removing the 'future' looking aspect of the text. We also have #129 that needs doing that will provide a place this text can include a link to for more information.

**Comment by knolleary** [comment]
The message should include a 'for more info' type link to `docs/admin/telemetry.md` that was added in #303 . For now, it should link to the file on github and open in a new tab.

There is a screenshot in the docs of the *old* message before we added the clarification in 0.1 that it wasn't enabled:

https://github.com/flowforge/flowforge/blob/main/docs/install/images/setup-04-options.png

We'll need to redo that screenshot with the new message.
