### ISSUE TITLE
Team switching sometimes blocked

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#306]
### Current Behavior

- Navigate to the "Settings" view on a team
- Switch, using the dropdown in the top-left, to a team that you are not an admin on
- The navigation is blocked (assuming because you don't have permissions to view the "Settings" page in the team you're navigating too.
- The fallback is then the "Overview" tab of your currently active team, following which, you can then successfully navigate to the new team.

### Expected Behavior

- Rather than falling back to the "Overview" tab on my existing team, it should navigate to the "Overview" tab of the team I am navigating to.

### Steps To Reproduce

As per "Current Behaviour"

### Environment

- FlowForge version: 0.1.1
- Node.js version: 16.13.2
- npm version: 8.1.2
- Platform/OS: Mac OS Monterey
- Browser: Google Chrome

**Comment by knolleary** [comment]
This is marked as Done in the project board, but there's no link PR. What's the true status?

**Comment by joepavitt** [comment]
Associated PR: https://github.com/flowforge/flowforge/pull/329
