### ISSUE TITLE
Setup payment on team creation

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#312]
### Epic

#224

### Description

**As a:** team owner

**I want to:** be redirected to stripe checkout when I'm creating a new team

**So that:** I can be charged for my projects

### Acceptance Criteria

- [x] Customer Completes Stripe Checkout Process
- [x] SubscriberID and CustomerID in flowforge DB
- [x] TeamID in Stripe subscripton Metadata

**Comment by sammachin** [comment]
FF will create a new checkout session (https://stripe.com/docs/api/checkout/sessions/create) 
This mode of this session is `subscription` 
The `line_items` will contain the basic team price ID and a `quantity` of 1 
The `subscription_data.metadata.teamid` object  will contain the `team hashid`.
The `subscription_data.metadata.teamname` object  will contain the `team name`.

`payment_method_types` shall only contain `card`
`success_url` Will be a url to redirect the customer back into the forge application with a `CHECKOUT_SESSION_ID` 
`cancel_url` will be a url to return customers to on the forge platform that aborts the team creation.
createSession returns an object that contains a `url` value
The customer should be redirected to this URL
This URL will have the checkout_session_id in the query string, using this value we can then retrieve the session (https://stripe.com/docs/api/checkout/sessions/retrieve) this will contain the customerID and subscriptionID, along with the metadata we set containing the team hashid. customerID and subscriptionID need to be stored against the team object in the forge application.

**Comment by hardillb** [comment]
Backend done in #332

**Comment by joepavitt** [comment]
Golden Path added in f970bea9

**Comment by sammachin** [comment]
@joepavitt  When the user returns to FlowForge from Stripe having successfully setup billing we should show a message that confirms their billing is ready and they can start to create projects.
