### ISSUE TITLE
Remove storage nodes on flowforge.cloud instances

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#318]
When the driver in use doesn't allow us to use the disk, like with kubernetes, the storage nodes should not be exposed in the user interface.

**Comment by sammachin** [comment]
its something I'm aware of and we need to make users aware that the filesystem isn't persistent on flowforge cloud, however I'm not sure we should remove the file nodes, there are use cases where a flow might need to work with files on a temporary basis even if they are not going to survive a restart.

**Comment by hardillb** [comment]
Removing the filesystem access nodes is the right thing to do. Users should not be trying to write files to the container and there is no external storage mapped in (I've done this for a client, but it doesn't scale well and you then get into re-selling EFS/EBS storage and need ways to assign costs to users.)

**Comment by knolleary** [comment]
>  there are use cases where a flow might need to work with files on a temporary basis even if they are not going to survive a restart.

The very real danger is users don't appreciate the non-persistent nature of it and rely on the files being there. I would prefer to disable by default and then add back in if there is a demand and if/when we decide to have local filesystem storage as an add-on feature.

From an implementation POV, this will be achieved as part of the default template the admin creates when they setup the platform. Which also would allow another instance of FF to have them enabled by default.

**Comment by sammachin** [comment]
I agree there's a danger to users not understanding the filesystem but I don't think just blocking the nodes is a good option medium term, we need to figure out how to enable and communicate to users how they can (safely) work with files in flowforge.

**Comment by sammachin** [comment]
This will be done in https://github.com/flowforge/CloudProject/issues/41

**Comment by sammachin** [comment]
done
