### ISSUE TITLE
Admin invite user to team

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#342]
### Description

**As a:** admin

**I want to:** be able to add members (including myself) to a team that I do not own

**So that:** I can manage the users in a team.

### Acceptance Criteria

- [ ] On the `/team/:team/members/general` view I have the `+add user` button for all teams

**Comment by knolleary** [comment]
I'm not sure this is the way to solve the problem.

I don't think an Admin should be able to add themselves to a team - that doesn't give them any access they couldn't already have via Admin tools to administer the platform/team.

**Comment by sammachin** [comment]
Currently it`s not possible for an admin to add a user to a team.

![image](https://user-images.githubusercontent.com/187645/157654369-831cac91-d34d-41fd-97d4-ceda4ef885d8.png)

**Comment by sammachin** [comment]
So the admin shouldn't just be able to add themselves or a user to a team but they should have the `+add user` button for all teams that this should trigger an invite that needs to be accepted as if the owner of the team had invited the user.
If the admin chooses to invite themselves or another user.

**Comment by sammachin** [comment]
can rollover to 0.5

**Comment by knolleary** [comment]
The fixes in #493 allow admins to access the invite pages which should address this story.
