### ISSUE TITLE
Renaming a Project

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#347]
### Current Behavior

Its possible to rename a project via the `edit settings` button on the `project/:ID/settings/general` page

When running with the container drivers (k8s) this causes a number of issues, specifically:
- The Status Isn't reported
- Can’t Restart Project
- Doesn’t change project URL
(and possibly more)
it doesn't appear to cause issues with local-fs based installs.

Talking to @hardillb renaming of projects shouldn't currently be supported on the platform.

### Expected Behavior

I should not be able to change the name of a project

### Steps To Reproduce

Create a Project
Change the Name of the Project
Observe the status indicator isn't updated
Try and Restart the project
Observe that it does not restart
Change the name back to the original

### Environment

- FlowForge version: 0.2.0
- Node.js version: 16
- npm version: 8
- Platform/OS: MacOS 12.2
- Browser: Chrome 99

**Comment by hardillb** [comment]
Just to add some context, changing the name is a pretty disruptive change in the container implementations (it's used to internally access the container and in the ingress mapping). It should be possible to add it, but it's on a par with changing the stack (requiring a restart of the container) so can be added back in when we implement that.

**Comment by joepavitt** [comment]
Am I right in saying this is just us wanting to hide this functionality in the frontend?

**Comment by hardillb** [comment]
That would be the quickest fix for now

**Comment by sammachin** [comment]
Yes if we can make a frontend change for now that disables the ability to edit the name then we can look at a proper story around renaming

**Comment by sammachin** [comment]
@joepavitt as part of this can we add a note/label to the create project page that warns a user they cannot change the name once its created.

**Comment by joepavitt** [comment]
Of course - going to wait for the billing stuff to get merged before touching this though, as it'll clash quite heavily.
