### ISSUE TITLE
Status label doesn't update

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#348]
### Current Behavior

When I create a new project the status shows as 'starting' but this doesn't automatically change to running unless I refresh the page

### Expected Behavior

The label should be updated without a page refresh

### Steps To Reproduce

Create Project
Observe the Status Indicator

### Environment

- FlowForge version: 0.2.0
- Node.js version: 16
- npm version: 8
- Platform/OS: Mac 12.2
- Browser: Chrome 99

**Comment by joepavitt** [comment]
Are we looking at implementing some kind of Websockets here to handle this, or just http polling (ew!)?

**Comment by knolleary** [comment]
@joepavitt With the Changing Stacks PR (#437) I have made a number of improvements in how state is reported - particularly during 'expected' transitions (such as 'starting' and 'stopping') - and improved how the UI detects a change is in progress and refreshes (yes with polling... I know).

There is still a need, I believe, for a separate API for querying the status - see #370 - which will allow for a more responsive UI. And that yes, that could well become a WebSocket API so it scales better.

**Comment by sammachin** [comment]
with 437 merged the experience is now improved, the screen updated to show the project as started in around 10sec
