### ISSUE TITLE
Fleet management

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#351]
### Description

Flows developed are sometimes intended to be deployed to devices in the wild. Deployment to external devices should be a capability of FlowForge.

Prerequisites:
* User already has Node-RED installed on the device (Unknown version?)
* The Node-RED has connectivity and can initiate a TCP connection

**Comment by sammachin** [comment]
This is much wider than just a single epic, this is potentially a whole new mode of operation for the platform, it`s useful to have captured but will need a lot more research and thought before we get into details.

**Comment by ZJvandeWeg** [comment]
While I agree @sammachin, let's get the first iterations done in this issue. Feel free to update the issue and work on this.

**Comment by sammachin** [comment]
Closing this as we now have epics & stories for our MVP of Edge in #446 #447
