### ISSUE TITLE
Secure Environment Variables

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#354]
### Description

As an owner, I'd like certain details hidden for others that have read access to my project. This includes:
1. API Secret
2. Global config nodes
3. ???

FlowForge should offer the ability to inject them from outside Node-RED, which we have the start of support for with environment variables. Cloaking of them would be a requirement.

**Comment by hardillb** [comment]
Node-RED's default handling should already provide most (if not al of this).

As long as the node in question is flagging the value as a credential it is never returned to the editor after entry.

What we could offer is the ability to inject them from outside Node-RED (from the FlowForge Platform), which we have the start of support for with environment variables and I know Nick was looking at being able to cloak some of these iirc

**Comment by ZJvandeWeg** [comment]
> What we could offer is the ability to inject them from outside Node-RED (from the FlowForge Platform), which we have the start of support for with environment variables and I know Nick was looking at being able to cloak some of these iirc

That's what I'm after indeed! Will use your eloquent words in the description as if they were mine.

**Comment by knolleary** [comment]
This will be covered, in part, by #225 

The main additional factor is to consider how we properly store anything declare a secret.

**Comment by MarianRaphael** [comment]
See also: https://github.com/flowforge/flowforge/issues/2289

**Comment by ZJvandeWeg** [comment]
Closing as duplicate of #2289

**Comment by knolleary** [comment]
I believe there is an aspect of this that is not covered by #2289.

#2289 is about a Team Owner preventing others in the team from seeing values - that certainly solves the customer requirement related to that issue. However, the Team Owner still has access to the values.

We ought to have the ability to store values in a way that cannot be returned to the UI for *any* user. This is a pretty standard capability for all platforms that provide env vars.
