### ISSUE TITLE
Admin can modify team members

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#355]
### Description

**As an admin**

**I want to: be able to change the role of and remove a team member**

**So that I can manage teams and users**

### Acceptance Criteria

- [ ] Admin user has the dropdown for change role & remove on team members page

**Comment by joepavitt** [comment]
@sammachin is this not already in?

<img width="852" alt="Screenshot 2022-04-13 at 08 53 06" src="https://user-images.githubusercontent.com/99246719/163127573-e594725a-3f43-4afc-9e4e-d7dcd462cfbf.png">

**Comment by hardillb** [comment]
But if the admin can't see the team (always redirected to the billing page https://github.com/flowforge/flowforge/issues/466) they can't get to that page to remove the user...

**Comment by joepavitt** [comment]
Okay, but that would mean this particular story (to add this functionality) isn't required, it's a requirement instead, to fix #466

**Comment by hardillb** [comment]
We can't verify this story until #466 is resolved

**Comment by sammachin** [comment]
Have just verified this on an 0.3.0 instance without billing enabled (so 466 isn't a blocker)

Once an admin has been added/invited to a team they can modify other members even if they are not an owner, BUT they have to be a member of the team.

If they are not a member of the team they can only view the members they cannot modify them, so this story is valid in that an admin should be able to modify members of a team even if they are not a member of that team.
![image](https://user-images.githubusercontent.com/187645/163157680-49355b02-6f5d-4b71-bf90-389c49ac77c9.png)

**Comment by sammachin** [comment]
If we can resolve #342 then this story becomes less of an issue because then the admin can first make themselves a member of the team to then modify the members

**Comment by joepavitt** [comment]
Your statement is contradictory:

1. Admin must be a member of a team in order to modify the team (but doesn't have to be an owner)
> Once an admin has been added/invited to a team they can modify other members even if they are not an owner, BUT they have to be a member of the team.

2. Admin can modify the team members, even if they are not a member of the team.
> so this story is valid in that an admin should be able to modify members of a team even if they are not a member of that team.

**Comment by joepavitt** [comment]
I also don't like how confusing these permissions are. Either an admin can do everything, or they can't, there shouldn't be if's/but's about it.

**Comment by joepavitt** [comment]
or are you saying that (1) is how things are now, but they should in fact be like (2)?

**Comment by sammachin** [comment]
Yes 1 is the current state
2 is the state desired by this story.

1 would be acceptable if #342 was resolved because then and admin can become a member of the team without an existing owner inviting them.

**Comment by joepavitt** [comment]
Fundamentally, all of these issues boil down to the fact that we haven't set the correct permissions for an Admin user.

**Comment by sammachin** [comment]
The overall goal of this is for an admin to be able to remove a user from the system without that user needing to do anything,  which is the story in https://github.com/flowforge/flowforge/issues/338 
That sets a requirement that in order to delete an owner they must not be the owner of any teams, so the admin needs to be able to modify the teams that the user is an owner of to remove them before they can be deleted

**Comment by sammachin** [comment]
can rollover to 0.5
