### ISSUE TITLE
Can't navigate away from "Admin > Teams"

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#359]
### Current Behavior

When clicking on the "Teams" tab in the Admin panel, navigation then breaks, until I refresh the page. No errors in console.

### Expected Behavior

I should be able to continue to navigate to any of the other tabs or pages, even when viewing the "Teams" tab.

### Steps To Reproduce

"Admin Settings" > "Teams" - then behaviour occurs 100% of the time for me. Do also notice that no teams are listed.

### Environment

- FlowForge version: 0.2.0
- Node.js version: 16.3.2
- Platform/OS: Mac
- Browser: Chrome

**Comment by joepavitt** [comment]
@hardillb @knolleary found this is due to a change I made on the frontend with the `route` params. I changed `id` to `team_slug` and it seems as though we have the `link` attribute for a team stored in the DB which still looks like this:

```
link:
    name: "Team"
    params:
        id: "billing-test-4"
```

We'll need that changed to:

```
    name: "Team"
    params:
        team_slug: "billing-test-4"
```

Not sure I'm a fan of having UI-reliant params in the DB, but I get why we've done it.

**Comment by knolleary** [comment]
The `link` property is not in the database. It is a property that gets added in the front-end within the api shims.

There are two places where it is incorrect:

1. `api/teams.js` - this is the shim that is used to get all teams on the platform - only usable by admin - https://github.com/flowforge/flowforge/blob/main/frontend/src/api/teams.js#L8
2. `api/team.js` - this is used to get the teams the current logged-in user has access to - https://github.com/flowforge/flowforge/blob/main/frontend/src/api/team.js#L11

Note there is another bug in that second one - it uses `slugify(r.name)` to generate the slug, but it should be using `r.slug` directly.
