### ISSUE TITLE
Applying linting rules to Vue code

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#362]
### Description

We do not currently lint the vue code... we should.

We have the rules in place, they just need enabling and the build updated to check the linting.

Rather than do it bit by bit, this needs to be a one-time, rip-off-the-plaster effort to update all existing code to meet the linting rules, as we did in the node.js side of things.

This ensures future PRs do not become a mix of 1 line fix and 100 lines of linting tweaks.

**Comment by knolleary** [comment]
The code has been linted via #386 

Last remaining task (I think... apols if the PR did it) is to ensure the build task runs the linting check against the vue code.

**Comment by knolleary** [comment]
I think its updating these two lines to include the vue files - https://github.com/flowforge/flowforge/blob/main/package.json#L12-L13

**Comment by joepavitt** [comment]
New PR open with respective updates: https://github.com/flowforge/flowforge/pull/396
