### ISSUE TITLE
Agree T&Cs on Signup

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#363]
### Description

**As a:** user

**I want to:** view and agree to terms and conditions when signing up

**So that:** I fully understand the contract I am entering into.

### Acceptance Criteria

- [ ] Signup page at `/account/create` has a link to view T&Cs 
- [ ] Signup page at `/account/create` has a checkbox that the user agrees to T&Cs (signup is blocked until they do so)
- [ ] Admin can toggle the requirement for T&Cs in config file 
- [ ] Admin can set the URL for the think to T&Cs in config file
- ...

**Comment by joepavitt** [comment]
Do we need any equivalent workflow for the admin setup process?

**Comment by knolleary** [comment]
No. This is only for end users signing up to an already running instance (eg flowforge cloud).

There is no equivalent for admin's going through the initial setup. If they are running a licensed version, they would have had to agreed to T&Cs as part of purchasing the license with us directly.
