### ISSUE TITLE
Allow user to suspend project so it doesnt consume resources

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#377]
### Epic

#787

### Description

**As a:** Owner

**I want to:** have the ability to stop a container for a project

**So that:** I am not charged for consuming resources 

### Which customers would this be availble to

- [X] All Users, (CE)
- [ ] Specific Project Types (EE)
- [ ] Specific Team Tiers (EE)
- [ ] Other (See comments)

### Acceptance Criteria

- [ ] Container is stopped/removed
- [ ] Project is removed from billing

**Comment by sammachin** [comment]
This needs some discussion about engineering design and UX, specific questions are:

Should this be a separate state from the current stopped project which stops Node-RED from handling any requests but doesn't remove the container?
Is that a useful state to keep for example if you need to just pause whatever your flow is doing.

Should that be renamed to pause?

What do we call this, halted?, terminated?

What is the billing experience, eg if a user stops and starts containers in a short timeframe do we refund and then charge again when its started?

Do we have any kind of charge/limit on the number of projects without a running container that a user might have?

**Comment by sammachin** [comment]
Also how does this experience relate and impact  localfs where there is no container as such, does the UI need to hide the option in localfs mode

**Comment by knolleary** [comment]
The work done in #392 and #437 has introduced the 'suspended' state to a Project - a necessary state when considering how stacks get changed.

Whilst developing and testing #437 I had added a 'suspend' option in the project action menu to help me test different state combinations.

I have *removed* the menu option from the final PR to not confuse matters. For future reference, this is the comit that did hid it - so you can see what front-end api is there to use in the future - https://github.com/flowforge/flowforge/pull/437/commits/cf3606ad4ce85cdd7b431f7c388d7cb2de2d27c6

But the main take-away is that the questions around what a suspended project means have been largely addressed through the lifecycle review work.

The remain piece of dev work is on how to expose it properly in the UI.

Whilst I had put it in the action menu (the drop-down menu in the RH side of the project screen) as a super convenient place whilst I was testing, it is more suited for the 'Danger' settings panel.

The text that goes on screen also needs to reference the impact on billing - but only if billing is enabled.

As such, I am going to add a small sizing for this item to reflect the relatively small piece of UI work needed.

**Comment by sammachin** [comment]
TODO Look at billing experience of stopping & starting with credits

**Comment by hardillb** [comment]
OK, basic UI done for suspending, might have a chat with @joepavitt tomorrow about if we want to change things for restarting.

The billing is currently already handled by the existing container code, so need to decide if we want to handle this differently to a stack upgrade (which can cause billing change)

**Comment by sammachin** [comment]
Stack upgrades shouldn't result in a billling change, only changing the project type (which isn't currently supported)
There's also a related task to remove the stop/start from actions (leave restart) https://github.com/flowforge/flowforge/issues/836

**Comment by hardillb** [comment]
We need to keep start (unless we also move that to Settings/Danger section as well)

**Comment by sammachin** [comment]
So start will start the container and node-red now?
We may need to change the labels depending on the UX converstaion with @joepavitt tmw
