### ISSUE TITLE
Introduce ProjectType

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#380]
### Epic

#224

**Note** This was originally a story around defining billing as part of the stack. This has evolved into a broader concept of Project Type and the description has been updated to match.

### Description

**As an:** Administrator

**I want to:** Define different types of Project

**So that:** I can have projects with different memory/cpu allocations and be able to charge users different amounts based on the choice of type/stack.

---

See https://github.com/flowforge/flowforge/issues/380#issuecomment-1106426912 for details

**Comment by sammachin** [comment]
The stack should be configured with the Product ID from the billing platform rather than a direct $ amount

**Comment by sammachin** [comment]
We also need to consider the path where a user changes a projects stack, if that new stack has a different price point.

**Comment by knolleary** [comment]
**The more I work through the design on this, the more I am convinced this is the wrong approach.**

I think there are quite a few changes needed around the Stack UX to do this properly. Our currently approach is very functional and needs a better user experience - especially when pricing is involved.

There is a complication where the stack provides both the pricing *and* the node-red version.

With our current approach of 'one price for everything' adding a stack for Node-RED 3.0-beta is simple - the user just picks the right stack from the list. But once you also have the pricing dimension we end up needing a stack for each combination of price-point and NR version we want to offer. That will make the list grow and grow and make the UX of picking the right stack harder and error prone.

Here's my alternative approach:

### Introduce `ProjectType`

Each Project will have a `ProjectType`. This will be an administrator-defined object that provides:
 - name (`Hobby`, `Standard`)
 - description
 - billing details (eg stripe product id)
 - billing description - text to show the user eg (`$15/month`)

### Associate Stacks to ProjectType

When creating a Stack, it is assigned to a ProjectType.

This means a Project can only pick from the Stacks associated with its ProjectType

One Stack can be marked as the default stack for a ProjectType.

### Changing stacks

This is unchanged from the current behaviour - other than the choice is limited to the stacks available for the ProjectType. But this can simplify the billing workflow as it doesn't need to add/remove itself from the subscription (as the ProjectType isn't changing)

### Changing ProjectType

A project can change its ProjectType. With billing enabled, this will update the subscription as needed.


### Initial Project Creation

Here's a mock-up of the create project screen (in figma).

<img width="867" alt="image" src="https://user-images.githubusercontent.com/51083/164703595-9ee7c455-58eb-4e8a-987a-fd614ce297db.png">

The boxes show the available ProjectTypes.

The details inside come from the ProjectType's default stack - we will need a discrete way for them to pick an alternative stack (to support the NR 3.0-beta for example). I say discrete as this shouldn't be main-path for most users.

**Comment by sammachin** [comment]
This seems good and provides flexibility

`The details inside come from the ProjectType's default stack - we will need a discrete way for them to pick an alternative stack (to support the NR 3.0-beta for example). I say discrete as this shouldn't be main-path for most users.`
On this I think it would be acceptable for now that a new project is created on the default stack and then the user can switch later? given that its likely to be an edge scenario anyway.

It would be useful to also be able to associate a template with a project type, particularly where we may want to impose additional limitations on things like which nodes can be used on a certain tier

**Comment by knolleary** [comment]
> It would be useful to also be able to associate a template with a project type, particularly where we may want to impose additional limitations on things like which nodes can be used on a certain tier

Yes - there are a few dimensions for scoping templates to consider when we come to it - global, by-projectType, by-team.

**Comment by sammachin** [comment]
> ### Changing stacks
> This is unchanged from the current behaviour - other than the choice is limited to the stacks available for the ProjectType. But this can simplify the billing workflow as it doesn't need to add/remove itself from the subscription (as the ProjectType isn't changing)

It seems like this part wasn't implemented? Looking at the code in https://github.com/flowforge/flowforge/blob/main/forge/containers/wrapper.js we still make the call to update billing whenever the container is stopped or started, eg for a stack change.
