### ISSUE TITLE
Installed nodes removed after FF Cloud upgrade

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#385]
### Current Behavior

<img width="503" alt="Screenshot 2022-03-18 at 10 34 38" src="https://user-images.githubusercontent.com/99246719/158988051-e6c0e6d9-db60-4af8-8709-9e12de8bd784.png">

After the recent FlowForge upgrade, our Feedback bot stopped working. Upon investigation, the additional nodes (node-red-contrib-slack) that I had installed had been removed. I can only assume this is something to do with the platform upgrade?

### Expected Behavior

The flows should have continued to operate seamlessly, even when the platform has been upgraded.

### Steps To Reproduce

May be difficult to reproduce. I had installed the Slack nodes via the "Manage Palette" option in Node-RED. Since the upgrade, the nodes were removed.

### Environment

- FlowForge version: 0.2.0 -> 0.3.0
- Node.js version:
- npm version:
- Platform/OS: Mac OS (Although using FF Cloud)
- Browser: Chrome

**Comment by hardillb** [comment]
This is expected, and is problem from the outage on Tues/Weds. It is also being tracked in https://github.com/flowforge/flowforge-nr-launcher/issues/24

**Comment by sammachin** [comment]
The email that was sent to all users when service was restored also mentioned that custom nodes would need to be re-installed.
