### ISSUE TITLE
User Lifecycle Review

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#393]
### Description

We need to review the overall lifecycle of a User to cover - invite, signup, password reset, suspension, deletion, changing email, etc.

This directly feeds into the following stories:

 - #338
 - #222 
 - #233 
 - #234 

Goal is to produce a state machine view to help us understand what states exist, what transitions are needed and what role Admin plays in it.

**Comment by sammachin** [comment]
See Figma architecture folder for style

**Comment by sammachin** [comment]
Figma https://www.figma.com/file/OcFn11K0g8iM1mJdLJhLnj/User-Lifecycle?node-id=0%3A1

![Image](https://user-images.githubusercontent.com/187645/180726113-7b6062fa-b4cb-4803-b88f-1b8bf08defc8.png)

**Comment by sammachin** [comment]
Functionality Table
|                      | Unverified | PW Expired | Active | PW Reset | Suspended | Deleted |
|----------------------|------------|------------|--------|----------|-----------|---------|
| Forge Login          |      Y     |     Y      |   Y    |    Y     |     Y     |    N    |
| NR Login             |      N     |     N      |   Y    |    Y     |     N     |    N    |
| Change Username      |      N     |     N      |   Y    |    Y     |     N     |    N    |
| Change Name          |      N     |     N      |   Y    |    Y     |     N     |    N    |
| Change Email         |      N     |     N      |   Y    |    Y     |     N     |    N    |
| Change Password      |      N     |     Y      |   Y    |    ?     |     N     |    N    |
| Create Team          |      N     |     N      |   Y    |    Y     |     N     |    N    |
| Manage Projects      |      N     |     N      |   Y    |    Y     |     N     |    N    |
| Manage Team          |      N     |     N      |   Y    |    Y     |     N     |    N    |
| Manage Devices       |      N     |     N      |   Y    |    Y     |     N     |    N    |
| Admin Settings       |      N     |     N      |   Y    |    Y     |     N     |    N    |
