### ISSUE TITLE
Disable Welcome Tour in Template

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#404]
### Epic

#141

### Description

**As a:** user

**I want to:** set the welcome tour in my templates

**So that:** I don't have to see it on every new instance
### Which customers would this be availble to

- [X] All Users, (CE)
- [ ] Specific Project Types (EE)
- [ ] Specific Team Tiers (EE)
- [ ] Other (See comments)

### Acceptance Criteria

- [ ] Welcome Tour true/false toggle/radio button in template editor

**Comment by knolleary** [comment]
Closing as #996 and https://github.com/flowforge/flowforge-nr-launcher/pull/66 are both merged

**Comment by hardillb** [comment]
Tested on staging (with Test template)
