### ISSUE TITLE
Dev installation requires NPM install command for all repos

### ISSUE THREAD

**Issue by PLCMercenary** [flowforge/flowforge#420]
npm run dev:local on a fresh machine wont start any NR instances failing with "unable to load settings" - traceback shows missing modules. 

running npm install from each of the flowforge-nr-Audit-logger, flowforge-nr-auth, and flowforge-nr-storage repos got it working. 

**steps to reproduce-** 
1. on a clean machine or new VM follow the installation instructions from [Contribute Docs](https://github.com/flowforge/flowforge/blob/main/docs/contribute/README.md). Observe flowforge is unable to start any projects. 
2. cd to `../flowforge-nr-launcher/node_modules/@flowforge` 
3. from each of the symlinked directories `npm install`
4. observe flowforge can create and connect to nodered instances

**Comment by knolleary** [comment]
Solved via [`flowforge-dev-env`](https://github.com/flowforge/flowforge-dev-env)
