### ISSUE TITLE
Audit Log presentation

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#428]
### Description

The presentation of the project/team audit/activity logs is inconsistent.

Some log events get custom display with icons, others get their raw info dumped. This happens because the AuditLog frontend code only knows about some event types and how to render them. Anything that isn't known gets dumped in as-is.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/51083/160835368-a5ac9a60-d8b9-45ad-a53b-5fa739a622b9.png">

We need a better strategy for how we *implement* the presentation so that when new event types are adding in the runtime, there is a clear process/method for updating the frontend to match.

Questions to consider:

1. should it be a requirement that if you add a new event log entry type to the runtime, that you also add the code to render it in the frontend?
2. how could the rendering of 'unknown' event types be improved?

### Progress:

- [x] https://github.com/flowforge/flowforge/issues/1340
- [x] https://github.com/flowforge/flowforge/issues/1341
- [x] https://github.com/flowforge/flowforge/issues/1352
- [x] https://github.com/flowforge/flowforge/issues/1353

### Epic/Story

#1166

**Comment by joepavitt** [comment]
<img width="1045" alt="Screenshot 2022-07-08 at 09 22 41" src="https://user-images.githubusercontent.com/99246719/177961559-a6d16a3f-88a5-4263-917b-c40d1fe61743.png">

iteration of audit log design.

**Comment by joepavitt** [comment]
@knolleary 
> should it be a requirement that if you add a new event log entry type to the runtime, that you also add the code to render it in the frontend?
- I would naturally argue this should be the case. My plan with the above design is to "group" events, e.g. linked to snapshots, node-red, settings, users. As long as new events align to one of these, it's fairly trivial. The main "customisation" as such is the natural language messaging associated to an event, e.g. `"Project Name" created with project id: 123445456`

> how could the rendering of 'unknown' event types be improved?
- Is there such a thing as an "unknown" type if we're controlling/defining all of the audit log events?

**Comment by knolleary** [comment]
> Is there such a thing as an "unknown" type if we're controlling/defining all of the audit log events?

If we are successful in keeping everything in sync, then there shouldn't be an unknown event in the log. That is absolutely Plan A.

But just in case, it would be prudent to be able to display an event we don't otherwise recognise (maybe its a new Node-RED generated event in a beta version we've added to the platform but not yet deployed an update to know about it...)

**Comment by joepavitt** [comment]
@knolleary are there instances of unknown events that wouldn't originate in Node-Red? At the moment, design has a generic "Node-RED" type for events-styling anyway.

**Comment by joepavitt** [comment]
Happy with the UX designs above, but just need to refine the list of types. @knolleary iirc we have a Google Sheet somewhere, would be good to formalise here before dev starts.

**Comment by joepavitt** [comment]
<google-sheets-html-origin><style type="text/css"></style>

Event ID | Source ( ff / nr ) | Scope | Identifies User | Event Body
-- | -- | -- | -- | --
project.start.failed | ff | project | no | { error }
user.invite.accept | ff | team | yes |  
user.invite.reject | ff | team | yes |  
team.created | ff | team | yes |  
user.added | ff | team | yes | { role }
billing.session.completed | ff | team | no | { session }
billing.session.created | ff | team | yes | { session }
project.created | ff | project | yes |  
project.duplicated | ff | team | yes | { sourceId, sourceName, newId, newName }
project.created | ff | team | yes | { id, name }
project.deleted | ff | project | yes |  
project.deleted | ff | team | yes |  
project.suspended | ff | project | yes |  
project.stack.changed | ff | project | yes | { stack, name }
project.started | ff | project | yes |  
project.suspended | ff | project | yes |  
project.settings.updated | ff | project | yes |  
project.stopped | ff | project | yes |  
project.restarted | ff | project | yes |  
billing.subscription.deleted | ff | team | yes | { subscription }
team.deleted | ff | team | yes |  
team.settings.nameChanged | ff | team | yes | { oldName, newName }
team.settings.slugChanged | ff | team | yes | { oldSlug, newSlug }
user.invited | ff | team | yes | { users }
user.uninvited | ff | team | yes | { users }
user.removed | ff | team | yes | { user }
user.roleChanged | ff | team | yes | { user, role }
project.snapshot.created | ff | project | yes | { id }
project.snapshot.deleted | ff | project | yes | { id }
project.snapshot.deviceTarget | ff | project | yes | { id }
team.device.created | ff | team | yes | { id }
team.device.deleted | ff | team | yes | { id }
team.device.unassigned | ff | team | yes | { id, project }
project.device.unassigned | ff | project | yes | { id }
team.device.assigned | ff | team | yes | { id }
project.device.assigned | ff | project | yes | { id, project }
team.device.updated | ff | team | yes | { id }

**Comment by joepavitt** [comment]
Icon Grouping Proposal, all icons coming from heroicons: https://heroicons.com/

Except for the "nodes" icon which is our own custom icon.

Icon | Group | Description
-- | -- | -- 
solid > user | Single User | Any actions linked to a single user, e.g. login/logout
solid > users | Team/Collaboration | Invitations or team member changes
outline > cog | Settings | Scope at either the team or project level, and covers general settings being updated.
custom > nodes | Node-RED | Any events logged to the audit from node-red are captured by this icon
outline > clock | Snapshots | Whenever snapshots are created, deleted, edited, this icon/group is used.
outline > currency-dollar | billing | Events linked to billing changes
outline > chip | devices | Addition, deletion or editing of devices.

**Comment by Steve-Mcl** [comment]
@joepavitt in #1084, a new Scope named "platform" is being introduced to capture admin settings changes.

Could you please review the comments and questions in...
* https://github.com/flowforge/flowforge/pull/1084#issuecomment-1280522945
* https://github.com/flowforge/flowforge/pull/1084#issuecomment-1280527541

**Comment by joepavitt** [comment]
You've linked the same issue twice - intentional?

**Comment by Steve-Mcl** [comment]
@joepavitt FYI, I updated the GSheet list with all the admin/user scope audit logs entries that were added in [#1048](https://github.com/flowforge/flowforge/pull/1084)

**Comment by joepavitt** [comment]
Will ensure UX alignment across the Project/Team logs and Platform Logs (#517). This issue will be constrained to the development of the new component only, which will be used in the layout shown above.

After this, layout changes will be introduced across all views as part of #517 to include filtering.

**Comment by joepavitt** [comment]
All child tasks completed for Audit Log revamp scoped in this issue

**Comment by hardillb** [comment]
Verified on staging
