### ISSUE TITLE
Devices

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#446]
### Description

A **Device** is a new concept within the FlowForge platform.
It is created by a team owner and owned by that team.
Once created the owner will be given  config (address and credentials) that can be entered into the `Edge Agent` such that it can register with the platform as that device.

- Devices can be assigned to a project or unassigned
- A device cannot be assigned to more than one project at a time 
- A device can move between assigned and unassigned in its lifecycle
- A device must be unassigned before it can be deleted.

The Device has the following properties (not exhaustive)
- ID (unique internal system ID)
- Name
- Description
- Credentials
- Status (online/offline)
- Last seen timestamp (or null)
- IP address (src IP of the edge agent)

**Comment by knolleary** [comment]
The scope of this item is to create the Device model, controllers and runtime API for the basic CRUD operations.

This is a prerequisite of the Device related stories around what a user can then do with devices in the frontend.

**Comment by knolleary** [comment]
# Runtime API

This will require the basic CRUD api end points for the Device object. This should follow our standard API pattern


 - `GET /api/v1/devices/:id` - return details of an individual device
 - `POST /api/v1/devices` - create new device. This will return the credentials object (format TBD)
 - `PUT /api/v1/devices/:id` - update the device details
 - `DELETE /api/v1/devices/:id` - delete a device
 - `POST /api/v1/devices/:id/actions/XYZ` - device actions (`XYZ` == `start` `stop` `restart` ... specifics tbd.
 - `GET /api/v1/team/:teamId/devices` - return a paginated list of devices owned by a team

**Comment by sammachin** [comment]
The initial work for devices will be hidden behind a feature flag so that we can do some enabling work in one release and allow users to to play with it locally but not turn it on for FlowForge Cloud until there is something fully usable with the edge agent as well

**Comment by knolleary** [comment]
As this is the Epic for the Devices work, we should keep it open to track the individual stories.

**Comment by knolleary** [comment]
This has become a catch-all Epic for Devices. As I mention above, we could keep this open to tag stories related to Devices - to give us an easy way to find them.

On balance, it would be better to use GH labels for that - and having a longstanding open Epic that never finishes, isn't ideal.

So I propose we close this epic and move forward.

**Comment by knolleary** [comment]
As described - closing this epic. We will use `device` label to identify items
