### ISSUE TITLE
User can install an edge agent on a device

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#449]
### Epic

#447

### Description

**As a:** User

**I want to:** Install an Edge agent on my device

**So that:** It can register with the FlowForge Platform

### Acceptance Criteria

- [ ] Edge Agent can be installed with one line command on a Raspberry Pi running default RasPi OS
- [ ] User can supply address and credentials of the FF platform for the device to register with

**Comment by hardillb** [comment]
Adding details to the projects README.md explaining how to install.

**Comment by knolleary** [comment]
The agent repo README has details on how to install. It is quite manually for this release - we do not have an install script or other packaging solution (rpm/deb for most common platforms). 

This is sufficient for the first iteration of the agent.
