### ISSUE TITLE
User can create device in their Team

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#450]
### Epic

#446

### Description

**As an:** Owner

**I want to:** Create a new device in my Team

**So that:** I can configure an Edge Agent

### Acceptance Criteria

- [ ] Devices view within Team
- [ ] User is given credentials for Device to enter into Agent
- ...

**Comment by knolleary** [comment]
### Frontend

 - A new 'Devices' section to the Team view is added
 - 'Add Device' button opens dialog (or dedicated page like create project/team...) to prompt for device information.
    - user is given (copy/paste... download file?) a set of API tokens to use (specific details TBD) (this is the only time the user can access those tokens)
 - The Device is then listed in the Devices table

### API

This will require the basic CRUD api end points for the Device object (#446).
