### ISSUE TITLE
Be able to update T&Cs and prompt users to accept update

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#451]
### Description

**As a:** Admin

**I want to:** be able to update the T&Cs of the platform and require users to accept the new terms

**So that:** I know who has/hasn't accepted the latest terms

---

Follow on to #363 and #443 which allows the admin to require T&C acceptance on sign up.

High level implementation thoughts

 - [ ] sign-up api should require a flag to confirm T&C acceptance rather than just a UI block on submitting the form
 - [ ] update User model to record a date of when they accepted T&Cs
 - [ ] provide option to admin to trigger update of t&c
 - [ ] when user logs in, compare the t&c date with the user-accepted date. If t&cs newer - trigger a reconfirmation prompt.

**Comment by Steve-Mcl** [comment]
### Implementation Question RE: _"provide option to admin to trigger update of t&c"_


Is there any preference for UI?...

* An "terms updated" button? (server will update DB with server DT)  **My default choice**
* A free entry date-time field? (Admin can set any date from today)
* Change of T+C URL + settings save action? (saving a change to URL would update the DT on DB with server DT)
* Something else?


This will require storage of a T+C Datetime...
* Is this a row in an existing table? (PlatformSettings) **My default choice**
* Is this a new table?
  * Extensible (row of key+value like the ProjectSettings but for "TermsAndConditions")
  * Dedicated "TermsAndConditions" table (e.g. "id", "TermsAndConditions", "created
* A new field in and existing table? 
* Something else?

**Comment by Steve-Mcl** [comment]
### Workflow proposal...

#### User Login, Terms and Conditions check

```mermaid
sequenceDiagram

title User Login, Terms and Conditions check

participant User
participant Ui
participant Runtime
participant DB

User->>Ui: Clicks Login
Ui->>Runtime: POST /account/login
Runtime->>DB: Check T+C date
alt T+C Expired
DB->>Runtime: T+C required
Runtime->>Ui: 4xx: New T+Cs (403 Forbidden? 428 Precondition Required?) 
Ui->>User: Show T+Cs dialog
User->>Ui: Checks "Accept" and clicks "Continue"
Ui->>Runtime: POST /account/eula
Runtime->>Ui: 200: Logged in
else T+C OK
DB->>Runtime: T+C OK
Runtime->>Ui: 200: Logged in
end
Ui->>User: Redirect to overview

```

**Comment by Steve-Mcl** [comment]
### Workflow Proposal...

#### User Signup, Terms and Conditions check

```mermaid
sequenceDiagram
title User Signup, Terms and Conditions check

participant User
participant Ui
participant Runtime
participant DB

User->>Ui: Accesses a protected URL
Ui->>Runtime: GET url
Runtime->>DB: Is T+C enabled?
DB->>Runtime: T+C required
Runtime->>Ui: Redirect
Ui->>User: Show Signup + T+C checkbox
User->>Ui: Clicks submit
Ui->>Runtime: POST /account/register
Runtime->>DB: Is T+C enabled AND did user accept?

alt T+C not checked
DB->>Runtime: T+Cs required, not accepted
Runtime->>Ui: 4xx: (403 Forbidden? 428 Precondition Required?) 
Ui->>User: Visual Feedback - T+C acceptance required
User->>Ui: Checks "Accept" and clicks "Signup"
Ui->>Runtime: POST /account/register
Runtime->>DB: Create user, update T+C date
DB->>Runtime: Update successful
Runtime->>Ui: 200: Account Created
else T+C checked
DB->>Runtime: T+Cs required & accepted
Runtime->>DB: Create user, update T+C date
DB->>Runtime: Update successful
Runtime->>Ui: 200: Account Created
end
Ui->>User: Redirect to overview
```

**Comment by sammachin** [comment]
> ### Implementation Question RE: _"provide option to admin to trigger update of t&c"_

Yes a button to say "Terms Updated" would be fine, This should require a confirmation as its potentially a significant impact if clicked incorrectly.
It should also show in the same view the last updated date/time 

>Implementation Question RE: "when user logs in, compare the t&c date with the user-accepted date. If t&cs newer - trigger a reconfirmation prompt"
Yes a similar UI to the signup screen is fine with "Terms and Conditions have changed on {{date}} and the check box to indicate acceptance and a submit button.

**Comment by knolleary** [comment]
> This will require storage of a T+C Datetime...
> Is this a row in an existing table? (PlatformSettings) My default choice

It is a new setting defined in `forge/settings/defaults.js` to sit alongside `user:tcs-url` - for example `user:tcs-date`. You do not interact with the PlatformSettings table directly.

The admin settings view currently allows the user to provide the URL. We cannot rely on just recording when the url changes because the terms could be updated but keep the same url. Having a button next to the url field that says 'require users to reaccept terms' that posts to the existing admin settings endpoint, but just to set `user:tcs-date` to the current date.


At this stage, there is no requirement to block all API access until they have accepted the new terms. We simply need a mechanism to prompt the user at the right time - ie when they login or load the page.

To minimise the changes needed, I suggest a single approach that covers both login flow, and what happens when an existing session is used to load the page.

1. the login flow is unchanged - if the username/password is correct, they get a valid login session. No need for new 4xx responses.
2. the `/api/v1/user` endpoint is updated to include a flag if t&cs need accepting.
3. if the app sees that flag, it can show the prompt dialog - done at the top level of the app as we do for email verification etc.
4. accepting the new t&cs can be done via a PUT to `/api/v1/user/accept_tcs` (or something similar)

**Comment by Steve-Mcl** [comment]
@knolleary 

Questions and Workflows now updated to match PR  (& to keep good history)
