### ISSUE TITLE
User can see list of edge devices in their Team

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#457]
### Epic

#446

### Description

**As a:** owner

**I want to:** see a list of my devices on my team page 

**So that:** I can see the status of my devices

### Acceptance Criteria

- [ ] New Devices Item in team page menu bar
- [ ] Table listing Devices 
- [ ] Device connection state in table (online, offline, never seen)
- [ ] Project that device is assigned to (or unassigned)
- ...

**Comment by knolleary** [comment]
Runtime API work in #446 is a prerequisite to this story
