### ISSUE TITLE
User can assign a device to a project

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#459]
### Epic

#446

### Description

**As a:** Owner

**I want to:** assign (and unassign) a device to a project

**So that:** I can push the project to my device

### Acceptance Criteria

- [ ] Devices Tab in Project view
- [ ] List of assigned devices
- [ ] Method to select an unassigned device and assign to project
- [ ] Method to unassign a device from a project
- ...

**Comment by knolleary** [comment]
Runtime API work in https://github.com/flowforge/flowforge/issues/446 is a prerequisite to this story
