### ISSUE TITLE
User list not refreshing after changing user details

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#463]
### Current Behavior

As an admin you can expire user passwords. When you do, the user list page is not updated and doesn't display the users password as expired. After a refresh of the page, the field does read "true".

### Expected Behavior

List is refreshed automatically.

### Steps To Reproduce

Expire a password in the admin interface.

### Environment

- FlowForge version: 0.3

**Comment by sammachin** [comment]
Refreshing of all views to be revistied after re-brand of app.

**Comment by sammachin** [comment]
issue still exists in 0.8 after the table re-design
@joepavitt is there a quick fix to refresh the table after a model closes?

**Comment by knolleary** [comment]
Yes - its s simple call to refresh the data after the dialog closes - we do that in other views.
