### ISSUE TITLE
Admin viewing team is prompted to setup billing

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#466]
### Current Behavior

When I am logged in as an admin user and I goto a team that I am not a member of (via /admin/teams) I am shown the setup billing prompt even if that team already has already setup billing

### Expected Behavior

I should be able to view the team details such as projects and audit log

### Steps To Reproduce

Login as admin user to a system with billing enabled
Goto a team that has configured billing but the admin user is NOT a member of

### Environment

- FlowForge version: 0.3.5
- Node.js version: 16 
- npm version: 8 
- Platform/OS: Mac
- Browser: Chrome

**Comment by joepavitt** [comment]
If the admin member is not a member of that team, then surely they shouldn't be able to see the team?

**Comment by hardillb** [comment]
Admin should be able to see all

**Comment by joepavitt** [comment]
I've created #478 - it cleans when the billing/permission checks are done in the frontend, however the `http://localhost:3000/ee/billing/teams/<team_id>` call is returning a 404 - which the frontend interprets as "billing not enabled".

**Comment by joepavitt** [comment]
@hardillb I'm guessing that this is coming back as `false` for an admin?

https://github.com/flowforge/flowforge/blob/f5b8b7ec44f047cf7cd2b8d43b2579d1861343ba/forge/ee/routes/billing/index.js#L138

**Comment by hardillb** [comment]
It shouldn't, needsPermission is defined here:

https://github.com/flowforge/flowforge/blob/f5b8b7ec44f047cf7cd2b8d43b2579d1861343ba/forge/routes/auth/permissions.js#L37-L47

And Admin should be able to do all by the looks of it.

**Comment by hardillb** [comment]
Also if it fails the permission check it 403's not 404's

**Comment by hardillb** [comment]
It's this section that is causing the problem

https://github.com/flowforge/flowforge/blob/f5b8b7ec44f047cf7cd2b8d43b2579d1861343ba/forge/ee/routes/billing/index.js#L141-L146

Need to think what to do with an admin user in this case
