### ISSUE TITLE
Audit log entry for login event captures wrong ip address

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#507]
### Current Behavior

Logged into a project on ff cloud. Noticed the audit log entry contains a 192.168.... address which is not very helpful

<img width="320" alt="image" src="https://user-images.githubusercontent.com/51083/164700560-a2844318-531c-4a02-b6be-91c6a2cadd04.png">

### Expected Behavior

The IP address should reflect the user logging in - not some internal ip address.

As Node-RED is providing the log entry content we will need to raise an upstream issue.

### Environment

- FlowForge version: 0.4
- Node-RED: 2.2.2

**Comment by Steve-Mcl** [comment]
@knolleary a direct question for you please (node-red related)

There are 2 approaches and I believe the best chance of success would be to implement both, but partly hidden (disabled by default) in settings js.

1. Enable `app.set('trust proxy', trustProxy)` if `trustProxy` has a value set in `settings.js`
    * `trustProxy: null` null/undefined/missing  ==> no change / same as now NR v2
    * `trustProxy: true` ==> `app.set('trust proxy', true / false)` 
        * // if true, the client’s IP address is understood as the left-most entry in the X-Forwarded-For header.
        * // If false, the app is understood as directly facing the client and the client’s IP address is derived from req.socket.remoteAddress. This is the default setting.
    * `trustProxy: 'loopback' ` ==> `app.set('trust proxy', 'loopback')` // specify a single subnet
    * `trustProxy: 'loopback, 123.123.123.123' ` ==>  `app.set('trust proxy', 'loopback, 123.123.123.123')` // specify a subnet and an address
    * `trustProxy: '' 'loopback, linklocal, uniquelocal'` ==>`app.set('trust proxy', 'loopback, linklocal, uniquelocal')` // specify multiple subnets as CSV
    * `trustProxy: ['loopback', 'linklocal', 'uniquelocal'] ` ==> `app.set('trust proxy', ['loopback', 'linklocal', 'uniquelocal'])` // specify multiple subnets as an array
    * `trustProxy: () => { (ip) => { return ip === '127.0.0.1' }`  ==>  // function - Custom trust implementation.

2. Add [request-ip](https://www.npmjs.com/package/request-ip) as a dependency to node-red 
    * This will replace the current "get client IP" logic in [node-red](https://github.com/node-red/node-red/blob/6fb96fa3c157e6f34e2a99a2fd87c52e2fad0a2d/packages/node_modules/@node-red/util/lib/log.js#L221)) .
    * Reasoning : as a dependency, any improvements to client IP detection will be gained without changes to node-red

Please let me know your thoughts on this approach

**Comment by Steve-Mcl** [comment]
After some testing, I am moving away from adding `trustProxy` setting and using the existing mechanism of `settings.httpServerOptions` . We can do this in FF today e.g...

```
    httpServerOptions: { 
        trustProxy: true
    },
```

or

```
    httpServerOptions: { 
        trustProxy: 'whatever,whatever2'
    },
```

As for `request=ip` package - this is working well as a middleware & gives us the benefit of future enhancements without NR modification.

That leaves the questions...

1. Should the use of `request-ip` package be optional (i.e. behind a setting in settings.js)
   * IMO - no, just use it as is. 
2. For FF what would we use for `trustProxy`

**Comment by hardillb** [comment]
We should just use `trustProxy: true` then we don't have to worry about the IP address of the proxy and use the exisitng `httpServerOptions` in the settings.js  (we would modify the template in the nr-launcher

**Comment by Steve-Mcl** [comment]
Thanks for the reply @hardillb but i am having a proper  "eats shoots and leaves" moment

Can I paraphrase you to make sure I understand?...

_"We should just use `trustProxy: true` via the existing `httpServerOptions` and not bother with the `request-ip` package"_  - Correct?

**Comment by hardillb** [comment]
Yes, There shouldn't be a need for an extra package iirc

**Comment by Steve-Mcl** [comment]
@hardillb ok, thanks for confirming.

I will go with this for now. 

I do think the [minimal client IP detection logic](https://github.com/node-red/node-red/blob/6fb96fa3c157e6f34e2a99a2fd87c52e2fad0a2d/packages/node_modules/@node-red/util/lib/log.js#L221) we have in node-red ATM would benefit from this small package but we will see.

We can always revisit 👍

**Comment by Steve-Mcl** [comment]
PR ready for review: https://github.com/flowforge/flowforge-nr-launcher/pull/45
