### ISSUE TITLE
Link to the install docs from the README

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#510]
### Description

GitHub renders the README very prominently. As such I think we should link to the install guide when people are here through Google/DuckDuckGo, and want to try FlowForge. Not only to develop on it.

**Comment by sammachin** [comment]
Should we just show the main docs readme on the github project page? 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes seems to imply that removing the README from root will then look in /docs
