### ISSUE TITLE
Audit logging of admin events

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#518]
### Description

**As a:** admin

**I want to:** see platform wide events in the audit log in #517 such as:
 - user creation
 - user deletion
 - password resets
 - team creation
 - team deletion

**So that:** I can observe activity across the platform and Identify when users are created

### Acceptance Criteria

- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3
- ...

**Comment by Steve-Mcl** [comment]
@knolleary does the logging Sam suggests warrant a new log section - perhaps named "platform"

**Comment by knolleary** [comment]
yes, that's the way to do it

**Comment by Steve-Mcl** [comment]
NOTE TO SELF: I am not admin on staging so will be possible to only verify the audit logs are not visible and not accessible via the endpoint.

**Comment by Steve-Mcl** [comment]
Confirmed non admin cannot see or access via API (API returns `{"code":"unauthorized","error":"unauthorized"}`.

@knolleary @hardillb could one of you guys please verify that as an admin on staging, you can access / view audit logs pls?

**Comment by hardillb** [comment]
I can see platform audit logs on staging

**Comment by Steve-Mcl** [comment]
confirmed on staging and local
