### ISSUE TITLE
Billing API returns a 200 OK, even when Billling not setup

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#522]
### Current Behavior

Seems to be in local changes, not on cloud-hosted release yet.

- In the UI, select the "Create New Team" option
- Fill out the new team's name and slug
- Select "Proceed to Stripe"
- DO NOT setup billing, instead select the "Back" option (top-left) 
- The Billing API (`http://localhost:3000/ee/billing/teams/<team_id>`) should be returning a 404 (as occurs in prod), but now returns a 200 OK, with the following payload:
```
{
    items: []
    next_billing_date: 1651223304486
}
```

### Expected Behavior

The Billing API should be returning a 404 if billing is not setup, as such, the UI will redirect to the Billing tab to ensure the user cannot proceed with creating projects, etc.

### Steps To Reproduce

See "Current Behaviour"

### Environment

- FlowForge version: `main` branch
- Platform/OS: Mac
- Browser: Chrome

**Comment by knolleary** [comment]
This is happening because (I am guessing...) you are logged in as an Admin user.

I have tested `main` with a non-admin user, and the behaviour is as expected - accessing the team redirects to the billing setup page.

The code currently handles admin users differently - returning the 200 response even if billing isn't setup. I think that was to allow an admin to 'see' the details of the team without getting redirected.

We should review if that is necessarily - or whether the response should be clearer to allow the frontend to display something.

**Comment by joepavitt** [comment]
In that case, the next issue that arises is that:
- Admin can create a Project (should this be the case)
- If the admin creates a Project, then upon creation any call to `http://localhost:3000/api/v1/projects/<project_id>` returns a `500`:

```
[2022-04-29T10:15:19.839Z] ERROR: Cannot read properties of undefined (reading 'state')
    req: {
      "method": "GET",
      "url": "/api/v1/projects/02622e10-4931-4bed-92ed-517f2ee810e2",
      "hostname": "localhost:3000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 64144
    }
    res: {
      "statusCode": 500
    }
    reqId: "req-2ua"
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'state')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'state')
              at Object.details (/Users/joepavitt/Documents/flowforge/development/flowforge/flowforge/node_modules/@flowforge/localfs/localfs.js:357:40)
              at Object.details (/Users/joepavitt/Documents/flowforge/development/flowforge/flowforge/forge/containers/wrapper.js:158:40)
              at Object.<anonymous> (/Users/joepavitt/Documents/flowforge/development/flowforge/flowforge/forge/routes/api/project.js:80:48)
    }
[2022-04-29T10:15:32.511Z] ERROR: Cannot read properties of undefined (reading 'state')
    req: {
      "method": "GET",
      "url": "/api/v1/projects/02622e10-4931-4bed-92ed-517f2ee810e2",
      "hostname": "localhost:3000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 64198
    }
    res: {
      "statusCode": 500
    }
    reqId: "req-2us"
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'state')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'state')
              at Object.details (/Users/joepavitt/Documents/flowforge/development/flowforge/flowforge/node_modules/@flowforge/localfs/localfs.js:357:40)
              at Object.details (/Users/joepavitt/Documents/flowforge/development/flowforge/flowforge/forge/containers/wrapper.js:158:40)
              at Object.<anonymous> (/Users/joepavitt/Documents/flowforge/development/flowforge/flowforge/forge/routes/api/project.js:80:48)
```

**Comment by sammachin** [comment]
Thinking about the desired experience here:

Should the billing check only be done on create project, if the user tries to create a project when billing is not enabled then they see a message prompting them to complete setup.
This would mean that then both user/owners and admins could see anything in a team even without billing enabled, but they wouldn't be able to make a chargeable event like creating a project.

I believe the redirecting users to setup billing was put in to catch the small number of users that have grandfathered projects from before we setup billing to prevent them from accessing those projects, but I'm not sure this is required. For a new user that creates the team but does not complete billing setup they would be able to view the limited options for that team but still need to setup billing to create a projet.

**Comment by joepavitt** [comment]
> Should the billing check only be done on create project

I agree entirely. Although, I would say that breaches the bounds of this PR/issue. Worth adding an issue to describe your thinking here @sammachin and I would support us making that change

**Comment by sammachin** [comment]
Moving back to Product/Design so we can properly think through what we want the experience to be here

**Comment by sammachin** [comment]
#594 will influence this

**Comment by sammachin** [comment]
@knolleary is this still an issue with the new Admin RBAC changes in 0.10?

**Comment by knolleary** [comment]
This can be closed. The billing api returns a consistent response regardless of user level now.
