### ISSUE TITLE
Unexpected sidebar scrolling

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#524]
When the page needs to scroll, the sidebar scrolls with it. The page content scrolls under the header, the sidebar scrolls over it. Not sure if that is intended, but it feels weird.

My preference would be for the sidebar to not scroll.

![psFd0Mskwx](https://user-images.githubusercontent.com/51083/166069823-87dbc002-7752-4ee5-ba57-e3cab7c8546e.gif)

**Comment by joepavitt** [comment]
Completely agree - thay shouldn't be scrolling.
