### ISSUE TITLE
"Admin Settings" show for non-admin users

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#526]
### Current Behavior

<img width="416" alt="Screenshot 2022-05-03 at 09 01 23" src="https://user-images.githubusercontent.com/99246719/166421192-d7ce8058-1bd8-4add-a8d3-2eac81dee304.png">

### Expected Behavior

The "Admin Settings" option should only show for "Admin" users

**Comment by knolleary** [comment]
With this fix in place, I now don't get the Admin Settings option when logged in as admin

**Comment by joepavitt** [comment]
<img width="614" alt="Screenshot 2022-05-03 at 16 48 51" src="https://user-images.githubusercontent.com/99246719/166488448-42b15529-241c-4771-b198-f2a30c84ccf3.png">

I'd mixed up "Team Admin" and platform Admin roles/data. As the above `admin` field for a Platform admin?

**Comment by knolleary** [comment]
Yes - the admin flag is for platform-wide admin users

**Comment by joepavitt** [comment]
Fixed pushed - apologies
