### ISSUE TITLE
Project sidebar navigation proposal

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#533]
When viewing a project in the platform, the sidebar looks like this:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/51083/166561913-e3c788c3-6858-475c-98eb-c489022bac2b.png">

Having used it for a couple days, some bits aren't quite working for me.

1. The 'Back to Projects' link at the top assumes you've arrived at this page from the Team Projects page. That isn't necessarily true as you can reach a Project via various links. Having a back button take me somewhere different to where I came from doesn't feel right
2. You don't have the context of which team you're in when viewing the project

I've put together the following mockup (in Figma - FlowForge Platform) as a suggested alternative:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/51083/166562433-6905f66f-f44b-4008-be57-a2d7ec44440f.png">

1. The top entry is always the Team name. This keeps you grounded in which team you're working within
2. The next entry is the Project name, using in a consistent style with the Team entry.

**Comment by knolleary** [comment]
@joepavitt can I get your opinion on this? If its appropriate, I'd like this to get into 0.5

**Comment by joepavitt** [comment]
counter proposal (with the "Team: Development" bit being clickable to return to Team Overview)

<img width="372" alt="Screenshot 2022-05-05 at 13 26 30" src="https://user-images.githubusercontent.com/99246719/166922600-02e0cf55-faef-48fa-9d4f-aaa07e52568b.png">

**Comment by knolleary** [comment]
Yup - happy for you to play with the specifics - but the key point is keeping the team item at the top and a project item below it.
