### ISSUE TITLE
Rebrand: 404 page

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#550]
Whilst not awful, the 404 page needs a bit of rebrand attention.

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/51083/167447624-45066e4e-6411-4592-a4ce-fb7c9df9b3ce.png">

**Comment by joepavitt** [comment]
Nothing too complicated required here, tried our website 404, but it didn't quite sit right, so keeping it simple:

<img width="1112" alt="Screenshot 2022-05-20 at 15 14 45" src="https://user-images.githubusercontent.com/99246719/169546996-f895d358-6db0-4862-816d-667029a890e7.png">
