### ISSUE TITLE
Rebrand: Server Offline page

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#551]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/51083/167447928-cf554fe0-36f4-4824-88f6-c5c8f84be533.png">

 - Start FF
 - Navigate to a team page
 - Stop FF in the background
 - Click on the projects page (which triggers an API request that will fail to trigger the server offline view)

**Comment by joepavitt** [comment]
Updated design: 
<img width="1112" alt="Screenshot 2022-05-20 at 15 00 09" src="https://user-images.githubusercontent.com/99246719/169544091-981da3c5-315a-44c8-8979-85ae471ab159.png">
