### ISSUE TITLE
Rebrand: Loading page

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#552]
Another, not awful page - but should get a similar treatment to #550  #551
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/51083/167448538-55fe6f11-1db3-493b-8597-efe1ec887365.png">

**Comment by joepavitt** [comment]
New loading graphic inline:

https://user-images.githubusercontent.com/99246719/169522899-d8c1250e-3350-4a13-a1ad-3d3d75e086ae.mov

**Comment by joepavitt** [comment]
and full screen variation (with dark background):

https://user-images.githubusercontent.com/99246719/169523494-35308095-4cfc-4a4b-99ea-55cab1d507e3.mov
