### ISSUE TITLE
Introduce spellcheck GH action on markdown files

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#554]
I wonder if there's a GitHub action that can spell check `.md` files?

_Originally posted by @ZJvandeWeg in https://github.com/flowforge/flowforge/pull/553#discussion_r868951433_

**Comment by ZJvandeWeg** [comment]
@Pezmc Are you picking this up?

**Comment by Pezmc** [comment]
It's on my backlog but relatively low priority (i.e. a nice to have if other 1.1 stories have been handled). Being tracked in https://github.com/flowforge/handbook/issues/129. Happy to reprioritise if needed!

**Comment by MarianRaphael** [comment]
Implemented with https://github.com/flowforge/flowforge/pull/1727
