### ISSUE TITLE
Rebrand: password reset page

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#557]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/51083/167644030-10a0b53b-418a-4ede-a6a4-6001a11fca4d.png">

 - log in as admin
 - go to Admin Settings -> Users
 - edit the current user - click expire password (as of right this moment, you'll get an error in the forge app which I'm fixing atm, but the expiry will have happened)
 - click to navigate somewhere else in the app - you'll get prompted to update your password

**Comment by joepavitt** [comment]
This is also the case in `Account > PasswordReset` when navigating after `ForgotPassword`. Redesign:

<img width="1728" alt="Screenshot 2022-05-11 at 09 34 13" src="https://user-images.githubusercontent.com/99246719/167805896-9fc7d47e-a844-4eba-bcf5-88ee1b23ffec.png">

**Comment by joepavitt** [comment]
and then the original page updates requested:

<img width="1728" alt="Screenshot 2022-05-11 at 09 37 20" src="https://user-images.githubusercontent.com/99246719/167806549-a7a55b92-f3b5-455a-a6f5-6d444ff30479.png">
