### ISSUE TITLE
Rebrand: forgot your password page

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#559]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/51083/167680502-4d21e491-04eb-4b05-849c-e417863fc283.png">

Remember to enable 'allow users to reset their password' via Admin Settings in order to get to this page.

**Comment by joepavitt** [comment]
<img width="918" alt="Screenshot 2022-05-11 at 09 33 01" src="https://user-images.githubusercontent.com/99246719/167805656-b49096d1-4153-4417-9dd0-b2a995fe9d48.png">
