### ISSUE TITLE
Improve Information on billing

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#563]
### Description

**As a:** user 

**I want to:** understand why I need to enter my card details what I will be charged for and who I am dealing with

**So that:** have confidence that I won't be ripped off

### Acceptance Criteria

On the /team/create page there is a view that has the link to "Proceed To Stripe"

We can use this space to add some additional copy answering some questions and hopefully allaying doubts.
![Screen Shot 2022-05-11 at 9 10 15 AM](https://user-images.githubusercontent.com/187645/167801247-596164fa-f948-492e-a8a8-bde6dbd1eeb5.png)

Copy for page is at
https://docs.google.com/document/d/1LZOlfK211brVCdxWfzYR8OYWxWMclnZTcZNclCI7KVU/edit?usp=sharing

**Comment by sammachin** [comment]
Feedback from customers has been that they don't feel confident in entering their card details, this is a simple iteration to improve that.

**Comment by joepavitt** [comment]
Proposal for new design of this page, including FAQ section:

<img width="1764" alt="Screenshot 2022-05-11 at 10 03 57" src="https://user-images.githubusercontent.com/99246719/167812637-766d56b3-5dc5-44ff-bccb-cb01395a9d6d.png">

**Comment by joepavitt** [comment]
> Is that all the text? what about the "who are flowforge" and "are my card details safe" copy?
> 
> Also can we link to the billing page on docs

It's not all the etxt, you'll see more when scrolling, I just put those in for demonstration purposes to get approval on the design/layout.

**Comment by sammachin** [comment]
Wondering, should we have a "no thanks" button at the bottom that we can then track a metric on? or is having a negative CTA too much of a bad thing

**Comment by joepavitt** [comment]
> Wondering, should we have a "no thanks" button at the bottom that we can then track a metric on? or is having a negative CTA too much of a bad thing

If we configure Plausible before release, we'll know the numbers that turn away from this page without going to Stripe.

**Comment by sammachin** [comment]
perfect

**Comment by knolleary** [comment]
Issue raised to track getting PA configured in production: https://github.com/flowforge/CloudProject/issues/50
