### ISSUE TITLE
FF Cloud is not reporting telemetry data

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#577]
### Current Behavior

We are not seeing any telemetry data from either the staging or production installs of ff cloud.

We have verified that telemetry is enabled in both the `flowforge.yml` and in the Admin Settings - but no data is arriving.

We need to investigate why not.

To aid with debugging this in the future, I propose we add an option eye-catcher property to the telemetry setting in `flowforge.yml` that gets included in the ping packet - an entirely optional property we can set ourselves to help us quickly correlate the otherwise randomised ping payloads back to our known instances.

We can also encourage devs to set it in their local environments to help us correlate those instances.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by ZJvandeWeg** [comment]
I spotted it in the data, closing this now. Sorry for the confusion @knolleary
