### ISSUE TITLE
Secure HTTP end points in Node-RED (httpNodeAuth)

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#578]
### Description

**As a:** user

**I want to:** secure my http end points in Node-RED

**So that:** I can deploy a dashboard with some level of access control.

---

The security of the http end points is set by the `httpNodeAuth` property of the settings file.

This is a very crude setting - it only enables HTTP Basic auth and can only use a single hardcoded username/password  combination. It is *not* integrated with `adminAuth` - the full multi-user security model used by the editor.

The MVP for this story will be to let the user provide a username/password via the project settings that should be used to secure those end points.

The Node-RED position has been you are better off running NR behind something like nginx for providing proper HTTP level access control. That position only goes so far in defence of why NR doesn't provide anything better. I have long thought there are some incremental improvements to be had on the NR side here.

Beyond the MVP for this story, we have an opportunity in FF to provide a much better access control story - but will likely need some upstream changes in NR to provide a better set of options.

**Comment by hardillb** [comment]
As a possible next step:
Since we have full control over the `settings.js` we can inject our own middleware. I have implemented httpNodeAuth like control using this to tie into the same database as the adminAuth in the past.

**Comment by ZJvandeWeg** [comment]
For FlowForge internal usage this would be a nice feature to:
* Allow user input to kick off a workflow
* Share dashboards internally, but hide details externally

**Comment by ZJvandeWeg** [comment]
@sammachin Can we move this to the design stage? This needs thinking around RBAC etc too.

**Comment by sammachin** [comment]
Have moved it up for desing in the next available iteration, Prob 1.0 then 1.1 release.
There's certainly several iterations that can be done here, the most basic as Nick described above of HTTP basic auth with static credentials does also have some value in protecting webhook endpoints that people may want to restrict.
An eventual goal of utilising FF user accounts is good, we can then consider the roles within RBAC particularly the new view only role that is proposed, and if there is demand create another lower tier of user that only has access to endpoints too.

**Comment by hardillb** [comment]
We need to hash the password to add it to the `settings.js` I'm going to work on the assumption that we should just store the hash in the database, so we never have access to recover the users password

**Comment by hardillb** [comment]
Verified on Staging (test Template)
