### ISSUE TITLE
Shebang missing from top of install-stack.js

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#580]
### Current Behavior

`node_modules/.bin/ff-install-stack x.y.z` fails

### Expected Behavior

`node_modules/.bin/ff-install-stack x.y.z` succeed 

### Steps To Reproduce

See above

### Environment

- FlowForge version: 0.5.1
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: any Unix esc platform
- Browser: NA

**Comment by PranaySewatkar** [comment]
hi are you working on this issue, if not i am glad to solve this issue

**Comment by hardillb** [comment]
Feel free, it's a single line change. I raised the issue to remind me to fix it later
