### ISSUE TITLE
Node-RED isn't ready when Forge app says running

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#586]
### Current Behavior

When i create a new project on k8s (or Docker) the forge app returns me to the project status screen and the status says "starting" after a period this auto updates to running and I get a URL for the editor.

However if I then click that url I initially get an nginx 503 page which after a few secs then changes to an 502 page.

After around 30secs the node-red app has fully started and I can login to the editor.

I realise this is because the container is running but node-red hasn't started up yet but for a user this is a confusing initial experience as it appears the project creation has failed.

### Expected Behavior

The Forge app should only show the project as running when node-red has finished starting.

### Steps To Reproduce

On Staging

Create a project,

As soon as the status changes to running click the url

Reload the page periodically.

### Environment

- FlowForge version: 0.5.1
- Node.js version: 16
- npm version: 8
- Platform/OS: 
- Browser: Chrome

**Comment by ZJvandeWeg** [comment]
@knolleary @sammachin I've put this into 0.7 optimistically. Feels like a bug in first use experience we should fix.

**Comment by knolleary** [comment]
Yes - this is a bug and we can improve this for 0.7.

Currently the k8s driver does a very optimistic 5 second wait for the container to be ready. It ought to gently polling the launcher admin api until it is responsive.

**Comment by sammachin** [comment]
can we get a "quick fix" here with a custom 502/503 error page in the nginx proxy saying "if you have just started this project please wait a few mins"

**Comment by sammachin** [comment]
Does this PR only address the issue with k8s? 
What about Docker installs? the same problem exists in Docker although to a lesser extent as it seems slightly faster to spin up a container.

**Comment by hardillb** [comment]
@sammachin This is an issue, not a PR, the linked PR only addresses K8s because it's against the K8s driver and solves the issue as raised.

**Comment by hardillb** [comment]
I am looking at the Docker driver at the moment

**Comment by sammachin** [comment]
I've created https://github.com/flowforge/flowforge/issues/751 as a the same issue but for Docker
