### ISSUE TITLE
Snapshot/Rollback

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#587]
### Epic

#218

### Description

**As a:** owner

**I want to:** be able to rollback my project to a previous deployment.

**So that:** I can undo changes made by others in my team

---

0.6 added the ability to create snapshots.

The focus shifts to allowing a project to be rolled back. See https://github.com/flowforge/flowforge/issues/587#issuecomment-1155156854 for details

---

This is an MVP of version control meant to just be a basic snapshot of the flows, it does not prevent us offering a more complex feature later with git integration and such.
The project should be to keep a certain number or days of snapshots (amount may vary based on Project type in future)

Open questions to consider:
 - Are snapshots automatic and done at certain intervals or on each deploy, or is there a manual intervention to keep a snapshot, (If snapshots are on every deploy this could create a large number)

- How long/how many snapshots do we hold, is this X snapshots for Y days?

These are also potentially differentiators for different tiers so offering more/longer retention on higher tiers.

MVP would be to just rollback the flows file, any nodes installed or removed would be outside the scope of this.

**Comment by knolleary** [comment]
Some of this work will be needed for the Device work - being able to create snapshots of the project which can then be deployed to the devices.

The following is focussed on the snapshot part of this. It does not cover the rollback aspect - that isn't on the critical path for the Device work.

### What is a snapshot

A snapshot is a single JSON object containing all of the information needed to reproduce the project. This does *not* include capturing the stack choice - that is independently managed.

```
{
   flows: [],
   credentials: {},
   settings: {},
   env: {
      FOO: "hi",
      BAR: "bar"
   },
   modules: {
      "node-red": "3.0.0-beta.2",
      "node-red-node-random": "x.y.z"
   }
}
```

### Database Model

Table: `ProjectSnapshot`
 - `id`
 - `name`
 - `settings` - JSON encoded text of the project settings (`{ settings, modules, env }`)
 - `flows` - JSON encoded text of the project flows/credentials (`{ flows, credentials }` )
 - `createdAt`
 - `updatedAt`



### API Updates

 - `GET /api/v1/projects/:id/snapshots` - list project snapshots
 - `POST /api/v1/projects/:id/snapshots` - create a snapshot
 - `GET /api/v1/projects/:id/snapshots/:id` - get a snapshots details - this does *not* include any content of the snapshot itself - just the meta data about the snapshot
 - `DELETE /api/v1/projects/:id/snapshots/:id` - delete a snapshots


### UX

Super simple mockup - a new Snapshot tab on the project page
 - option to create a snapshot. User prompted via dialog to enter an optional name for the snapshot
 - each row has a dropdown menu - `delete snapshot`




<img width="632" alt="image" src="https://user-images.githubusercontent.com/51083/169003395-50c88f16-9b30-4d81-bd8a-a2851cf9a485.png">

Future improvements would be to let the user view diffs between snapshots etc. More design work needed for future stories around what this enables.

**Comment by hardillb** [comment]
Looks good,

The `modules` section is for populating a `package.json` rather than the equivalent of `.conf.nodes.json`? Will we need to  generate that from the settings object from the Storage API?

**Comment by knolleary** [comment]
Correct - modules is the list of modules (and versions) that should be installed.

Providing it in this format would allow the edge agent (or anything else wanting to take the snapshot and 'run it', to do all the npm installing that is needed, rather than rely on Node-RED trying to dynamically install

**Comment by knolleary** [comment]
With the snapshot work delivered in 0.6, the focus here is now on the rollback side of things.

A user should be able to select a snapshot to restore it to the project.

This action should include a warning that it will overwrite anything running the project - and any changes made since the last snapshot was taken will be lost.

### API Design

Add a new endpoint to trigger the rollback.

 - `POST /api/v1/projects/:id/actions/rollback` which receives a payload of `{ snapshot: <id> }`.

**Comment by Steve-Mcl** [comment]
@knolleary I have been working through this. I have done the API and mapped it from a (temporary) UI action. Next step is to action the rollback request at the serverside - is there some code already written for performing the rollback?
If not, are the steps required to perform the rollback written up somewhere or could you give me a leg up please?
