### ISSUE TITLE
Free Project Tier

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#590]
### Description

User feedback is that its not possible to assess the value of the flowforge cloud platform without providing card details so the proposal is to create a free tier.

This should allow the user to asses that FF/Node-RED can be used to solve their problem without actually delivering too far on the solving the problem before they are asked to pay.

**Comment by joepavitt** [comment]
This has now been shipped with 1 month trials & the on-going [Team Trial work](https://github.com/flowforge/flowforge/pull/1611)
