### ISSUE TITLE
Change project type

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#595]
### Description

**As a:** Owner 

**I want to:** Change my project type

**So that:** So that I can use a stack with additional resources or features

2 paths to think about here, upgrading and downgrading, upgrade should be the simpler path but downgrading a project type may be that the project is using features which are not available in the lower tier.
For MVP only having upgrade would be a viable iteration.

A user can move a project to a different tier today by  copying the project to a new one on a different type but this means changing the name and URL of the project when may no be desirable.

**Comment by sammachin** [comment]
@nick is this implemented in 0.7?

**Comment by knolleary** [comment]
No - as described in #739, allowing a user to change the projecttype is not in scope of this initial work.

**Comment by Steve-Mcl** [comment]
@knolleary.  @hardillb. 

Need a direction on this feature please.

I see this going 2 ways...

1. Upon selecting a different project type, the user is offered the choice of stacks
2. Upon selecting a different project type, the default stack is assumed (or is inhibited if no default set)

`1.` seems the more friendly way
`2.` presents us with an opportunity to encourage users to setup the defaults.

<br>

Regarding Sams comment about "only having upgrade would be a viable iteration" is this a necessity? And if so, what determines a smaller/larger stack?  Perhaps MVP is to permit either direction and the consequences are the users responsibility? (perhaps offered with a suitable warning)

**Comment by ZJvandeWeg** [comment]
@Steve-Mcl is this going to ship? It would be great if everyone knew what 1.2 would include

**Comment by Steve-Mcl** [comment]
I dont believe it will make the cut ZJ. 

I have started a branch but there is more than meets the eye.

**Comment by Steve-Mcl** [comment]
Following discussion with Nick and Joe, this item is UI heavy and needs to be done right with consideration to the duplication of code and UI around the whole "Create Project, user billing changes etc). 
Instead of trying to rush this into 1.3 it is to be deferred once more. I have setup a meeting with Joe for next Friday (following launch retro) to get this right from the start.

**Comment by robmarcer** [comment]
I've moved this to 1.4 as per Steve's post above, hope that's OK.

**Comment by joepavitt** [comment]
Just spoke with Steve. Given @Pezmc's recent work on the Create Project page, and Steve's expertise not being FE, I think this would best suit Pez to conduct the front-end work required for this.

**Comment by Steve-Mcl** [comment]
Following discussion with @joepavitt the approach should be as follows...

1. Work on frontend and backend should be split to suitable devs
1. Duplicate `packages/flowforge/frontend/src/pages/team/createProject.vue` to `packages/flowforge/frontend/src/pages/project/ChangeProjectType.vue`
2. Remove items not required (see screenshot)



![Image](https://user-images.githubusercontent.com/44235289/213687481-6823630e-8d34-476f-9356-3412f1ca6c88.png)





_This work may be temporary if the request to make Project Stacks agnostic (i.e. project type can be changed without changing stack - see https://github.com/flowforge/flowforge/issues/1603 ) is accepted._

**Comment by Steve-Mcl** [comment]
@joepavitt @Pezmc 

In branch [change-project-type](https://github.com/flowforge/flowforge/tree/change-project-type) most of the work is done but there are some questions & and I am not super happy about the UI (needs Pez's artistic touches)


First, a demo (questions below): 

https://user-images.githubusercontent.com/44235289/213888508-86714596-4f62-4681-8576-1f6820bff21d.mp4


1. Should we only permit the <kbd>Confirm Changes</kbd> when a different **Project Type** is selected?
1. Should we also permit the template to be changed at the same time?
1. @Pezmc Should I PR this? and you gonna branch off this / modify this branch?

**Comment by Pezmc** [comment]
@Steve-Mcl If it's ok with you I think I'll make any changes directly in that branch, but perhaps your running me through where things are at will save some time?

**Comment by Steve-Mcl** [comment]
I am happy to do a screenshare and huddle to impart my thoughts and direction. 

Also, please do continue on this branch.

**Comment by joepavitt** [comment]
> First, a demo (questions below):

Great stuff, Steve. I see @Pezmc will take over here. Regarding the question, my input would be:

1. & 2. - Really, we're offering more than just a change of Project Type here, which I'm fine with, but we may want to re-consider the labelling of the "Change Project Type" option, I think the button and header are fine, but perhaps more detail in the description of that optio to detail it's possible to change Stack/Template too?

**Comment by Steve-Mcl** [comment]
> 1. re-consider the labelling of the "Change Project Type" option

Agreed. @Pezmc and I discussed this & Pez is going to combine this to reduce UI and code duplication.



> 1. optio to detail it's possible to change Stack/Template too

Sorry I should have followed up that comment. After discussions with Pez and Nick, it was determined that changing the template type Is not something we will address right now.

**Comment by Steve-Mcl** [comment]
tested locally and in staging.

changed stack only - ok. 
changed from small -> medium - ok
changed from medium -> small- ok

Each time the project stopped and restarted correctly.

NOTE: Also tested from a stopped project. The project changed but did not start up (stayed stopped) as expected
