### ISSUE TITLE
npm run start-watch -  cross-dev not found

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#599]
### Current Behavior

typo in script causes error

Should be `"start-watch": "cross-env NODE_ENV=development nodemon -w forge -w ee/forge -i forge/containers/localfs_root forge/app.js",`

not 

`"start-watch": "cross-dev NODE_ENV=development nodemon -w forge -w ee/forge -i forge/containers/localfs_root forge/app.js",`

### Expected Behavior

no error

### Steps To Reproduce

run `npm run start-watch` 

### Environment

- FlowForge version: 0.5.0
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
@Steve-Mcl can you PR the fix for this please?
