### ISSUE TITLE
Sort list of users

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#600]
### Description

**As a:** admin

**I want to:** sort the list of users in /admin/users/general

**So that:** I can find the user I am looking for

Order By:
Date Created ascending/descending
Username alphabetical ascending/descending
Password expired true/false
Email Verified true/false
Admin true/false

Should also have a 'show' all to turn off pagination when displaying a sorted list

**Comment by sammachin** [comment]
@joepavitt Is the enabling design work around tables covered to ship this in 0.9?

**Comment by joepavitt** [comment]
I am actually hoping this will be a 0.8 release. The new data table enables sort really easily, just working through updates of the tables atm and ironing out any issues I find with the underlying components before I can say for certain.

**Comment by joepavitt** [comment]
Verified in latest release
