### ISSUE TITLE
UX: Creating a new team is not obvious

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#616]
### Current Behavior

Found it hard to find where the button is to create a new team.

### Expected Behavior

It should be easier.

### Environment

- FlowForge version: Staging @ 23rd of May

**Comment by ZJvandeWeg** [comment]
Don't know, but found myself clicking around for a minute or so to figure out where it's supposed to go @joepavitt

**Comment by joepavitt** [comment]
Without knowing where you did go to look for the create team option, the feedback isn't entirely useful. If you can offer insight into where you'd expect it to be, then we have something to work with.

**Comment by sammachin** [comment]
@joepavitt will this be picked up in the sidebar redesign? hopefully making the team navigation clearer will iterate on it at least?

**Comment by joepavitt** [comment]
There are no changes being made to team selection or creation of new team. As far as I'm concerned, it's okay as it is for now. If other users believe it's difficult to find, then I will look at an alternative. The main question I have, which has so far been unanswered, is "where did you look/go to create a new team". For me, it is intuitive to look at the team switch option.

**Comment by sammachin** [comment]
I agree that in team selection/switch is the most logical place, I think this is related to my issue https://github.com/flowforge/flowforge/issues/690 around activating the team selection

**Comment by joepavitt** [comment]
I don't believe @ZJvandeWeg's issue is the same. ZJ's point is that the create team should be in a completely different place. Your point is that clicking the team name should bring up the switch team list (which it now does, subject to a [PR review](https://github.com/flowforge/flowforge/pull/701) from Nick)

**Comment by joepavitt** [comment]
Thoughts on this as an alternative @ZJ? Not entirely sure how it affects our admin/user settings side bar yet, nor how you'd navigate back to the team view - but thought it worth sharing.

![Image](https://user-images.githubusercontent.com/99246719/174792298-c5a98ff4-c74b-4497-9433-d9ebf386edc5.png)

**Comment by ZJvandeWeg** [comment]
@joepavitt That's better. Don't know if it scales to more than 5 teams though?

**Comment by joepavitt** [comment]
Implemented:

<img width="1172" alt="Screenshot 2022-07-01 at 13 35 00" src="https://user-images.githubusercontent.com/99246719/176895489-eec50099-d720-46cb-802e-40695941f028.png">

**Comment by ZJvandeWeg** [comment]
Love it Joe, thanks!
