### ISSUE TITLE
"Create Project" Timeout

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#647]
### Current Behavior

When creating a project, more often that not, the creation of the container is timing out, with the following error:

```
Error: timeout of 5000ms exceeded
    at createError (createError.js:16:15)
    at XMLHttpRequest.handleTimeout (xhr.js:130:14)
```

This results in the UI displaying the "Server Offline" page, where the user naturally hits the "Try Again" button. This refreshes successfully back to the "Create Project" page. However, the project has actually been created successfully in the background.

Confirmed that the starting of the container is the issue, I placed a `console.log` either side of the `await app.container.start(project` in `/routes/api/project.js`:

```
starting container
[2022-06-01T10:18:51.540Z] INFO: Adding Project 47a17e2a-2377-486a-8753-c6a8774c3194 to Subscription for team BKXAw41qwm
[2022-06-01T10:18:56.984Z] INFO: Creating project directory: <dir>/flowforge/var/projects/47a17e2a-2377-486a-8753-c6a8774c3194
started container
[2022-06-01T10:18:57.101Z] INFO: Set FORGE_NR_PATH to <dir>/flowforge/var/stacks/0.2
```

No errors are reported, but the timeout/response seems to occur about the time the project directory is created 

### Expected Behavior

The API call should not time out, and even if it does, we should not see the server offline screen (given that the server never goes offline)

### Steps To Reproduce

- Create a project

### Environment

- FlowForge version: 0.5.0
- Node.js version:
- npm version:
- Platform/OS: Mac
- Browser: Chrome

**Comment by knolleary** [comment]
Our default request timeout is [5 seconds](https://github.com/flowforge/flowforge/blob/f980bb107f1291c1862c09dfb1b589a2ff8911a0/frontend/src/api/client.js#L8)

We have the ability to increase that timeout on a per-route basis, so we could selectively increase it for routes that involve synchronous calls to stripe.

But having initially considered that approach, I don't see any reason to be selective about that. We should just increase the global timeout to something more reasonable to accommodate unexpected delays.
