### ISSUE TITLE
Layout of 'thank you for signing up' page needs improving

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#648]
### Current Behavior

As this is one of the early screens a new user encounters, it would be good if the layout was tidied up so the billing message isn't crashing into the button.

<img width="1521" alt="image" src="https://user-images.githubusercontent.com/51083/171388070-ec613475-7c71-4aeb-962a-c4c33e4f62a4.png">

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by joepavitt** [comment]
I think it does actually - thanks for bumping

**Comment by knolleary** [comment]
Works for me

**Comment by joepavitt** [comment]
alternatively, something a little more obvious re: the thank you

<img width="1728" alt="Screenshot 2022-07-21 at 16 40 43" src="https://user-images.githubusercontent.com/99246719/180255392-f6010517-4abd-44fe-8ed0-5f80e30154ee.png">
