### ISSUE TITLE
Remove Devices feature flag

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#669]
### Description

As the devices feature flag was introduced behind a feature flag there's still some leftover bits now it's enabled for all our customers. This leftover code can be removed in this release.

**Comment by knolleary** [comment]
There is a Product level discussion to be had as to whether we want to remove the flag entirely. There are use cases where someone wants to host their own FF to manage Node-RED, but does not want the devices feature because they want to keep it self-contained.

I would not want to rush into removing the flag without having that discussion as part of our standard planning process.

**Comment by ZJvandeWeg** [comment]
@knolleary I disagree, our product should not be infinitely configurable. That increases the testing matrix and makes it like using multiple Jira's. When effective in one organisation with a tool, you should be effective in another with the same tool.

**Comment by sammachin** [comment]
I agree that we should use configuration options sparingly to avoid too many different combinations however I do think that devices are an area that is sufficiently prominent in the application and something that may be totally irrelevent to a customers use case that we should keep the option to hide them in the configuration.
The default should also be that the feature is on.

We may need to revisit this once we have a firm decision on pricing, for example if devices becomes an enterprise feature then it may be hidden by a license flag.

**Comment by sammachin** [comment]
Now that we have a path on licensing regarding devices I'm revisting this.

What about removing the feature flag from config but if a platform has a license for 0 devices then it should hide the devices from the application.

**Comment by ZJvandeWeg** [comment]
Devices are a vital part of the strategy around Node-RED, and not pidgin-hole'ing Node-RED. It should always be visible.Further, discussions on the mechanics of the license indicate that blocking new projects from being created if the license doesn't allow it is a no-go, and these should be charged at a later date. I propose we do the same with devicesOp 27 sep. 2022 11:29 schreef Sam Machin ***@***.***>:
Now that we have a path on licensing regarding devices I'm revisting this.
What about removing the feature flag from config but if a platform has a license for 0 devices then it should hide the devices from the application.

**Comment by sammachin** [comment]
work scheduled to remove feature flag in the 1.0 release

**Comment by knolleary** [comment]
> Further, discussions on the mechanics of the license indicate that blocking new projects from being created if the license doesn't allow it is a no-go

That is not what the agreed pricing principles state:

> If a customer attempts to exceed their licensed amounts they are prevented from creating the resource until the license is upgraded.

https://flowforge.com/handbook/product/pricing/#:~:text=If%20a%20customer%20attempts%20to%20exceed%20their%20licensed%20amounts%20they%20are%20prevented%20from%20creating%20the%20resource%20until%20the%20license%20is%20upgraded.

This is the behaviour that has been implemented for the 0.10 release via https://github.com/flowforge/flowforge/pull/947 and associated PRs that add the same policing of limits for teams, devices and users.

If we want to change what was agreed on the pricing principles and allow a user to exceed the terms of the license, then we need a separate set of stories to cover that and plan it in for 1.0.

**Comment by Steve-Mcl** [comment]
devices are present and correct on local and staging. I believe we can consider this verified.
