### ISSUE TITLE
Loading animation glitches

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#683]
### Current Behavior

When pages poll for a status update (eg started/running or device status) the page glitches to the loading animation for ~100ms

https://user-images.githubusercontent.com/187645/172805535-64df0fc6-e0e3-4ba3-916c-8ddbb243bb08.mp4

### Expected Behavior

Page shouldn't glitch

### Steps To Reproduce

Create a new project, wait for the page to get to running and watch for glitches on updates.

### Environment

- FlowForge version: 0.6.0 (staging pre-release)
- Node.js version:
- npm version:
- Platform/OS: MacOS 12.3.1
- Browser:Chrome 102.0.5005.61

**Comment by joepavitt** [comment]
Not sure what you're expecting here. The loading graphic needs to show when the page is loading, and hide when it is not. I can't control, nor predict, how quickly the page loads?

**Comment by joepavitt** [comment]
Ah, it's only on updates. Fairly sure that Nick pushed a fix for that already? Do you have the latest `main`?

**Comment by sammachin** [comment]
duplicate of #674
