### ISSUE TITLE
Cannot add device to project in Flow Forge Cloud

### ISSUE THREAD

**Issue by mtoko** [flowforge/flowforge#686]
### Current Behavior

I was originally using a Pi Zero2 but this is Arm6 so cannot install Node 16. I then started with fresh install on Pi3B and installed npm and then Node 16 but not Node Red. Followed the instructions in the docs to install the device agent and started the agent. In the terminal you can see the agent calling home and in the Flow Forge cloud the device is "seen" every 30 secs, but it is not possible to assign the device to a project and the status is always stopped. There is a 403 error code in the console associated with the device id of the agent on the device 
When I could not add a device I attempted to delete the created devices to restart, but it is not possible to delete devices. I have tried to refresh the browser and log out and then in again but devices are still listed with status stopped and unassigned. The agent cannot run as a service so the "call home" can bee seen running in the terminal of the device. It is important to note that "normal" Node Red should not be installed or running on the device
![FlowForge3](https://user-images.githubusercontent.com/4711179/173109116-3bbe66ea-7008-46c9-aa1b-7f34a7e88de7.jpg)
![FlowForge2](https://user-images.githubusercontent.com/4711179/173109119-d1f79ed7-8e4c-4229-b7c8-0a9b494c102f.jpg)
![FlowForge1](https://user-images.githubusercontent.com/4711179/173109120-afa7f2e0-26b2-460b-8e8d-33d4897de056.jpg)

### Expected Behavior

I have followed the agent install instructions in the docs, I expected the agent could run as a service and then to assign the device to a project create a snapshot and send this to the device.

### Steps To Reproduce

Install the device agent on a Raspberry Pi 3B+ and attempt to assign this to an existing project in Flow Forge Cloud

### Environment

- FlowForge version: 0.6
- Node.js version: 16.15.1
- npm version: 8.11.0
- Platform/OS: Raspberry pi 3B+ /raspian bullseye
- Browser:Chrome and Firefox

**Comment by knolleary** [comment]
Thanks for reporting the issue @mtoko 

I have managed to reproduce this locally, but still working through to understand what is happening.
