### ISSUE TITLE
Need help, fresh Flowforge installation (Project crashed after creation);Raspberry Pi4 2GB

### ISSUE THREAD

**Issue by picotouch** [flowforge/flowforge#693]
Hi,
I'm trying to install Flowforge 0.6.0 on a Raspberry Pi 4 2GB.

The OS on Pi is freshly installed; "Raspberry Pi OS with desktop",Release date: April 4th 2022, System: 64-bit, Kernel version: 5.15, Debian version: 11 (bullseye).
An OS update was made after installation.

When installing Flowforge, I followed the instructions from: [https://flowforge.com/docs/install/local/](https://flowforge.com/docs/install/local/)

Using wget https://github.com/flowforge/installer/releases/download/v0.6.0/flowforge-installer-0.6.0.zip I downloaded the file, unzipped it and copied the contents to the created directory (/opt/flowforge; (owner changed to pi; all according to instructions above).
In /opt/flowforge I start ./install.sh.

After a successful installation (at the end of the instalation I chose to run Flowforge as a service, and as a user I chose current (pi)).

Then, I edited flowforge.yml in /opt/flowforge/etc:

host: 0.0.0.0
base_url: http://192.168.0.201:3000

I didn't change the rest.

I started the service with: sudo service flowforge start

From another computer, I accessed the address 192.168.0.201:300, enter the necessary data to the end, and then log in.

I created:
- team (tim1),

and then through Admin Settings, created:
- Stack; (Name: stack1, Node-RED Version: 2.2.2, Memory (MB): 512),
- Template; (Name: template1)

Now I have created a project, but I get in the status: running, and in Recent Activity: crashed.

In Logs I have:

Launcher Started
13. 06. 2022. 12:02:15
[system]
Loading project settings
13. 06. 2022. 12:02:15
[system]
Target state is 'running'
13. 06. 2022. 12:02:15
[system]
Starting Node-RED
13. 06. 2022. 12:02:15
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:15
[system]
Starting Node-RED
13. 06. 2022. 12:02:15
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:15
[system]
Starting Node-RED
13. 06. 2022. 12:02:15
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:15
[system]
Starting Node-RED
13. 06. 2022. 12:02:16
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:16
[system]
Starting Node-RED
13. 06. 2022. 12:02:16
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:16
[system]
Node-RED restart loop detected. Restarting in safe mode
13. 06. 2022. 12:02:16
[system]
Starting Node-RED
13. 06. 2022. 12:02:16
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:16
[system]
Starting Node-RED
13. 06. 2022. 12:02:16
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:16
[system]
Starting Node-RED
13. 06. 2022. 12:02:16
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:16
[system]
Starting Node-RED
13. 06. 2022. 12:02:16
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:16
[system]
Starting Node-RED
13. 06. 2022. 12:02:16
[system]
Node-RED exited rc=1 signal=null
13. 06. 2022. 12:02:16
[system]
Node-RED restart loop detected whilst in safe mode. Stopping.

Where to start?

**Comment by hardillb** [comment]
First question, did you install the stack?

https://flowforge.com/docs/install/local/stacks/#production

If so can you look in `/var/flowforge/var/projects/` there should be a directory with the uuid of the project. In there there should be a file called `out.log` which may have some more useful information.

**Comment by picotouch** [comment]
**I didn't install the stack!**

When I type "install-stack.sh 2.2.2" in /opt/flowforge I get the message:
"bash: install-stack.sh: command not found"

What is the correct procedure to install stack?

Can I manually perform the steps described in the procedure that describes what this script does?

**Comment by hardillb** [comment]
From the docs :

> `bin/install-stack.sh 2.2.2`

You need to pre-fix it with the `bin/` so it runs the command from the bin directory

**Comment by hardillb** [comment]
OK, that could be caused by 1 of 2 possible options.

Can you please run the following in order :
- `cd /opt/flowforge/var/projects/87e30917-bda0-443c-8758-d215086b7532`
- `node --version`
- `export NODE_PATH=/opt/flowforge/app/node_modules`
- `node`
- `require('./settings.js')`

This should 
1. print the nodejs version
2. start nodejs
3. try and load the `settings.js` file
4. print out the error from loading the `settings.js` file

**Comment by picotouch** [comment]
copy/past from cmd:

pi@rpi41:~ $ cd /opt/flowforge/var/projects/87e30917-bda0-443c-8758-d215086b7532
pi@rpi41:/opt/flowforge/var/projects/87e30917-bda0-443c-8758-d215086b7532 $ node --version
v16.15.1
pi@rpi41:/opt/flowforge/var/projects/87e30917-bda0-443c-8758-d215086b7532 $ export NODE_PATH=/opt/flowforge/app/node_modules
pi@rpi41:/opt/flowforge/var/projects/87e30917-bda0-443c-8758-d215086b7532 $ node
Welcome to Node.js v16.15.1.
Type ".help" for more information.
> require('./settings.js')
Uncaught Error: Cannot find module '@flowforge/nr-auth'
Require stack:
- /opt/flowforge/var/projects/87e30917-bda0-443c-8758-d215086b7532/settings.js
- <repl>
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/flowforge/var/projects/87e30917-bda0-443c-8758-d215086b7532/settings.js',
    '<repl>'
  ]
}
>

**Comment by hardillb** [comment]
Can you run `ls /opt/flowforge/app/node_modules/@flowforge`

**Comment by picotouch** [comment]
Of course,

ls /opt/flowforge/app/node_modules/@flowforge returns:

flowforge  
forge-ui-components  
localfs  
nr-audit-logger  
nr-auth  
nr-launcher  
nr-storage

**Comment by hardillb** [comment]
OK, this isn't making a lot of sense at the moment, the `nr-auth`  package is present where it should be and the `NODE_PATH` is set by the flowforge launcher before starting Node-RED so it should be able to load it.

Just to double check one more time please run the following from in the `/opt/flowforge/var/projects/87e30917-bda0-443c-8758-d215086b7532` directory:

- `NODE_PATH=/opt/flowforge/app/node_modules node`
- `require('./settings.js')`

This just combines 2 of the previous lines into one to ensure that it truly is in scope for the nodejs process.

Actually finally sanity check also run `ls /opt/flowforge/app/node_modules/https://github.com/flowforge/nr-auth`

**Comment by picotouch** [comment]
;)

- CHANGELOG.md  
- lib  
- LICENSE  
- package.json  
- README.md

**Comment by picotouch** [comment]
Just for information, I installed the same OS image on a USB stick and did a Flowforge installation from scratch, it works OK!

Then I uninstalled the nodejs on the existing microSD card and deleted the flowforge directory, made a new Flowforge installation from scratch, and it works OK!
Note: yesterday I tried to install Flowforge again (without uninstalling nodejs) but it didn't work so it seems that something with nodejs was a problem ...

Thank you very much for your help!!
