### ISSUE TITLE
PostHog - Integrate into FlowForge

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#695]
### Description

~~Currently, plausible provides us information about routing based on the URLs of each page. This is fine for static sites, however, it gives us skewed information as team/project views contain team/project ids in the URLs, meaning that we lose the grouped data to inform us of common navigation paths.~~

~~We need to investigate whether Plausible can provide data in a non-url format, where we could (possibly?) provide names for each URL, or create custom reports whereby we group together URLs.~~

With the limitations of Plausible, we will be switching over to PostHog for our user path and event tracking. This should be configurable via the `flowforge.yml`. See below thread for the discussion and further details.

**Comment by joepavitt** [comment]
So, I have managed to get manual page views working, however, it turns out Plausible never tracks the info we want, i.e. how a user navigates around our application. It is only tracking the `entry` and `exit` of a session, not the in-between. See their definitions: https://plausible.io/docs/metrics-definitions

Not sure if I'm missing something here, it seems like quite a fundamental feature missing?

**Comment by joepavitt** [comment]
Seems as though there is a long-standing open feature request for this: https://github.com/plausible/analytics/discussions/149

**Comment by sammachin** [comment]
I'm not an expert in analytics but it seems this is maybe the differentiation between a wesbite and a web applicaiton, the former you're really interested in where people come from and when they leave, but in an application you're more interested in what they do while they're in your app.

So while plausible works for flowforge.com maybe we need a different solution for flowforge cloud.

One that might be worth a look is https://posthog.com/ Has a similar business model to us, free hosted version for up to 1m requests and an option of open source self hosted?

**Comment by joepavitt** [comment]
Looks like the download/export of data from Plausible is no help either unfortunately. Just offers the same data visualised in the dashboard, with no insight into user journey through the site.

**Comment by joepavitt** [comment]
Just recording another feature request thread for Plausible that would also help here, is "[Funnels](https://github.com/plausible/analytics/discussions/171)". But unfortunately not available now, nor imminently.

**Comment by ZJvandeWeg** [comment]
Seems like it’s most productive to move away from Plausible and to posthog then?

**Comment by joepavitt** [comment]
> Seems like it’s most productive to move away from Plausible and to posthog then?
If @ZJvandeWeg and @sammachin are happy for me too, I'll sign up and start investigating

**Comment by joepavitt** [comment]
Spent the afternoon playing with Posthog and it will definitely do what we want, although does require a lot more customisation/configuration to get going. Have  some basic bits working, but still trying to get my head around it's potential and how it operates.

As such, I'll update this task name to reflect the work to be done

**Comment by joepavitt** [comment]
PostHog is excellent. Provides all the customisation/labelling we need, and also has a great browser plugin that overlays all the interaction data to any running instance of FlowForge when I'm logged into PostHog.

<img width="1728" alt="Screenshot 2022-08-05 at 07 53 47" src="https://user-images.githubusercontent.com/99246719/183019334-11444020-046f-489c-8288-46e740304d3a.png">

**Comment by joepavitt** [comment]
and we have user paths:

<img width="1432" alt="Screenshot 2022-08-05 at 10 33 41" src="https://user-images.githubusercontent.com/99246719/183049082-36505840-1f85-4198-b34f-087fc19d0096.png">

**Comment by joepavitt** [comment]
> and we have user paths:

worth noting though we cannot use wildcards in the free tier. If we add credit card details (still up to 1m events for free), then we can wildcard these pages to group projects/teams together as a single "Team" view and "Project" view for example.

**Comment by joepavitt** [comment]
Functional, although having to inject via index.html as we do with Plausible. In turn, that's raising the following error (despite it actually still working):

<img width="621" alt="Screenshot 2022-08-05 at 15 48 35" src="https://user-images.githubusercontent.com/99246719/183103236-4074d8c2-fb70-4c04-a5de-0f0497df74f3.png">

I've contacted posthog support as per the suggestion.

**Comment by joepavitt** [comment]
> although having to inject via index.html as we do with Plausible. In turn, that's raising the following error (despite it actually still working): 

Fixed. I had left an instance of the import posthog where we do a check for the active user.

**Comment by Steve-Mcl** [comment]
Verified on posthog we can see clicks, paths, operations etc from flowforge staging
