### ISSUE TITLE
Nested Sidebar Re-Design

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#697]
### Description

Covers #646 & #690

When a project is selected the sidebar main navigation options (associated to a Team) should slide left, showing icons only). Then, a new menu shows with options associated with the selected Project.

This same navigation hierarchy should then be applicable when selecting a "Device" (tbc in https://github.com/flowforge/flowforge/issues/698)

<img width="1700" alt="Screenshot 2022-06-14 at 13 10 43" src="https://user-images.githubusercontent.com/99246719/173573890-eb0271ac-2ef5-4e49-ac31-42b12f8376c3.png">

**Comment by joepavitt** [comment]
https://user-images.githubusercontent.com/99246719/173782027-abf6b14a-5ae2-4612-a681-be18bb651f78.mov

**Comment by knolleary** [comment]
Looks good
