### ISSUE TITLE
Sign in using email address or  username

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#705]
### Description

**As a:** user

**I want to:** be able to sign in with my email address OR my username.

**So that:** I don't have to remember a username

### Acceptance Criteria

- [ ] Username box on login screen accepts email address or username

**Comment by joepavitt** [comment]
Not necessarily got to be an `instead` of here, could it be an `or`?

**Comment by ZJvandeWeg** [comment]
> Not necessarily got to be an instead of here, could it be an or?

I'm fine with this, maybe even best to have an or clause there as long as usernames don't include the @

**Comment by knolleary** [comment]
It should be OR. For local/individual installs we do not require email to be setup, so there is only username available.

**Comment by sammachin** [comment]
Rewritten as a story,

Usernames Must only contain a-z 0-9 - _

So checking for an @ in the string should be sufficient to determine if the input is a username or an email address therefore we can avoid having any kind of user input to set the type
