### ISSUE TITLE
Story: Change my default team

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#72]
### Description

**As a:** User

**I want to:** Change my default team

**So that:** I can chose which team I am shown when I log in

### Acceptance Criteria

 - [ ] ...

**Comment by ZJvandeWeg** [comment]
@hardillb I think this has been fixed by you, though I can't find the PR. Has it been done?

**Comment by hardillb** [comment]
I don't think so

**Comment by sammachin** [comment]
delievered in #810
