### ISSUE TITLE
Add tests for rollback

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#736]
### Description

As mentioned in "initial rollback support #730 " once implementation is fixed, we should write tests to ensure stability.

**Comment by knolleary** [comment]
Tests should be part of the original PR - not treated as a separate task.

**Comment by Steve-Mcl** [comment]
Wasn't sure. Didn't want them to be forgotten. ( I guess they'd be flagged at the project board. My bad)

**Comment by knolleary** [comment]
#730 won't get merged until there are some tests - unless there's a reason to pull out to a separate task.
