### ISSUE TITLE
Found on github - A way to Enable/Disable flow from a button

### ISSUE THREAD

**Issue by grawsom** [flowforge/flowforge#743]
### Current Behavior

Don't know if this is posible other ways, but after finding out that you don't have editor posibilities on the device, I needed to find a solution where I could enable/disable a flow from the dashboard.

I found this [one](https://github.com/NRCHKB/node-red-contrib-homekit-bridged/issues/334#issuecomment-721291246) and it is working fine on device, but you can't test it in the editor on FF, there it don't work.

From what I can see, when using "normal" NR we have `http://localhost:1880/#flow/something` but on FF theres an ? before #flow `http://localhost:7880/?#flow/something`

### Expected Behavior

To see the flow get disabled / enabled in the editor

### Steps To Reproduce

Test the flow from the github page, [here](https://github.com/NRCHKB/node-red-contrib-homekit-bridged/issues/334#issuecomment-721291246)

```
[{"id":"15d7457.fcac4bb","type":"subflow","name":"Change Flow Disabled","info":"","category":"","in":[{"x":40,"y":40,"wires":[{"id":"42613114.0e42c"}]}],"out":[{"x":860,"y":40,"wires":[{"id":"bc4c108.66f42f","port":0}]}],"env":[{"name":"flowId","type":"str","value":"PUT_FLOW_ID_HERE","ui":{"icon":"font-awesome/fa-id-card","label":{"en-US":"Flow ID"},"type":"input","opts":{"types":["str"]}}},{"name":"nodeRedUrl","type":"str","value":"http://localhost:1880/flow","ui":{"icon":"font-awesome/fa-chain-broken","label":{"en-US":"Node RED api url"},"type":"input","opts":{"types":["str"]}}}],"color":"#DDAA99"},{"id":"8920ad34.ac04a","type":"http request","z":"15d7457.fcac4bb","name":"Retrieve current flow state","method":"GET","ret":"obj","paytoqs":"ignore","url":"","tls":"","persist":false,"proxy":"","authType":"","x":200,"y":80,"wires":[["2c17ab5e.baf484","4ae06e4d.49bdf"]]},{"id":"bc4c108.66f42f","type":"http request","z":"15d7457.fcac4bb","name":"Update flow state","method":"PUT","ret":"obj","paytoqs":"ignore","url":"","tls":"","persist":false,"proxy":"","authType":"","x":710,"y":80,"wires":[["50c71a03.281e54"]]},{"id":"2c17ab5e.baf484","type":"function","z":"15d7457.fcac4bb","name":"Change flow disabled","func":"switch (flow.get('action')) {\n    case true:\n        msg.payload.disabled = false\n        break;\n    case false:\n        msg.payload.disabled = true\n        break;\n    default:\n        msg.payload.disabled = !msg.payload.disabled\n        break;\n}\n\n\nmsg.url = flow.get('url')\n\nreturn msg","outputs":1,"noerr":0,"initialize":"","finalize":"","x":480,"y":80,"wires":[["bc4c108.66f42f"]]},{"id":"4ae06e4d.49bdf","type":"debug","z":"15d7457.fcac4bb","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":150,"y":120,"wires":[]},{"id":"50c71a03.281e54","type":"debug","z":"15d7457.fcac4bb","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":690,"y":120,"wires":[]},{"id":"42613114.0e42c","type":"function","z":"15d7457.fcac4bb","name":"Prepare URL","func":"//action true-enable false-disable else toggle\nflow.set('action', msg.payload)\n\nreturn {\n    url: flow.get('url')\n}","outputs":1,"noerr":0,"initialize":"flow.set('url', env.get('nodeRedUrl') + '/' + env.get('flowId'))","finalize":"","x":150,"y":40,"wires":[["8920ad34.ac04a"]]},{"id":"92fa3829.8bf878","type":"inject","z":"e0a1eb30.3f3ea","name":"enable","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":350,"y":280,"wires":[["42ec474e.43e4c8"]]},{"id":"42ec474e.43e4c8","type":"subflow:15d7457.fcac4bb","z":"e0a1eb30.3f3ea","name":"","env":[{"name":"flowId","value":"8adfcdfd.a8bc9","type":"str"}],"x":600,"y":280,"wires":[[]]},{"id":"ba661f80.77b37","type":"inject","z":"e0a1eb30.3f3ea","name":"toggle (default)","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":380,"y":240,"wires":[["42ec474e.43e4c8"]]},{"id":"9803b7c0.d164c8","type":"inject","z":"e0a1eb30.3f3ea","name":"disable","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"false","payloadType":"bool","x":350,"y":320,"wires":[["42ec474e.43e4c8"]]}]
```

### Environment

- FlowForge version: 0.6.2
- Node.js version: 16.13.2
- npm version: 8.10.0
- Platform/OS: Local / Win11
- Browser: Edge

**Comment by grawsom** [comment]
> You won't be able to make calls to the admin api manually because adminAuth is enabled and that requires the correct token in the HTTP headers.

And I'm still a NR novice, so this I don't understand

> But why can't you just disable the flow (tab) as normal from the editor?

Because I need to this on the device, but there is the editor disabled !
But as I said - I have it working, but would have been nice to see it in action on FF editor. 

So let be with that, maybe I find a way another day.

**Comment by hardillb** [comment]
What you have described does mean we need to enable adminAuth on the NR instance running on the device which is likely to break this subflow method.

adminAuth is how username/password is enabled for the editor, but it also applies to the admin API endpoints, which in the device case really should also be locked down.

You should not be toggling flows on/off like this, it would be better to put use the context and to add gates into the flow it's self.

**Comment by grawsom** [comment]
> What you have described does mean we need to enable adminAuth on the NR instance running on the device which is likely to break this subflow method.

Don't think you need to enable anything, it's working fine on the NR instance running on the device!

> You should not be toggling flows on/off like this, it would be better to put use the context and to add gates into the flow it's self.

I have not at precent time another solution for what I'm using, maybe there's another way - buy I haven't found it.
I'm using an SMS/internet solution with a GSM dongle - using 6 year old "smstools" and when I need to see signals etc. for the modem, I need to stop a service first before I can use the "disabled" flow - this flow can't be enabled when the service is running - using same comport.
But I'm in the proccess to use another version dongle, that let's me use some API from the dongle - but it all takes time.

Some other thing - will there be a fora someday, so question like mine could be asked there insteed?

**Comment by hardillb** [comment]
I'm saying this will not work in the next release as it is a security problem.

You can ask questions on the Node-RED slack in #floeforge

**Comment by hardillb** [comment]
I'm going to close this as I've explained why the method doesn't work in the cloud and that it will not work on the device in the next release.

What I will say is that USB GSM devices tend to present multiple serial interfaces so you can run PPP on one and still send AT commands to track single strength or send/receive SMS messages on the others (most have at least 2 but some even 3). I suggest you look at that going forward. (Modern LTE USB devices tend to present as USB-Ethernet devices)
