### ISSUE TITLE
Project isn't stopped before deletion

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#756]
### Current Behavior

- Delete a running project
- Create a new project
- Open Editor for the new project
- The editor loads the contents of the deleted project.

### Expected Behavior

If I delete a project, I expect that FlowForge should stop the NR instance for me automatically.

**Comment by knolleary** [comment]
It certainly should be stopping it... which driver are you using? localfs?

**Comment by joepavitt** [comment]
yep - localfs. Just working through it with Steve and it was an issue. Had to kill the processes via node
