### ISSUE TITLE
License Limits

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#775]
### Description

Introduce the concept of the license setting limits on the number of a resource that can be created within the platform.
If user on the system attempts to create a resource that would exceed this limit that action must fail and they are shown an appropriate error message.
As per the pricing principles document installs of FlowForge should be limited by:

- [x] #776
- [x] #777
- [x] #778
- [x] #779
- [x] #781
- [x] #780

The license file may specify a value that is lower than the default value in the CE edition, this is a valid scenario as the presence of the license also unlocks additional features.

The license file should specify these numbers,
Where the value is 0 then this would prevent that item being created on the platform (eg devices)
Where the value is -1 then there is no limit to the number that can be created.

**Comment by knolleary** [comment]
I propose we do not support '-1 means no limit'. We do not have a use-case for unlimited values that cannot be satisfied by just setting it to a sufficiently large value. It removes the need for any special case handling.

**Comment by knolleary** [comment]
All of the stories are now merged. I believe this addresses all of the immediate requirements of the licensing.
