### ISSUE TITLE
Device Billing

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#782]
### Epic

#446

### Description

implement billing for devices where the platform has billing enabled.

Devices are a new subscription product within Stripe.
There is only one type of device at a single price point
The number of devices on the team will be reflected by the quantity of the device product in the subscription

Team Tiers #733 may define that a team type includes a number of free devices, in which case this should be taken into account when setting the quantity on the subscription.

### Acceptance Criteria

- [ ] When a new device is created the team must be billed for the device by incrementing the quantity in the device product attached to the team subscription. If there is no device product as part of the subscription one should be created
- [ ] When a device is deleted from the team the quantity in the device product subscription should be decremented.
- [ ] The owner should be shown a check box and asked to accept additional charges when creating a new device.

**Comment by knolleary** [comment]
This is what our pricing guide current says (bulleted for ease of reference):

> 1. The team is billed per device at the same rate regardless of tier or number of devices.
> 2. A team plan may include a number of free devices.
> 3. The EE License will be for a defined number of devices on the platform regardless of teams.
> 4. The CE license will allow 50 devices.

From (1) - a single stripe product/price ID will be provided via `flowforge.yml` for the device object.

The CE(4)/EE(3) License determines the total number of devices allowed on the platform (implemented via #961)

From (2) - the `TeamType` needs to be able to specify how many devices are free. We have a similar concept for `userLimit` - which is set to `3` for the default `starter` team (although we aren't talking about a limit here - just a free allocation of devices). Let's call the new property `deviceFreeAllocation` - until I think of something better.

I think the following describes how that property will be handled. @sammachin please let me know if this makes sense to you:
1. On CE, `deviceFreeAllocation` is the limit of how many devices you can have in the team
2. On EE (without billing enabled), `deviceFreeAllocation` has no effect - you can have as many devices as you want in a team (you are already paying for them via the license fee)
3. On EE (with billing enabled), `deviceFreeAllocation` is the free allocation, anything after that is then billed in addition (whilst staying within the overall platform-wide limit on devices as set by the license).

**Comment by sammachin** [comment]
> * On CE, `deviceFreeAllocation` is the limit of how many devices you can have in the team

I don't believe we specified a limit on devices per team in CE, just 50 across the platform. So if you run CE with 1 team that team could have 50 devices.

I'm not opposed to putting a limit on CE teams I'm just not sure its really required, it feels like additional complexity to explain to a customer.

**Comment by knolleary** [comment]
Further discussion on this has lead to the following requirements:

1. TeamType can include *two* properties - `deviceLimit` and `deviceFreeAllocation`
2. `deviceLimit` limits how many devices can be assigned to a team
3. `deviceFreeAllocation` determines how many devices a team is allowed before billing kicks in.

The exact values are TBD - but the engineering work to support these values if provided can make progress.

**Comment by knolleary** [comment]
Work delivered via:
 - #970 
 - #971
