### ISSUE TITLE
Update selection tile to use ff-selection-tile

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#791]
### Description

With the new `selection-tile` available in `forge-ui-components` ([PR](https://github.com/flowforge/forge-ui-components/issues/29)) we should update the instances of this UX in FlowForge to utilise this new component and create more consistent visual appearance across the app.

**Comment by joepavitt** [comment]
Dependent upon https://github.com/flowforge/forge-ui-components/pull/40

**Comment by Steve-Mcl** [comment]
checked in staging. 
NOTE: an issue was raised by Ben (same one spotted by Nick in the PR) regarding wrapping of tiles. 
Otherwise verified.
