### ISSUE TITLE
(re)-verify on email change.

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#813]
### Epic

#393 
### Description

**As a:** user

**I want to:** have my email verified when its changed 

**So that:** I can ensure the correct email is on the account.

### Which customers would this be availble to

- [X] All Users, (CE)
- [ ] Specific Project Types (EE)
- [ ] Specific Team Tiers (EE)
- [ ] Other (See comments)

### Acceptance Criteria

- [ ] When user changes email a verification link is sent to the new address
- [ ] When user changes verifies the change via the email link, an "Email Changed" email is sent to the original address
- [ ] ~The user is prevented from accessing the account (session logged out) until they have completed the verification~
- [ ] If the new verification is not completed after 48hrs access is restored and the original email is kept on the account.
- [ ] user cannot use an existing email address
- [ ] audit log entries are made
  - [ ] for generating change request 
  - [ ] for verifying/completing the change request

**Comment by sammachin** [comment]
#815 should be implemented before or at the same time as this

**Comment by knolleary** [comment]
There's a mismatch between title ('on password change') and description ('on email change'). I assume its the latter?

**Comment by sammachin** [comment]
yes, sorry got my wires crossed writing so many email/password stories!
have updated title

**Comment by sammachin** [comment]
Following discussion we have agrreed the following flow for this:
- user submits email change
- we create a ‘pending change’ record
- existing email is still the active email on the account
- user clicks the link to verify the change - only at that point does the account email get changed
- if user doesn’t click the link, the pending change expires - nothing to revert as the change didn’t get applied

**Comment by sammachin** [comment]
When the new email is in the 'pending change' list it should therefore be prevented from being used to signup for a new account or changed to be used on another account.
Emails in the pending change list that have been there for  more than 48hrs should be removed as the token will be expired

**Comment by sammachin** [comment]
If the user attempts to login with the new unverified email address (once #705 is implemented) this should fail as that address is not yet on the account so should be treated as an unknown address for login purposes

**Comment by Steve-Mcl** [comment]
It looks like this will require a new table, similar to the "Initiations" table. 

This could be a table specifically for this feature (e.g. `PENDING_EMAIL_ADDR_CHANGES`) but I suspect the earlier posts may be hinting towards a more generic table (e.g. `PENDING_CHANGES`) that could be used for other/future changes that require another "operation" (e.g. "pending restart", "at a later time", awaiting admin approval etc)

I figure it would store:
* `id` identity
* `token` for validation
* `expiry` 
* `changeType` a string or number indicating the type of change (in this case, a users own email address)
* `changes` a JSON field with values structured according to an expected format (dictated by the value of `changeType`) 
* `options` a JSON field with values structured according to an expected format (dictated by the value of `changeType`) 

`changes` field would dictate what is to be changed
`options` field could dictate what when it occurs, who can execute, any pre-conditions?


For this particular implementation, I see the following design
```mermaid
sequenceDiagram
    %% 
    autonumber
    participant UE as UserEmail
    actor US as User
    participant UI
    participant RT as Runtime
    participant DB
    title User Email Address Change
    US->>UI: User enters new Email Address on "User Settings" page
    US->>UI: Clicks "Save Changes"
    UI->>+RT: PUT /api/v1/user/
    RT->>RT: Generate Email Verification Token
    RT->>DB: Store 'pending change' record
    par Runtime to UserEmail
        RT->>UE: Send email containing verification link /account/verify/{token}
    and Runtime to UI
        RT-->>-UI: { status: 'okay' }
    end
    UI->>US: Show 'Check your email' page
    UE-->>US: Email received
    US->>+UI: Opens /account/verify/{token}
    UI->>US: Displays page asking user to "verify your email address"
    US->>UI: Click "Verify email address" button
    UI->>+RT: POST /account/verify/{token}
    RT->>RT: Checks {token} is for the logged in user
    RT->>DB: User.email={new email address}
    RT-->>-US: Logout user, redirect to '/'
```


@knolleary please advise.

**Comment by Steve-Mcl** [comment]
@knolleary bump :)

**Comment by knolleary** [comment]
I don't see any requirement for a generic 'pending changes' table. Changing email is the only thing in scope for this issue.

I will leave it to your judgement whether to create a generic table or not - but this *must not* scope-creep to accommodate a more generic approach.

**Comment by Steve-Mcl** [comment]
@knolleary I pretty much created the table and migration etc but while working on the front end stuff and token generation, it occurred to me we can achieve the same thing without any DB work at all.

As a test, I added data to the `jwt` payload (i.e. I added the new email address in the JWT.
When the token is used, I direct user to a "Confirm your change of Email Address" page (similar to how the Verify Email stuff is done)
When the user clicks the button, the the backend code does the following....
1. Same user who generated the token is the currently logged in user
2. The Users EMail has not changed since the Pending Email Change token was generated
3. The new Email address is present in the token
4. That the token is valid / not expired

At this point, I know the user who generated the change of Email is currently logged in, that the users Email Address has not changed (same as the `sub` in the token`) and so proceed with the change.

What are you thoughts on this approach?

I realise the original story talks of DB fields but on the off chance the approach I have taken was simply not considered - I thought I would see how you feel about it.

**Comment by knolleary** [comment]
@Steve-Mcl That seems a pragmatic approach. The JWT is signed so cannot be tampered with. If they don't receive the email for any reason, they still login via their existing email address as that is still considered verified.

**Comment by Steve-Mcl** [comment]
Grand. Thanks for the feedback. I will apply finishing touches and add tests.

Also, will grab 5 mins of @joepavitt time to discuss UI (as it is currently only "functional" AKA not pretty :) )

**Comment by Steve-Mcl** [comment]
PR raised and acceptance criteria updated.

**Comment by Steve-Mcl** [comment]
Criteria updated to reflect the requested changes to who gets email.
