### ISSUE TITLE
Notify User on password change

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#814]
### Epic

#393 
### Description

**As a:** user

**I want to:** be notified by email when my password is changed

**So that:** I can spot someone attempting to take over my account

### Which customers would this be availble to

- [X] All Users, (CE)
- [ ] Specific Project Types (EE)
- [ ] Specific Team Tiers (EE)
- [ ] Other (See comments)

### Acceptance Criteria

- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3
- ...

**Comment by Steve-Mcl** [comment]
confirmed on staging (email received)
