### ISSUE TITLE
Input text is unreadable in login form

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#825]
### Current Behavior

The font colour of the input boxes in the login dialog has changed recently to be unreadable.

This is `main` and on staging:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/51083/181782093-efdf4330-90ef-4731-b75d-fa1c9c28abc5.png">

This is production:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/51083/181782358-9fce4627-50ba-4680-bc52-efd7037ad000.png">

### Expected Behavior

To be able to read the text in the login box.

### Environment

- FlowForge version: latest code *after* 0.7 release

**Comment by joepavitt** [comment]
This has already been fixed in https://github.com/flowforge/flowforge/pull/798 - once merged it'll disappear. It's linked with a change I've had to make with the `ff-text-input` in ui-components and consequent CSS updates required in FlowForge

**Comment by joepavitt** [comment]
Will wait for that PR to be merged and verified before closing this though

**Comment by knolleary** [comment]
#798 has been merged and all is well again.
