### ISSUE TITLE
DeprecationWarning: The del method is deprecated

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#826]
Opened a Node-RED editor via the platform dashboard. In the flowforge server log got this - might have been a coincidence. Either way, need to hunt down and fix.

```
(node:61070) [LRU_CACHE_METHOD_del] DeprecationWarning: The del method is deprecated. Please use cache.delete() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by hardillb** [comment]
https://github.com/flowforge/flowforge/blob/18ba9dcb18254ef5dd1417a27216f93c103670bb/forge/routes/auth/oauth.js#L211

**Comment by hardillb** [comment]
I'd seen it before, just not got round to fixing it
