### ISSUE TITLE
How to migrate to FlowForge

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#831]
### Description

Documentation should be provided to users on how to migrate a running Node-RED instance to FlowForge.

As such as possible it should be handholding and fool-proof.

Including:
- [ ] How to copy the flows
- [ ] Export credentials
- [ ] Setup 3rd party nodes
- [ ] Environment Variables

**Comment by sammachin** [comment]
The current process is far from foolproof and not something that can be greatly improved with docs alone, however this will be a useful activity to identify areas where we can improve the process incrementally. 
I have already added #835 to the backlog around importing credentials files into flowforge, other stories should come out of this work

**Comment by protocolus** [comment]
Being able to pull the flows from a running node-red instance thru the API would be a nice feature.

**Comment by ZJvandeWeg** [comment]
First iteration of this issue has been completed through: https://github.com/flowforge/flowforge/pull/897
