### ISSUE TITLE
Removed member notification references member by UUID

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#833]
### Current Behavior

When a member is removed a notification is shown which member is removed. The removed member is referenced by UUID, not by their name.

### Expected Behavior

The notification either shows their name or "This member has been removed"

### Steps To Reproduce

Remove a member from a team

### Environment

- FlowForge version: 0.7.0
- Node.js version: 16.15
- npm version:
- Platform/OS:
- Browser:

**Comment by sammachin** [comment]
Recreated on staging video attached

https://user-images.githubusercontent.com/187645/182157594-07f6b23a-c83e-4577-bf26-2a8ea95676bc.mp4

**Comment by sammachin** [comment]
Need to review other notifications to check what object property they display

**Comment by sammachin** [comment]
Alerts were introduced in https://github.com/flowforge/flowforge/pull/713

Looks like most of the alerts don't include any object specific information, but there are a couple there to review.

**Comment by sammachin** [comment]
Have reviewed the code for all instances of `alerts.emit` there are only 3 places that use any variables in the list,
[frontend/src/pages/team/dialogs/InviteMemberDialog.vue](https://github.com/flowforge/flowforge/blob/74b6bee184f0895ef3699c2f3f91cf6d025adad3/frontend/src/pages/team/dialogs/InviteMemberDialog.vue) Uses the value entered by the user in the input field
And this one in frontend/src/pages/team/dialogs/ConfirmTeamUserRemoveDialog.vue
All others are fixed strings
