### ISSUE TITLE
Update Fastify to 4.x

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#844]
### Description

Fastify released their 4.x major release earlier this year. We should update to match prior to our 1.0 release.

Some minor changes will be needed. This will also enable us to update all of the down-level fastify plugins.

https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/

**Comment by hardillb** [comment]
note: this will allow fastify-helmet to move from 0.8.x to 0.9.x at the same time

**Comment by hardillb** [comment]
Running on Staging, all looks good
