### ISSUE TITLE
Review outdated/unused configuration options

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#851]
### Description

`etc/flowforge.yml` contains some options that are no longer used/required

e.g.

- the k8s container driver takes a registry to load containers from
- ee - billing has product/price entries that are now added via Project Types

Should clean up before 1.0

**Comment by knolleary** [comment]
The billing details are used as fallback if none are provided in the Project Type.

I didn't explicit test the path where they aren't provided in the yml, but are provided in the ProjectType. We should double check there isn't any validation in the billing code that checks for those values to be present before removing them.

**Comment by hardillb** [comment]
Include compare to options exposed via the helm chart

**Comment by knolleary** [comment]
@hardillb can you do a first pass on what configs you think can be removed?

**Comment by hardillb** [comment]
First rapid pass

**Drivers**

k8s:
- driver/options/registry (only used as a fallback for a state we should never be able to reach on current version with stacks which expect fully qualified container names)

docker:
- driver/options/registry (not used at all)

localfs:
- no unused options

**Billing**
Used as defaults if no team type defined?
- billing/stripe/team_price
- billing/stripe/team_product
- billing/stripe/project_price
- billing/stripe/project_product

**Features**

All been removed? Devices being removed by #669 

**Telemetry**
- telemetry/frontend/plausible/* not used any more

**Comment by knolleary** [comment]
First pass of this done via #1152 to cover the MQTT options needed in `flowforge.yml`. But I think there may be more to be done in the helm/docker stuff.

Moving this over to 1.1 to get a final look at.

**Comment by joepavitt** [comment]
> Do we want to remove them in the next release

Sensible

**Comment by knolleary** [comment]
Residual tasks:

 - [ ] Remove all support for Plausible analytics
