### ISSUE TITLE
Editing Stacks silently fails

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#853]
### Current Behavior

If you try to edit a stack property e.g. CPU % for an already deployed stack the dialogue allows you to make and submit the change and updates the table with the new value even though the change has been silently dropped.

If you refresh the page then the value reverts to it's original value.

### Expected Behavior

An error should be shown and the change should not be made to the table (or it should reload from the backend to always show the true values)

### Steps To Reproduce

- Deploy a stack with Docker/K8s backend
- Try and edit the stack CPU/Memory values

### Environment

- FlowForge version: 0.8
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Linux/Alpine/Docker
- Browser: Chrome

**Comment by sammachin** [comment]
@hardillb is is possible to change the values of the stack once it has been created? should these fields just not be editable once created?

**Comment by hardillb** [comment]
@sammachin It should definitely not be possible to change these properties on a stack that has any deployed projects.

But yes, having it be uneditable would be a possible solution.

**Comment by sammachin** [comment]
This error also occurs when trying to change a stacks active state

**Comment by sammachin** [comment]
Verified on staging
