### ISSUE TITLE
Non owner user can "Set as Device Target"

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#858]
### Current Behavior

It is possible as a non-owner user to operate snapshot action "Set as Device Target"

### Expected Behavior

Should fail with error 403

### Steps To Reproduce

* Log in to FF as non owner
* Select a project with devices
* View snapshots
* Select a snapshot and operate "Set as Device Target"

### Environment

- FlowForge version: 0.8
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by sammachin** [comment]
Set as Device Target is akin to deploying a flow just in this case its deploying to a device, Therefore we need to consider if this is the desired behaviour or if this is indeed a bug.

**Comment by Steve-Mcl** [comment]
@sammachin thanks, as discussed I will update https://github.com/flowforge/flowforge/tree/main/docs/user/team so that we have a better footing for this issue and #854
