### ISSUE TITLE
Add Launcher Version in Node-RED Menu FF-Theme

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#860]
### Description

The hamburger menu should have the launcher version displayed under the FlowForge Website Link.

Both these items should be in a separate menu separator to the Node-RED Link and Version

**Comment by hardillb** [comment]
Any reason this needs to be shown in the Node-RED instance and not just on the project page in the app? (where it already is)

**Comment by sammachin** [comment]
@hardillb its on the original figma design for the theme, we did debate this but decided to include it assuming its an easy value to get into the theme, we may drop it if the work to access the value becomes ardious

**Comment by sammachin** [comment]
yup
