### ISSUE TITLE
FF Theme - Move Project Settings to Hamburger Menu

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#861]
### Description

Move the `Project Settings` item in the User Menu into the FlowForge section of the Hamburger Menu and Rename to `FlowForge Application`

**Comment by Steve-Mcl** [comment]
Now confirmed on production...


![Image](https://user-images.githubusercontent.com/44235289/187938967-e7dd3902-9336-4d8b-a926-dc8330a465a8.png)

**Comment by Steve-Mcl** [comment]
@sammachin - can close now?

**Comment by Steve-Mcl** [comment]
@sammachin - ok to close?
