### ISSUE TITLE
Allow a team to be deleted that doesn't have billing setup

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#871]
### Description

**As a:** user

**I want to:** delete a team I created but changed my mind before setting up billing

**So that:** I don't have to provide a credit-card number to delete the team

---

With billing enabled, if a user creates a team, but then aborts the stripe setup, they are left in a state where the only thing they can do is setup billing. There is no way for them to change their minds and delete the team.

Forcing a user to provide a credit-card so they can delete the resource they don't want to use isn't ideal.

Allowing access to the Team Settings page is problematic - as there are lots of options under there the user shouldn't be able to modify whilst in this state.

It may be more pragmatic to add a 'Changed your mind? Delete this team' option on the Team Billing page (that shows the usual delete team dialog etc).

(not a real figma mockup....)
<img width="937" alt="image" src="https://user-images.githubusercontent.com/51083/183879129-a1f71258-fcf6-4b55-854b-525234f9ebb0.png">

### Which customers would this be availble to

Specific Team Tiers (EE)

### Acceptance Criteria

- [ ] User can delete a team without having setup billing

**Comment by joepavitt** [comment]
The other option here is to enable the "Team Settings" tab as a Team Owner, even when billing isn't setup. They'd then see the "Danger Zone" and consequently Delete.

Part of me is hesitant about making it _too_ easy to back out from payment

**Comment by sammachin** [comment]
Another option would be to cleanup these teams periodically, if the user abandons ship at the strip checkout page they may never come back to the forge app to see the delete team button anyway.

Having the ability either as an admin manually or a script to remove any teams without billing that are more than X days old?

**Comment by knolleary** [comment]
In checking through the code, I can see the logic that forces you to the billing page makes an exception for `/settings/danger` - so if you know the url, you can get to the page to delete the team.

However we don't have anything in the UI to directly navigate there - the Team Settings page hits `/settings` first which bounces you away to the billing page.

If we add `/settings` and `/settings/general` to the permitted list for teams without billing, then it will be possible to get there.

As it stands 'delete team' is the only option on the danger page - so no further work is needed to limit the options on the page. But we'll have to keep that in mind if other options are added in the future.
