### ISSUE TITLE
Update Admin Overview to include Devices and any other obvious metrics

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#880]
### Description

The Admin Overview page gives an at-a-glance view of information about the platform.

It includes counts of users, teams and projects.

We should add equivalent info on Devices and any other obvious metrics.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/51083/184117954-38368cdc-502b-4284-ac3c-397087a5338a.png">

The information is largely derived from the `/api/v1/admin/stats` endpoint - which should be updated to include the information to be displayed.

**Comment by sammachin** [comment]
Breaking down the projects and teams by type would also be useful.
