### ISSUE TITLE
When device is re-assigned to a new project old project & snapshot still run

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#888]
### Current Behavior

If I have a device and assign it to a Project, then set a target a snapshot of that project it runs fine.

However if I then assign the device to a different project, but don't set a target snapshot for that new project the device continues to pickup and run the original snapshot

### Expected Behavior

Device should stop running the snapshot of the original project and sit waiting for a new one.

### Steps To Reproduce

Create project A & device, assign device to project.
Create snapshot and set as target, ensure it is running on the device.

Stop device agent,

Create a 2nd project B, and assign the device to that new project, (observe that the device has been removed from project A)

Start device agent,

Observe that device is running Project A still 

### Environment

- FlowForge version: 0.8.0 (staging)
- Agent 0.2.0
- Node.js version: 16.16

**Comment by knolleary** [comment]
My first attempts to recreate this have not been successful.

Following the steps to reproduce, using the latest code across the board, I see the new project running on the device after it is restarted. I cannot find any path that results in the old project to be restarted.

**Comment by sammachin** [comment]
@knolleary do you have a target snapshot on project B? I'm pretty sure I didn't set one

**Comment by sammachin** [comment]
I found the path that I used, its not in the latest release but is still there on prod
The devices screen in the project (not team) had the kebab menu which let you assign a device to another project from it, 
![image](https://user-images.githubusercontent.com/187645/187716514-b5009f52-9d23-445a-a4d4-0e41adb5c749.png)

Thats now gone and you can only manage the device (unassign, regen creds etc) from the team devices page. Which I think is correct. I'm not sure where that change was made though, #908 touched the table but I can't see the menu being removed
