### ISSUE TITLE
Docker nginx defaults to first project alphabetically on unknown project name

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#894]
### Current Behavior

IN the Docker install, if you try to load the url for a project that isn't know in the database eg https://[random-garbage].sammachin.com 
It will redirect you to the first project that exists alphabetically, for example I just created https://aaa.sammachin.com
Which is now served for all unknown project names, (previously it was returning alexa.sammachin.com)

### Expected Behavior

The forge app should be the default application for an unknown project.

### Steps To Reproduce

See current behaviour

### Environment

- FlowForge version: 0.8.0 Docker
- Node.js version: 16.15

**Comment by hardillb** [comment]
I think this is an artefact of the https setup:
https://github.com/nginx-proxy/nginx-proxy/issues/2015
