### ISSUE TITLE
Broken Stack State Logic

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#901]
### Current Behavior

In trying to delete a stack, I am presented with the following error:

```
Error: Cannot delete stack is active replacing another stack
```

The stack was created as a replacement of an existing stack which has a project associated to it. When creating, the existing stack successfully moved to "Inactive". 

I then went to test deletion and the changing of active/inactive state of a stack. I was unable to delete or de-activate the newly created stack.

If I created a new version, of the new version, then I could delete the first copy fine. 

### Expected Behavior

Either:

~1. Allow deletion/inactivate state for the newly created Stack~
2. Clearer user feedback as to why the deletion/editing of active/inactive state was not possible

I suspect this behaviour is in place to ensure we always have the top of the hierarchy of stacks available to users, in which case, (2) should be enacted.

### Steps To Reproduce

1. Create a stack
2. Click the kebab-menu options and select "Create New Version"
3. Then try to delete the newly created stack.

### Environment

- FlowForge version: 0.8.0 (`main`)
- Platform/OS: Mac
- Browser: Chrome

**Comment by sammachin** [comment]
The behaviour is correct in that you can't delete the latest version of a stack, however the error message should be improved
