### ISSUE TITLE
Specify packages on a Project

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#905]
### Description

As part of migrating a project to FlowForge one of the pain points is installing any custom nodes the original project used.
While the user can install these via the palette manager there are 3 pain points:

It is somewhat tedious to install several pacakges
The user cannot specify an older version they can only install latest
If the package is on npm but not in the public catalog.

The last 2 can be solved via downloading a tgz from NPM and uploading via the editor but this is far from optimal approach.

Considering possible  solutions to this:
 - Allow the user to specify package names and versions as part of project settings,
 - Allow the user to pass an NPM install command with params via the editor (change to Node-RED or a Plugin)
 - Something else?

**Comment by sammachin** [comment]
Related to https://github.com/flowforge/flowforge/issues/405

**Comment by knolleary** [comment]
I think 405 will address 80% of this - with the remaining 20% (custom tgz files/nodes not on public npm) being a much more complex proposition as we will need to store the tgz's somewhere indefinitely so they can be reinstalled whenever the project is resumed (ie restarted in a clean container).

I would prioritise 405 - being able to specify nodes/version on the assumption they come from public npm catalog.

**Comment by knolleary** [comment]
With #405 merged in 1.0, we have a way for the user to list packages in project settings. It still relies on them being npm installable nodes (but they don't have to be listed on flows.nodered.org) - which I think will satisfy just about all cases.

The only scenario it won't help with is where a user has a custom node they want including that isn't published to public npm. We have the concept of private node catalogues in the backlog which can cover some of that.

All of that said, I'm going to close this issue as I think we have addressed the core of it.
