### ISSUE TITLE
Cannot view a team

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#906]
### Current Behavior

As an admin if I open the /admin/teams view I can list the teams but there is now nothing to click on to open the team overview page.
The slug isn't listed in the table so I can't even copy that and create the url 

### Expected Behavior

Clicking the team name should open the team overview

### Steps To Reproduce

Goto /admin/teams

Try clicking on a team

### Environment

- FlowForge version: 0.8.0
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
Verified OK in staging
