### ISSUE TITLE
Project Template is hidden

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#912]
### Current Behavior

When viewing a project in FlowForge, there is no way to confirm/check which Template was used when creating a Project.

### Expected Behavior

I expect this to be viewable in the "Project Overview" at least.

**Comment by sammachin** [comment]
Templates are currently very basic compared to stacks, there isn't any versioning on templates and a project just clones the current values from a tempate when its created.
This means that its possible to have 2 projects created from the "same" template in terms of name but with different values.
The template lifecycle needs an overhaul in an upcoming release.

**Comment by sammachin** [comment]
Having reviewed this the template works as follows:

A template is created in the platform with settings and a name
Projects are then created from that template,
The template can be changed but the name stays the same
Projects will pickup the new settings when the container is next restarted, unless the project has overridden a setting.

There is _some_ value in showing the name of the template in use on a project but as there is no versioning the only way to be sure that the project is using the latest version of a template is to restart the container.

**Comment by hardillb** [comment]
Verified on Staging
