### ISSUE TITLE
UX Bug: Long passwords can lead to failed sign up

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#921]
### Current Behavior

When signing up for FlowForge a user can create a very long password (over 1mb in length). This leads to an error for the user without specifying why the error occurred.

### Expected Behavior

When a password is too long the submit button is disabled.

### Environment

- FlowForge version: FlowForge Cloud August 2022

**Comment by sammachin** [comment]
The 1mb limit is the max size of the POST body, so we need to look at the total length of the username , password, real name and email combined. Or implement a sensible limit check on each in the UI say 1000 chars.
