### ISSUE TITLE
4xx Errors not shown in App

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#929]
### Current Behavior

Certain actions return a 400 error, for example trying to change a project type on a stack (see #853)

While this particular error shouldn't have been returned (and is now fixed in #928) plus the UI prevents editing the project type once set, it does highlight that there is no indication to the user that the error occurred.

In theory it should not be possible for a user to make a bad request using the forge app as the front end should prevent this being sent, however as a belt & braces approach it would be better to show an error messsage if it does occur to aid in tracking down issues.

### Expected Behavior

400 Errors should trigger a notification toast.

### Steps To Reproduce

Make a request that results in a 400 error, 

Once way to do this is to edit a stack and then remove the disabled flag from the project type dropdown so that it can be changed.

### Environment

- FlowForge version: 0.8.0
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by sammachin** [comment]
This may not be all 4xx errors across the platform #853 did not show in the UI but #901 did 

![Image](https://user-images.githubusercontent.com/187645/187889882-f7be6303-9391-44db-9318-49cb9ba92ba9.png)

Need to determin if this is a common setting or if certain errors are not being thrown properly to show up

**Comment by joepavitt** [comment]
We have catch alls for 401's and 500's in https://github.com/flowforge/flowforge/blob/main/frontend/src/api/client.js

Other errors should, one could argue, be handled on a request by request basis. Possibly, we manage the reporting of those errors via toast in a catch-all architecture, but the particular behaviour we expect to see or handle should be done on a request by request basis?

**Comment by Pezmc** [comment]
What about wrapping the axios methods (via the [api client](https://github.com/flowforge/flowforge/blob/3970242792a9dce99267bff0486eba1c4291eec2/frontend/src/api/client.js#L6-L11)) in a try/catch so they fall back to a global catch-all error handler that displays a toast. That way, if the error is caught or the promise rejection handled when the request is made, as it ideally should be, it wouldn't bubble up.

That feels to me like it gives a best of both worlds, ideally custom failure state handling for each request, but if that's not implemented, the errors are at least visible to the user and they know something is broken.

**Comment by joepavitt** [comment]
I agree @Pezmc and is what I meant by:

> Possibly, we manage the reporting of those errors via toast in a catch-all architecture, but the particular behaviour we expect to see or handle should be done on a request by request basis

Although, I see your point about the bubbling up. If we put a catch on a particular request (without including a toast call in that catch for example) - then the higher-level axios interceptor/catch wouldn't be called?

**Comment by Pezmc** [comment]
Right, in my mind the catch-all toast would only be for _if_ an error handler for the request wasn't set up; rather than being in addition to any custom error handling for a particular request. Though I can equally see the advantage of having global error handling, rather than having to add error handling and toast reporting to every request.

i.e. interceptor -> local error handler (if set) -> new global catch-all

Having said that, other than adding global error handling (checking the error type) across the app, I'm not clear technically how we'd ensure the catch-all ran _after_ the local error handler in an easy way.

**Comment by Pezmc** [comment]
Verified, the `Request Failed: operator does not exist: character varying = integer`) audit log issue is showing in the UI.
