### ISSUE TITLE
UI artefacts on smaller devices

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#936]
### Current Behavior

On smaller devices and smaller browser windows, elements overflow.
![image](https://user-images.githubusercontent.com/44235289/187947677-1e1f5960-b04a-4484-a6c4-45dc289fb433.png)

![image](https://user-images.githubusercontent.com/44235289/187947705-813811b6-202d-446f-97de-5cc103d2c5d5.png)

![image](https://user-images.githubusercontent.com/44235289/187947753-d2360de3-0570-4c20-966a-355f89217ea4.png)

### Expected Behavior

Expect menu to collapse sooner to provide more space for UI
Expect panels to contain elements (min-width?)

### Steps To Reproduce

View on smaller device / size down the browser window

### Environment

- FlowForge version: 0.9
- Node.js version: 16
- Platform/OS: Windows (cloud and localfs)
- Browser: Chrome Version 104.0.5112.102 (Official Build) (64-bit)
 (up to date as of writing)

**Comment by ZJvandeWeg** [comment]
@joepavitt Do we have capacity to squeeze this into 1.1? Or should we line up this item for 1.2?

**Comment by knolleary** [comment]
Whilst not specifically motivated by this issue, work has happened in recent releases that improves the small-screen handling:



![Image](https://user-images.githubusercontent.com/51083/225726779-ba17b753-a460-4354-be12-ec68bd4f8d5f.png)



Given that covers the specific items mentioned in this issue, I'm going to close this off.
