### ISSUE TITLE
Node-Red Isn't ready when Forge app says it is running following a project restart

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#941]
### Current Behavior

When i restart a running project on the cloud, the forge app shows project status screen and the status says "starting" then "started after only a couple of seconds. 

However, if I open the editor, I initially get an 502 error

After around 30secs the node-red app has fully started and I can access editor.

This was fixed for creating a container (https://github.com/flowforge/flowforge/issues/751) but still exists when restarting it.

### Expected Behavior

status to reflect actual state like it does when a project is first created

### Steps To Reproduce

* navigate to a running project on the cloud (n staging or in production)
* Click the action menu, click "restart"
* monitor the indicator until it says "started"
* try accessing the editor

### Environment

- FlowForge version: 0.9.0
- Platform/OS: Cloud, LocalFS
- Browser: All

**Comment by Steve-Mcl** [comment]
The PR in action...

![Code_T1elHlPMBL](https://user-images.githubusercontent.com/44235289/189913130-145a2470-7670-463d-9fc6-42d763be157b.gif)

**Comment by sammachin** [comment]
verified on staging, requires project to be running the latest version of the stack/launcher so may need a suspend start to pickup the change.
