### ISSUE TITLE
Admin can edit team membership

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#943]
### Epic

#940

### Description

**As a:** admin

**I want to:** be able to edit (add, remove, modify) the membership of a team from the admin pages.

**So that:** I can manage teams or add myself to a team to perform further actions

### Which customers would this be available to

All

### Acceptance Criteria

- [ ] New action control on https://forge.flowforge.dev/admin/teams menu to 'Edit Membership'
- [ ] Modal view of team members with button to delete and dropdown to modify access level
- [ ] In Modal, option to add a member to the team (bypassing invite) and set their level.
- .

**Comment by knolleary** [comment]
With the change in approach identified for #940, an admin can now access a Team's pages as if they were an owner. I believe that removes the need for this story so we can close it?
