### ISSUE TITLE
Admin can change project state

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#944]
### Epic

#940

### Description

**As a:** admin

**I want to:** be able to change the state of any project (suspend, start, delete) from the admin menu

**So that:** I can manage the platform

Dependent on #381 which is dependent on #370

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

- [ ] On admin list of projects (delivered in 381) there is an action menu with suspend, start & delete actions

**Comment by Steve-Mcl** [comment]
Should an admin be able to suspend/start/delete projects? 

Consider: the system admin might have no awareness of criticality of a running project (to production).

**Comment by knolleary** [comment]
@Steve-Mcl if an admin identifies a project that is breaching the T&Cs of the platform, they need the tools to deal with it.

**Comment by Steve-Mcl** [comment]
_(thinking out loud)_ 

If the admin stops a project the only way to prevent the offender re-starting it is to delete the project or demote all owners.  Are we to consider a "lock" of sorts? (as in "this project was locked by an administrator, please contact xxxxx to understand why this was done and to regain access")?

**Comment by knolleary** [comment]
With the change in approach identified for https://github.com/flowforge/flowforge/issues/940, an admin can now access a Team's pages as if they were an owner. I believe that removes the need for this story so we can close it (once we've verified the work done for 940 permits the actions required for this story)
