### ISSUE TITLE
On Kubernetes project names can not start with a number

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#948]
### Current Behavior

It looks like k8s has rules for service names which mean they can not start with a number

https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc-1035-label-names

> Some resource types require their names to follow the DNS label standard as defined in [RFC 1035](https://tools.ietf.org/html/rfc1035). This means the name must:
> 
>   -  contain at most 63 characters
>   -  contain only lowercase alphanumeric characters or '-'
>   -  start with an alphabetic character
>   -  end with an alphanumeric character

### Expected Behavior

Reject projects that start with leading number

### Steps To Reproduce

Create project called `233test`

### Environment

- FlowForge version: 0.9.0
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: K8s/Linux
- Browser: NA

**Comment by sammachin** [comment]
`end with an alphanumeric character`
Our current default project names all end with a number

**Comment by hardillb** [comment]
> end with an alphanumeric character
> Our current default project names all end with a number
`alphanumeric` -> a-z0-9

**Comment by hardillb** [comment]
Added @Steve-Mcl so he can find it
