### ISSUE TITLE
Inconsistent api response format for errors

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#956]
### Current Behavior

We have an inconsistent style of response errors in the api.

We have a lot of:
```
{ error: 'invalid username' }
```

But we also have some:
```
{ status: 'error', message: err.toString() }
```

We need to standardise the format and make it consistent across the whole api surface.

The frontend should not rely on the particular spelling of an error message in order to detect it as that makes it impossible to consider i18n in the future.

### Expected Behavior

A consistent format for api errors

**Comment by Steve-Mcl** [comment]
We also consider adding documentation to the handbook about the final API design pattern - for future new starters and reference

**Comment by knolleary** [comment]
The api design guidelines are documented in this repo - `docs/contribute/api-design.md` - rather than the handbook.
