### ISSUE TITLE
Wrong name property in NoVerifiedEmail.vue

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#960]
### Current Behavior

Spotted what looks to be a copy+paste error in the name property ...
https://github.com/flowforge/flowforge/blob/main/frontend/src/pages/account/NoVerifiedEmail.vue#L29

Though seemingly not causing any problems

### Expected Behavior

Should be `name: 'NoVerifiedEmail',` 

### Steps To Reproduce

N/A

### Environment

- FlowForge version: 0.9.0-git

**Comment by hardillb** [comment]
Moving to done, because there is nothing we could observe externally for this
