### ISSUE TITLE
When editing a template save/cancel hidden unless change is made

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#963]
### Current Behavior

When trying to edit a template there is no obvious way to exit if no changes are made.

You can use the sidebar menu, but it feels strange to not be able to close the edit screen.

### Expected Behavior

Cancel & Save should always be shown, but save should be disabled until there is a change

### Steps To Reproduce

As admin
View Templates
Edit an existing template
Make no changes.

### Environment

- FlowForge version: 0.9
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Linux
- Browser: Chrome

**Comment by knolleary** [comment]
Conceptually it was intended more as a 'view template' option, with the save/cancel buttons only present if youve changed anything.

The cancel button doesn't navigate away, it reverts any edits.

**Comment by hardillb** [comment]
I was comparing it to the create template behaviour, which always shows the buttons setting the expectation for them to be there and where cancel drops you back to the list of existing templates.

**Comment by Steve-Mcl** [comment]
I understand the reason that "Cancel" closes the "new template" and instead discards edits. However, with the  "Edit Form" and "New Form" being identical, naming the cancel button "Cancel" on both implies the same behaviour.

So would it be acceptable instead of changing behaviour, change the text of the cancel button when editing to "Discard Changes"?

Example...
![Image](https://user-images.githubusercontent.com/44235289/193293601-e8f92f9a-156e-4ce6-a2da-b7b5d21bf22c.gif)

**Comment by Steve-Mcl** [comment]
@hardillb @knolleary 
Unless you have a different direction, I will go with simple renaming of button to match the behaviour & differentiate this from the "New Template" "Cancel" action.

**Comment by joepavitt** [comment]
> So would it be acceptable instead of changing behaviour, change the text of the cancel button when editing to "Discard Changes"? 

I think @hardillb's point is that he wants a way to navigate away from the Template view, without clicking the side navigation - not necessarily linked to any changes that may or may not have been made.

As an aside though, I do agree/like the wording changes you have made @Steve-Mcl wrt the reverting of local changes.

**Comment by Steve-Mcl** [comment]
Thanks guys. As #1041 has a far wider scope, in the short term, to differentiate the 2 views, I will go with the simple rename. If #1041 completely changes the UI/UX then there is little lost.

**Comment by Steve-Mcl** [comment]
@hardillb Ben, I discussed this with @joepavitt  earlier today & we agreed several improvements (PR incoming) 

1. Change button name of "Edit Template" to "Discard Changes"
2. Always show the "Save Changes" button, but conditionally enabled/disabled if fields have changed
3. Hid the "Discard Changes" button, and only show it if fields have changed
4. Add a kinda mini breadcrumb that takes you back to templates list
5. Make items in templates list clickable to default operation (edit)  (saves 1 click & moving mouse to far side)

In action...


![Image](https://user-images.githubusercontent.com/44235289/195680572-4fddd662-56d5-4a52-99d4-5a3c5106f37c.gif)

**Comment by hardillb** [comment]
Verified on Staging
