### ISSUE TITLE
No feedback when an API error occurs editing user

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge#966]
### Current Behavior

Server-side validation errors are **not** shown to admin user

### Demo show where an attempt to change the name of user **test5** to **user4** - note **user4** already exists but no error is show.
![chrome_FyITRIblTL](https://user-images.githubusercontent.com/44235289/189392206-fe6b095a-d9f0-4242-af12-3aeb2708ddaa.gif)

The same issue is present for API errors
* "Invalid username"
* "email must be unique"
* unknown errors

### Expected Behavior

Dialog to remain open and to inform user of issue via the validation text

NOTE: the validation text is already present but is impossible to show since the `ff-dialog` closes upon confirm regardless of the API call success

Related: https://github.com/flowforge/forge-ui-components/issues/48

### Steps To Reproduce

with 3 users named **admin1** (admin) & **user1** **user2** (non admin)...
1. login as **admin1**
2. edit user1
3. set user1 name to user2

dialog is dismissed and no change has occured.

### Environment

- FlowForge version: 0.9.0-git
- Node.js version: NA
- npm version: NA
- Platform/OS: All
- Browser: All

**Comment by Steve-Mcl** [comment]
@knolleary @hardillb as a non admin on staging, I cannot check this - would one of you be kind enough to verify this pls?

**Comment by hardillb** [comment]
I now see a error text under the username if trying to change it to an existing user.
