### ISSUE TITLE
Keep sessions valid for 2 weeks

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#972]
### Description

Everytime I use FlowForge I feel like I have to sign in again. I would like not to sign in often, once every 2 weeks should be enough.

**Comment by sammachin** [comment]
2 weeks feels like a very long time, recognising that we are not the typical users of the platform and likely login more frequenty.

OWASP Best practice states `Set session timeout to the minimal value possible depending on the context of the application.`
https://owasp.org/www-community/Session_Timeout

We need to ascertain what sort of value is relevant to our application, We should be able to get this data from PostHog to see how frequently a user logs in and then set the timeout to the value of the 50th percentile?

**Comment by ZJvandeWeg** [comment]
Google has a weekly schedule. GitHub seems to be once a month. As such I think 2 weeks is fair.

> We should be able to get this data from PostHog to see how frequently a user logs in and then set the timeout to the value of the 50th percentile?

Data will be skewed to the low end because of our current policy?

**Comment by sammachin** [comment]
Action on @knolleary Nick to review the way cookies are handled and what effect the remember me checkbox has in Chrome and how this impacts our sessions then com up with an optimal user experience.

**Comment by sammachin** [comment]
This sounds like a good approach, I would suggest make the idle timeout 32hours so as to give an overlap of 1 working day (24+8), so action at 0900 on Monday won't timeout till 1700 Tuesday, allowing for daily activity without requiring the same time each day.

With this idle timeout I think we could push the session expiry to 2 weeks or longer but 1 week is a good starting point and now that we have a clear understanding of the timings it should be simpler to adjust in future iterations if required.

Just for the sake of completeness I assume that a user actively clicking the logout removes the session object immediately and clears the cookie?

**Comment by sammachin** [comment]
Verifed that the `sid` cookie has an expiry of 7 days on staging, can't easily confirm the other features.

**Comment by michelebrami** [comment]
I get that this is closed, but is there any way to tweak this setting on an on-premise installation? I have a requirement to have the session expire or request re-authentication once every 12 hours.
 
> idle timeout 32hours so as to give an overlap of 1 working day (24+8), so action at 0900 on Monday won't timeout till 1700 Tuesday, allowing for daily activity without requiring the same time each day.

**Comment by knolleary** [comment]
Hi @michelebrami 

It isn't a setting we expose, so would require patching the code which isn't ideal. I'll raise a separate issue to enable customisation of this setting.

**Comment by knolleary** [comment]
@michelebrami I've raised https://github.com/FlowFuse/flowfuse/issues/4201 and scheduled it for our next release that will be available in two weeks time.
