### ISSUE TITLE
Replace file nodes with object storage nodes

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#988]
### Description

FlowForge Cloud doesn't include the file nodes, as files persisted to the disk will not survive a restart of the container. Files are however very important to customers. Many files are still being used to interact with older systems. CSV, Spreadsheets, etc still need parsing.

FlowForge should feature custom nodes that under the hood use an object storage that persists data but to the end user feel like it's a file on disk.

**Comment by sammachin** [comment]
merging into #998
