### ISSUE TITLE
Provide the first iteration of user docs on project nodes

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#995]
### Description

[Project nodes](https://github.com/flowforge/flowforge-nr-project-nodes) are currently only documented in the readme of their Git repository. Features should be documented in this repository as those are deployed on our homepage, allows for better cross-linking, and it's the go-to place to search.

**Comment by ZJvandeWeg** [comment]
@sammachin Please pick this up this week, thank you!

**Comment by knolleary** [comment]
@ZJvandeWeg we already have #890 for this and it is planned for this iteration
