### ISSUE TITLE
Core Nodes - Files

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#998]
### Description

Using these epics to explore options for users around the core nodes that are disabled in FlowForge Cloud.

Specifically in this case the filesystem nodes, while it is valid that these are disabled in FF Cloud because the containers do not have a persistent filesystem there are 2 areas where a user is then impacted:

- Creating Flows to run on devices that may need to access the devices local filesystem

- Working with files in the cloud.

There are 3 nodes in this group:
- Write File
- Read File
- Watch File
The first 2 represent the majority of use cases, and certainly when it comes to the cloud re the MVP, the ability to watch a file for changes on an external storage platform is possibly beyond the scope.

However this watch file could well be used in certain device scenarios.

**Comment by knolleary** [comment]
We have to consider how this works across the different container runtimes.

For localfs, you have a filesystem, so there's no immediate need to do anything different.

For docker/k8s, something else is needed.

In our managed platform on AWS, we can assume to use AWS S3 to provide object storage under the node. Does that hold true for the more general docker-compose solution? Or even k8s on a non-AWS platform?

We can use our managed platform on AWS as the starting point to solve, but we *must* have a solution that makes sense for the others.

We need to confirm what restrictions/best practices exist around multi-tenancy of S3 buckets. There is a limit around how many buckets a single account can have - so having one bucket per team/project is not scalable.

We would need a single bucket to contain storage for multiple teams. For the time being, assume a single bucket, but spare a thought for how the teams could be sharded across multiple buckets. Within the bucket, object paths would be used to provide proper access controls. But that is where it starts to get more complicated from an architecture PoV.

Currently we have nothing hardcoded to AWS within FF. It would be preferable to keep it that way. But here we have a requirement to be able to dynamically provision security on an AWS bucket - something which does beyond the 'standard' S3 API (I think).

### Questions to address

1. Do we need a pluggable mechanism to provide FF a module that is responsible for setting up the security whatever storage mechanism is being used?
2. What makes sense in a docker-compose environment? Is there an OSS solution that provides an S3 compatible API that could be deployed in this scenario? How does its security model work?
3. Given all of the above, what configuration options would be needed in `flowforge.yml` to bootstrap the service - and what config options would need passing down to individual NR launchers for the nodes to be able to operate?

**Comment by sammachin** [comment]
Few options on here worth looking at https://geekflare.com/self-hosted-s3/

**Comment by hardillb** [comment]
Having played with Minio for a few days, I'm not convinced it will work for what we need.

The authentication API is really complicated (uses openid connect), I can't get the ACLs to work sensibly and I think we would need to publicly expose the bucket end point in k8s. Will look at Ceph next

**Comment by hardillb** [comment]
Having reviewed the available S3 based options, have come to the conclusion that it's probably not possible to do what we want.

Alternative approach of implementing a minimal CRUD object API in a small standalone web app that can be either backed by a directory or a single S3 bucket may be the better solution.

This allows us to have control of all the authentication and to implement quotas.

**Comment by hardillb** [comment]
Going to start on a basic CRUD API for this today

**Comment by hardillb** [comment]
I'll close this when all tested

**Comment by ZJvandeWeg** [comment]
I'd expected the "Working with Projects" section of the docs to include a link to the documentation around this feature
